### ISSUE TITLE
Click menu for "initialize solr connection" not visible in 8.6.0

### ISSUE THREAD

**Issue by tomasnorre** [TYPO3-Solr/ext-solr#1047]
After upgrading to TYPO3 8.6.0, the click menu for "initialize solr connection" is not visible in click menu. 

Solr: dev-master
TYPO3: 8.6.0

![solr_clickmenu_missing](https://cloud.githubusercontent.com/assets/1212481/23095325/5f747db8-f608-11e6-80bf-6a0aa1af68a8.png)

**Comment by thomashohn** [comment]
@tomasnorre Seems to be a "copy" of #962

**Comment by tomasnorre** [comment]
You're indeed correct.. Try to search but didn't find anything,.. Only searched for 8.6 not for context menu or similar.
