### ISSUE TITLE
[BUG] further psr-2 issues

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Solr/ext-solr#106]
https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/Access/Rootline.php

The following call is most likely wrong:
$rootline = $pageSelector->getRofalsee($pageId, $mountPointParameter);

**Comment by AndreasA** [comment]
Could it be that the option to format the code to psr-2 were wrong because how could getRootline be converted to getRofalsee ?

**Comment by irnnr** [comment]
Yep, PhpStorm crashed while doing the conversion

**Comment by AndreasA** [comment]
Ah. 
I did it on my own project with the same tool as the core (php-cs-fixer) and the .php_cs file from typo3 cms.

**Comment by irnnr** [comment]
In hindsight I should have done a reset and then simply retry. Worked pretty well when it didn't crash. ^^

**Comment by dkd-dobberkau** [comment]
hindsight is 20/20 :-)

**Comment by AndreasA** [comment]
@dkd-dobberkau agreed :)
