### ISSUE TITLE
[TASK] Feature flag for tracking records outside the siteroot.

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#1081]
It would be nice to have a flag to be able to disable the tracking of records outside the siteroot for sites where this is not needed. It gives some overhead in multi-sites where this feature is not needed. 
I think we should discuss this @timohund / @irnnr

**Comment by timohund** [comment]
@thomashohn What is the peformance difference when this feature is enabled or disabled?

**Comment by thomashohn** [comment]
@timohund - so roughly (#multi-sites-1) x 1 second. So in my case 3 seconds - I'll implement the flag and i think it should as default be disabled - or?
