### ISSUE TITLE
[FEATURE] Add possibility to exclude Tables

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#1115]
On complex installations with a lot of custom tables that are related to pages and tt_content the hook processDatamap_afterDatabaseOperations sends a lot of notifications for tables that you might never want to index. 

With the new Extension configuration it would be nice to have a setting called useConfigurationNeverIndexCustomtables which contains a list of tables that can be used for an early return before the existing check $this->hasRecordBeenProcessed

**Comment by timohund** [comment]
I would say for this a configuration in ext_conf_template.txt "limitToTables" makes sence, when nothing is configured all tables get tracked, when a list ist set it can be used.

E.g like that:
```php
$extensionConfiguration->getIsAllowedTable($tablename);
```

Which allways returns true when nothing is configured and false, when something is configured and the tablename does not match.

**Comment by thomashohn** [comment]
Makes sense 👍

**Comment by irnnr** [comment]
I'd propose to call the option `monitorTables` to go with the Record Monitor name. What do you think?

**Comment by timohund** [comment]
Sound more consistent
