### ISSUE TITLE
[Task] check whether a hint for "optimize index scheduler task" in the docs is still valid

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#1125]
Is 
https://github.com/TYPO3-Solr/ext-solr/blob/f8ed95931655026224b95049726e450a9603ecbb/Documentation/Solr/IndexMaintenance.rst#initializing-the-spell-checker still OK or can we drop it from docs?

Question coming from Slack https://typo3.slack.com/archives/ext-solr/p1488534076685771

**Comment by irnnr** [comment]
yeah, we're not doing/recommending optimize anymore
