### ISSUE TITLE
[FEATURE] Allow to import and export synonyms and stopwords

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#1135]
It would be nice to have the possibility to import and export syonyms from the solr backend module.

The format can be mentioned as here: https://github.com/TYPO3-Solr/ext-solr/pull/658

**Comment by sfsmfc** [comment]
First approach can be find on https://github.com/TYPO3-Solr/ext-solr/compare/master...sfsmfc:master

StopWords Im-/Export & Synonym Im-/Export down.
