### ISSUE TITLE
[FEATURE] Support grouped search with fluid

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#1136]
After solrfluid is part of the core extension and we drop the old templating it makes sence to support the grouping in the EXT:solr extensions:

Todo:

* Check the grouping support on the query level
* Implement the grouping into the domain model of EXT:solr
* Add default templating

**Comment by lorenzulrich** [comment]
What do you mean with "grouping" in this regard?

Does it include the request in my former issue https://forge.typo3.org/issues/66067 (which is not publicly accessible anymore) or would this be a separate issue?

**Comment by timohund** [comment]
@lorenzulrich This is the text of you issue: 

> 
> Currently, if the same FAL file is linked from multiple pages, the file is indexed and displayed multiple times. E.g. if a file is linked ten times and is the best match for a search, the whole first result page will only contain this file repeatedly. There should be an option to filter out duplicates so the same file is only displayed once.
> According to Olivier this has been part of "solrfile" or "solrdam" but didn't make it into solrfal yet.

This issue is allready resolved, you have the following possibilities:

- Use variants in EXT:solr (possible since EXT:solr 5.1.0, which is technically using solr fieldCollapsing)
- Use document merging in EXT:solrfal (possible since solrfal 4.0.0, which is merging before writing the documents)

The issue here is about to support grouping with fluid, which requires to implement the grouping for the domain objects to make them renderable with fluid.

**Comment by rnakielski** [comment]
Is it currently possible to use solrgrouping (by Ingo Renner) together with solrfluid?
Are there any example templates to download somewhere?

**Comment by timohund** [comment]
EXT:solrfluidgrouping will be available as addon for EB 2018
