### ISSUE TITLE
[FEATURE] Force commit after indexing

### ISSUE THREAD

**Issue by arnoschoon** [TYPO3-Solr/ext-solr#1158]
A bit of a trade off after reading #870 where the point is to avoid committing. I would like to see an option to execute a commit after running the `IndexQueueWorker`.

In a very early release of EXT:solr there was a scheduler task for this, but the `autoCommit` feature of Solr is a better alternative, not even because a commit should only take place if things have changed and not periodically.

In a platform where we have replication set up between multiple Solr servers the client demands that even small changes are visible almost immediately. For that purpose I've created a small patch https://github.com/arnoschoon/ext-solr/commit/d6589551a5ee2d2039f4d1c4301dc6600adb5065 that adds an option to the task configuration and issues a `commit` after indexing documents.

I'm aware of the fact that this could seriously harm performance, but for these "large" setups we host Solr on dedicated machines for each client (private networks). I'm not sure yet if this option should be added as a checkbox in the back-end interface or (like #875) as a directive in TS. The `autoCommit` feature https://github.com/TYPO3-Solr/ext-solr/blob/master/Resources/Private/Solr/configsets/ext_solr_6_1_0/conf/solrconfig.xml#L94 is also a viable option, but what would be sensible values?

Any thoughts, ideas and criticism are welcome.

**Comment by timohund** [comment]
@arnoschoon Is it an option to set:

```
plugin.tx_solr.index.enableCommits = 1
```

**Comment by arnoschoon** [comment]
Missed that one, thanks for pointing that out Timo :)

But (as far as I can see) this is only implemented for the `GarbageCollector` and `ReIndexTask`?! Should I update my patch and create a PR for https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/Task/IndexQueueWorkerTask.php?

**Comment by timohund** [comment]
Sorry for the delay Arno, sounds good for me.
