### ISSUE TITLE
[TASK] Deprecated calls, which will be removed in CMS v.8 LTS

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#1166]
# Here is the place for current release.

### Currently there is nothing in the logs except multiple occurrences of following line:

`EXT:form: Do not use "layout." anymore. Deprecated since TYPO3 CMS 7, this function will be removed in TYPO3 CMS 8.`

Feel free to add new ones for 8 LTS.

**Comment by timohund** [comment]
@dkd-kaehm Can you check if this comes from EXT:solr. If yes we should fix it otherwise maybe create an issue for the component that is producing this log entry.

**Comment by dkd-kaehm** [comment]
Hi,
also definitely it comes from other side. It comes by requesting FE sites.
