### ISSUE TITLE
[BUG] Frontend not rendering in TYPO3 version 7.5

### ISSUE THREAD

**Issue by timoschmidt** [TYPO3-Solr/ext-solr#117]
Was fixed with a workaround in 18a57e6 we need to find a solution for this.

Currently we get the following error in the frontend:

Fatal error: Class 'Tx_Solr_ViewHelper_Lll' not found in /var/www/7.5.0.local.typo3.org/typo3_src/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4345

**Comment by timoschmidt** [comment]
I am starting to investigate this issue

**Comment by dkd-dobberkau** [comment]
Hi Timo. We will only support TYPO3 Versions 6.2 and 7 LTS. Please double check after the release of TYPO3 today.

**Comment by timoschmidt** [comment]
Ok

**Comment by timoschmidt** [comment]
Checked in TYPO3 7.6 LTS and everything is working here. So we can close this issue
