### ISSUE TITLE
Status report crashes with exception when wrong solr port configured

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#118]
Solr response does not appear to be valid JSON, please examine the raw response with getRawResponse() method

Apache_Solr_ParserException thrown in file
/var/www/7.5.0.local.typo3.org/typo3conf/ext/solr/Resources/Private/Php/SolrPhpClient/Apache/Solr/Response.php in line 189.

I think we should catch the exception and let the report fail.

**Comment by thomashohn** [comment]
Could not be reproduced - please close issue.
