### ISSUE TITLE
[TASK] Extract QueueItemRepository and QueueItemService from ApacheSolrForTypo3\Solr\IndexQueue\Queue

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#1180]
For the 6.1 release we have moved most of the SQL Queries to the Queue Class. The Queue Class is currently doing many things beside the database access. The database access should be done in less components as possible.

We can do the database access in only two components and extract them from the Queue Class that no database operations to `tx_solr_indexqueue_item` are left in any other classes:

ApacheSolrForTypo3\Domain\Index\Queue\QueueItemRepository:

* Reposibility: Handle all read/write/retrieve/empty operation to `tx_solr_indexqueue_item` 
* Methods:
   *

ApacheSolrForTypo3\Domain\Index\Queue\QueueItemService:

* Reposibility: Handles state change operations (e.g. with DatabaseUtility::transactionStart)
  * Initialize
* Methods:
  *

**Comment by dkd-kaehm** [comment]
### ApacheSolrForTypo3\Domain\Index\Queue\ItemRepository:
  * Responsibility: Handle all read/write/retrieve/empty operation to tx_solr_indexqueue_item
  * Methods:
    * `findOneLatestIndexedByRootPageId($rootPageId) : ApacheSolrForTypo3\Solr\IndexQueue\Item bzw ApacheSolrForTypo3\Domain\Index\Queue\Item` 
    * `findNotIndexed() : Array|Collection<Item>`
    * `initializeFirstTimeQueue($queueName) : void`  Warning: not right place evtl.

### ApacheSolrForTypo3\Domain\Index\Queue\ItemManager:
  * Responsibility: Handles state change operations (e.g. with DatabaseUtility::transactionStart)
    Initialize
  * Methods:
    * `queue($queueName, Item $item) : void`
    * `peek($queueName, $limit = 1) : Item`

### ApacheSolrForTypo3\Domain\Index\Queue\QueueManager:
  * Responsibility: reads the configurations from available Sites/Cores etc
  * Methods:
    * getQueue(string $queueName/$siteName) : Queue

**Comment by timohund** [comment]
@dkd-kaehm I would propose to extract the ItemRepository in the first step and do the other things in a second step.
