### ISSUE TITLE
[TASK] Reports Module should trigger warning instead of error when indexing is disabled 

### ISSUE THREAD

**Issue by LeoniePhiline** [TYPO3-Solr/ext-solr#1184]
On a multi-site installation I have indexing enabled for two of six sites.

TYPO3 greets me - and my customers - with:

> Important Notice!
> One or more problems were detected with your TYPO3 installation. Please check the status report for more information.

The reports module shows a red error:

> Indexing is disabled
> You need to set config.index_enable = 1 to allow page indexing. The following sites were found with indexing disabled:
> 
>     [1] Site 1
>     [42] Site 2
>     [1303] Site 3
>     [1386] Site 4

This makes quite a bad impression, when **actually the configuration is absolutely correct.**

Please change `Status::ERROR` to `Status::NOTICE` in `\ApacheSolrForTypo3\Solr\Report\SolrConfigurationStatus::getConfigIndexEnableStatus()`. Line 193 in the current master.

https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/Report/SolrConfigurationStatus.php#L193

**Comment by timohund** [comment]
@LeoniePhiline I think throwing an ERROR is not the right way thats true. But i would propose to at show a warning when config.index_enable = 0  & and plugin.tx_solr.enabled = 1 the you can disable solr to get no warning. What do you think?

**Comment by LeoniePhiline** [comment]
Sounds good - thanks!
