### ISSUE TITLE
remove whitespace from KEY in ext_tables.sql

### ISSUE THREAD

**Issue by aWuttig** [TYPO3-Solr/ext-solr#1197]
please remove whitespace after comma from 

https://github.com/TYPO3-Solr/ext-solr/blob/master/ext_tables.sql#L125

and

https://github.com/TYPO3-Solr/ext-solr/blob/master/ext_tables.sql#L126

because this will lead to problem during DB Compare.

**Comment by thomashohn** [comment]
Thx :-)

**Comment by aWuttig** [comment]
Unfortunatly you forgot one whitespace in https://github.com/TYPO3-Solr/ext-solr/blob/master/ext_tables.sql#L126

**Comment by thomashohn** [comment]
Damm - will remove that one too 👍
