### ISSUE TITLE
[TASK] Proofread documenation

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#1222]
We should proof read the documentation and check if there is stuff that is outdated.

[ext-solr.pdf](https://github.com/TYPO3-Solr/ext-solr/files/886239/ext-solr.pdf)

**Comment by irnnr** [comment]
I'll try to look into this

**Comment by dkd-kaehm** [comment]
I noticed following things:

* The links are working but not marked as links
* Sentence "All of these installers can be used to setup a plain, reboot save solr server:"  what does reboot mean?
* Chapter "Install EXT:solr" should begin with composer variant and notice that composer way is recommended
* to be continued
