### ISSUE TITLE
Determine nested root pages properly

### ISSUE THREAD

**Issue by kraftb** [TYPO3-Solr/ext-solr#1223]
When siteroot pages are nested the rootpage does not get detected properly. Instead always the lowest-level root page will get returned: The root page (is_siteroot flag set) which is nearest to the pagetree root.

Reason for this is in:
ApacheSolrForTypo3\Solr\System\Page\Rootline::getRootPageId() in line 95:
https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/System/Page/Rootline.php#L95

Instead of doing a "break" the loop will continue and thus deliver the most top-level root page instead of the root-page being "responsible" for the current page.

This issue will not have any effect if root pages are not nested but all are children of some common non-root-page parent page or are directly at the page tree root level.

**Comment by irnnr** [comment]
Nested root pages are not supported, they're not considered good practice.
