### ISSUE TITLE
[BUG] Solr Root Page in user configuration is not cleared after reinitialization of Solr connections

### ISSUE THREAD

**Issue by levitin** [TYPO3-Solr/ext-solr#1234]
## Preconditions

TYPO3 version: 8.7.0-dev, 6.2.25

Given an installed ext-solr extension with a configured and working connection for TYPO3 domain "Domain1" (Root Page ID = 1)

## How to reproduce

1) Copy TYPO3 domain "Domain1" and call it "Domain 2" (Let's say the new Page ID = 38)
2) Disable Solr on Domain 1 with 
```
plugin.tx_solr.enabled = 0
```
3) Reinitialize Solr Connections in toolbar menu

If you now change in Search module, you will see, that there is only one active connection to Domain 2 available (that's so far correct), but solr is still trying to establish a connection to Domain 1.

![broken_solr_connections](https://cloud.githubusercontent.com/assets/3276278/24648948/ae21917c-1925-11e7-94c3-c71d59011406.png)

## Initial analysis

Solr extension saves the current module data as a serialized object of `ApacheSolrForTypo3\Solr\Domain\Model\ModuleData` in backend user configuration (table `be_users` -> `uc`). Among other things, it contains the Solr Root Page`ApacheSolrForTypo3\Solr\Site`, the current user has successfully visited in search module for the last time. 

When search module is opened after the reinitialization of Solr connections again, the last active Solr Root Page is read out from the user configuration, regardless whether the corresponding Solr configuration and connection still exist.

## Expected behavior

One of the possible solutions would be to clear the stored Solr Root Page in module configuration for each backend user after reinitialization of Solr connections.

**Comment by timohund** [comment]
I would propose to detect if the configuration is invalid, since otherwise you might need to update hundrests of users what could be very slow. I would propose to fall back to the first valid site if the site is invalid.

@levitin Did you really check this with the latest EXT:solr version? I thought this is allready fixed.

**Comment by timohund** [comment]
I though this was fixed here: https://github.com/TYPO3-Solr/ext-solr/pull/158/commits/f9a8b9302e5001c23774503ae80bafd5de7da9af

**Comment by levitin** [comment]
> Did you really check this with the latest EXT:solr version? 

I reproduced the described bug with the latest EXT:solr version '6.1.0-dev'.

> I thought this is allready fixed.

Then you thought unfortunately wrong :)

> I would propose to fall back to the first valid site if the site is invalid.

👍 

> I would propose to detect if the configuration is invalid

Yes, exactly this case is missing in `EXT:solr/Classes/Controller/AdministrationController.php::resolveSite`

**Comment by webfacer** [comment]
Does this effect that it also call wrong Root Page? because this happens to me. After i turned the debug on it throws old request_url. I also remove the old Root Id

**Comment by dkd-kaehm** [comment]
@webfacer Yes, it uses the wrong site from be_user uc.

**Comment by webfacer** [comment]
that wasn´t this issue. That happens because of to many domains where decleared. But the order is also important. If i change the order of Domainrecords it works. That means if it takes some other Domainrecord then the one it is set as root check your order of Domainrecords. May be your issue is there.
