### ISSUE TITLE
[RecordMonitor] Monitor changes through Extbase repositories

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/ext-solr#126]
When records are updated through Extbase they are not detected by the record monitor as these changes do not go through TCEmain.

Use signals in Extbase repositories to detect these changes.

**Comment by Mabahe** [comment]
I need this in my current project, so I will 	shortly implement and share this. Did you already have a detailed idea?

**Comment by irnnr** [comment]
nope, patches welcome!

**Comment by hhoechtl** [comment]
Feel free to generalize my solution: https://gist.github.com/hhoechtl/cd57e7b68e8fe6642165

**Comment by Mabahe** [comment]
Cool, thx, this is a good start.

**Comment by irnnr** [comment]
Linking Marc Bastian's WIP patch: https://github.com/Mabahe/ext-solr/commit/0c3d6db8fcec0410666f1c70ecca997096543ac2

**Comment by Mabahe** [comment]
I see a reference above your comment.

**Comment by irnnr** [comment]
Saw that too after I added the link :)

**Comment by Mabahe** [comment]
Former patch versions could be found here:
Based on ext-solr 8.1.x (TYPO3 8.7), tested and running in production: https://github.com/Mabahe/ext-solr/tree/feature/release-8.1.x/126-extbase-domain-observer
Based on ext-solr 10.0.x, rebased by @dkd-kaehm, but not tested by me: https://github.com/Mabahe/ext-solr/tree/feature/release-10.0.x/126-extbase-domain-observer
