### ISSUE TITLE
Update to 6.1.0 breaks results pagination

### ISSUE THREAD

**Issue by markuskobligk** [TYPO3-Solr/ext-solr#1274]
After upgrading EXT:solr 6.0.0 to 6.1.0 and EXT:solrfluid to 2.0.0 the pagination on the results page is broken after the first click on any pager link.

All links then look like this:
`http://domain.tld/suche.html?q=###q###&tx_solr%5Bpage%5D=###q:tx_solr:page###`

**Comment by alappe** [comment]
I don't have that behaviour. Weird that you get markers when using solrfluid – are you sure you have the solrfluid plugin selected to render the results/pager?

**Comment by markuskobligk** [comment]
Yes, it is definitely solrfluid.
Maybe the Solr viewhelper that creates the pagination URLs does something wrong there, 
I did not have the time to have a closer look at it last week,

**Comment by markuskobligk** [comment]
Appendix: This happens only, if URL Rewriting is activated

**Comment by timohund** [comment]
I think the problem could be that typolink calls get cached (for facets for performance reasons), maybe this cache needs to be disabled when realurl should is used.

**Comment by markuskobligk** [comment]
In my case the problem was a double url_encoding. The parameters get encoded in the SearchUriBuilder of Solrfluid and CoolUri did the same again internally. That broke the links build by the SearchUriBuilder...

**Comment by timohund** [comment]
@markuskobligk so can we close this issue, i would say who encodes something also needs to decode it, and both is done by solr. Even when another component does that again it should be ok when it does both (encoding and decoding)?

**Comment by markuskobligk** [comment]
Agree, this can be closed.
