### ISSUE TITLE
ConfigurationPageResolver::getPageIdsWithTemplateInRootLineOrderedByDepth does not order by depth

### ISSUE THREAD

**Issue by LeoniePhiline** [TYPO3-Solr/ext-solr#1275]
The method \ApacheSolrForTypo3\Solr\System\Configuration\ConfigurationPageResolver::getPageIdsWithTemplateInRootLineOrderedByDepth() does not actually order anything by depth.

This is a problem in a setup where I have a main site with root template, and some subsites under path /Shortcuts/, which catch domains (are root pages with a root template with empty PAGE object) and just redirect to paths inside the main site.

When entering \ApacheSolrForTypo3\Solr\System\Configuration\ConfigurationPageResolver::getPageIdsWithTemplateInRootLineOrderedByDepth(), $pageIdsClause becomes 0,7882,7381,2, where 2 is the site root page and 7882 is the nested root page, which is used as redirecting domain catcher.

Here, the method name claims that the deepest nested page ID will be returned (7882), but no ordering happens. Instead, the record with uid=2 appears first in the database and thus first in the DB query results. So in the end, 2 is chosen and returned, instead of 7882.

**Comment by dkd-kaehm** [comment]
Do we need to resolve closest page in tree regarding to nesting position but not by ordering PID number?

@LeoniePhiline: could you please provide a test case or fixture with usage example?

**Comment by dkd-kaehm** [comment]
### Fixed on EXT:solr 11.5.x+ in !!![TASK] Improve and Fix TSFE Initialization https://github.com/TYPO3-Solr/ext-solr/commit/a246cb8e34d80da6227445c0c800620f16264a00

It uses the "closest root page" feature under the hood. See `getClosestPageIdWithActiveTemplate`:

https://github.com/TYPO3-Solr/ext-solr/blob/ddcbc3bb6034ec3a02f410ee1a6b2ff961ff594d/Classes/FrontendEnvironment/Tsfe.php#L324-L347
