### ISSUE TITLE
hiding a news shows error 1309272922

### ISSUE THREAD

**Issue by eBornstein** [TYPO3-Solr/ext-solr#1276]
If you hide a news with the context menu, the following error appears.
Hiding with button shows no error but the loading has no end.

![](https://cloud.githubusercontent.com/assets/17193249/25118614/4a8ca64a-2417-11e7-9f54-9244c38b3c02.png)

![](https://cloud.githubusercontent.com/assets/17193249/25118616/4ab02f16-2417-11e7-8ce3-2951d1731b35.png)

The pid 65 is the folder containing the news and its not marked as root page.
Here is the errorpage behind the link: https://wiki.typo3.org/Exception/CMS/1309272922
I use ext:solr 5.1.1

The bugreport here (https://github.com/georgringer/news/issues/304) was unfortunately rejected.

**Comment by dkd-kaehm** [comment]
@eBornstein please try with currently supported version, maybe it is already fixed.
Please see the [versionsmatrix](https://github.com/TYPO3-Solr/ext-solr/blob/master/Documentation/Appendix/VersionMatrix.rst)
We support two latest CMS LTS versions.

**Comment by dkd-kaehm** [comment]
@eBornstein 
I asked about this issue in Slack see [the message in slack](https://typo3.slack.com/archives/C02FF05Q4/p1493109886400996)
: "doesn’t happen on my environment. TYPO3-CMS `7.6.15`, EXT:news `5.3.1`, EXT:solr `6.1.0`"

You need Apache Solr 6.3 for EXT:solr 6.1.

**Comment by timohund** [comment]
@eBornstein 

Is the sysfolder 65 inside of a sideroot? Can you maybe add a screenshot of your tree structure, where the news is located?

* There should not be a problem, when the news is inside a siteroot.
* When the newsfolder is outside the sideroot, the sysfolder should be refrenced as additionalPageId in the news queue configuration (and in the extension configuration "Enable/Disable record tracking outside siteroot" should be active). If you do not want to index the news you should disable solr on the sysfolder by typoscript "plugin.tx_solr.enabled = 0"

Can you check this and give me some feedback?

**Comment by timohund** [comment]
I guess this issue was resolved with #1299. Since now feedback was provided i'll close this issue. If the issue remains, please open a new one.
