### ISSUE TITLE
Page Indexer HTTP request failed

### ISSUE THREAD

**Issue by klodeckl** [TYPO3-Solr/ext-solr#1281]
I sometimes get the error from scheduler:

www1.hostxyz.de:/var/www/htdocs/ - core: Core: Error handler (BE): PHP Warning: file_get_contents(https://www.hostxyz.de/index.php?id=376&L=0): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
in /var/www/htdocs/typo3conf/ext/solr/Classes/IndexQueue/PageIndexerRequest.php line 378

Until now I could not find out when the error occurs and when the error does not occur.
TYPO3 7.6.16
ext solr 6.0.0
PHP 7.0.x

**Comment by dkd-kaehm** [comment]
@klodeckl Hi,
it seems, that your page with uri `/index.php?id=376&L=0` is broken. 

Please try to get the exactly error message in the logs(maybe trying to call this uri in browser or curl).

PS: Please use Solr 6.1 this should be compatible with your current setup.

PPS: Please feel free to reopen this issue, if you are sure that your page does not send WSOD or 500.

**Comment by klodeckl** [comment]
If I open the url in the browser, it works. Also when trying it with a PHP script with file_get_contents or even with wget it works.

I will update soon, but I think this is not the problem, I got the problem since many versions of the ext.

Any other hint?

**Comment by timohund** [comment]
@klodeckl is allow_url_fopen active for php, what does your report say?

**Comment by klodeckl** [comment]
Yes it is on. The problem only occurs sometimes.

**Comment by dkd-kaehm** [comment]
Not sure, but if it occurs "sometimes", then try to log/track the OFs and FDs in your system. Maybe it occurs if to many files are opened at same time. 

see: https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by klodeckl** [comment]
I don’t know why, but it seems that the issue is gone away. Maybe because I updated all extensions and TYPO3 or a config issue.
