### ISSUE TITLE
Clarify Search>Index Maintenance>>[Reload Configuration] button purpose.

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#1283]
It seems that the button currently does not have any important point in backend module, except applying changes, which were done with external tools.

Also the create-, delete-, updateActions for Stop-words and Synonyms already reloading the cores.

Question: Is this button/action needed in Backend Module?

**Comment by thomashohn** [comment]
I think the button is needed - but the text is misleading. You might not have access to start/stop the solr Server so in that case it would be nice to be able to reload the core.

**Comment by timohund** [comment]
@dkd-kaehm Can we close this issue?

**Comment by dkd-kaehm** [comment]
Yes, now its cleared.
