### ISSUE TITLE
[FEATURE] Make facet.method configurable for suggestions

### ISSUE THREAD

**Issue by alappe** [TYPO3-Solr/ext-solr#1286]
Recently we were having an issue with Solr throwing exceptions like »Solr Exception: Too many values for UnInvertedField faceting on fieldspell« when one of our indexes grew up to a certain size and suggestion was used. This is exactly what has been reported six years ago here:

http://lists.typo3.org/pipermail/typo3-project-solr/2011-September/000595.html

and the fix still works fine. While `facet.method=enum` is supposed to be a slower method, we found the performance to still be very good, thus a great fix.

Since this »feature request« has been reported six years ago and then was dropped, I just wanted to post it again – maybe this time you want to enable a configuration value for this.

For now we're using XClass which in this case is simple enough and we are happy with it.

Best
Andreas

**Comment by timohund** [comment]
@alappe it would be nice, when you could provide a pull request to implement that and add it to the documentation. Do you think you have the time for that?

**Comment by dkd-kaehm** [comment]
@alappe 
could you please post the solution here?

**Comment by alappe** [comment]
From the old project:

```php
<?php
namespace Z7\Bootstrap\XClass\Solr;

/**
 * Reasons:
 * http://lists.typo3.org/pipermail/typo3-project-solr/2011-September/000595.html
 * https://code.z7.io/entega/extranet/issues/173
 */
class SuggestQuery extends \ApacheSolrForTypo3\Solr\SuggestQuery
{
    public function getQueryParameters()
    {
        return array_merge(
            parent::getQueryParameters(),
            [
                'facet.method' => 'enum'
            ]
        );
    }
}
```

**Comment by markuskobligk** [comment]
@alappe Thx for sharing, worked well for me on EXT:solr 8.1.2

@dkd-kaehm 
For EXT:solr 9 it should be:
```
public function __construct($keywords, $solrConfiguration = null)
{
    parent::__construct();
    $this->addParam('facet.method', 'enum');
}
```

Instead of hard coding the facet method here it could be read from the TS settings of the suggest section with a new optional option there (documentation has to be updated and maybe some tests as well).
`plugin.tx_solr.suggest.facetMethod = ...`

`$this->addParam('facet.method', $this->configuration['facetMethod']);`
