### ISSUE TITLE
Sitemap sites are not reindex when source content is updated

### ISSUE THREAD

**Issue by lorenzulrich** [TYPO3-Solr/ext-solr#1289]
Scenario:

* Sitemap page showing title and some content from all subpages
  * Subpage 1 with content
  * Subpage 2 with content
  * ...

When I update content on the subpages, this also affects the Sitemap page. But reindexing of the site is not triggered.

I know this is not easy to achieve because Solr would need to "know" which content is used on which page. Are there any considerations to make this work?

**Comment by dkd-kaehm** [comment]
Hello @lorenzulrich, do you want to reindex sitemap page on each change?

Not sure if that works, but since 6.1
