### ISSUE TITLE
Shouldn't initializeHttpHost also set HTTP_HOST without realurl?

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Solr/ext-solr#132]
Why does initializeHost require realurl?
https://github.com/TYPO3-Solr/ext-solr/blob/abd9baaa9bb5d122f22cb9f0e3d574e3b34516f3/Classes/Task/IndexQueueWorkerTask.php#L305

From what I know typolink itself already respects Hosts with >= 6.2 (and probably earlier), although it might depend on TypoScript settings but better to set it then not :)

**Comment by irnnr** [comment]
It does not depend on real url, but the other way around... realurl depends on the HTTP_HOST variable to be set, which for obvious reasons is not the case in CLI environment. That method sets HTTP_HOST so that realurl correctly creates URLs.

... just like the method's phpdoc says

**Comment by AndreasA** [comment]
No, I meant regarding the check, I think the variable also needs to be set without realurl because if you check ContentObjectRenderer typolink method there are various Domain checks in it that also use the HTTP_HOST variable.

**Comment by AndreasA** [comment]
Created a corresponding PR
https://github.com/TYPO3-Solr/ext-solr/pull/133

**Comment by irnnr** [comment]
ok, makes sense now. Thanks for clarifying!

**Comment by AndreasA** [comment]
PR was merged so this can be closed.
