### ISSUE TITLE
[BUG] Facet option selectingSelectedFacetOptionRemovesFilter not supported

### ISSUE THREAD

**Issue by dkd-friedrich** [TYPO3-Solr/ext-solr#1351]
Facet option `selectingSelectedFacetOptionRemovesFilter` is currently not working in the new Fluid templating.

We should readd this feature or at least update the documentation, imho the facet view helper `addFacetItem` could be extended to recognize this setting.

As long as this feature isn't reintegrated a condition could be used in the templates:
```
{f:if(condition: '{0:1,1:1} == {0: \'{option.selected}\', 1: \'{option.facet.configuration.selectingSelectedFacetOptionRemovesFilter}\'}', then: '{s:uri.facet.removeFacetItem(facet: facet, facetItem: option)}', else: '{s:uri.facet.addFacetItem(facet: facet, facetItem: option)}')}
```

**Comment by dkd-friedrich** [comment]
As there are several options to achieve this behaviour with Fluid, we decided to drop this configuration option, the documentation will be updated and examples will be added.

**1.  Conditions in default Facet template**

_7.6_ 
```
{f:if(condition: '{0:1,1:1} == {0: \'{option.selected}\', 1: \'{option.facet.configuration.selectingSelectedFacetOptionRemovesFilter}\'}', then: '{s:uri.facet.removeFacetItem(facet: facet, facetItem: option)}', else: '{s:uri.facet.addFacetItem(facet: facet, facetItem: option)}')}
```
_8.7_
```
{f:if(condition: '{option.selected} && {option.facet.configuration.selectingSelectedFacetOptionRemovesFilter}', then: '{s:uri.facet.removeFacetItem(facet: facet, facetItem: option)}', else: '{s:uri.facet.addFacetItem(facet: facet, facetItem: option)}')}
```
**2 Separate partial**

1. TypoScript
plugin.tx_solr.search.faceting.<facet>.partialName = xyz
2. Partial xyz
```
{f:if(condition: '{option.selected}', then: '{s:uri.facet.removeFacetItem(facet: facet, facetItem: option)}', else: '{s:uri.facet.addFacetItem(facet: facet, facetItem: option)}')}
```

**Comment by timohund** [comment]
As discussed i'll remove the setting from the documentation and add a note / FAQ entry in the documentation for that.
