### ISSUE TITLE
[TASK] Page Indexer missing Proxy settings

### ISSUE THREAD

**Issue by johanneshahn** [TYPO3-Solr/ext-solr#1354]
Hi there,

i had an issue with Page Indexing through a proxy. Adding the proxy manually to the stream context Options in Class ApacheSolrForTypo3\Solr\IndexQueue\PageIndexerRequest ... Function:  getUrl

```
$options = [
            'http' => [
                'header' => implode(CRLF, $headers),
                'timeout' => $timeout,
                'proxy' => 'tcp://proxy.halligalli.net:80/'
            ],
        ];
```

solved my problem.

**Comment by timohund** [comment]
@johanneshahn Do you have the time to create a patch, to make it configureable for the frontendIndexing? It would be nice to have a patch including test cases and documentation.

**Comment by johanneshahn** [comment]
@timohund Yes its possible for me to write a patch. Why not using Typo3 GeneralUtility::getUrl? ... instead of own file_get_content implementation?

**Comment by timohund** [comment]
@johanneshahn as long as it is possible to configured to:

* Allow self signed certificates
* Set the headers and timeout as we need them

I did not had a closer look on this be now, but when changig that we should make sure that there is an alternative/support for these setups.

**Comment by johanneshahn** [comment]
@timohund ok i'll keep that in mind ;)

**Comment by andreknieriem** [comment]
Hi any progress here so far? I need the same functionality.

**Comment by timohund** [comment]
@andreknieriem No currently not. If you want you can create a patch or we can implement it for you, based on our support conditions.

**Comment by timohund** [comment]
Since #1837 we use TYPO3's guzzle integration for page indexing. This can be configured to use a proxy: https://forum.typo3.org/index.php/t/216306/typo3-8-7-hinter-proxy-guzzle

Therefore i'll close this issue. If you have anything else, please open a new issue.
