### ISSUE TITLE
date range facet - on tx_news datetime will not work

### ISSUE THREAD

**Issue by rnakielski** [TYPO3-Solr/ext-solr#1362]
I can't get this to work (for facetting tx_news - news by field datetime):
```
            facets.date{
                type = dateRange 
                label = Datum
                #field = datetime_stringS
                #field = created
                field = crdate
                dateRange {
                    start = NOW/DAY-10YEARS
                    end = NOW/DAY+1YEAR
                    gap = +1DAY
                }
             }

```
It works using field created - but not with datetime or crdate from the tx_news database. I tried with and without
```
         fieldProcessingInstructions{
            datetime_stringS = timestampToIsoDate
            crdate = timestampToIsoDate
        }
```

SOLR reports a "Bad Request" even when the facet input is not used. 

This is the part of the query: `&facet.range=datetime_stringS&f.datetime_stringS.facet.range.start=NOW%2FDAY-1YEAR&f.datetime_stringS.facet.range.end=NOW%2FDAY%2B1YEAR&f.datetime_stringS.facet.range.gap=%2B1DAY`

By the way: there is a documentation Bug in the extension Manual:
```
plugin.tx_solr.search {
    faceting = 1
    faceting {
        creationDateRange {
            label = Created Between
            field = created
            type = dateRange
        }
    }
}
```

I think this should be:
```
  faceting = 1
    faceting {
        facets{
        creationDateRange {
```

Or is this my mistake?
I can't be the first trying ths?

**Comment by timohund** [comment]
Your second proposal is correct, but this was allready fixed in the documentation today (https://github.com/TYPO3-Solr/ext-solr/pull/1353) or where is that from? Can we close the issue?

**Comment by rnakielski** [comment]
I am using EXT:solr 5.1.1 (my Hoster does not allow V6)

I managed to get the date facet working. 
I had to define the datetime field for SOLR as a *_tDateS

so in index.queue I defined:

```
plugin.tx_solr.index.queue{
    news = 1
    news{
        table = tx_news_domain_model_news
        fields {
            ...
 	    datetime_tDateS = datetime
           ... 
```
in index I defined this field

```
 index{
        fieldProcessingInstructions{
            datetime_tDateS = timestampToIsoDate
        }
```
and the facet like this:

```
            facets.date{
                type = dateRange 
                label = Datum
                field = datetime_tDateS
            }
```

This way it works without a "Bad Request" response from SOLR.

Ticket can be closed.

**Comment by timohund** [comment]
@rnakielski Thanks for your response, i'll close the issue
