### ISSUE TITLE
[TASK] Use doctrine in ApacheSolrForTypo3\Solr\ContentObject\Relation

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#1370]
DatabaseConnection a.k.a. $["TYPO3_DB"] has been marked as deprecated in TYPO3 v8 and will be removed in TYPO3 v9. Please use the newly available ConnectionPool and QueryBuilder classes.

We should migrate the Relation class to use the QueryBuilder.

**Comment by timohund** [comment]
Split issue from #1165

**Comment by mbresch-sf** [comment]
Okay, will fix this task.

**Comment by dkd-kaehm** [comment]
@mbresch-sf Do you need help here? What is missing?
