### ISSUE TITLE
[TASK] Migrate SolrConfigurationStatus::getPages to use PagesRepository

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#1372]
Currently SolrConfigurationStatus::getPages uses $GLOBALS['TYPO3_DB'] we should use the PagesRepository (ApacheSolrForTypo3\Solr\System\Records\Pages) instead. Maybe the method findAllRootPages can be used. 

The report currently does some additional checks ( deleted = 0 AND hidden = 0 AND pid != -1 AND doktype IN(1,4)), we should check if we can use findAllRootPages or add a new method with a different name and these additional checks.

Along with that we should check if the report is coverd with tests.

**Comment by timohund** [comment]
Split issue from #1165

**Comment by mbresch-sf** [comment]
Maybe I can take a look of this tonight
