### ISSUE TITLE
7.6.0 RTE linkhandler does not open after save because TSFE is not removed

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Solr/ext-solr#138]
Due to reading configuration of solr when saving records a temporary TSFE object is created.
However, it is not removed afterwards which results in wrong check if TSFE is checked (e.g. \TYPO3\CMS\Rtehtmlarea\RteHtmlAreaApi::writeTemporaryFile).

A specific case is the above mentioned, a RTE Link handler will not open after save because a temporary file path is missing the "../"

**Comment by AndreasA** [comment]
Bugfix PR:
https://github.com/TYPO3-Solr/ext-solr/pull/137

**Comment by timoschmidt** [comment]
Thanks for your pull request, i'll check it as soon as possible!

**Comment by AndreasA** [comment]
There is already a fix in 7.6.1 that will improve the check in core too but I still think we should clean up properly.

**Comment by timoschmidt** [comment]
Was merged, so we can close this issue?

**Comment by AndreasA** [comment]
Yes it can be closed

**Comment by irnnr** [comment]
To automatically close an issue when the PR gets merged, just mention "Fixes #xxx" in your commit message.
