### ISSUE TITLE
version 6.1.1 is not available at packagist 

### ISSUE THREAD

**Issue by mediaessenz** [TYPO3-Solr/ext-solr#1387]
It seems that version 6.1.1 is not available via packagist at the moment.
I have this requirement in my root composer.json, which worked until the last days:
```
"apache-solr-for-typo3/solr": "6.1.1"
```
Now I get this error message during composer update:
```
[Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - The requested package apache-solr-for-typo3/solr 6.1.1 exists as apache-solr-for-typo3/solr[7.0.x-dev, dev-master] but these are rejected by your constraint.
```

**Comment by timohund** [comment]
Is it maybe a local issue or a packagist issue? Seems to be available here: 

https://packagist.org/packages/apache-solr-for-typo3/solr#6.1.1

**Comment by timohund** [comment]
Tried it locally:

/v/w/7.6.local.typo3.org $ composer require "apache-solr-for-typo3/solr:6.1.1"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                                 
Package operations: 1 install, 0 updates, 0 removals
  - Installing apache-solr-for-typo3/solr (6.1.1): Downloading (100%)         
Writing lock file
Generating optimized autoload files
Generating  class alias map file
...

Seems to be no issue, if the issue still remains please open a new issue
