### ISSUE TITLE
Different type for index queue configuration

### ISSUE THREAD

**Issue by klodeckl** [TYPO3-Solr/ext-solr#1402]
I have two indexing queue configurations, both for extension irfaq. For one I would like to set a different type (not the table name) to filter this records separately via facets, but it seems this is not possible. 

If I set the field type in the indexing queue configuration, I get an exception:

1435441863: ApacheSolrForTypo3\Solr\IndexQueue\InvalidFieldNameException: Must not overwrite field .type in /var/www/htdocs/typo3conf/ext/solr/Classes/IndexQueue/AbstractIndexer.php:87

**Comment by timohund** [comment]
Type is an internal field, that should not be overwritten, please use your own field for that.

**Comment by klodeckl** [comment]
So I have to write a new field to every index item for that separately and use this as a facet, okay.
