### ISSUE TITLE
Stop words and synonyms in backend module don’t work

### ISSUE THREAD

**Issue by klodeckl** [TYPO3-Solr/ext-solr#1403]
I want to add stop words or synonyms via the backend module, but no stop words or synonyms get saved. I used the current configset ext_solr_6_1_0.

**Comment by timohund** [comment]
@klodeckl can you analyze it. Maybe tis is related to your setup, since this is tested with an automated test: https://github.com/TYPO3-Solr/ext-solr/blob/master/Tests/Integration/SolrServiceTest.php Please provide some more information on that.

**Comment by klodeckl** [comment]
Sure, but how to analyse it?

**Comment by klodeckl** [comment]
Solved! It was a write permission problem in the solr config.
