### ISSUE TITLE
Evaluate use of curl_multi_getcontent() to index pages

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/ext-solr#141]
Right now when indexing pages one page is indexed after the other. The process is slow for multiple reasons. We should check however, whether it is possible to use curl_multi_*() to index multiple pages at the same time. 

Whether we can use multi curl also depends on whether that feature is available on common hosting packages.

http://php.net/manual/en/function.curl-multi-getcontent.php

**Comment by dkd-dobberkau** [comment]
I still like the idea to create a special page type that would only hold the content of the page without the menus and other non indexed stuff. I am sure this would speed up indexing of pages quite well.

**Comment by timoschmidt** [comment]
I like both ideas maybe we do a profiling and check where most of the performance is lost. Reusing curl handles is definitly a good idea.

**Comment by irnnr** [comment]
@dkd-dobberkau yes, but that's unrelated/a separate issue

**Comment by kasperligaard** [comment]
Maybe make it a TYPO3 8 LTS only feature and then use Guzzle for it? See for instance https://blog.madewithlove.be/post/concurrent-http-requests/ (or create a Guzzle extension that would be added as a dependency for TYPO3 7 LTS users).

I would expect that Guzzle handles the presence or absence of curl_multi_getcontent transparently.

Another benefit of using Guzzle would be for users of New Relic (and likely other Application Monitoring services) is that Guzzle actions are automatically detected and statistics gathered nicely in the interface (at Systime we are looking forward to switching to TYPO3 8 and see Guzzle stats in New Relic :-)).

**Comment by timohund** [comment]
@kasperligaard I think using guzzle is a good idea. The next version 6.1.0 will still support 7.6 LTS i would propos to do this, when 7.6 support will be dropped (In EXT:solr version 7.0.0)

**Comment by kasperligaard** [comment]
I agree. Another question: Are there any public and updated roadmap with planned/projected dates for release of 6.1, 7.0 etc. ..?
