### ISSUE TITLE
[TASK] Make custom template configureable

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#1412]
In #1325 we added support for custom templates. To make this more friendly for editors and less error prone.

Todo:

* Allow to configure a set of templates
* Use this set in the flexform and make sure that overwriting in the typoscript still works

**Comment by georgringer** [comment]
Just a hint there: if en editor can choose templates, e.g. by defining a path, it opends a security issue as any html template can be used for e.g. XSS

**Comment by timohund** [comment]
@georgringer The path needs to be configured with TypoScript
