### ISSUE TITLE
BUG in 6.1.1 with multiple search forms on one page

### ISSUE THREAD

**Issue by BlaupauseDaniel** [TYPO3-Solr/ext-solr#1420]
Dear TYPO3 Solr Team,

first of all thanks a lot for your great work. I ran into a problem and found a fix for it so I thought I'd share it with you. 

I was trying to have two search fields on one page. One for a search through the whole page and on pre filtered one (in my case only "tt_address" records). I ran into a problem with the autocomplete. The variable "tx_solr_suggestUrl" gets defined for every content record. Therefore  the "tx_solr_suggestUrl" is always the one of the last search form in the source code.

To avoid this I'd suggest the following changes:
**typo3conf/ext/solr/Classes/SuggestFormModifier.php**
After line 98 define "$markers['suggest_url_plain'] = $suggestEidUrl;"

**typo3conf/ext/solr/Resources/Templates/PiResults/results.htm**
Add "data-suggest-url="###FORM.SUGGEST_URL_PLAIN###"" to any class="tx-solr-q" input

**typo3conf/ext/solr/Resources/JavaScript/EidSuggest/suggest.js**
In line 14 change

> jQuery('.tx-solr-q').autocomplete({

to

> jQuery('.tx-solr-q').each(function(){
>  		if($(this).attr('data-suggest-url_plain')){
> 			var tx_solr_suggestUrl = $(this).attr('data-suggest-url_plain');
> 		}
>  		$(this).autocomplete({

_$markers['suggest_url_plain'] could also be overwritten but I left it in for backwards compatibility of external templates_

I hope this helps and might find its way in an new 6.X Extension Version. 
The behavior in the current 7.X version seems to be different but I couldn't test the behavior since I don't have a 8.X. test environment.

–––––––––––––––––––––––––––––––

**My System Info:**
TYPO3 version:  7.6.20
Solr version: 6.5.0
Solr Extension: 6.1.1
PHP version: 7.0.21

**Comment by timohund** [comment]
@BlaupauseDaniel Thanks for the detailed Feedback. Since the old templating is not supported anymore, i would not create a patch for that. If you want, feel free to create a pull request for the 6.1.x branch.
