### ISSUE TITLE
[BUG] Wrong record localization on SOLR_RELATION content types

### ISSUE THREAD

**Issue by onigunn** [TYPO3-Solr/ext-solr#1428]
Since updating to TYPO3 7.6 from 6.2 we seem to have an issue regarding indexing custom records in our multiple language setup. Each language has its own core, which is configured due TS.

### Expected behavior
Each core holds documents in related/configured language.

### Actual behavior
On each index run, first document is correct, after this, all other documents are indexed in the last configured language. In my given example config this results that all documents after the first have french content.

After debugging I setteled down at one point. `Relation->getTranslationOverlay` calls`$GLOBALS['TSFE']->sys_page->getRecordOverlay` to create the overlay. After the first record `$GLOBALS['TSFE']->sys_language_uid` doesn't change anymore and sits on the last language uid.

I'm not quite sure if this is an core bug or a solr ext. problem. If you point to the core guys, just let me know and I'll open an issue on forge.

### Example Config
```
plugin.tx_solr.solr.path = /solr/core-en/

[globalVar = GP:L = 1]
  plugin.tx_solr.solr.path = /solr/core-de/
[global]

[globalVar = GP:L = 2]
  plugin.tx_solr.solr.path = /solr/core-fr/
[global]
```

#### IndexQueue Config
```
plugin.tx_solr.index.queue {
  products = 1
  products {
    table = tx_og_domain_model_product

    fields {
      title = name

      content = SOLR_CONTENT
      content {
        cObject = COA
        cObject {

          10 = SOLR_RELATION
          10 {
            localField = details
            foreignLabelField = bodytext
            singleValueGlue = | |
          }

          20 = SOLR_RELATION
          20 {
            localField = dimensions
            foreignLabelField = bodytext
            singleValueGlue = | |
          }

          30 = SOLR_RELATION
          30 {
            localField = categories
            foreignLabelField = name
            singleValueGlue = | |
          }

        }
      }

    language_intS = SOLR_CONTENT
        language_intS {
            field = sys_language_uid
        }

      url = TEXT
      url {
        typolink.parameter = {$plugin.tx_ogp.settings.productPagePid}
        typolink.additionalParams = &tx_og_ogfe[controller]=Product&tx_og_ogfe[action]=search&tx_og_ogfe[product]={field:uid}&L={field:__solr_index_language}
        typolink.additionalParams.insertData = 1
        typolink.useCacheHash = 0
        typolink.returnLast = url
      }
    }

  }

}
```

### Enviorment
PHP: 7.0.21-1
TYPO3: 7.6.20
ext-solr: 6.1.0
SOLR Server: 6.3.0

**Comment by timohund** [comment]
@onigunn Can you try this with the latest EXT:solr 6.1.x release 6.1.2? This could be related to: https://github.com/TYPO3-Solr/ext-solr/pull/1418

**Comment by onigunn** [comment]
Thanks @timohund - yes. Is working now. Just for documentation: We don't have content_fallback as language_mode. In our setup it is strict.

I close this issue.
