### ISSUE TITLE
ExtensionManagementUtility::registerExtDirectComponent has been removed with CMS9

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Solr/ext-solr#1440]
The usage of ExtJS has been marked as deprecated, therefore also \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::registerExtDirectComponent` has been deprecated with 8 and removed with 9.

IMO the whole functionality to trigger a connection update for a specific page can be removed as there is the action for all pages in the top bar. If you think this feature is useful it must be migrated to the new context menu. (drop a note if you need help there)

**Comment by timohund** [comment]
Thanks @georgringer for pointing this out. Is it the same issue as this? https://github.com/TYPO3-Solr/ext-solr/issues/1097. There is also a comment on that issue that might during implementation. If you want to work on that, this would be nice for sure.

**Comment by georgringer** [comment]
closed as duplicate of #1097
