### ISSUE TITLE
Provide Solr Docker containers through install script

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/ext-solr#15]
Add install scripts that simply load/install ready made Docker containers with the correct Solr version for the extension.

This can also help during development to quickly switch between multiple Solr versions.

**Comment by dkd-dobberkau** [comment]
You mean something like: docker run -d -p 8983:8983 -t makuk66/docker-solr:5.2 ?

https://registry.hub.docker.com/u/makuk66/docker-solr/

**Comment by irnnr** [comment]
yes, that looks nice already

**Comment by lorenzulrich** [comment]
BTW, we're using https://github.com/obi12341/solr-typo3 (current version throws an error, see issues, but worked nicely in former versions).

**Comment by obi12341** [comment]
@lorenzulrich i fixed it

**Comment by lorenzulrich** [comment]
Thanks!

**Comment by irnnr** [comment]
This might be interesting as well, official Solr Docker image: https://hub.docker.com/_/solr/

**Comment by obi12341** [comment]
Updated to newest version: https://github.com/obi12341/solr-typo3

**Comment by DanielSiepmann** [comment]
On docker it's available as https://hub.docker.com/r/writl/solr-typo3/ .
I've already documented this docker image in PR #424 as it works out of the box very fine.

**Comment by timohund** [comment]
This can be one task in the codesprint.

Important:
* We should be able to start a solr server with the install script (provided with docker)
* All integration test, that use the installer as well need to work with the new script

**Comment by obi12341** [comment]
That would be fine, if wanted, I can help you with that

**Comment by timohund** [comment]
Since all the docker stuff is merged and we can use the Extension with the docker image and the installer, i close this issue.
