### ISSUE TITLE
News indexer (tt_news).Fail to build document URL to access restricted news detail page 

### ISSUE THREAD

**Issue by artur2000** [TYPO3-Solr/ext-solr#1540]
Hi, We have the following scenario:

TYPO3-Version 7.6.14
EXT:solr Version 5.1.0.
EXT:realurl Version 2.1.5.

Among others we run an indexer job for access restricted tt_news records, where the news details page is access restricted as well.
Now in the context of a cron job/ CLI environment the indexer isn't able to build the document URL for the news records.
All news records in question get a redirection URL to the login page.
Running the indexer from within TYPO3 backend everything is fine.
At the same time the page indexer has no problems building links to restricted pages even in cron job context.

Is this a known problem? Did I miss some detail in the docs?

For the record, this is our TypoScript-Configuration (field:tx_single_pid is our proprietary hack and gets always resolved correctly)

```
            tt_news {

                fields {
                    abstract = short
                    author = author
                    description = short
                    title = title
                    uid = uid
                    content = SOLR_CONTENT
                    content {
                        field = bodytext
                    }

                    category_stringM = SOLR_RELATION
                    category_stringM {
                        localField = category
                        relationTableSortingField = sorting
                        multiValue = 1
                    }

                    lang_intS = __solr_index_language
                    categoryMain_stringS = TEXT
                    categoryMain_stringS {
                        cObject = SOLR_RELATION
                        cObject {
                            localField = category
                            relationTableSortingField = sorting
                            singleValueGlue = ,
                        }

                        split {
                            token = ,
                            returnKey = 0
                        }
                    }

                    categoryid_intS = category
                    keywords = SOLR_MULTIVALUE
                    keywords {
                        field = keywords
                    }

                    url = TEXT
                    url {
                        typolink.parameter = {field:tx_single_pid}
                        typolink.parameter.insertData = 1
                        typolink.additionalParams =
&tx_ttnews[tt_news]={field:uid}&L={field:__solr_index_language}
                        typolink.additionalParams.insertData = 1
                        typolink.returnLast = url
                        typolink.useCacheHash = 1
                    }

                    sortAuthor_stringS = author
                    sortTitle_stringS = title
                }

                attachments {
                    fields = news_files
                }
            }

```

**Comment by timohund** [comment]
@artur2000 this bug is fixed in EXT:solr 6.1.3 can you update to this version?

**Comment by timohund** [comment]
This is the pull request that contains the fix: https://github.com/TYPO3-Solr/ext-solr/pull/1418

**Comment by artur2000** [comment]
Thank you, I will have look into it and report back.

**Comment by timohund** [comment]
@artur2000 if the problem remains with 6.1.3 please create a new issue. I'll close the issue for now.

**Comment by mmalisz** [comment]
Hi,
I use example config of tt_news and the extension won't generate any URL to the news.

TYPO 7.6.23
ext-solr 6.5
Solr 6.6.2

**Comment by dkd-kaehm** [comment]
@mmalisz 
Please use slack #ext-solr @ typo3 for those questions.

Make sure the sys folder with news is inside your site root.
