### ISSUE TITLE
[BUG] SQL Error in statistics module (only 8.0.x dev)

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#1562]
An exception occurred while executing 'SELECT `keywords`, `num_found as hits`, COUNT(`keywords`) AS `count` FROM `tx_solr_statistics` WHERE (`tstamp` > 1500292603) AND (`root_pid` = 1) AND (`num_found` > 0) GROUP BY `keywords`, `num_found` ORDER BY `count` DESC, `hits` DESC, `keywords` ASC LIMIT 5': Unknown column 'num_found as hits' in 'field list'

**Comment by timohund** [comment]
We should add an intregration test that covers this part as well.

**Comment by dkd-kaehm** [comment]
OK this happans before CMS 8.7.4 
https://github.com/TYPO3/TYPO3.CMS/commit/0c4742866643dbd8e4f89bd8788414cf74ac4314

**Comment by timohund** [comment]
Ah ok i see.
