### ISSUE TITLE
[BUG] MySQL Query for search buckets is faulty

### ISSUE THREAD

**Issue by mschwemer** [TYPO3-Solr/ext-solr#1575]
The database query for calculating the buckets in the statistics module is partially faulty. In certain mysql server conditions, this leads to a graph like this: 

<img width="1047" alt="solr_search_graph" src="https://user-images.githubusercontent.com/103594/29425188-a6ea8fc2-8382-11e7-8265-bea4e7798c79.png">

For each day there are two rendered points. 

Reason is the function "getQueriesOverTime" in "EXT:solr/Classes/Domain/Search/Statistics/StatisticsRepository.php". There is a todo in there ...

But even for mySQL this does not work in every case. The mySQL docs warn that there might be different results: https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_unix-timestamp

**Comment by dkd-kaehm** [comment]
@mschwemer Thanks for reporting.
Will #1556 solve this issue?

**Comment by mschwemer** [comment]
@dkd-kaehm I think so.
