### ISSUE TITLE
[TASK] Clarify what should happen with faceting.facets.[facetName].singleOptionMode

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#1589]
In the Docs the TS option faceting.facets.[facetName].singleOptionMode is described but nowhere implemented.

What should we do?:
* Implement this feature
* Add the Hint in the docs that it is dropped and how to do the same instead

**Comment by mbresch-sf** [comment]
I think the best way is to keep (get back) this option in 7.0. 

The "solrfluid" solution is fine too, but you should deprecate the singleOptionMode before dropping
this without any hint. :-)

**Comment by timohund** [comment]
@dkd-kaehm @mbresch-sf 

I would proposer to add another partials for that, that shows how it works and to document that, otherwise we maintain this logic in EXT:solr and it is allready possible just by using the correct methods in the template.
