### ISSUE TITLE
Typoscript integration of the 7.0 version

### ISSUE THREAD

**Issue by Simz** [TYPO3-Solr/ext-solr#1590]
Hi ,

Typoscript integration of the search result plugin raise this exception :

#1476107295: PHP Warning: trim() expects parameter 1 to be string, array given in typo3/sysext/core/Classes/Utility/GeneralUtility.php line 1800 (More information)

TYPO3\CMS\Core\Error\Exception thrown in file
typo3/sysext/core/Classes/Error/ErrorHandler.php in line 112.

`
lib.recherche_principale < tt_content.list.20.solr_pi_results
`
It seems to be related to flexform loading/overriding settings.

May be related to #1561.

**Comment by dkd-kaehm** [comment]
@Simz please leave a comment why its closed ;)

**Comment by Simz** [comment]
This bug is closed because i was trying to integrate solr with typoscript using the extension tscobj.
