### ISSUE TITLE
tsfe settingLocale - reason why this is not done in \Tx_Solr_Util::initializeTsfe ?

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Solr/ext-solr#16]
Is there a reason why settingLocale is not executed in \Tx_Solr_Util::initializeTsfe but in \Tx_Solr_IndexQueue_AbstractIndexer::resolveFieldValue instead/only ?

**Comment by irnnr** [comment]
probably no, might be a bug/inconsistency

**Comment by AndreasA** [comment]
So I can creat3e a pull request to add settingLocale to initializeTsfe in Tx_Solr_Util ?
