### ISSUE TITLE
RecursiveValueResolution does not work on n:m relations

### ISSUE THREAD

**Issue by AlexKvrlp** [TYPO3-Solr/ext-solr#1608]
When enableRecursiveValueResolution is used and the foreignTable value field references another table , only the first record of the foreign table is indexed.

IMHO the problem is the getRelatedItemsFromMMTable method in ApacheSolrForTypo3\Solr\ContentObject\Relation.

All fine, all related records will be returned.
https://github.com/TYPO3-Solr/ext-solr/blob/c4b7b22af2a8a6133c338cc3fac4f4ac19cc9fab/Classes/ContentObject/Relation.php#L186

running through all relatedItems to fetch related items. Still good.
https://github.com/TYPO3-Solr/ext-solr/blob/c4b7b22af2a8a6133c338cc3fac4f4ac19cc9fab/Classes/ContentObject/Relation.php#L187

but then: return after getting recursive value items for the FIRST records. All other records are not resolved. 
https://github.com/TYPO3-Solr/ext-solr/blob/c4b7b22af2a8a6133c338cc3fac4f4ac19cc9fab/Classes/ContentObject/Relation.php#L202

IMHO the resulting items of $this->getRelatedItems($contentObject) should be added to $relatedItems array.

**Comment by timohund** [comment]
@AlexKvrlp Can you provide an example typoscript configuration, or can your provide a patch or pull request?

**Comment by timohund** [comment]
@AlexKvrlp Thanks for the patch. Can you please also add an example to the ticket or an integration testcase that checks that scenario?

**Comment by timohund** [comment]
Integration test was added that showed no problem, therefore i'll close the issue. Please open a new one with a concrete example or testcase, if you think the problem still exists.
