### ISSUE TITLE
document._fields should contain the scheme

### ISSUE THREAD

**Issue by DanielRuf** [TYPO3-Solr/ext-solr#1617]
Currently the _fields only contain the site (domain) and url fields but no scheme field.

In our case we have to show the (supported scheme, https if supported) and build an absolute url from it.

**Comment by timohund** [comment]
@DanielRuf i think you can do that with a dynamic field

**Comment by DanielRuf** [comment]
Not sure how, never did that and I am just working on the frontend side =/

**Comment by timohund** [comment]
Please read the documentation or ask in the slack channel:

* https://docs.typo3.org/typo3cms/extensions/solr/
* https://typo3.slack.com/
