### ISSUE TITLE
Streamline typoscript configuration handling

### ISSUE THREAD

**Issue by Mabahe** [TYPO3-Solr/ext-solr#163]
I still have the problem, that there is a lot of typoscript configuration that is used by direct access of 
`$GLOBALS['TSFE']->tmpl->setup['plugin.']['tx_solr.']`. Especially in context of the content objects it is very annoying, because it is  mostly not possible to handle a different configuration for a special solr based content element, defined by
```
10 = COA
10 {

	10 < plugin.tx_solr_PiResults_Results
	10 {
		search {
			ignored, like e.g. faceting configurations
		}
	}
}
```

**Comment by irnnr** [comment]
I understand the problem, but what would you suggest to fix it?

**Comment by Mabahe** [comment]
Too fast ;-) Here is the patch. Waiting with a pull request for your feedback. E.g. if we should call the object TyposciptConfiguration instead of Configuration.

**Comment by irnnr** [comment]
ok, I left some comments :)

**Comment by irnnr** [comment]
I think I actually tried to start something like that in EXT:tiki, but eventually did not follow through.

**Comment by Mabahe** [comment]
@timoschmidt @irnnr so here is the squashed and optimized commit. I renamed and reorganized some parts and changed the usage of the moved Util functions, which are deprecated now. It is not yet tested in the project branch I implemented this for. I will create a PR after a successfull test.

**Comment by timoschmidt** [comment]
@Mabahe thanks for you effort, looks good for me. Looking forward for your pull request
