### ISSUE TITLE
[BUG] TYPO3 scheduler not usable Solr task has unknown rootPage

### ISSUE THREAD

**Issue by saitho** [TYPO3-Solr/ext-solr#1669]
When the TYPO3 scheduler has a reference to a root page that does not exist in the database the whole scheduler is not usable anymore, as an exception is thrown.

## Versions

* TYPO3 version: 8.7.3
* Ext:solr version: 7.0.2
* Solr version: 6.3.0
* PHP version: 7.0.22

## Error messages / stack traces

Initially my scheduler task did have a root page id (whyever that was the case). The serialized task object contained the data _"*rootPageId";s:0:N;_ which caused this error:
> #1487326416: The rootPageRecord for the given rootPageRecord ID '' could not be found in the database and can therefore not be used as site root rootPageRecord. (More information)

When a root page that is used by the scheduler task is deleted (e.g. page id 103) this exception comes up when opening the scheduler:
> #1487326416: The rootPageRecord for the given rootPageRecord ID '103' could not be found in the database and can therefore not be used as site root rootPageRecord. (More information)

## Expected behavior

The scheduler should be available.

## Actual behavior

The scheduler is not available due to an exception.

## Steps how to reproduce the issue

1. Create a new page and make it a root page
2. Create a sys_domain entry for the newly created root page
3. Create a new Solr Indexer task and use the newly created root page
4. Delete(!) the root page in the database (DELETE FROM pages WHERE ...)
5. Open the scheduler - you should see an exception.

Alternative approach:

1. Create a new Solr Indexer task just as you always to
2. Go into the database and change the ID of the root page (_*rootPageId_) in the _serialized_task_object_ to a page id that does not exist (make sure to adjust the value length as well, see syntax of serialized objects in PHP)
3. Open the scheduler - you should see an exception.

**Comment by timohund** [comment]
@saitho In this cases you should re-initialize the solr connections and the index queue.

**Comment by timohund** [comment]
But in general i would say it would be good to throw a specific exception that the solr site is not available and catch it during the processing, that at least the other sites are still useable.

Can you provide a patch include test cases?
