### ISSUE TITLE
Objectmanager uses deprecated "create" method

### ISSUE THREAD

**Issue by sorenmalling** [TYPO3-Solr/ext-solr#17]
The method "create" in the ObjectManager is deprecated since 6.1[1] and usage of "get" is suggested

[1] http://api.typo3.org/typo3cms/current/html/class_t_y_p_o3_1_1_c_m_s_1_1_extbase_1_1_object_1_1_object_manager.html#a86bc72800a9cbabe2b1fb2aadf68bbe6

**Comment by sorenmalling** [comment]
@irnnr I have a patch ready - what branches should i create PR for?

**Comment by irnnr** [comment]
Just created a branch for you; PR into typo3-minimum-62 🎉👍🏻

**Comment by irnnr** [comment]
actually, forget about that... Since master/3.1 will require 6.2, just open a PR for master
