### ISSUE TITLE
Observe the new logos of Solr for the upcoming release

### ISSUE THREAD

**Issue by dkd-dobberkau** [TYPO3-Solr/ext-solr#170]
We need to observe the new logos of Solr for the upcoming release:
http://lucene.apache.org/solr/logos-and-assets.html

**Comment by irnnr** [comment]
* InitSolrConnections.png
* ext_icon.gif

**Comment by irnnr** [comment]
ext icon ![ext_icon](https://cloud.githubusercontent.com/assets/320915/11552611/5589fb78-993b-11e5-924d-19a1886a2444.png)

**Comment by irnnr** [comment]
I also have the other one ready, but need to try it out in the backend first

**Comment by dkd-dobberkau** [comment]
I would prefer the one with the white background.

**Comment by timoschmidt** [comment]
@irnnr 
@dkd-dobberkau 

I think this was done, can we close this issue?

**Comment by irnnr** [comment]
the extension icons yes, but there are a few left overs that I didn't get to yet. Please leave it open, I'll close it when done.

**Comment by timohund** [comment]
@irnnr What is left here? Can we close the issue?

**Comment by timohund** [comment]
New logos are in place, i think we can close the issue

**Comment by irnnr** [comment]
I think the icon for init Solr connections is still using an old logo
