### ISSUE TITLE
News Hitlist with images

### ISSUE THREAD

**Issue by SicorDev** [TYPO3-Solr/ext-solr#1701]
Hello Solr Team,

maybe I'm misinterpreting the docs, but shouldn't this little config snippet put the image path of a tx_news item into the search index?

image_stringS = SOLR_RELATION
image_stringS {
     localField = fal_media    (This is the link to sys_file)
     foreignLabelField = identifier  (This is where sys_file stores the desired path)
}

I'm getting the correct sys_file uid with just this, so I'm not that far off I think:

image_stringS = SOLR_RELATION
image_stringS {
     localField = fal_media
}

**Comment by timohund** [comment]
Please ask support questions in the channel or send a mail to solr-eb-support@dkd.de

**Comment by SicorDev** [comment]
Thanks, I'll do so when I have one, but what about the error I reported? It is not working after all.

**Comment by mtness** [comment]
For the records, here is how it is done on typoe3.org:
https://git.typo3.org/services/t3o-sites/typo3.org/typo3.org/-/blob/develop/extensions/t3org_layout/Configuration/TypoScript/Ext/Solr.typoscript#L78
