### ISSUE TITLE
Facet requirements: React to _selected_ values only

### ISSUE THREAD

**Issue by SomeBdyElse** [TYPO3-Solr/ext-solr#1729]
According to the docs requirements for facets "are dependencies on values of other facets being **selected** by the user.". 

https://docs.typo3.org/typo3cms/extensions/solr/Configuration/Reference/TxSolrSearch.html#faceting-facets-facetname-requirements-requirementname

In the current implementation, a requirement can be met by non-selected items as well. 

```
# Display a static menu of all available types
type {
  minimumCount = 0
  keepAllOptionsOnSelection = 1
  singleOptionMode = 1
  showEvenWhenEmpty = 1
}

pageHierarchy {
  field = rootline
  label = Rootline
  type = hierarchy
  partialName = Rootline
  
  # Show the hierarchy menu only if the user is looking for pages or news
  requirements {
    typeHasHierarchy {
      facet = type
      values = pages,tx_news_domain_model_news
    }
  }
}
```

Expected result: The hierarchy facet only appears if the user limits the search results to either pages or news. 

Actual result: The hierarchy filter will always be displayed, as long as there are pages or news in the index.

**Comment by timohund** [comment]
@SomeBdyElse How do you access the facets in the template? Are you using the default partials? The filtering on requirements is only happening when you call FacetCollection::getAvailable, this is also done in the default partials:

{resultSet.facets.available}

**Comment by SomeBdyElse** [comment]
@timohund I use the default Results/Facets.html partial, which uses `{resultSet.facets.available}`. 

To my eyes the problem lies within the RequirementsService::getRequirementMet method. It uses `getActiveItemValues` to get a list of all active facet options. Instead it should get a list of all active items, but of all _selected_ items.

**Comment by SomeBdyElse** [comment]
Hey @timohund. Maybe the above commit makes it clearer what I am aiming at. The interesting change is this one here: 

https://github.com/SomeBdyElse/ext-solr/commit/725eaabffc8bcaa9a9f45368cf2af5fd194be567#diff-bcb7d40d6abe516bfcebb3a9adcb9157R102
