### ISSUE TITLE
Suggest does not respect configured filters.

### ISSUE THREAD

**Issue by tbd-rsm** [TYPO3-Solr/ext-solr#1758]
Hi,

I'm using Solr 7.0.2 in a Typo3 8.7.6.

Shouldn't the suggest endpoint respect filters set via `plugin.tx_solr.search.query.filter`? Is there another way to do that?

My filter is set correctly. It works for the normal search. But`EXT:solr/Classes/Eid/Suggest.php` still suggests words that definately do only exist in documents that should not be found after applying that filter.

I think the problem lies in `ApacheSolrForTypo3\Solr\SuggestQuery::getQueryParameters` at [Line 104](https://github.com/TYPO3-Solr/ext-solr/blob/94ae6145ee838d7c185504ee14981d6e7680f31f/Classes/SuggestQuery.php#L104).
`$this->filters` probably should be `$this->getFilters()->build()`.

Here is my xclass workaround in case someone else runs into the same issue:

```
# EXT:mysolr/ext_localconf.php

[...]

$GLOBALS['TYPO3_CONF_VARS']['SYS']['Objects']['ApacheSolrForTypo3\\Solr\\SuggestQuery'] = array(
    'className' => 'Mysolr\\Mysolr\\SuggestQuery'
);
```

```
# EXT:mysolr/Classes/SuggestQuery.php

<?php
namespace Mysolr\Mysolr;

class SuggestQuery extends \ApacheSolrForTypo3\Solr\SuggestQuery
{
    /**
     * Returns the query parameters that should be used.
     *
     * @return array
     */
    public function getQueryParameters()
    {
        $suggestParameters = parent::getQueryParameters();
        return array_merge($suggestParameters, $this->getFilters()->build());
    }
}
```

**Comment by timohund** [comment]
Fixed by #1802
