### ISSUE TITLE
Cannot set collapseSingleValueArrays of SolrPhpClient with TS configuration

### ISSUE THREAD

**Issue by masi** [TYPO3-Solr/ext-solr#1773]
The default is to collapse arrays with a single item to a string. I find this rather annoying especially with Fluid's for view helper.

I cannot think of any good reason to want it that way, but what di I know. So a new configuration variable in the plugin's TypoScript setting to change the behaviour would be nice.

**Comment by timohund** [comment]
@masi Are you talking about this change, or the old behaviour?: 

https://github.com/TYPO3-Solr/ext-solr/pull/1748

**Comment by timohund** [comment]
As far as i understand this should be fixed with #1748 if you want, you can backport it to the 7.5 branch?

**Comment by masi** [comment]
Yes, but I don't like the solution. See #1748 for my proposal.

**Comment by masi** [comment]
I don't like the old behaviour, so the suggesion of a TS setting is only to provide backwards compatibility for whoever wants that.

Do you want  a patch for that?
