### ISSUE TITLE
Check support of PHP 7.0

### ISSUE THREAD

**Issue by timoschmidt** [TYPO3-Solr/ext-solr#179]
Since the performance improvements sound great we should support ext_solr to run on PHP 7.

- Enable in travis ci and make tests running
- Run Extension on PHP7
- Maybe fix upcomming error and add tests for them.

**Comment by dkd-janke** [comment]
+1

**Comment by timoschmidt** [comment]
I think this issue can be closed, because we check this with travis-ci allready
