### ISSUE TITLE
Grouping results (EXT:solr 7.0.2)

### ISSUE THREAD

**Issue by kassor** [TYPO3-Solr/ext-solr#1790]
Hello guys,

I'm using 

- EXT:solr 7.0.2
- Solr Apache Version 6.3.0
- TYPO3 8.7.

The EXT:solrgrouping is not more compatible and my question is - **how can I group my search results now?**

Thx for help!

**Comment by dkd-kaehm** [comment]
there is grouping extension late RC for EB-Partner Available, please contact us via  solr-eb-support@dkd.de

PS: please use EXT:solr 7.5 and Apache Solr Server for this version, because the Apache Solr for EXT:solr 7.0 has security bugs!
