### ISSUE TITLE
Install solr doesn't support Java version 9

### ISSUE THREAD

**Issue by griebie** [TYPO3-Solr/ext-solr#1794]
The install-solr.sh script running under Java9 results in this error:

ERROR parent directory: (/opt) of install path (/opt/solr) is not writeable.
You have installed Java version 0. Please install Java 8 or newer.
Please install all missing requirements or fix any other errors listed above and try again.

**Comment by mbresch-sf** [comment]
Will provide a patch soon.

**Comment by mbresch-sf** [comment]
Java changes his version number to a "normal" one. ;-)

Now Java 9 has the version "9.0.1" instead of "1.9.0_1".

see https://blogs.oracle.com/java-platform-group/a-new-jdk-9-version-string-scheme for more informations

**Comment by mbresch-sf** [comment]
Hi @griebie ,
is this patch working for you?
