### ISSUE TITLE
[BUG] Inaccurate analysis?

### ISSUE THREAD

**Issue by klodeckl** [TYPO3-Solr/ext-solr#1805]
I get the following message:
= 0 (Inaccurate analysis! Not all parts of the score have been taken into account.)

I researched but found no way to deal with it. Can somebody tell me what the problem could be?

**Comment by dkd-kaehm** [comment]
This is debug info printed for users logged in in Backend.
I gues 0 comes if Apache Solr does not send debug Data on response.
Please try to activate debug mode with TypoScript.

**Comment by klodeckl** [comment]
plugin.tx_solr.enableDebugMode = 1 is already set…

**Comment by fnagel** [comment]
Same here. `showDocumentScoreAnalysis` and `enableDebugMode` enabled and still got no results.

**Comment by timohund** [comment]
@klodeckl @fnagel Is anybody able to analyze it further and work on a patch?

**Comment by Mabahe** [comment]
Seems Solr 6 has a different explain schema, which doesn't match to the regex in ScoreCalculationService anymore.

Example for an explain result
```
98.444336 = sum of:
  98.444336 = max of:
    6.2762194 = weight(tagsH2H3:coach in 610) [SchemaSimilarity], result of:      6.2762194 = score(doc=610,freq=1.0 = termFreq=1.0
), product of:
        3.0 = boost
        2.0920732 = idf, computed as log(1 + (docCount - docFreq + 0.5) / (docFreq + 0.5)) from:
          29.0 = docFreq
          238.0 = docCount
        1.0 = tfNorm, computed as (freq * (k1 + 1)) / (freq + k1) from:
          1.0 = termFreq=1.0
          1.2 = parameter k1
          0.0 = parameter b (norms omitted for field)
    13.230293 = weight(tagsH1:coach in 610) [SchemaSimilarity], result of:
      13.230293 = score(doc=610,freq=1.0 = termFreq=1.0
), product of:
        5.0 = boost
        2.6460586 = idf, computed as log(1 + (docCount - docFreq + 0.5) / (docFreq + 0.5)) from:
          30.0 = docFreq
          429.0 = docCount
        1.0 = tfNorm, computed as (freq * (k1 + 1)) / (freq + k1) from:
          1.0 = termFreq=1.0
          1.2 = parameter k1
          0.0 = parameter b (norms omitted for field)
    98.444336 = weight(content:coach in 610) [SchemaSimilarity], result of:
      98.444336 = score(doc=610,freq=27.0 = termFreq=27.0
), product of:
        40.0 = boost
        1.1881583 = idf, computed as log(1 + (docCount - docFreq + 0.5) / (docFreq + 0.5)) from:
          503.0 = docFreq
          1651.0 = docCount
        2.0713642 = tfNorm, computed as (freq * (k1 + 1)) / (freq + k1 * (1 - b + b * fieldLength / avgFieldLength)) from:
          27.0 = termFreq=27.0
          1.2 = parameter k1
          0.75 = parameter b
          218.57965 = avgFieldLength
          334.36734 = fieldLength
    2.8561218 = weight(tagsInline:coach in 610) [SchemaSimilarity], result of:
      2.8561218 = score(doc=610,freq=1.0 = termFreq=1.0
), product of:
        2.8561218 = idf, computed as log(1 + (docCount - docFreq + 0.5) / (docFreq + 0.5)) from:
          16.0 = docFreq
          286.0 = docCount
        1.0 = tfNorm, computed as (freq * (k1 + 1)) / (freq + k1) from:
          1.0 = termFreq=1.0
          1.2 = parameter k1
          0.0 = parameter b (norms omitted for field)
",
```

With an additional parameter `debug.explain.structured=true` you get a nice json result. 

Also debugQuery is still only there for backwards compatibility and there are more options now:
https://lucene.apache.org/solr/guide/6_6/common-query-parameters.html#CommonQueryParameters-ThedebugParameter

**Comment by timohund** [comment]
@Mabahe Thanks for your research. I'll propose we have a look on it for 8.1 are you able to continue on that? Otherwise i'll have a look on it.

**Comment by timohund** [comment]
@klodeckl @fnagel  @Mabahe #2012 and #2013 will fix this issue and bring back the old behaviour for 8.1.0 and 8.0.4 in addition we will provide an advanced score analysis with the addon solrdebugtools that will be available soon:

![bildschirmfoto 2018-06-15 um 15 43 18](https://user-images.githubusercontent.com/964675/41471070-dde2c22e-70b2-11e8-898a-4bd4e99d8fd6.png)

**Comment by Norcoen** [comment]
I'm facing this message with version 8.1.1

Is that a regression?

**Comment by dkd-kaehm** [comment]
> I'm facing this message with version 8.1.1
> 
> Is that a regression?

@Norcoen 
its in 8.1 branch see 
https://github.com/TYPO3-Solr/ext-solr/commits/release-8.1.x/Classes/Domain/Search/Score/ScoreCalculationService.php
and in 8.1.2
