### ISSUE TITLE
Pages Index Queue: Subpages (recursive) of recycler pages must/should be excluded

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Solr/ext-solr#1813]
## Expected behavior

Any subpage of a doktype `255` needs to be excluded (per default → if there is a reason).

Would make sense to extend the module in a way to show a section, where the admin/backenduser get's informed about excluded pages due the recycler doktype.

## Actual behavior

Index error is thrown.

## Steps how to reproduce the issue

add a recycler page with subpages within your normal/indexed sitetree

## Stack Trace (EXT:solr index queue module) → show error:

    1275399922: ApacheSolrForTypo3\Solr\NoSolrConnectionFoundException: Could not find a Solr connection for root page [0] and language [0]. Initial page used was [17] in /html/app/vendor/typo3/cms/typo3/sysext/core/Classes/Utility/GeneralUtility.php:3904
    Stack trace:
    #0 /html/app/web/typo3conf/ext/solr/Classes/ConnectionManager.php(185): TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('ApacheSolrForTy...', 'Could not find ...', 1275399922)
    #1 /html/app/web/typo3conf/ext/solr/Classes/ConnectionManager.php(206): ApacheSolrForTypo3\Solr\ConnectionManager->getConfigurationByPageId('17', 0, '')
    #2 /html/app/web/typo3conf/ext/solr/Classes/IndexQueue/Indexer.php(559): ApacheSolrForTypo3\Solr\ConnectionManager->getConnectionByPageId('17', 0, '')
    #3 /html/app/web/typo3conf/ext/solr/Classes/IndexQueue/PageIndexer.php(113): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->getSolrConnectionsByItem(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item))
    #4 /html/app/web/typo3conf/ext/solr/Classes/IndexQueue/PageIndexer.php(59): ApacheSolrForTypo3\Solr\IndexQueue\PageIndexer->getSolrConnectionsByItem(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item))
    #5 /html/app/web/typo3conf/ext/solr/Classes/Domain/Index/IndexService.php(196): ApacheSolrForTypo3\Solr\IndexQueue\PageIndexer->index(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item))
    #6 /html/app/web/typo3conf/ext/solr/Classes/Domain/Index/IndexService.php(130): ApacheSolrForTypo3\Solr\Domain\Index\IndexService->indexItem(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), Object(ApacheSolrForTypo3\Solr\System\Configuration\TypoScriptConfiguration))
    #7 /html/app/web/typo3conf/ext/solr/Classes/Task/IndexQueueWorkerTask.php(69): ApacheSolrForTypo3\Solr\Domain\Index\IndexService->indexItems(5000)
    #8 /html/app/vendor/typo3/cms/typo3/sysext/scheduler/Classes/Scheduler.php(181): ApacheSolrForTypo3\Solr\Task\IndexQueueWorkerTask->execute()
    #9 /html/app/vendor/typo3/cms/typo3/sysext/scheduler/Classes/Controller/SchedulerModuleController.php(870): TYPO3\CMS\Scheduler\Scheduler->executeTask(Object(ApacheSolrForTypo3\Solr\Task\IndexQueueWorkerTask))
    #10 /html/app/vendor/typo3/cms/typo3/sysext/scheduler/Classes/Controller/SchedulerModuleController.php(243): TYPO3\CMS\Scheduler\Controller\SchedulerModuleController->executeTasks()
    #11 /html/app/vendor/typo3/cms/typo3/sysext/scheduler/Classes/Controller/SchedulerModuleController.php(158): TYPO3\CMS\Scheduler\Controller\SchedulerModuleController->getModuleContent()
    #12 /html/app/vendor/typo3/cms/typo3/sysext/scheduler/Classes/Controller/SchedulerModuleController.php(314): TYPO3\CMS\Scheduler\Controller\SchedulerModuleController->main()
    #13 [internal function]: TYPO3\CMS\Scheduler\Controller\SchedulerModuleController->mainAction(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(TYPO3\CMS\Core\Http\Response))
    #14 /html/app/vendor/typo3/cms/typo3/sysext/core/Classes/Http/Dispatcher.php(41): call_user_func_array(Array, Array)
    #15 /html/app/vendor/typo3/cms/typo3/sysext/backend/Classes/Http/BackendModuleRequestHandler.php(169): TYPO3\CMS\Core\Http\Dispatcher->dispatch(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(TYPO3\CMS\Core\Http\Response))
    #16 /html/app/vendor/typo3/cms/typo3/sysext/backend/Classes/Http/BackendModuleRequestHandler.php(89): TYPO3\CMS\Backend\Http\BackendModuleRequestHandler->dispatchModule('system_txschedu...')
    #17 /html/app/vendor/typo3/cms/typo3/sysext/core/Classes/Core/Bootstrap.php(315): TYPO3\CMS\Backend\Http\BackendModuleRequestHandler->handleRequest(Object(TYPO3\CMS\Core\Http\ServerRequest))
    #18 /html/app/vendor/typo3/cms/typo3/sysext/backend/Classes/Http/Application.php(92): TYPO3\CMS\Core\Core\Bootstrap->handleRequest(Object(TYPO3\CMS\Core\Http\ServerRequest))
    #19 /html/app/vendor/typo3/cms/typo3/sysext/backend/Resources/Private/Php/backend.php(24): TYPO3\CMS\Backend\Http\Application->run()
    #20 /html/app/vendor/typo3/cms/typo3/sysext/backend/Resources/Private/Php/backend.php(25): {closure}()
    #21 /html/app/vendor/typo3/cms/typo3/index.php(3): require('/html/app/vendo...')
    #22 {main}

> page uid 17 = a subpage of a recycler page

## My environment

> TYPO3 version: 8.7 stable
> EXT:solr version: 7.5.0 stable
> Solr Server version: 6.3.0
> PHP version 7.2

**Comment by timohund** [comment]
Closing this issue because i've added it as a comment to #1832

**Comment by josefglatz** [comment]
still open in TYPO3 12.4 LTS: https://github.com/TYPO3-Solr/ext-solr/issues/1832#issuecomment-2098171037
