### ISSUE TITLE
Disable SSL Connection

### ISSUE THREAD

**Issue by bandanh** [TYPO3-Solr/ext-solr#1833]
Hi there,

I set up a fresh TYPO3 8 LTS via composer and the current version of ext:solr. I created 3 pages, root, home, search and a basic TS to `config.index_enable = 1`, include static (`base config, default styles, openSearch`) and a basic solr TypoScript:
```
plugin {
    tx_solr {
        solr {
            host = 127.0.0.1
            port = 8983
        }
        statistics = 1
        index.queue.pages.frontendDataHelper.scheme = http
    }
}
```
In the Backend in the `Solr > Info` Module I get a green ok on the connection to my local Solr 6.6.2 Server. But when I try to index pages in the `Solr > Index Queue` with `Index now`, then I get an error.

```
1476107295: TYPO3\CMS\Core\Error\Exception: PHP Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in ./solr.dev/htdocs/typo3conf/ext/solr/Classes/IndexQueue/PageIndexerRequest.php line 407 in ./solr.dev/vendor/typo3/cms/typo3/sysext/core/Classes/Error/ErrorHandler.php:107
```

Since I use a self signed Cert I set: 
```
$GLOBALS['TYPO3_CONF_VARS']['HTTP']['verify'] = 1
```
But the problem remained unchanged. Then I tried it without https and added the following to my ts, as you can see above:
```
index.queue.pages.frontendDataHelper.scheme = http
```
Any Idea how I can test locally with or without self signed cert?

**Comment by dkd-dobberkau** [comment]
https://docs.typo3.org/typo3cms/extensions/solr/Configuration/Reference/ExtensionSettings.html
set allowSelfSignedCertificates to 1

**Comment by bandanh** [comment]
Ah, thanx for the quick response, that fixed it.
I actually miss understood https://github.com/TYPO3-Solr/ext-solr/pull/1133#issuecomment-304696412
I thought that was implemented and the way to go and didn't search any further on how to allow self signed certs.
