### ISSUE TITLE
[BUG] result-range always shown

### ISSUE THREAD

**Issue by DanielRuf** [TYPO3-Solr/ext-solr#1835]
It makes not much sense to show the `result-range` eg when we have only 10 or less results, it says.
> Showing result 1 - 10 of 10

**Comment by timohund** [comment]
@DanielRuf I think we could adapt the default partials and only show it when the results are more then the per page limit. Can you provide a pull request for it?

**Comment by DanielRuf** [comment]
Right. Will create the PR when I find the time. Hopefully this week or so.
