### ISSUE TITLE
Allow facets to be configured and not rendered

### ISSUE THREAD

**Issue by timoschmidt** [TYPO3-Solr/ext-solr#184]
It would be nice when a facet could be configured but not rendered in order to allow deep linking to a facetted search, where the facet does not need to be visible in the search results itself.

**Comment by irnnr** [comment]
not sure what you want to achieve, but your description (apart from deep linking) sounds like it is already possible using 

https://forge.typo3.org/projects/extension-solr/wiki/Tx_solrsearch#facetingfacetsfacetNameincludeInAvailableFacets
https://forge.typo3.org/projects/extension-solr/wiki/Tx_solrsearch#facetingfacetsfacetNameincludeInUsedFacets

**Comment by timoschmidt** [comment]
https://forge.typo3.org/projects/extension-solr/wiki/Tx_solrsearch#facetingfacetsfacetNameincludeInAvailableFacets worked well thx
