### ISSUE TITLE
[TASK] Extend test runner to use default values

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#1851]
When you run the tests on the command line by using

```
source ./Build/Test/bootstrap.sh --local
./Build/Test/cibuild.sh
```

You need to type in the default values. We should add the default values from the dev environment here that you just need to hit enter. This save time when you bootstrap the testing environment,

**Comment by dkd-kaehm** [comment]
or --use-defalts flag ;)
