### ISSUE TITLE
cacheId of configurationObjectCache does not repect initializeTsfe

### ISSUE THREAD

**Issue by Mabahe** [TYPO3-Solr/ext-solr#1858]
Fact: a configuration could differ, if TSFE is initialized or not.

Bug: If a configuration is cached with initializeTsfe = false, a second call in the same run with initializeTsfe = true returns the cached wrong configuration.

**Comment by timohund** [comment]
@Mabahe What did you do to see any wrong behaviour in the frontend? By adding this to the cache key we also reduce the amount of hits and we should only to that, when it is really required.

**Comment by Mabahe** [comment]
Like also discussed personally, it is required to get the expected behaviour of getting a fully initialized TSFE in the second call, if the first call used `$initializeTsfe = false`. And this happens when bootstrapping the indexer from scheduler.
Backgroup: the parsed typoscript getting from the mini TSFE fallback in `getConfigurationFromExistingTSFE()` is different from the full object in `initializeTsfe()`
