### ISSUE TITLE
PHP Warning in BE module "Index Queue"

### ISSUE THREAD

**Issue by Mabahe** [TYPO3-Solr/ext-solr#1864]
Core: Error handler (BE): PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'ApacheSolrForTypo3\Solr\ViewHelpers\Backend\Security\IfHasAccessToModuleViewHelper' does not have a method 'render' in ../vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php line 261

**Comment by Mabahe** [comment]
TYPO3 8.7
Caused by 80523fb1ff7b67de0ddbe82da8594d8ca79cadc6

**Comment by timohund** [comment]
This is the related and fixed issue in Fluid:

https://github.com/TYPO3/Fluid/commit/a65912ad94fbf173293e6026f30f6849ea32465b

We could add a render method to avoid the warning, but i would say the correct solution would be to apply the fix above.

**Comment by timohund** [comment]
@Mabahe can you check if https://github.com/TYPO3-Solr/ext-solr/pull/1865 resolves the problem?

**Comment by timohund** [comment]
Could be fixed with #1865 but is also resolved by updating to TYPO3 8.7.10

**Comment by Mabahe** [comment]
gna, sorry. Is still an 8.7.9 instance. Another 8.7.10 doesn't show the warning,

**Comment by Mabahe** [comment]
Jep, #1865 fixes the warning in 8.7.9
