### ISSUE TITLE
Do not render unused subparts in template

### ISSUE THREAD

**Issue by Mabahe** [TYPO3-Solr/ext-solr#188]
Avoids some renderings for less rendering time depending on the template for sure.

PR follows.

**Comment by irnnr** [comment]
Feel free to work on it, but personally I wouldn't put any more effort into the current tempting engine

**Comment by Mabahe** [comment]
Patch is done, just want to share it. And the rendering time of the current project really profits from the change.

**Comment by timoschmidt** [comment]
Sound promissing, would be nice when you share the patch

**Comment by timoschmidt** [comment]
@Mabahe Do you have  a patch that you want to contribute or could we close this issue?

**Comment by Mabahe** [comment]
jep, I still have it in pipeline

**Comment by timohund** [comment]
no relevant anymore
