### ISSUE TITLE
Dispatch signals in controller actions

### ISSUE THREAD

**Issue by Mabahe** [TYPO3-Solr/ext-solr#1889]
I have the request to add data to the view in search controller actions. 
Before the fluid rewrite we had the FormModifier hook to achieve this.

Inspired by gorgeous ext:news it would be helpful to emit signals to adapt the assigned variables for the view.

**Comment by timohund** [comment]
@Mabahe Can you please provide a description here?

**Comment by timohund** [comment]
We need a description for the issue and a short part in the documentation how to use it.
