### ISSUE TITLE
[BUG] Add version to composer.json again

### ISSUE THREAD

**Issue by timoschmidt** [TYPO3-Solr/ext-solr#189]
When you install 3.1.0 (from tag, and also dev master) and install an extension that depends on the solr extesion you get the following error in the extension manager:

Uncaught TYPO3 Exception
#1395614959: Version number in composer manifest of package "solr" is missing or invalid (More information)

TYPO3\CMS\Core\Package\Exception thrown in file
/var/www/6.2.15.local.typo3.org/typo3_src/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php in line 225.

I think we need to add the version in composer.json again and keep it in sync with the ext_emconf.php

**Comment by irnnr** [comment]
I noticed that, but I consider that a bug in the EM. Let's investigate that first. I'd rather not have the version in composer.son if we can avoid it.

I noticed that error with 6.2, but haven't tried 7.6 yet.

**Comment by irnnr** [comment]
hmm, looks like we'll have to add it for the 3.1 branch...
https://typo3.slack.com/archives/typo3-cms-composer/p1450436224000029

For 7.6 LTS+ we're good

**Comment by timoschmidt** [comment]
Fixed for 3.1.x with https://github.com/TYPO3-Solr/ext-solr/pull/194
