### ISSUE TITLE
Solr tracking own table

### ISSUE THREAD

**Issue by michelle-ews** [TYPO3-Solr/ext-solr#1913]
Hi everyone, having an issue with the solr index queue. I want to track changes on my table. Records wich are changed, deleted or created should track the index queue worker. If I change records from the typo3 backend it works, but not when I change records directly at my table.
Can anyone help me?

**Comment by timohund** [comment]
@michelle-ews EXT:solr can not detect when you change your records directly in the database. Maybe you can create a scheduler task the queue's the whole table for re-indexing once a night?

**Comment by michelle-ews** [comment]
That’s the problem. When I re-indexing the whole table the scheduler clear the index and my cars disappear at my car search extension for a few minutes. Our customer doesn’t want this :(

Mit freundlichen Grüßen

Michelle Ayadi
------------------------------------------------
Einmahl WebSolution GmbH

Ehrenstraße 69
50672 Köln

Tel.: +49 (0) 221 29 83 12 853

E-Mail: m.ayadi@einmahl.de
Web: www.einmahl.de

**Comment by timohund** [comment]
As far as i see, you would need the implementation of this patch: https://github.com/TYPO3-Solr/ext-solr/pull/924. Unfortunately there was no feedback provided. Do you think you could port this patch to the master branch and fix the mentioned issues? Otherwise we could offer you to do this based on our support conditions.

**Comment by sfsmfc** [comment]
Hi @michelle-ews,

you could also register a "processDatamapClass" with a "processDatamap_afterDatabaseOperations" function for your car table and put the records in the solr index queue again.

**Comment by michelle-ews** [comment]
We will try this today. If our solution works, we will provide the code. Thank you for your help.

**Comment by michelle-ews** [comment]
@sfsmfc Your hint was the solution. Thank you :)

**Comment by dkd-dobberkau** [comment]
Next time: Please don't send emails to two Mailinglist, a personal one to me or open an issue here. THIS IS NOT A SUPPORT FORUM. If you need commercial support then consider paying for it.

**Comment by dkd-dobberkau** [comment]
I will close all issues being hidden support requests.
