### ISSUE TITLE
[BUG] Support of "useConfigurationMonitorTables" setting is incomplete

### ISSUE THREAD

**Issue by robert-heinig** [TYPO3-Solr/ext-solr#1916]
The check for this setting is missing in:
\ApacheSolrForTypo3\Solr\IndexQueue\RecordMonitor::processCmdmap_postProcess()
\ApacheSolrForTypo3\Solr\IndexQueue\RecordMonitor::processCmdmap_preProcess()

Specific example: If you delete a tt_content element, "pages" is not a monitored table, then processCmdmap_preProcess will add the page element to the index queue.

**Comment by robert-heinig** [comment]
\ApacheSolrForTypo3\Solr\GarbageCollector
is also affected.

**Comment by timohund** [comment]
@robert-heinig 
- Which versions are you using?
- Can you please add more information to the issue?  
- Which tables did you configure as monitored tables and what happend then?

**Comment by timohund** [comment]
Closing since no feedback was provided. Please open a new issue if the problem remains.
