### ISSUE TITLE
[BUG] Sorting item option fixedOrder broken since fluid rewrite

### ISSUE THREAD

**Issue by Mabahe** [TYPO3-Solr/ext-solr#1968]
Documentation: https://docs.typo3.org/typo3cms/extensions/solr/Configuration/Reference/TxSolrSearch.html#sorting-options-optionname-fixedorder

**Comment by timohund** [comment]
@Mabahe this can be achieved by adapting the partial for one particular sorting. I would propose to move that option from the documentation.

**Comment by Mabahe** [comment]
I'm ok with this.
