### ISSUE TITLE
Facet requirements are not fulfilled if facet is filter is set in plugin

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Solr/ext-solr#1998]
Given are the following facets
```
location {
                    label = Ort
                    field = location_stringS
                    partialName = Options
                }

category {
                    label = Kategorie
                    field = category_stringS
                    partialName = Options

                    requirements {
                        locationIsSet {
                            facet = location
                            values = __any
                        }
                    }
                }
```
So if a location is selected, the category facet is shown, everything is fine. 

Problem is if I set the facet `location` in the plugin
![bildschirmfoto 2018-05-30 um 08 59 06](https://user-images.githubusercontent.com/1905663/40704205-c7792014-63e7-11e8-955c-c2dadb2a11d8.png)

=> This leads to the problem that the result is filtered by the location but the category facet is still not shown.

**Comment by Mabahe** [comment]
facet != filter, so you need an extra option to set a selected facet by configuration.

Filter: https://docs.typo3.org/typo3cms/extensions/solr/Configuration/Reference/TxSolrSearch.html#query-filter

**Comment by timohund** [comment]
What @Mabahe said is true facet != filter, but i think these terms are sometimes mixed and we should make this more clear.

e.g. in the url's facets are passed with the arguments "filter" what is missleading. I think we should streamline this in one of the next versions and use the term "facet" whenever we talk about facets and "filter" whenever we talk about filters.

I think i the scope of this issue we should implement to preselect a facet option by configuration, what is not possible yet.

**Comment by timohund** [comment]
I've created an issue for the streamlining of the naming: #2027

**Comment by dkd-kaehm** [comment]
I'll close this issue. 
First step will be #2027 then #2958
