### ISSUE TITLE
Umlaut in autocomplete/autosuggest

### ISSUE THREAD

**Issue by Gitsko** [TYPO3-Solr/ext-solr#1999]
Hello,

via autocomplete I can search terms with geman umlauts like ä, ö, ü and these will also be found. However, autocomplete does not display a suggestion with an umlaut. 

For example, "Süden" will not display "Suden" but will.

What do I have to do to get umlauts in autocomplete?

**Comment by timohund** [comment]
I've checked that an in my installation i see no problem:

![umlauts](https://user-images.githubusercontent.com/964675/41465204-69dff8ac-709d-11e8-8bf8-7ac8b920b358.png)

**Comment by timohund** [comment]
@Gitsko could it be that Süden is the only term and this issue is the problem: https://github.com/TYPO3-Solr/ext-solr/pull/2008 ?

**Comment by timohund** [comment]
Closing since no feedback was provided. Please open a new issue if the problem remains.
