### ISSUE TITLE
Port documentation to rst

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/ext-solr#20]
Port documentation from forge wiki to rst format.

(This is an easy task for anyone wanting to help out)

**Comment by irnnr** [comment]
Once this is done, remove reference to forge in README.md

**Comment by peterkraume** [comment]
I will take care of this. I've already started, but it might take a while until I'm finished.

**Comment by irnnr** [comment]
@peterkraume any updates?

**Comment by peterkraume** [comment]
I was on holidays the last two weeks. Expect progress within the next two weeks.

**Comment by irnnr** [comment]
ok cool, thx

**Comment by peterkraume** [comment]
@irnnr here is the progress I've made so far. Unfortunately it's way more work than I expected bug I'm gaining speed.

The current status can always be found here:
http://solrdoku2rst.dev.dasrv5.de/Index.html
Basic Auth protection: web/web

Please let me know, what you think, especially about the TypoScript Reference.
http://solrdoku2rst.dev.dasrv5.de/ConfigurationReference/TypoScript/Index.html

**Comment by peterkraume** [comment]
The source code is available here:
https://github.com/peterkraume/ext-solr/tree/documentation/Documentation

**Comment by irnnr** [comment]
Thanks for your efforts Peter!
Regarding the TS reference I would suggest to simply stay with the formatting as in the current wiki. That seems to be a lot simpler to write and more importantly easier to read. I'm not sure where the t3o online documentation styling is heading but I think the current table-style reference is not the best choice in terms of usability and readability.

Let me know if you have an opinion on that.

**Comment by peterkraume** [comment]
I'd prefer to stick with the "official" way to write TS documentation because people are used to it and many other extension documentations (e.g. EXT:news) use this way of documentation. I'm aware of the fact that this will mean a lot of additional work for me, but that's ok.

**Comment by irnnr** [comment]
Please do NOT use those tables, just because it's official doesn't mean it's good.

**Comment by peterkraume** [comment]
Well, I didn't say it's good! I just said that it's a standard for TYPO3 documentation and widespread. I'm not a big fan of doing things different from the standard.

**Comment by dkd-dobberkau** [comment]
I think its good to have documentation that would come with the extension. I wonder if we could derive from markdown to ReST?

**Comment by irnnr** [comment]
@dkd-dobberkau That's the point, rest will ship with the extension and is a readable text format already. GitHub does render it, too. 

@peterkraume Another point against those tables: GitHub does not render them as on t3o. We can also discuss this in a Skype/Hangout/video session, I feel like text is not the right medium.

**Comment by timoschmidt** [comment]
What is the status on this issue? Can i support somewhere?

**Comment by peterkraume** [comment]
Well, I was in discussions with @irnnr and @dkd-dobberkau about the format, but that's still undecided.

**Comment by dkd-dobberkau** [comment]
so how do we get to a next step here folks?

**Comment by irnnr** [comment]
We will have documentation in reST and there's a branch already where I've started moving pages from the wiki to reST.

https://github.com/TYPO3-Solr/ext-solr/tree/documentation-rst

**Comment by irnnr** [comment]
Probably will have to pull some of @peterkraume's fork to finish it.

**Comment by martinhummer** [comment]
what is the status of this issue?
are you going to move the documentation to an own github repository and sync it with ter?
support needed?

**Comment by peterkraume** [comment]
Sorry guys, I'm currently not able to contribute to the documentation. Feel free to take all you need from my fork: https://github.com/peterkraume/ext-solr/tree/documentation

**Comment by DanielSiepmann** [comment]
@martinhummer the documentation will leave in _Documentation_ subfolder following TYPO3 best practice.

Currently you can contribute by forking and migrating the current documentation from forge to rst.
Also new and updated parts are welcome of course.

You can also take a look at @peterkraume 's fork and check what's missing or can be provided as a pull request to this main repository.

**Comment by timohund** [comment]
Closing the issue. Documentation was merged with #465
