### ISSUE TITLE
Add contribution rules to contrib.md file

### ISSUE THREAD

**Issue by timoschmidt** [TYPO3-Solr/ext-solr#202]
We should add a contrib.md file that describes how contributions can happend to give contributors more informations how they can get involved.

**Comment by timoschmidt** [comment]
@dkd-dobberkau 
@dkd-friedrich 
@dkd-janke 
@irnnr 

From the things i know right know i've prepared a draft version for our contribution guidelines:

https://github.com/timoschmidt/ext-solr/blob/task/add-contributing-md/CONTRIBUTING.md

It would be nice to get you feedback and when you could propose changes and stuff that is missing from you opinion.

**Comment by dkd-janke** [comment]
CONTRIBUTING.md reviewed

Todos/my thoughts:
- addon: i would not mention any further solr addon in this document
- wording: @irnnr please deliver the information up to 15.02.2016
- vagrantbox: @timoschmidt please move the vagrant box into the ext-solr-github project
- dockerimage: we would remove the docker hint, @innr feel free to deliver the dockerimage up to 15.02.2016
- review process: one review->one approval->merge.
