### ISSUE TITLE
[TASK] Get use of middleware stacks in TYPO3 9 for TSFE

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#2022]
In TYPO3 9 middleware stacks are use for the initialization of the TypoScriptFrontendController (TSFE). EXT:solr does the initialzation of the TSFE at some parts (e.g. in Util::initializeTSFE()). Since this should be avoided or might be impossible we should evaluate and implement the usage of middleware stacks for our needs when the TSFE is required.

**Comment by opi99** [comment]
Its needed to work with the new TypoScript conditions (Site, SiteLanguage, ...). They require initializing of NormalizedParamsAttribute (or better the Line with `$GLOBALS['TYPO3_REQUEST'] = $request;`) to work.

**Comment by bmack** [comment]
We can surely help with this. Some basic things regarding that:
- PSR-15 is not available for CLI
- only possible for TYPO3 v9

**Comment by timohund** [comment]
@bmack That sounds good. Our current plan is to release EXT:solr 9 by the end of december. In the version after 9, we plan to drop the support of TYPO3 8. I think it would be nice when you could help then. Or when you think it is easliy possible to implement into EXT:solr that it will work with TYPO3 8 and 9 then it would also be possible to do that earlier.

**Comment by dkd-kaehm** [comment]
### Done with #2529 via #2450.
