### ISSUE TITLE
TS error in ConnectionFromConfVars/setup.txt

### ISSUE THREAD

**Issue by gaumondp** [TYPO3-Solr/ext-solr#2036]
"solr.path.value =" is used instead of only "solr.path =" in file /Configuration/TypoScript/Examples/ConnectionFromConfVars/setup.txt

Quick fix for us:
plugin.tx_solr.solr.path.value >

**Comment by gaumondp** [comment]
Sorry it looks it's the other way around. It's the documentation that is in error at page:

https://docs.typo3.org/typo3cms/extensions/solr/Frontend/Languages.html?highlight=path

Value is missing there.

**Comment by timohund** [comment]
I think both is correct

This shows how it can be used without cObject, just by adding the plain value:

https://docs.typo3.org/typo3cms/extensions/solr/Frontend/Languages.html?highlight=path

The example "/Configuration/TypoScript/Examples/ConnectionFromConfVars/setup.txt" 
shows how to use it with values from the ConfVars (e.g. when they are set by the deployment"

so:

```
plugin.tx_solr.solr.path = TEXT
plugin.tx_solr.solr.path.value = /solr/core_en
```
and:

```
plugin.tx_solr.solr.path = /solr/core_en
```

should be the same. Or do you see any bug here?

**Comment by gaumondp** [comment]
I think my initial error was omitting the "= TEXT" part.

You can close this without worries.
