### ISSUE TITLE
[BUG] Uncached Plugins are not indexed

### ISSUE THREAD

**Issue by DonRagout** [TYPO3-Solr/ext-solr#2037]
Hi,

inside the fromPage function in the line 
`$contentExtractor = $this->getExtractorForPageContent($page->content);`
$page->content does not contain my uncached plugin. Instead it contains the INT.SCRIPT marker. Am I doing something wrong?

Thanks

**Comment by dkd-dobberkau** [comment]
ext:solr only indexes cached content.

**Comment by DonRagout** [comment]
OK thank you.
