### ISSUE TITLE
Minor config issue in solr 4.10.4

### ISSUE THREAD

**Issue by heiko-hardt** [TYPO3-Solr/ext-solr#205]
Hi, 

the log solr reports a minor configuration issue in the file "ext-solr/Resources/Solr/typo3cores/conf/solrconfig.xml". 
"Can't find (or read) directory to add to classloader: ../contrib/dataimporthandler/lib/"
In solr v.solr-4.10.4 this directory seems to be in ../contrib/dataimporthandler-extras/lib

kind regards
Heiko

**Comment by timoschmidt** [comment]
@heiko-hardt thx for reporting, i'll fix this soon.

**Comment by timoschmidt** [comment]
@heiko-hardt I've changed the configuration and created a pull request. Can you maybe shortly check if this is working for you as expected now? Then we can merge the pr and close this issue.

**Comment by heiko-hardt** [comment]
Hi Timo, sorry for the delay ... I checked your pull request. Looks great :) Thanks for fix.
Regards Heiko
