### ISSUE TITLE
Update solr index of subpages when branch gets moved

### ISSUE THREAD

**Issue by kraftb** [TYPO3-Solr/ext-solr#206]
When moving a page with subpages (branch) the "tstamp" of the moved pages get updated by the DataHandler but not the "tstamp" field of the subpages. The RecordMonitor will also just update the page being moved but not all pages in the branch.

As the "url" field of a solr document gets generated upon indexing a FE search result will point to a page which does not exist anymore.

**Comment by timoschmidt** [comment]
@kraftb 

Thx for the report. I think this could be done by refactorin isRecursiveUpdateRequired and taking the command/action into account and create and recusriveUpdateConfiguration in getUpdateSubPagesRecursiveTriggerConfiguration that is listening on timestamp and bound to a move only.
