### ISSUE TITLE
Index Inspector not showing in info module

### ISSUE THREAD

**Issue by LimeUwe** [TYPO3-Solr/ext-solr#2100]
Hi,

in version SOLR 8.1.0 / TYPO3 8.7.17 the search index inspector does not appear in the info module.
In another project with SOLR 7.5.2 / TYPO3 8.7.17 the inspector show up.

Looks like this issue: [#241](https://github.com/TYPO3-Solr/ext-solr/issues/241)

Regards,
Zwe

**Comment by timohund** [comment]
The index inspector was moved to the solr module "Info -> Indexed Documents"

**Comment by ste101** [comment]
Same problem here with TYPO3 8.7.18 and Solr 8.0.
No entry in the info module.
Works in 7.5
