### ISSUE TITLE
Overwrite local_lang with TypoScript fails for custom labels

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Solr/ext-solr#2108]
Hi folks,

# Problem

I add THE website's solr searchbox to the header of the website with TypoScript:

```
lib.View.Navigation.Search = COA
lib.View.Navigation.Search {
	10 < plugin.tx_solr_PiSearch_Search
	10 {
		search {
			targetPage = {$Tree.PageID.Search}
			ignoreGlobalQParameter = 1
		}

		view {
			pluginNamespace = tx_solr
			templateRootPaths < plugin.tx_solr.view.templateRootPaths
			templateRootPaths.20 = EXT:o5_theme/Resources/Private/Templates/Extensions/Solr/Searchbox/
		}
	}
}
```

and I extend EXT:solr's TypoScript setup like so:
```
plugin.tx_solr
	_LOCAL_LANG {
		de {
			submit = Suchen
			placeholderquery = Suchbegriff eingeben
		}

		en {
			placeholderquery = Enter search term
		}
	}
}
```

**The described configuration works when I set the cachingConfiguration to NullBackend**

```php
foreach ($GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations'] as $cacheName => $cacheConfiguration) {
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations'][$cacheName]['backend'] = \TYPO3\CMS\Core\Cache\Backend\NullBackend::class;
}
```
otherwise, following error is thrown:

	

> Oops, an error occurred!
> PHP Warning: Declaration of ApacheSolrForTypo3\Solr\ViewHelpers\TranslateViewHelper::compile($argumentsName, $closureName, &$initializationPhpCode, TYPO3\CMS\Fluid\Core\Parser\SyntaxTree\ViewHelperNode $node, TYPO3Fluid\Fluid\Core\Compiler\TemplateCompiler $compiler) should be compatible with TYPO3\CMS\Fluid\ViewHelpers\TranslateViewHelper::compile($argumentsName, $closureName, &$initializationPhpCode, TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\ViewHelperNode $node, TYPO3Fluid\Fluid\Core\Compiler\TemplateCompiler $compiler) in /app/web/typo3conf/ext/solr/Classes/ViewHelpers/TranslateViewHelper.php line 0
> More information regarding this error might be available [online](https://typo3.org/go/exception/CMS/1476107295).

Overwriting via TypoScript here works, if the locallang-key is know by EXT:solr. So if I change the following part in my custom fluid template from

> `{s:translate(extensionName: 'solr', key: 'placeholderquery')}`
to
> `{s:translate(extensionName: 'solr', key: 'submit')}`

no error is thrown.

**I can only reproduce the error when a detail page with EXT:news is shown** (Didn't tested another extbase ext so far...)

---

Is this a limitation of TYPO3 or the s:translate() VH? Or is it a bug? Or do I something wrong? (it worked in TYPO3 6.2 and an older ext:solr version=

---

### **Env:**

TYPO3 8.7 LTS, EXT:solr 8.1 stable, PHP 7.2

Maybe related: https://github.com/TYPO3-Solr/ext-solr/pull/269

**Comment by josefglatz** [comment]
thx @timohund for your support! 050ae71c480f6b668fbce5f070469e8e8335c4b8 is the fix.. Sorry that I did not test myself the actual dev-branch.

**Comment by josefglatz** [comment]
You can require the actual branch until the fixed version is published `composer require apache-solr-for-typo3/solr:dev-release-8.1.x`

> for reference: the fix is https://github.com/TYPO3-Solr/ext-solr/commit/050ae71c480f6b668fbce5f070469e8e8335c4b8

**Comment by josefglatz** [comment]
There must be also something else. I will try ti re-investigate

**Comment by timohund** [comment]
@josefglatz i'll close this for now, if you have anything new, please re-open the issue.
