### ISSUE TITLE
TSFE not properly initialised when indexing records via additionalPageIds

### ISSUE THREAD

**Issue by rschaufler** [TYPO3-Solr/ext-solr#2150]
Used version: 8.1.2

When indexing records that are configured via `additionalPageIds`, the `$GLOBALS['TSFE']` is not properly initialised.
Example:

Page ID root: 1
Page ID records (not within root): 20

when indexing records from pid 20, the indexer tries to find an indexing configuration on pid 20 first, see https://github.com/TYPO3-Solr/ext-solr/blob/8.1.2/Classes/IndexQueue/Indexer.php#L280

This leads to `$GLOBALS['TSFE']` being initialised for page ID 20. Since there is no configuration, the root page of this item will be used to find the configuration, see https://github.com/TYPO3-Solr/ext-solr/blob/8.1.2/Classes/IndexQueue/Indexer.php#L282

While this returns the proper configuration, the TSFE is still initzialized for page ID 20 which is wrong.
TSFE should be initialised for page id 1 instead.
Due to a broken TSFE, the URL to the record can't be rendered properly, especially when using realurl.

As a temporary solution i modified https://github.com/TYPO3-Solr/ext-solr/blob/8.1.2/Classes/Util.php#L138 as follows:

```
    /**
     * Loads the TypoScript configuration for a given page id and language.
     * Language usage may be disabled to get the default TypoScript
     * configuration.
     *
     * Forces re-initialization of TSFE
     *
     * @param int $pageId Id of the (root) page to get the Solr configuration from.
     * @param string $path The TypoScript configuration path to retrieve.
     * @param bool $initializeTsfe Optionally initializes a full TSFE to get the configuration, defaults to FALSE
     * @param int $language System language uid, optional, defaults to 0
     * @param bool $useTwoLevelCache Flag to enable the two level cache for the typoscript configuration array
     * @return TypoScriptConfiguration The Solr configuration for the requested tree.
     */
    public static function getConfigurationFromPageId($pageId, $path, $initializeTsfe = false, $language = 0, $useTwoLevelCache = true)
    {
        $pageId = self::getConfigurationPageIdToUse($pageId);

        static $configurationObjectCache = [];
        $cacheId = md5($pageId . '|' . $path . '|' . $language . '|' . ($initializeTsfe ? '1' : '0'));

        // force proper TSFE re-initialisation
        if ($initializeTsfe) {
            Util::initializeTsfe($pageId, $language);
        }

       [...]
```

**Comment by froemken** [comment]
I have created a PullRequest with a solution and 3 UnitTests for class Util. Hope they will merge it.

**Comment by froemken** [comment]
As I don't know, if this patch will be backported to earlier version, we have added this patch to our jwtools2 as XClass: https://github.com/jweiland-net/jwtools2 Go into EM and activate Checkbox to use the patched version.

**Comment by Mabahe** [comment]
Would like to have this in release-9.0.x, too. @froemken you wanna add a second PR?

**Comment by froemken** [comment]
@Mabahe 

If you need it in earlier versions we and also you can install jwtools2 where this patch is activateable.

Stefan

**Comment by Mabahe** [comment]
Pushed it myself. Thank for your help. Installing an additional tools extension just to get a patch is no option. Also using xclasses is the last option to go because of various reasons. I prefer composer patches.
