### ISSUE TITLE
FlexForm filter values are force quoted

### ISSUE THREAD

**Issue by rschaufler** [TYPO3-Solr/ext-solr#2151]
Version: 8.1.2

When trying to add more complex filter rules to the FlexForm filter section, all values are quoted which prevents them to work.

**Examples:**

Works:

![screenshot 2018-10-09 at 11 45 58](https://user-images.githubusercontent.com/3216408/46661182-f5058200-cbb8-11e8-904d-9568dd7fcddc.png)

Does not work:

![screenshot 2018-10-09 at 11 46 37](https://user-images.githubusercontent.com/3216408/46661217-0484cb00-cbb9-11e8-83e7-7a8df5140fcf.png)

Reason: https://github.com/TYPO3-Solr/ext-solr/blob/8.1.2/Classes/System/Service/ConfigurationService.php#L135

Maybe the quotes should not be applied at all and the user should just be aware of that. If using a phrase that contains spaces, the user could apply quotes himself

**Comment by markuskobligk** [comment]
I can confirm this behaviour, it breaks the autoauggest functionality in my project sind the value of filter gets quoted and breaks the request.

**Comment by rschaufler** [comment]
also found that this was intentionally implemented, see [https://github.com/TYPO3-Solr/ext-solr/issues/1742](https://github.com/TYPO3-Solr/ext-solr/issues/1742)

i think this fix broke the functionality more than it helped.

**Comment by rschaufler** [comment]
@markuskobligk if you want to fix this, just XCLASS the class mentioned in my issue description and remove the quoting. That's how i solved this problem for now

**Comment by timohund** [comment]
I would propose to add functional tests for this AND for #1742 instead of just removing it.

**Comment by benwalch** [comment]
@timohund @dkd-kaehm 
I think the best way would be to remove the force quoting entirely and update the documentation accordingly that string values with spaces have to be quoted.
This would add the most flexibility, and users can completely rely on the lucene query parser syntax when inserting custom filters. https://lucene.apache.org/core/3_0_3/queryparsersyntax.html

**Comment by echavaillaz** [comment]
I make a PR: https://github.com/TYPO3-Solr/ext-solr/pull/3703

I add a regex to prevent too big breaking change. The old behaviour is still working, so if a string value contains space(s) and no special characters of the solr query parser, the string is always wrapped with double quotes.

But if the string contains special characters no wrapping happen.

There is some cases where this PR can break, for example if the filter value is something like `toto AND tata` or `music (rock)` but I think this is not usual use case. So the breaking is as little than possible.
