### ISSUE TITLE
Adjust cURL options

### ISSUE THREAD

**Issue by jackd248** [TYPO3-Solr/ext-solr#2155]
Used version: 8.1.2

Hi, is there any way to adjust the page indexing process to ignore the http proxy? We have following problem: the environment system uses a http proxy to communicate to the www, so the proxy is set in the environment variables and the LocalConfiguration. But trying to index the pages resolves in a _curl error 28: operation timeout._ I can reproduce the situation on the shell, using a `--noproxy` option for the curl request is a solution for this problem. Obviously can the proxy not route the request on the own server correctly, but I have no option to access the settings of the proxy. Is there a solution in TYPO3 or in the ext-solr for this situation?

**Comment by timohund** [comment]
Did you try to configure a proxy with the TYPO3 settings?:

```
$GLOBALS['TYPO3_CONF_VARS']['HTTP']
```

We are using the guzzle package that is shipped with TYPO3 for the pgage indexing

**Comment by jackd248** [comment]
Yes, but this setting is used for the whole TYPO3 system. So e.g. an API interface needs to communicate via the proxy to the outside, but the page indexing process is addressing the own server via the proxy (and that causes in some issues). So is it possible to configure the proxy/cURL besides the global TYPO3 settings, just for the ext-solr?
