### ISSUE TITLE
Template not loaded if helhum/typo3-secure-web is used

### ISSUE THREAD

**Issue by garbast** [TYPO3-Solr/ext-solr#2168]
For some reason when working with helhum/typo3-secure-web Template->loadHtmlFile causes an oops

```
Oops, an error occurred! Code: 20181029103811d8cef7ad
- {"exception":"RuntimeException: Could not load template file \"EXT:sitepackage\/Resources\/Private\/Templates\/Extensions\/solr\/Templates\/PiResults\/results.htm\" in \/html\/deployment\/releases
\/47\/private\/typo3conf\/ext\/solr\/Classes\/Template.php:118
```

This can be solved by adding PATH_site in front of $GLOBALS['TSFE']->tmpl->getFileName($htmlFile);

**Comment by timohund** [comment]
@garbast Which version of EXT:solr are you using? This looks like an very old version that does not support FLUID templating.

**Comment by garbast** [comment]
Extension version is 6.5.1 and you are right its without fluid templating. Sorry for bothering.
