### ISSUE TITLE
possible analysis error when using textTight typo on some values

### ISSUE THREAD

**Issue by mopahle** [TYPO3-Solr/ext-solr#2180]
TYPO3 version: 9.5.1
Solr version: 7.4.0
PHP version: 7.2.11

Error messages / stack traces:
java.lang.IllegalArgumentException: startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=20,lastStartOffset=19 for field 'number_textTS'

Steps how to reproduce the issue
Index a document with german schema.xml and a field of type textTight (e.g. field_textTS). Use "0824638/BESCHRIFTET2" as value for this filed.

Expected behavior
The document is added to the index

Actual behavior
the index process fails (see error above)

Additional informations:
the solr documentation says that a Word Delimiter Graph Filter must be followed by a Flatten Graph Filter (during indexing). Adding a Flatten Graph Filter to the field type config after the Word Delimiter Graph Filter seems to solve the issue.

**Comment by timohund** [comment]
@mopahle Which EXT:solr version are you using? I think that this is fixed in dev-master, can you maybe check that?

**Comment by dkd-kaehm** [comment]
```
5.11.2020, 18:02:15 | ERROR false | x:core_de | RequestHandlerBase | org.apache.solr.common.SolrException: Exception writing document id adb9f05f793589a52bf2862108be842cd62b620b/pages/87/0/2/0 to the index; possible analysis error: startOffset must be non-negative,&#8203; and endOffset must be >= startOffset,&#8203; and offsets must not go backwards startOffset=0,&#8203;endOffset=20,&#8203;lastStartOffset=19 for field 'title_textTS'
```
by adding following to TypoScript setup and titling the page with "0824638/BESCHRIFTET2"
```
plugin.tx_solr.index.queue.pages.fields.title_textTS = title
```

**Comment by dkd-kaehm** [comment]
Test successful, all PR can be merged.

**Comment by dkd-kaehm** [comment]
There are a lot of other languages, which must be fixed as well.
