### ISSUE TITLE
Missing total matches for a group

### ISSUE THREAD

**Issue by Mabahe** [TYPO3-Solr/ext-solr#2190]
To be able to show a "nothing found" message one would need the total matches for a group.

solrfluidgrouping needs to be patched, too.

**Comment by Mabahe** [comment]
Will be set in resultSet::allResultCount with next solrfluidgrouping

**Comment by timohund** [comment]
@Mabahe what is left to close the issue? I guess it's resolved by using resultSet::allResultCount ?

**Comment by timohund** [comment]
@Mabahe  Closing this issue, if anything required in addition please re-open or create a new issue
