### ISSUE TITLE
Typo3 9.5.3

### ISSUE THREAD

**Issue by danaron** [TYPO3-Solr/ext-solr#2197]
Hi,
I do have TYPO3 9.5.3 and Apache Solr for TYPO3 8.1.2 on my system.
When I try to initialize the solr server, there is the error message:

Unable to contact following Apache Solr servers.

My host tells my that it is important that the versions match accouring to this matrix:
https://github.com/TYPO3-Solr/ext-solr/blob/master/Documentation/Appendix/VersionMatrix.rst
But there is no Version 9.5.3.

Somebody managed to make solr work on 9.5.3. and can provide the working configuration?
Thanks you.
Best regards
danaron

**Comment by timohund** [comment]
@danaron You should consider to sponsor the development of EXT:solr if you need a Version for TYPO3 9 LTS: https://www.typo3-solr.com/en/sponsors/our-sponsors/ . The reason why there is no version yet is the decrease of sponsors for EXT:solr in the last year.
