### ISSUE TITLE
Add default field configuration

### ISSUE THREAD

**Issue by dkd-friedrich** [TYPO3-Solr/ext-solr#222]
EXT:solrfal allows to define default fields that are valid for all contexts, see [_FILES.default](https://forge.typo3.org/projects/extension-solr/wiki/AddOnSolrfal#plugintx_solrindexqueue_FILESdefault). A possibility to define default fields that will be considered for all indexing configurations would be practical, too

Definition should be discussed, perhaps default fields could be defined via: 
plugin.tx_solr.index.queue._DEFAULT

**Comment by irnnr** [comment]
this already exists for all the TYO3 system fields like starttime, endtime, uid, pid...

**Comment by irnnr** [comment]
A bit more detailed:

EXT:solrfal is a bit special, and I think those default fields should be handled implicitly like in EXT:solr. It's not something the regular user should have to deal with or be able to tinker with. These are things that "should just work". In the context of files I'd treat them like system fields for other records, their behavior is well defined and should not change.

Therefore I'd actually suggest EXT:solrfal should remove that configuration and handle those internally. What do you think?

**Comment by irnnr** [comment]
Actually, I think I remember we already had a similar requirement in some project. So you could do something like this:

```
plugin.tx_solr.index.queue {

  _defaults = 0 // prevent indexing
  _defaults {
    foo = bar
    baz = TEXT
    baz.value = zzz
  }

  events < ._defaults
  events = 1
  events {
    title = ...
    content = ...
  }

  news < ._defaults
  news = 1
  news {
    title = ...
    content = ...
  }
}
```

**Comment by dkd-friedrich** [comment]
Yes, copying the indexing configuration or single fields is of course possible.

I thought it would be nice to have a possiblity to define default fields without copying, technically there is no need for this, just a nice to have.  

Further opinions? Should we close the issue?
