### ISSUE TITLE
[BUGFIX] HighlightResultViewHelper return htmlspecialchars error

### ISSUE THREAD

**Issue by ayacoo** [TYPO3-Solr/ext-solr#2229]
Hopefully this isn't a duplicate.

Context:
- TYPO3 8.7
- EXT:solr 8.1
- Apache solr 6.6.5

We haven't a "highlighting" in our response. The logic calls $document->getContent which returns an array with one item. So far so good.

Error message is now:
#1476107295: PHP Warning: htmlspecialchars() expects parameter 1 to be string, array given in .../typo3conf/ext/solr/Classes/ViewHelpers/Document/HighlightResultViewHelper.php line 107

IMO there should be a simple is_array fallback condition. 

If you should with this I can build a PR.

Best regards,
Guido.

**Comment by timohund** [comment]
@ayacoo By default only the field 'content' is configured to support highlighting and this is a string field. 

For sure it is possible to configure also multivalue fields for highlighting. If you want you can prepare a pull request that add's that support for the HighlightingResultViewHelper. Beside that it would require changes to the schema to support highlighting for other field types (see #2149).

**Comment by ayacoo** [comment]
@timohund Are you fine with this simple solution?

Our case could be fixed with "correct" typoscript settings and enable highlighting.

**Comment by timohund** [comment]
So would you need any change in EXT:solr?

**Comment by timohund** [comment]
When i configure:

```
plugin.tx_solr.search.results.resultsHighlighting = 0
```

There is no problem. Or do you mean something else?

**Comment by ayacoo** [comment]
I use the shipped base configuration and overwrite the results block:

```
        results {
            resultsHighlighting = 0
            resultsHighlighting {
                highlightFields = content
                fragmentSize = 200
                fragmentSeparator = [...]
                wrap = <span class="results-highlight">|</span>
            }
            siteHighlighting = 0
            resultsPerPage = 10
            showDocumentScoreAnalysis = 0
        }
```

**Comment by ayacoo** [comment]
Problem found: I use the standard solrconfig.xml and schema.xml. If i use your shipped example the problem isn't there. So i think we can close this issue. Sorry for the circumstances!
