### ISSUE TITLE
Garbage collector ignores records translations

### ISSUE THREAD

**Issue by dogawaf** [TYPO3-Solr/ext-solr#2235]
Hi

Scenario:
- a record is created in default language (gb)
- it is now in the index queue, and after indexing, in solr's core_gb
- the record is localized in the other language (fr)
- it is updated in the index queue, and after indexing, in solr's core_gb and core_fr

All is fine.

Now : 
- I hide the localized record
- the garbage collector does not remove the record from core_fr
- I hide the record in default language
- the garbage collector removes the record from both core_gb and core_fr

IMHO, the garbage collector should manage properly operations on overlayed records.

**Comment by internezzo-prod** [comment]
It seems the issue is that in  https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/GarbageCollector.php#L251 collectGarbage is called using the localized of the record.
But since the records are indexed using the uid of the default-language-record, nothing is removed...
