### ISSUE TITLE
Support autocorrection

### ISSUE THREAD

**Issue by timoschmidt** [TYPO3-Solr/ext-solr#224]
When a user searches for something and there is no result but suggestions have been made a second search with the first suggestion should be triggered.

**Comment by irnnr** [comment]
Already exists and in use on typo3.org :)

`plugin.tx_solr.search.spellchecking.searchUsingSpellCheckerSuggestion = 1`

**Comment by irnnr** [comment]
Might be broken though :-/ https://typo3.org/extensions/repository/?id=23&L=0&q=cintent

**Comment by dkd-dobberkau** [comment]
Are you sure this works?

https://typo3.org/search/?id=180&L=0&q=smp

**Comment by timoschmidt** [comment]
I'll check for the existance and fix it.

**Comment by irnnr** [comment]
... used to work
