### ISSUE TITLE
Deprecation Notice in "Info" after Update to 9.0

### ISSUE THREAD

**Issue by mjpr263** [TYPO3-Solr/ext-solr#2247]
After updating from version 8.1.2 to 9.0.0 (Typo3 8.7.24) i get the folowing error after clicking an the "Info"-Tab:

TYPO3 Deprecation Notice: AbstractSolrService::getPath is deprecated please use getCorePath() now. Will be dropped with EXT:solr 10 in /xxx/htdocs/typo3conf/ext/solr/Classes/System/Solr/Service/AbstractSolrService.php line 114

So i can not view the Info-Tab. Solr seems to work.

**Comment by timohund** [comment]
@mjpr263 Do you have any addons installed or other extensions that are using the solr api? Did you clear the cache and also the cached fluid templates?

**Comment by mjpr263** [comment]
Yes, id did. I cleared the cache via backend, i cleard "all caches" via install-tool, i even re-installed the extension. The 3 other tabs in the backend are working, but the info-tab is not.

**Comment by timohund** [comment]
@mjpr263 i can  confirm that, will be fixed with EXT:solr 10 and 9.0.1
