### ISSUE TITLE
[FEATURE] Support route enhancers of TYPO3

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#2257]
**Is your feature request related to a problem? Please describe.**

It would be nice to support route enhancers of TYPO3 9 LTS in EXT:solr in order to support speaking urls. We need to check for which use cases this makes sence.

**Target versions**

10

**Comment by dkd-kaehm** [comment]
Related: #2307

**Comment by jproy418** [comment]
+1, Looking foward for this feature. Thanks for doing that!

**Comment by dkd-kaehm** [comment]
@jproy418 
please checkout `upcoming-feature/Introduce_Route-Enhancer` branch and test it.
Make comments in #2755
