### ISSUE TITLE
[BUG] EXT:solr does not work with current solarium release

### ISSUE THREAD

**Issue by tbd-rsm** [TYPO3-Solr/ext-solr#2260]
**Describe the bug**
EXT:solr can not establish connection to solr since solarium 4.3.0.

**To Reproduce**
1. composer update, so that solarium is at `4.3.0-alpha.2`
2. Solr Status Report fails.

**Expected behavior**
I expect EXT:solr to establish a connection to Solr, as it did before for the same setup/configuration.

**Used versions (please complete the following information):**
 - TYPO3 Version: [9.5.4]
 - Browser: [chrome]
 - EXT:solr Version: [9.0.0]
 - Used Apache Solr Version: [x.x.x]
 - PHP Version: [7.2.0]
 - MySQL Version: [x.x.x]

**Additional context**
EXT:solr has dependency `"solarium/solarium": "^4.2.0",`
When updating, solarium `4.3.0-alpha.2` is installed.

That version introduced a breaking change: 
> In almost every setup, the path has to be set to / instead of /solr with this release!
- https://github.com/solariumphp/solarium/releases/tag/4.3.0-alpha.2

EXT:solr builds the solarium endpoint path in `ApacheSolrForTypo3\Solr\System\Solr::getCoreBasePath()` and the solarium endpoint core name in `ApacheSolrForTypo3\Solr\System\Solr::getCoreName()`.

For `plugin.tx_solr.solr.read.path = /solr/foo/` that makes `/solr/` and `foo`.
For `plugin.tx_solr.solr.read.path = /foo/` that makes `//` and `foo`.
Both variant lead to invalid URIs.

When I (as a test) modify `ApacheSolrForTypo3\Solr\System\Solr::getCoreBasePath()` to always return `"/"`, the status check works fine.

**Workaround**
Adding `"solarium/solarium": "~4.2.0"` to my project's `composer.json` restricts solarium version to `< 4.3.0`. After reinstalling/updating this solves the problem.

**Comment by timohund** [comment]
@tbd-rsm thx for your report. I propose to set the dependency to "~4.2.0" in our composer.json file, and increase it when we have a solution for that.

**Comment by timohund** [comment]
@tbd-rsm i've created a pr for that. Can you please test that? We should add that to the 9.0.1 release

**Comment by tbd-rsm** [comment]
@timohund Thank you!

I tested installation in cloned ext-solr only, because I don't know how to tell composer to respect the patch while resolving solarium dependency in my project setup.
That worked as intended.

As mentioned before EXT:solr works well in my project setup when restricting to `4.2.0` manually. So I guess we can assume that the PR does what it should.

**Test Details**

```
git clone https://github.com/TYPO3-Solr/ext-solr.git
php composer.phar install -d ext-solr/
# solarium 4.2.0 installed
```
- [ ] Composer installed 4.2.0 because the conflicting release is `alpha`. -> This issue is not relevant for production builds yet, but will become so soon if not fixed.

```
php composer.phar config minimum-stability dev
php composer.phar update -d ext-solr/
# solarium 4.3.0-alpha.2 installed
```
- [ ] Composer installed conflicting 4.3.0-alpha.2 as expected.

```
cd ext-solr/
wget https://patch-diff.githubusercontent.com/raw/TYPO3-Solr/ext-solr/pull/2262.patch
git apply 2262.patch
cd ..
php composer.phar update -d ext-solr/
# solarium 4.2.0 installed
```

- [x] Composer installed 4.2.0 as intended by the patch.

**Comment by timohund** [comment]
@tbd-rsm thx for your feedback, will be part of 9.0.1
