### ISSUE TITLE
excludeContentByClass is slowing down Indexing

### ISSUE THREAD

**Issue by timoschmidt** [TYPO3-Solr/ext-solr#227]
The excludeContentByClass feature is currently slowing down the indexing process because the default configuration "excludeContentByClass = typo3-search-exclude" existst.

This means each page is checked for this class and a DOMObject is instanciated even when the class is not present at all. To avoid this we should optimize the perfomance here.

- Profile indexing peformance
- Add an early return when non of the classes is present (str_pos should be enough) and only do the parsing when needed.

**Comment by irnnr** [comment]
:+1:

**Comment by timoschmidt** [comment]
Should go into releases-3.1.x as well

**Comment by timoschmidt** [comment]
Not relevant for 3.1.x
