### ISSUE TITLE
[BUG] Wrong indexing configuration for records outside domain

### ISSUE THREAD

**Issue by dogawaf** [TYPO3-Solr/ext-solr#2303]
Hello

When indexing records from other site root, I have an issue and I do not understand ext:solr’s behaviour.

**Describe the bug**

When a record from another domain is indexed, it is the typoscript configuration of the another domain that it is used.

**Expected behavior**

When a record from another domain is indexed, the typoscript configuration of the domain for which the indexer is running should be used.

**Step to reproduce**

- Given a Site A and a Site B.
- The Site A contains a news folder, with a news record inside it.
- The Site B have this in its indexing configuration: `index.queue.news.additionalPageIds = <id of the news folder of Site A>`
- Edit the news on the Site A, two items are created is the index queue : one for each site, because the record is « attached » to the Site A by its rootline, and detected by the Site B, thanks to `additionalPageIds`.
- Run the indexer for the Site B.

Here is the problem: the index item of Site B is indexed with the indexing configuration of Site A. This is because the indexing configuration is loaded with the record pid (see `Indexer::getFieldConfigurationFromItemRecordPage()` ).

For me it is a problem: because the record has been queued for Site B, it should also be indexed with Site B indexingConfiguration.
Why is the item indexed with a different typoscript than when it was queued?

I fix the problem by passing the index queue item’s rootPageId instead of the record’s pid in `Indexer::getFieldConfigurationFromItemRecordPage()`

```php
// before
$solrConfiguration = Util::getSolrConfigurationFromPageId($item->getRecordPageId(), true, $language);
// after
$solrConfiguration = Util::getSolrConfigurationFromPageId($item->getRootPageUid(), true, $language);
```

What do you think about that?

Cheers
Rémy.

**Used versions (please complete the following information):**
 - TYPO3 Version: 8.7
 - EXT:solr Version: 8.0.3

**Comment by dogawaf** [comment]
Additional note : if the news folder is outside any domain, then the rootpageId of the index item will be used. So my issue arise only if the news folder is owned by a domain.

I think the fix of #1291 partially solved the original problem.
A record oustide any domain can be indexed, but a record from another domain is indexed with the wrong typoscript configuration.

I think we should inverse the loading of solrConfiguration in `\ApacheSolrForTypo3\Solr\IndexQueue\Indexer::getItemTypeConfiguration()`:
- first we should check if there is a configuration for the item with `getFieldConfigurationFromItemRootPage()`, which must returns the configuration if it exists for the item's rootpage AND if the item record's pid is found inside additionalPageIds.
- and then fallback to `getFieldConfigurationFromItemRecordPage()`

With that inversion, the fix of #1291 remains valid, and my issue is also solved.

**Comment by dogawaf** [comment]
Maybe related to #2150

**Comment by froemken** [comment]
As I don't know, if this patch will be backported to earlier version, we have added this patch to our jwtools2 as XClass: https://github.com/jweiland-net/jwtools2 Go into EM and activate Checkbox to use the patched version.
