### ISSUE TITLE
[BUG] Extbase ConfigurationManager loads the wrong typoscript

### ISSUE THREAD

**Issue by dogawaf** [TYPO3-Solr/ext-solr#2314]
**Describe the bug**
During the indexation from a scheduler task, the extbase ConfigurationManager always load the configuration of the root domain.

**To Reproduce**
1. Set a TYPO3 instance with 2 websites
2. Add a field in an index configuration for a record (like news) and use a FLUIDTEMPLATE for the rendering
3. In the fluidtemplate, call <f:cObject /> ViewHelper, with an existing typoscript path
4. The typoscript path should render something different for each website
5. Index with a scheduler task
5. The indexed content of the second website contains a content with the typoscript of the first website

**Expected behavior**
The extbase ConfigurationManager should load the configuration based on the rootpage id of the current site configuration.

Note: the issue does not exists if the indexing is triggered from the backend module, because a site is selected in the pagetree, and &id GET parameter contains something that is used by the extbase's configuration manager.

**Used versions (please complete the following information):**
 - TYPO3 Version: 8.7.24
 - EXT:solr Version: 8.0.3

**Comment by dogawaf** [comment]
Proposed patch: [solr.patch.txt](https://github.com/TYPO3-Solr/ext-solr/files/3187981/solr.patch.txt)

**Comment by dkd-kaehm** [comment]
Closing because the issue to old.
