### ISSUE TITLE
[BUG] successfull installation and indexing, but all querys fail due to weird solr behavior

### ISSUE THREAD

**Issue by AlexanderKoe** [TYPO3-Solr/ext-solr#2319]
Installed extension solr 9.0.2 on TYPO3 8.7.24, created solr-container with docker according to documentation. (apache solr 7.6.0)

Installation Extension: fine
Docker container: fine
Access to solr with Solr Admin: fine
Created typoscript and Connect Solr to TYPO3: fine
Indexed Pages: fine
Tested the indexed pages in Solr Admin: fine
(all contend successfully indexed, successful simple query with *.* offers multiple results with "content" and "title" filled)

Now the weird problem:
Search for simple word in typo3 solr frontend search form: does not display any results.
I finaly came down to test the query from solr extension in solr admin:

this is the query:

+DisjunctionMaxQuery(((tagsH2H3:fahrzeug)^3.0 | (keywords:fahrzeug)^2.0 | (tagsH4H5H6:fahrzeug)^2.0 | author:Fahrzeug | subtitle:Fahrzeug | navtitle:Fahrzeug | (description:fahrzeug)^4.0 | (tagsH1:fahrzeug)^5.0 | abstract:fahrzeug | (title:fahrzeug)^5.0 | (content:fahrzeug)^40.0 | tagsInline:fahrzeug)) ()

this query returns 0 results in solr admin, which is not true

now i tested more simple querys:

content:fahrzeug -> multiple results found, correct
content:fahrzeug | title:home    -> 1 results found, correct
content:fahrzeug | title:fahrzeug   -> ZERO results found, failed why? this is OR query? 

solr seems to have a problem with the same search word in multiple fields. The "OR" is useless.
based on this the complex typo3 query failed. Based on this all simplified query parts of the complete query fail, exept the simplest one: "content:fahrzeug" is the only one getting results.

has this ever happend before? any ideas?

**Comment by timohund** [comment]
@AlexanderKoe in guess the issue here is that the minimum match parameter is influencing the query and results:

https://blog.thedigitalgroup.com/solrs-mm-parameter-explanation-of-min-number-should-match
https://lucene.apache.org/solr/guide/6_6/the-dismax-query-parser.html

Did you try to adjust that?

**Comment by dkd-kaehm** [comment]
Closing due lack of response.
