### ISSUE TITLE
Prevent overwriting field type doesn't work for pages

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Solr/ext-solr#232]
The bugfix https://github.com/TYPO3-Solr/ext-solr/commit/d875657b6645c208dfbac0bb4a0b827b950a3894

to prevent overwriting field type does not work for pages as 
\ApacheSolrForTypo3\Solr\IndexQueue\FrontendHelper\PageFieldMappingIndexer

has its own resolveFieldValue method.

Corresponding exception should also be thrown there.

**Comment by timoschmidt** [comment]
@AndreasA I've created a fix for dev-master that fixes the problem. Can you please check and try if this resolves your problem?

**Comment by AndreasA** [comment]
@timoschmidt: I will re-test this but probably not this week. Probably next week but not 100% sure.
