### ISSUE TITLE
[BUG] TSFE is not properly initialised if configuration has a hit in 2nd level cache

### ISSUE THREAD

**Issue by Mabahe** [TYPO3-Solr/ext-solr#2328]
Stumbled over a similar problem like described in #2150, but with the second level cache.
As a result you get different TSFE objects when indexing records via additionalPageIds outside the normal page tree for the first indexing (without TwoLevelCache hit) and second indexing (with TwoLevelCache hit).

To fix this, TSFE needs to get also initialized, if $initializeTsfe is true and there is a hit in the 2nd level cache.

**Comment by dkd-kaehm** [comment]
@Mabahe which versions are affected?

**Comment by timohund** [comment]
@Mabahe can you please check if this issue is fixed for you with #2329 or if not, do you have the time to prepare a pr?

**Comment by Mabahe** [comment]
This is not related to #2329, since the 1stLevel cache is static var in Util::getConfigurationFromPageId(). Yes, will push a PR.
Perhaps the cache usage in  Util::getConfigurationFromPageId() could be optimized after this.

**Comment by Mabahe** [comment]
@dkd-kaehm in this project we are on 7.5. but also master is affected
