### ISSUE TITLE
getSolrConnectionsByItem returns solr connections for all available languages, even if the language doesn't have a connection

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Solr/ext-solr#233]
In \ApacheSolrForTypo3\Solr\IndexQueue\PageIndexer

we are doing:

```
foreach ($translationOverlays as $overlay) {
      $languageId = $overlay['sys_language_uid'];
      $accessibleSolrConnections[$languageId] = $solrConnections[$languageId];
}
```

That results in $accessibleSolrConnections having null values if there is no solr connection for a certain language which will then result in index error as indexPage is executed with no connection

**Comment by timohund** [comment]
Closing, pr was merged
