### ISSUE TITLE
[BUG] All indexing properties are deleted on IndexQueue initialization

### ISSUE THREAD

**Issue by friggingee** [TYPO3-Solr/ext-solr#2335]
**Describe the bug**
When using index queue item properties and initializing the index queue for more than one index queue item type, all index queue properties are deleted regardless of their belonging.

**To Reproduce**
1. Create two index queue configurations, both of which needs to make use of indexing properties.
2. Initialize the index queue for both index queue configurations.
3. The index queue item property table `tx_solr_indexqueue_indexing_property` table will only contain the index queue properties of the last processed configuration.

**Expected behavior**
The index queue item property table shows the index queue item properties of all index queue items initialized.

**Used versions (please complete the following information):**
 - EXT:solr Version: >= 8.0.0

**Additional context**
This error occurs because of this commit: https://github.com/TYPO3-Solr/ext-solr/commit/6b12dbce50e647487598698c17bdf7b72925d521.
More specifically, the reason is this piece of code: https://github.com/TYPO3-Solr/ext-solr/commit/6b12dbce50e647487598698c17bdf7b72925d521#diff-860383d1d0d4508c3d7cecf72b95f51dR382 which still lives on in the current master: https://github.com/TYPO3-Solr/ext-solr/blob/151fd124af52eb85a7d58136fca1bb25e98a7fa1/Classes/Domain/Index/Queue/QueueItemRepository.php#L489.

The issue here is that this `delete` query always results in `DELETE FROM tx_solr_indexqueue_indexing_property;` without a `WHERE` or `JOIN` because of https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Database/QueryBuilder/Index.html#delete:
> ->delete() ignores ->join() 

This construct of "deleting by a join condition" worked before the commit mentioned above because there a plain SQL query was used instead of doctrine DBAL.

**Comment by friggingee** [comment]
Any ETA on this issue?

**Comment by dkd-dobberkau** [comment]
How about a PR?
