### ISSUE TITLE
Synoym containing / char can't be deleted (depends on SOLR-6853)

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Solr/ext-solr#2336]
A customer created the following synoym:
- Base word: `1/2"`
- Synonyms: `0, 1/2", 5`

The synonym can now not be deleted anymore in the backend

**Screenshots**
![Bildschirmfoto 2019-07-30 um 09 16 05](https://user-images.githubusercontent.com/1905663/62108849-54995f00-b2ab-11e9-8de3-5d15e526bc47.png)

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.8
 - EXT:solr Version: 9.0.2(and all supported Versions)
 - Used Apache Solr Version: 7.6.0
 - PHP Version: 7.2.19

**Note from RK:** Depends on https://issues.apache.org/jira/browse/SOLR-6853

**Comment by dkd-kaehm** [comment]
Must be fixed. 
There is something with url/json encoding

**Comment by mschwemer** [comment]
Just tested it with EXT:solr 11.0.3 ... works here. 

Might be an issue with the solarium client ... see  also #2851

**Comment by dkd-kaehm** [comment]
Unfortunately that is still impossible.

**Comment by dkd-kaehm** [comment]
**This issue can be resolved only after https://issues.apache.org/jira/browse/SOLR-6853 is fixed.**

**Comment by dkd-kaehm** [comment]
Reopen to be able to fix it after SOLR-6853.
