### ISSUE TITLE
Fatal error in addDocumentFieldsFromTyposcript

### ISSUE THREAD

**Issue by nurbs999** [TYPO3-Solr/ext-solr#234]
We have an issue if some configured fields in Typoscript are empty. getItemTypeConfiguration return null instead of an empty array and the indexer dies.

PHP Catchable Fatal Error: Argument 2 passed to Tx_Solr_IndexQueue_AbstractIndexer::addDocumentFieldsFromTyposcript() must be an array, null given, called in /var/www/somesite/typo3conf/ext/solr/Classes/IndexQueue/Indexer.php

A fix could be
`$itemIndexingConfiguration = array();`
`if( !is_null($this->getItemTypeConfiguration($item, $language))) {`
`$itemIndexingConfiguration = $this->getItemTypeConfiguration($item, $language);`
`}`

**Comment by timoschmidt** [comment]
Hi @nurbs999 which version are you using? Looks like an older version of tx_solr

**Comment by nurbs999** [comment]
3.0.0
Is this an old bug which already got fixed?

**Comment by timohund** [comment]
This issue is fixed in 6.1.0
