### ISSUE TITLE
[BUG] Getting EventDispatcher error when trying getting the search result list

### ISSUE THREAD

**Issue by webfacer** [TYPO3-Solr/ext-solr#2344]
**Describe the bug**
When entering search result list. It works but when starting searching i am getting the error that Symphonie Dispatcher is depricated.

**To Reproduce**
1. Go to search result with some searchtext
2. Click on  search
3. and you should see the error

**Expected behavior**
It should show me the search result list.

**Screenshots**
Uncaught TYPO3 Exception
#1476107295: TYPO3 Deprecation Notice: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead. in /var/www/vendor/symfony/event-dispatcher/EventDispatcher.php line 5

caused by this line `Symfony\Component\EventDispatcher\EventDispatcher::dispatch("solarium.core.preCreateRequest", Solarium\Core\Event\PreCreateRequest)`

**Used versions (please complete the following information):**
 - TYPO3 Version: 8.7.27
 - EXT:solr Version: [e.g. 9.0.2]
 - Used Apache Solr Version: [e.g. 7.6.0]
 - PHP Version: [e.g. 7.2.21]
 - MySQL Version: [e.g. 5.5.5]

**Comment by dkd-kaehm** [comment]
@webfacer : 
Please configure `$GLOBALS['TYPO3_CONF_VARS'][SYS][exceptionalErrors]` properly
See https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/ErrorAndExceptionHandling/Configuration/Index.html (works on 8.7 as well)
and
https://maximivanov.github.io/php-error-reporting-calculator/

---

Caused in https://github.com/symfony/event-dispatcher/blob/4.3/EventDispatcher.php#L58
and Fixed in https://github.com/solariumphp/solarium/pull/682

@todo: upgrade to newer soalrium version in 10-dev

**Comment by webfacer** [comment]
this is not the answer which i looked for. if i am doing that, disable the exeptional Error. I get the SolrNotAvailable because the eventdispatcher is wrong configured. is this issue on the pipe because you closed it?

**Comment by webfacer** [comment]
sry i was wrong with it, because it was still cached and i did not recognized it. after clearing caches it works fine. thanks you!

**Comment by davidlemaitre** [comment]
thanks @dkd-kaehm, $GLOBALS['TYPO3_CONF_VARS'][SYS][exceptionalErrors] was configured with 20480 value (the default value according the help message in the Install Tool, but for the TYPO3 Core API doc, the default is 4341), I set it to 4341 and the error message has disappeared !
