### ISSUE TITLE
[BUG] Escaped xml-like strings are stripped form the search

### ISSUE THREAD

**Issue by Nemo64** [TYPO3-Solr/ext-solr#2348]
**Describe the bug**
The HtmlContentExtractor strips everything that looks like xml, even something like `<something else>`. There is a similar issue in #1541 but that did only resolve some cases.

**To Reproduce**
Add content like `<number>` to a page and index it, it will be stripped.

**Expected behavior**
All literal content should be searchable

**Used versions (please complete the following information):**
 - TYPO3 Version: 8.7.27
 - Browser: chrome
 - EXT:solr Version: 7.5.3 but also reproducable in 8.1.2
 - Used Apache Solr Version: 6.6.2
 - PHP Version: 7.1.31
 - MySQL Version: 5.7.27

**Comment by Nemo64** [comment]
Ohh, and I noticed, there is a test called `changesNbspToSpace` which actually did only not check for space but for [U+00A0](https://www.compart.com/de/unicode/U+00A0) which is the utf8 character for a no breaking space.

My changes accidentally fixed that functionality too, which means i had to change the test to actually check for a space. I assume it was a copy&paste error that there was an utf8 no breaking space in there.

**Comment by timohund** [comment]
@Nemo64 Can you create a pr for master and release-9.0.x as well?

**Comment by Nemo64** [comment]
done. It's basically a cherry-pick.
