### ISSUE TITLE
[TASK] Add documentation how to use EXT:solr with site handling

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#2362]
**What should be done in the scope of this task?**

* Document how to configure TYPO3 9 with the sitehandling as implemented in #2291 
* Explain the idea's behind as well (simpliefied and reduced configuration with the ui, advanced configuration by yaml)
* Explain how to setup username and password for solr with env variables

**Comment by NochEinKamel** [comment]
> Every setting can be defined on the language level, if it is not configured on the language level it fallsback to the global setting.

FYI custom values added to languages in the yaml do not survive a GUI edit of that language – Perhaps that should be added as a warning to "Limitations of the site UI and yaml configuration"?

**Comment by timohund** [comment]
@NochEinKamel It is allready mentioned in the release notes:

https://github.com/TYPO3-Solr/ext-solr/blob/master/Documentation/Releases/solr-release-10-0.rst#limitations-of-the-site-ui-and-yaml-configuration

and also in the documentation:

https://github.com/TYPO3-Solr/ext-solr/blob/master/Documentation/Backend/ConnectionManager.rst
