### ISSUE TITLE
[TASK] Add issue and PR templates

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/ext-solr#237]
We should put templates for different tasks into `./github` in order to take care all required informations are available.

Templates should be added for:
- [x] Bug reports
- [x] Feature requests
- [x] Tasks

Informations for bug reports:

- Desription
- How to reproduce
- Expected gehaviour
- Screenshot
- Core informations (TYPO3 etc.)
- Additional context

Information for issues:

- Steps to reproduce
- Expected behavior
- Actual behavior
- Composer mode, yes/no
- TYPO3 version
- EXT:solr version
- Apache Solr version
- PHP version

Information for pull requests:

- Fixes issue #
- Changes proposed
- Code review
- Tests included
-  Documentation provided

Documentation:
- https://github.com/blog/2111-issue-and-pull-request-templates
- https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests

**Comment by timoschmidt** [comment]
Nice!

**Comment by irnnr** [comment]
The article and the docs have some good examples. I think we should ask for 

**Issues**:
* Steps to reproduce
* Expected behavior
* Actual behavior
* Composer mode, yes/no
* TYPO3 version
* EXT:solr version
* Apache Solr version
* PHP version

**PRs**:
* Fixes issue # 
* Changes proposed
* [ ] Code review
* [ ] Tests included
* [ ] Documentation provided

anything else?

Also keeping an eye on this list, some are pretty good already: https://github.com/devspace/awesome-github-templates/blob/master/readme.md

**Comment by 3l73** [comment]
This issue is solved.
