### ISSUE TITLE
[TASK] Update the Documentation to use new rendering style

### ISSUE THREAD

**Issue by dkd-dobberkau** [TYPO3-Solr/ext-solr#2372]
Our current documentation shows this Hint:

This documentation is not using the current rendering mechanism and will be deleted by December 31st, 2020. The extension maintainer should switch to the new system. Details on how to use the rendering mechanism can be found here:

https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Index.html

Therefore we need to make sure that our documentation gets updated to a corresponding rendering style.

**Comment by timohund** [comment]
Done, webhook, was added, documentation is re-rendered for master
