### ISSUE TITLE
[BUG] SolrConfigurationStatus on missing domains reports wrong rootPages

### ISSUE THREAD

**Issue by tbd-rsm** [TYPO3-Solr/ext-solr#2375]
**Describe the bug**
In Typo3 backend status report page the EXT:solr check for domain records reports wrong rootPages with missing domains.

**To Reproduce**
1. Create 3 rootPages, one of them with a domain record, in my example:
    - id 1, title "page1"
    - id 11509, title "page2" (with domain record)
    - id 11510, title "page3"
2. Initialize solr connections
3. open status report
4. see section solr/domain records

**Observed behaviour**

```
Domain records missing
Domain records are needed to properly index pages. The following sites are marked as root pages, but do not have a domain configured:
* [11509] page2
* []
```

**Expected behavior**
I expect the domain record check to report the correct rootPages with missing domains.

```
Domain records missing
Domain records are needed to properly index pages. The following sites are marked as root pages, but do not have a domain configured:
* [1] page1
* [11510] page3
```

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.9
 - Browser: -
 - EXT:solr Version: release 9.0.2 and branch release-9.0.x (commit f5a6566428dd1d768c37828c2672b736fe39ac90)
 - Used Apache Solr Version: 7.5.0
 - PHP Version: PHP Version 7.2.13-1+0\~20181207100623.13+jessie\~1.gbpf57305
 - MySQL Version: 5.7.16

**Additional context**
The root of this lies in `\ApacheSolrForTypo3\Solr\Report\SolrConfigurationStatus::getRootPagesWithoutDomain`.
When a rootPage with missing domain is recognized it gets pushed to `$rootPagesWithoutDomain`. For that it is taken by ID from `$rootPages` as if the root pages array was associative, which it isn't.

I'll try to provide a PR soon.

**Comment by dkd-kaehm** [comment]
Two PRs covered this issue.
