### ISSUE TITLE
Classmap not generated properly when installing from typo3-ter/solr via composer

### ISSUE THREAD

**Issue by timoschmidt** [TYPO3-Solr/ext-solr#238]
When you install the extension from the typo3ter composer repository with composer the class "Apache_Solr_Service" is not found. Also the autoload section in the ext_emconf.php is missing

**Comment by KaffDaddy** [comment]
Workaround in composer.json:

```
{
  "repositories": [
    {
      "type": "composer",
      "url": "http://composer.typo3.org/"
    }
  ],
  "name": "YOURVENDOR/YOURPACKAGE",
  "description": "YOURDESCRIPTION",
  "license": "GPL-2.0+",
  "require": {
    "typo3/cms": "^7.6",
    "typo3-ter/solr": "3.1.1"
  },
  "extra": {
    "typo3/cms": {
      "cms-package-dir": "{$vendor-dir}/typo3/cms",
      "web-dir": "web"
    }
  },
  "autoload": {
    "files": [
      "web/typo3conf/ext/solr/Resources/Private/Php/SolrPhpClient/Apache/Solr/Service.php"
    ]
  }
}
```

**Comment by sebkiwi** [comment]
This only adds the service class. You should map the entire namespace. You can do so by adding this to your project's composer.json
`{
	"autoload": {
		"psr-0": {
			"Apache_": "typo3conf/ext/solr/Resources/Private/Php/SolrPhpClient/"
		}
	}
}`

**Comment by timoschmidt** [comment]
@KaffDaddy 
@sebkiwi 

This issue was fixed by the TYPO3 composer team, maybe you can shortly verify and we can close the issue.

**Comment by timoschmidt** [comment]
Checked and it's working closing the issue.
