### ISSUE TITLE
[TASK] Move site handling settings into an own namespace

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#2382]
**What should be done in the scope of this task?**

To have all solr related settings in one place, we should move them into an own namespace in the yaml file.

We need to:

* Move the settings into an own namesapace (e.g. solr. ...)
* Make sure that the fallback logic (for write and read cores, works with that change)

**Comment by achimfritz** [comment]
we see no possibility to introduce an own namespace with the current Implementation of SiteConfiguration Form-Engine (without XClassing)
