### ISSUE TITLE
[TASK] RuntimeException: Failed to execute Page Indexer Request

### ISSUE THREAD

**Issue by multras** [TYPO3-Solr/ext-solr#2389]
**What should be done in the scope of this task?**

I configured solr on my Typo3 web site successfully, but The indexing works fine for news but not for pages. 

I get this error :

`Manual Indexing
An error occurred while indexing manual from the backend.`

When I click on Show error, I found this error : 

`1319116885: RuntimeException: Failed to execute Page Indexer Request. See log for details. Request ID: 5d728d6969ccf in /var/www/mysite.com/typo3conf/ext/solr/Classes/IndexQueue/PageIndexerRequest.php:219`

My config :

EXT: solr : 9.0.2
Solr Apache : 7.6.0
TYPO3 : 9.5.3

--

**Comment by Udo771** [comment]
Maybe a problem with a proxy. Attempt to enable / disable proxy in LocalConfiguration.php ('HTTP' => ['proxy' => 'http: //yourProxy.tld: yourPort']).

**Comment by dogawaf** [comment]
You should look for a detailed error in the solr.log file.
The log file should be located in typo3temp/var/logs.
