### ISSUE TITLE
[BUG] site configuration write config issue

### ISSUE THREAD

**Issue by gionkoch** [TYPO3-Solr/ext-solr#2400]
**Describe the bug**
Not sure if it's rather a TYPO3 bug or on SOLR side, but when you disable `Use different write connection` in the solr tab the write configuration will still be written to the site configuration.

**To Reproduce**
1. Go to the site configuration
2. Enable `Use different write connection`
3. Save
4. Disable `Use different write connection`
5. Save again

**Expected behavior**
The write configuration should not be written to the site configuration yaml if *Use different write connection* is disabled.

**Screenshots**

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.9
 - Browser: Chrome
 - EXT:solr Version: master 4c6a8086
 - Used Apache Solr Version: 7.6.0
 - PHP Version: 7.2.21

**Comment by timohund** [comment]
@gionkoch Thanks for your feedback on the sitehandling. I think we need to have a deeper look on that and it should for sure work to disable it.

Without looking on the code by now i would think that this is somehow logical because custom settings need to be kept in the yaml file and not removed since they could also have been added manual. 

It think we should have a look on the core how cases like that are solved, by now i have two ideas in mind:

1. Bound the usage of the fallback to a flag and evaluate the write config only when the flag is true, so the settings are still present in the yaml but not evaluated.
2. Do some cleanup on save, when fallback is false (we need to check for hooks, for that)

**Comment by dkd-kaehm** [comment]
I'll propose to leave described behavior with `site/config.yaml` untouched. 
IMHO that is not a bug, but useful and nice feature. 
Biside of that, the same behaviour is on read_connection part.
See following states of `site/config.yaml` file(is like a patch file with + and -):

Enabling and configuring the read and write connections
```
rootPageId: 1
base: /
baseVariants: {  }
languages:
  -
    #...
    +solr_core_read: core_en
#...
+solr_enabled_read: true
+solr_scheme_read: http
+solr_host_read: solr
+solr_port_read: 8999
+solr_path_read: /solr/

+solr_use_write_connection: true
+solr_scheme_write: http
+solr_host_write: localhost
+solr_port_write: '8983'
+solr_path_write: /solr/
```

Disabling write and then read connection

```

-solr_enabled_read: true
+solr_enabled_read: false

-solr_use_write_connection: true
+solr_use_write_connection: false

```

---

Just imagine following situation:
* The switch "Use different write connection" manipulates the option `solr_use_write_connection: "SWITCH_STATE"` in sites config.yaml. So by disabling of write connection, the connection is not used. 
* The connection information, which stay after disabling is still useful for users and can be used later on by enabling the write connection. Also the connection infos can be prepared any time and user must just enable this connection if this feature is really needed.

---

## By analysing of that I thought on following missing things:

### 1. An switch for read and write connections on all Tools
  As an user I want to be able to switch between read and write connection, to see the contents of Index of desired connection.
### 1.2. Emptying index Buttons for read and write connections separately:
  As an user I want to empty the index for "read" or "write" or "both" connections to be sure, that my Index for read or write connection is clean from old things.

**Comment by timohund** [comment]
@dkd-kaehm i think we should evaluate  ```solr_use_write_connection``` when doing a fallback. Can you change that and add unit tests for all cases.
