### ISSUE TITLE
[TASK] Check skipped ConnectionManagerTest

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#2401]
**What should be done in the scope of this task?**

With the migration to the sitehandling in the functional tests (#2390) some tests have been skipped and subtasks have been created.

In the scope of this task we should check the following testcases in the ConnectionManger and either fix the bug or adapt the testcase:

* ApacheSolrForTypo3\Solr\Tests\Integration\ConnectionManagerTest::canFindSolrConnectionForMountedPageIfMountPointIsGiven
* ApacheSolrForTypo3\Solr\Tests\Integration\ConnectionManagerTest::exceptionIsThrownForUnAvailableSolrConnectionOnGetConfigurationByRootPageId

**Comment by dkd-kaehm** [comment]
Following Infos:
* ApacheSolrForTypo3\Solr\Tests\Integration\ConnectionManagerTest::canFindSolrConnectionForMountedPageIfMountPointIsGiven fails with: 
```
1) ApacheSolrForTypo3\Solr\Tests\Integration\ConnectionManagerTest::canFindSolrConnectionForMountedPageIfMountPointIsGiven
TYPO3\CMS\Core\Exception\SiteNotFoundException: No site found in root line of page 1

/var/www/html/packages/.Test-Build/public/typo3/sysext/core/Classes/Site/SiteFinder.php:132
/var/www/html/packages/ext-solr/Classes/Domain/Site/SiteRepository.php:437
/var/www/html/packages/ext-solr/Classes/Domain/Site/SiteRepository.php:271
/var/www/html/packages/ext-solr/Classes/Domain/Site/SiteRepository.php:125
/var/www/html/packages/ext-solr/Classes/Domain/Site/SiteRepository.php:107
/var/www/html/packages/ext-solr/Classes/ConnectionManager.php:158
/var/www/html/packages/ext-solr/Tests/Integration/ConnectionManagerTest.php:71
```
