### ISSUE TITLE
[BUG] No scheduler tasks can be created

### ISSUE THREAD

**Issue by kevinmeckl** [TYPO3-Solr/ext-solr#2414]
**Describe the bug**
No scheduler tasks can be created.

**Expected behavior**
Again, scheduler tasks can be created.

**Used versions:**
 - TYPO3 Version: 9.5.9
 - Browser: Chrome
 - EXT:solr Version: dev-master
 - Used Apache Solr Version: 7.6.0
 - PHP Version: 7.2.21
 - MySQL Version: 5.7.26

**Comment by achimfritz** [comment]
i think we should fix this, when fetching available sites, by keeping die rootPageId as array key (this will prevent also other site-effects, when fetching awailable Sites and rootPageId is expected as array key). (mix of legacyMode and Site-Based Configuration is no more supported)
s. https://github.com/TYPO3-Solr/ext-solr/pull/2424
