### ISSUE TITLE
[BUG] Pages secured with fe_group cant be indexed

### ISSUE THREAD

**Issue by Navi2016** [TYPO3-Solr/ext-solr#2417]
**Describe the bug**
When having protected pages in the backend, indexing works fine as long as the page itself isn't secured by a group.

Example:
- parent page 1 (has group id 400, extend to subpages enabled)
-- subpageA (no groups)
--- subSubPageA (no groups)

This works fine.

Now this example:
- parent page 1 (has group id 400, extend to subpages enabled)
-- subpageA (no groups)
--- subSubPageA (also has a group, id 500)

Now subSubPageA cant be indexed and will fail with a Failed to execute Page Indexer Request. See log for details.

**Possible solution**
It appears its going wrong in:
typo3conf/ext/solr/Classes/Access/Rootline.php:163

$currentPageRecord = $pageSelector->getPage($pageId);

the $currentPageRecord is empty because it's using a query with access fields like fe_group must be 0 etc.

Adjusted code to:

$currentPageRecord = $pageSelector->getPage($pageId, true);

and indexing seems to work for those pages as well.

Is this a bug and are there any downsides to this fix?
I hope this does not mess with showing pages unprotected in the search results, will check this of course.

**Used versions**
 - TYPO3 Version: 7.6.39
 - EXT:solr Version: 6.5.1
 - Used Apache Solr Version: 6.6.6
 - PHP Version: 7.2.22
 - MySQL Version: 5.5

**Additional context**
I know the used solr extension is older but its the last version to work with TYPO3 7.6 and the code seems unchanged in newer versions.

Might be related to:
https://github.com/TYPO3-Solr/ext-solr/issues/2341

**Comment by timohund** [comment]
Fixed with #2481
