### ISSUE TITLE
[BUG] Reset extendToSubPages & hidden together does not insert subpages in indexqueue 

### ISSUE THREAD

**Issue by christophlehmann** [TYPO3-Solr/ext-solr#2433]
**Describe the bug**

Edit page 
-> set hidden = 1, extendToSubpages = 1
-> save
-> page 1 + subpages are removed from indexqueue (okay)

Then edit page again
-> set hidden = 0, extendToSubpages = 0
-> save
-> page is added to indexqueue (okay) but not the subpages (Not okay)

**Expected behavior**
subpages should be added to indexqueue

**Used versions (please complete the following information):**
 - TYPO3 Version: 8.7
 - EXT:solr Version: 9.0.2

**Comment by dkd-kaehm** [comment]
Confirmed and must be fixed on following EXT:Solr versions:
* release-10.0.x 
* release-11.0.x
* master

**Comment by dkd-kaehm** [comment]
Confirmed and must be fixed on following EXT:Solr versions:
* release-10.0.x 
* release-11.0.x
* master
