### ISSUE TITLE
Javascript Files are not loaded anymore

### ISSUE THREAD

**Issue by tgriessbach** [TYPO3-Solr/ext-solr#244]
Prior to commit 67b051bd21b9d3f9b8b30f8167da0f995232ee21
the JS Files were loaded by 
`$this->configuration['javascriptFiles.'][$fileKey];`

The new Function getJavaScriptFileByFileKey() in \solr\Classes\System\Configuration\TypoScriptConfiguration.php
uses 
`$this->getValueByPathOrDefaultValue('plugin.tx_solr.javascriptFiles' . $fileKey, $defaultIfEmpty);`

A dot is missing between plugin.tx_solr.javascriptFiles and $fileKey.

**Comment by timoschmidt** [comment]
@tgriessbach Thx for reporting, i'll fix this

**Comment by timoschmidt** [comment]
@tgriessbach 

I fixed the issue and created a pull request. Would be nice, when you could review the fix. When you stumble upon other issues it would be nice when you could report them as well.

**Comment by tgriessbach** [comment]
looks good. Thanks for the quick fix!
