### ISSUE TITLE
[BUG] Indexing error when default language is disabled in Site config

### ISSUE THREAD

**Issue by NochEinKamel** [TYPO3-Solr/ext-solr#2451]
**Describe the bug**
If the Site language with language 0 is disabled (not "Visible in Frontend") in the Site configuration, page indexing fails with  the following error:
`1552491117: ApacheSolrForTypo3\Solr\NoSolrConnectionFoundException: Could not find a Solr connection for root page [1] and language [0].`

This is caused by the `Indexer` class always fetching the default connection with language id 0:
`$defaultConnection = $this->connectionManager->getConnectionByPageId($pageId, 0, $item->getMountPointIdentifier());`
The quick fix is put an empty try-catch around the line to catch the exception and ignore the defaultConnection (including the following if statement) – I've added this workaround to my local copy (see [Indexer-getSolrConnectionsByItem.txt](https://github.com/TYPO3-Solr/ext-solr/files/3689373/Indexer-getSolrConnectionsByItem.txt)) and couldn't find any issues derived from this.

Not sure how deep the real fix would have to go as there seem to be a lot of "if language == 0" statements and even getDefaultLanguageUid returns 0; in this setup there is not really a default language or "default connection".

Perhaps the issue can also be fixed in a different way; The ConnectionManager only uses enabled site languages which then throws an error if one requests a connection for a disabled language. Perhaps it would be more fitting to return connections for all languages in the ConnectionManager and let the indexers decide if they want to index the language, just like the PageIndexer ignores the default language if the checkbox "Hide default translation of page" is set.

**To Reproduce**
1. Create a TYPO3 site configuration with multiple languages
2. Disable "Visible in Frontend" for the default language
3. Trigger a page indexing

**Expected behavior**
Regardless of the state of the default language, the page should get indexed in all other languages which are enabled/"Visible in Frontend".

**Used versions:**
 - TYPO3 Version: 9.5.9
 - EXT:solr Version: dev-master

**Additional context**
I'm working on a project using several disabled languages (including the default language).

An example setup would be a Site config with languages:
[0] Base English (not enabled/Visible in Frontend) [default language]
[1] Base German (not enabled/Visible in Frontend)
[2] Germany - German (enabled; strict Fallback to Base German)
[3] Germany - English (enabled; strict Fallback to Base English)
[4] Switzerland - German (enabled; strict Fallback to Base German)
(and many more...)

For normal content pages only languages 0 and 1 are entered;
If there is a different content for the german page in Switzerland then the editors enter that content in language 4.
The frontend is only ever called in languages 2, 3 and 4 and typo3 automatically shows the entered content respecting the fallback even if the fallback language is disabled.

The main reason is that there are different products per country which are shown by plugins, but these different products shall also be marketed by editors. So they would have a marketing page for product X only in the language "Switzerland - German" as the product is only sold in CH.

**Comment by bibusdax** [comment]
Indexer.php Line 548 change 0 into $defaultLanguageUid:

        $defaultConnection = $this->connectionManager->getConnectionByPageId($pageId, 0, $item->getMountPointIdentifier());

this did the trick for me.

**Comment by bibusdax** [comment]
My fix did not work on sites which have default language disabled and only one alternative language enabled.
So I made a 2nd fix here:

Starting at line 612 of Indexer.php I adjusted the if conditions:

    private function getDefaultLanguageUid(Item $item, array $rootPage, array $siteLanguages)
    {
        $defaultLanguageUid = 0;
        if (($rootPage['l18n_cfg'] & 1) == 1 && count($siteLanguages) == 1 && $siteLanguages[min(array_keys($siteLanguages))] > 0) {
            $defaultLanguageUid = $siteLanguages[min(array_keys($siteLanguages))];
        } elseif (($rootPage['l18n_cfg'] & 1) == 1 && count($siteLanguages) > 1) {
            unset($siteLanguages[array_search('0', $siteLanguages)]);
            $defaultLanguageUid = $siteLanguages[min(array_keys($siteLanguages))];
        } elseif (($rootPage['l18n_cfg'] & 1) == 1 && count($siteLanguages) == 1) {
            $message = 'Root page ' . (int)$item->getRootPageUid() . ' is set to hide default translation, but no other language is configured!';
            throw new \RuntimeException($message);
        }

        return $defaultLanguageUid;
    }

Best regards,

Patrick Daxboeck

**Comment by SomeBdyElse** [comment]
I ran into the same issue but used a different fix to solve it:

```php
/**
 * Gets the Solr connections applicable for an item.
 *
 * The connections include the default connection and connections to be used
 * for translations of an item.
 *
 * @param Item $item An index queue item
 * @return array An array of ApacheSolrForTypo3\Solr\System\Solr\SolrConnection connections, the array's keys are the sys_language_uid of the language of the connection
 */
protected function getSolrConnectionsByItem(Item $item)
{
    $solrConnections = [];

    $pageId = $item->getRootPageUid();
    if ($item->getType() === 'pages') {
        $pageId = $item->getRecordUid();
    }

    // Solr configurations possible for this item
    $site = $item->getSite();
    $solrConfigurationsBySite = $site->getAllSolrConnectionConfigurations();
    $siteLanguages = [];
    foreach ($solrConfigurationsBySite as $solrConfiguration) {
        $siteLanguages[] = $solrConfiguration['language'];
    }

    $defaultLanguageUid = $this->getDefaultLanguageUid($item, $site->getRootPage(), $siteLanguages);
    if ($defaultLanguageUid == 0 && in_array(0, $siteLanguages)) {
        $defaultConnection = $this->connectionManager->getConnectionByPageId($pageId, 0, $item->getMountPointIdentifier());
        $solrConnections[0] = $defaultConnection;
    }

    $translationOverlays = $this->getTranslationOverlaysWithConfiguredSite((int)$pageId, $site, (array)$siteLanguages);
    $translationConnections = $this->getConnectionsForIndexableLanguages($translationOverlays);

    foreach ($translationConnections as $systemLanguageUid => $solrConnection) {
        $solrConnections[$systemLanguageUid] = $solrConnection;
    }
    return $solrConnections;
}
```

This `in_array` is the essence:
```
$defaultLanguageUid = $this->getDefaultLanguageUid($item, $site->getRootPage(), $siteLanguages);
    if ($defaultLanguageUid == 0 && in_array(0, $siteLanguages)) {
        $defaultConnection = $this->connectionManager->getConnectionByPageId($pageId, 0, $item->getMountPointIdentifier());
        $solrConnections[0] = $defaultConnection;
    }
```

**Comment by NochEinKamel** [comment]
sorry. miss-clicked :-(

Just wanted to add that it still doesn't work with master 99064679

**Comment by timohund** [comment]
@NochEinKamel i would prefer the solution provided by @bibusdax since this fixes the behaviour of the method "getDefaultLanguageUid". When 0 is not the default language this should not be returned. Are you able to test a pr with your use case if i provide it?

**Comment by timohund** [comment]
@NochEinKamel @SomeBdyElse are you able to check if #2596 is working with your usecases as well?

**Comment by NochEinKamel** [comment]
@timohund Sorry, I only managed to test it now.

The fix doesn't help for me as my default language still has the id 0 but is still disabled.

Perhaps there is a mixup between "language disabled in site config" and "hide default translation of page"?
I think @SomeBdyElse changes in getDefaultLanguageUid only address the second variant whereas my issue is with the first variant.

**Comment by ayacoo** [comment]
@Mabahe Thank you for the propasal. Can you perhaps post this as a PR? That was also the solution for our problem.

Context: We have a neutral source (0) with FE disabled and a standard language UID for the respective country.

**Comment by markusa86** [comment]
This error still occurs in version 12.0.5
