### ISSUE TITLE
[BUG] Language fallback/translationOverlay differs from TYPO3 page rendering

### ISSUE THREAD

**Issue by NochEinKamel** [TYPO3-Solr/ext-solr#2452]
**Describe the bug**

I'm working on a project using several disabled languages (including the default language).

An example setup would be a Site config with languages:
[0] Base English (not enabled/Visible in Frontend) [default language]
[1] Base German (not enabled/Visible in Frontend)
[2] Germany - German (enabled; strict Fallback to Base German)
[3] Germany - English (enabled; strict Fallback to Base English)
[4] Switzerland - German (enabled; strict Fallback to Base German)
(and many more...)

For normal content pages only languages 0 and 1 are entered;
If there is a different content for the german page in Switzerland then the editors enter that content in language 4.
The frontend is only ever called in languages 2, 3 and 4 and typo3 automatically shows the entered content respecting the fallback even if the fallback language is disabled.

The main reason is that there are different products per country which are shown by plugins, but these different products shall also be marketed by editors. So they would have a marketing page for product X only in the language "Switzerland - German" as the product is only sold in CH.

Ext-Solr only indexes languages which have a fallback language which is "Enabled in Frontend" or fall back to the default language (with id 0).

e.g. Base German has content but Germany German not, then neither are indexed.
But if Base English has content and Germany English does not; Germany English is indexed anyways.
TYPO3 however renders all languages in the frontend.

This is all down to the method `getTranslationOverlaysWithConfiguredSite` in the Indexer class.
The fallbacks only consider overlays which are enabled but should really consider all available overlays.
Possible solution: [Indexer-getTranslationOverlaysWithConfiguredSite.txt](https://github.com/TYPO3-Solr/ext-solr/files/3689472/Indexer-getTranslationOverlaysWithConfiguredSite.txt)
However this may not be correct for pages which additionally have "hide default translation" or "Hide page if no translation for current language exists" set.

**To Reproduce**
1. Create a TYPO3 site configuration with multiple languages
2. Disable "Visible in Frontend" for a language (Do not disable the default language)
3. Set another language to Fallback Mode strict and use the disabled language as fallback
4. Trigger a page index

**Expected behavior**
The PageIndexing should behave like the TYPO3 frontend – indexing the page in all languages which are not disabled themself and have content or a fallback regardless of the enable/disable state of said fallback.

**Used versions:**
 - TYPO3 Version: 9.5.9
 - EXT:solr Version: dev-master

**Comment by timohund** [comment]
@NochEinKamel Can you please re-check that with the current master (EXT:solr 11) and give feedback if your use case is working now?

**Comment by NochEinKamel** [comment]
I updated my local copy of the extension to master 99064679 but the issue still exists.

Only english variants are indexed as they use a fallback to language 0. Other languages with non 0 fallbacks are not indexed.


FYI: The workaround in my fork is in production since january and seems to work fine:
https://github.com/NochEinKamel/ext-solr/commit/202ff2b0b35e3f542d24da61f3a38867961a6e21?diff=split

**Comment by dkd-kaehm** [comment]
We can fix that issue on EXT:solr 11.5.x only, because of complexity and deep interlacement of TSFE usages and initialization in previous versions.

### Fixed in !!![TASK] Improve and Fix TSFE Initialization https://github.com/TYPO3-Solr/ext-solr/commit/a246cb8e34d80da6227445c0c800620f16264a00
