### ISSUE TITLE
[BUG] indexing failed using new site strategy

### ISSUE THREAD

**Issue by dev-rke** [TYPO3-Solr/ext-solr#2486]
**Describe the bug**
Exception is thrown when indexing with new site handling based indexing strategy.

**To Reproduce**
1. configure site, configure solr settings within site config
2. ensure to have no old solr config left and not using solr compatibility mode
3. try indexing
4. indexing fails

```
Argument 1 passed to TYPO3\CMS\Core\Site\SiteFinder::getSiteByPageId() must be 
of the type integer, string given, called in 
/var/www/typo3conf/ext/solr/Classes/Domain/Index/PageIndexer/Helper/UriBuilder/TYPO3SiteStrategy.php on line 73

in /var/www/typo3/sysext/core/Classes/Site/SiteFinder.php line 111
at TYPO3\CMS\Core\Site\SiteFinder->getSiteByPageId('4798')
```
(i was indexing page with uid 4798)

**Expected behavior**
Indexing should work. :-) 

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.9
 - Browser: latest stable Firefox
 - EXT:solr Version: 10.0
 - Used Apache Solr Version: 8.2
 - PHP Version: 7.2
 - MySQL Version: MariaDB 5.7 & Percona (5.6 compat)

**Comment by dev-rke** [comment]
Fixed via #2487

**Comment by dev-rke** [comment]
@timohund : Currently this prevents indexing, i use https://github.com/cweagans/composer-patches as workaround to use the patch. Maybe it might would be a good idea to provide a official bugfix release asap. :-)

**Comment by timohund** [comment]
@dev-rke yes, but we've tested that on multiple systems where this issue does not occur, so it seems to be somehow related to your system and not a general issue ;-). Nevertheless, we will ship that with 10.0.1

**Comment by timohund** [comment]
@dev-rke i would also assume that it is related to the database especially to the schema of ```tx_solr_indexqueue_item```. What is the output of ```show create table tx_solr_indexqueue_item;```? I think with your fix it will work in both environments nevertheless it would be interesting to figure out the reason.

**Comment by dev-rke** [comment]
Hi @timohund ,

sorry for my late reply, holidays first, work second. ;-)
The bugfix fixed the issue also in production, therefore i am happy now, thank you. :-)

Here some information of the database table:

```
mysql> DESCRIBE tx_solr_indexqueue_item;
+-------------------------+--------------+------+-----+---------+----------------+
| Field                   | Type         | Null | Key | Default | Extra          |
+-------------------------+--------------+------+-----+---------+----------------+
| uid                     | int(11)      | NO   | PRI | NULL    | auto_increment |
| root                    | int(11)      | NO   |     | 0       |                |
| item_type               | varchar(255) | NO   | MUL |         |                |
| item_uid                | int(11)      | NO   |     | 0       |                |
| indexing_configuration  | varchar(255) | NO   |     |         |                |
| has_indexing_properties | smallint(6)  | NO   |     | 0       |                |
| indexing_priority       | int(11)      | NO   | MUL | 0       |                |
| changed                 | int(11)      | NO   | MUL | 0       |                |
| indexed                 | int(11)      | NO   |     | 0       |                |
| errors                  | text         | NO   |     | NULL    |                |
| pages_mountidentifier   | varchar(255) | NO   |     |         |                |
+-------------------------+--------------+------+-----+---------+----------------+
11 rows in set (0.00 sec)
```


```
mysql> SHOW CREATE TABLE tx_solr_indexqueue_item;
CREATE TABLE `tx_solr_indexqueue_item` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `root` int(11) NOT NULL DEFAULT '0',
  `item_type` varchar(255) NOT NULL DEFAULT '',
  `item_uid` int(11) NOT NULL DEFAULT '0',
  `indexing_configuration` varchar(255) NOT NULL DEFAULT '',
  `has_indexing_properties` smallint(6) NOT NULL DEFAULT '0',
  `indexing_priority` int(11) NOT NULL DEFAULT '0',
  `changed` int(11) NOT NULL DEFAULT '0',
  `indexed` int(11) NOT NULL DEFAULT '0',
  `errors` text NOT NULL,
  `pages_mountidentifier` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`uid`),
  KEY `changed` (`changed`),
  KEY `item_id` (`item_type`,`item_uid`),
  KEY `pages_mountpoint` (`item_type`,`item_uid`,`has_indexing_properties`,`pages_mountidentifier`),
  KEY `indexing_priority_changed` (`indexing_priority`,`changed`)
) ENGINE=InnoDB AUTO_INCREMENT=497519 DEFAULT CHARSET=utf8
```

Seems to be properly configured, doesn't it?
