### ISSUE TITLE
[FEATURE] Own solr core configuration by application context / system

### ISSUE THREAD

**Issue by dkoether** [TYPO3-Solr/ext-solr#2488]
**Is your feature request related to a problem? Please describe.**
In almost all projects you have a development, one or more testing, a staging and one production system. In the newest version 10.0 you can configure which core should be used in the site configuration (which is cool!) but only one for all. If you use different naming of cores and different solr servers on each system this wont work.

**Describe the solution you'd like**
Add application context (TYPO3_CONTEXT) related solr configuration. Possibility to tell TYPO3 which core on which server should be used by the given application context "Development", "Testing" or "Production/XYZ".

e.g.

Development system:
en -> core_en on Solr server A with http on Port 8080
de -> core_de on Solr server A with http on Port 8080

Testing system:
en -> core_en_test on Solr server B with http on Port 8981
de -> core_de_test on Solr server B with http on Port 8981

...

Production system:
en -> core_en on Solr Server C with https on Port 8983
de -> core_de on Solr server E with https on Port 8983

**Target versions**
10.0 +

**If this can be achieved by customizing the yaml configuration please let me know**

Keep up the good work! Thanks in advance!

**Comment by timohund** [comment]
@dkoether i think you could define the core then in the yaml file by using an env variable

**Comment by dkoether** [comment]
Hello @timohund,
I'm totally fine if this option is not given in the UI of the site configuration and this will work for simple projects but we need a solution for this like baseVariants. I think setting env variables for each page is not a good way. It would be much better if you can define a condition in the yaml configuration.

**Comment by timohund** [comment]
> I think setting env variables for each page is not a good way. 

Why? I think this is the recommended way to store environment-specific configuration (https://12factor.net/de/config)
