### ISSUE TITLE
[BUG]  wrong solr core detection in EXT:solr 9.0.2

### ISSUE THREAD

**Issue by wolffc** [TYPO3-Solr/ext-solr#2499]
**Describe the bug**
if you configure two solr cores; the default core path is used for both languages

**To Reproduce**
1. create a rootpage, two languages, in our case de(id=0) and en(id=1)
2. use the following Typoscript:
```
plugin.tx_solr.solr {
    read {
        scheme = http
        host   = cockpit-aer-de.ddev.site
        port   = 8983
        path   = /solr/core_de/
    }
}
[globalVar = GP:L = 1]
    plugin.tx_solr.solr.read.path = /solr/core_en/
[end]
plugin.tx_solr.solr {
    write < .read
}
```
2. Click on "initalize solr connections..."
3. open the solr info module
4. see two connections:
```
http://cockpit-aer-de.ddev.site:8983/solr/core_de/
http://cockpit-aer-de.ddev.site:8983/solr/core_de/
```

**Expected behavior**

initalizie should detect: the correct cores per language:
```
http://cockpit-aer-de.ddev.site:8983/solr/core_de/
http://cockpit-aer-de.ddev.site:8983/solr/core_en/
```

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1393783/67862239-0d2ca400-fb22-11e9-8220-87241c0c0961.png)

![grafik](https://user-images.githubusercontent.com/1393783/67862272-1cabed00-fb22-11e9-8a74-e5d65114d707.png)

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.10
 - Browser: -- any
 - EXT:solr Version: 9.0.2
 - Used Apache Solr Version: --
 - PHP Version: 7.3.9
 - MySQL Version: Maria DB 10.2

**Additional context**

its not important in which way i initlazise the way using the cli command or the typo3 backend link

**Comment by dkd-kaehm** [comment]
Hello Christian,

is site handling activated on this site?
If so please use EXT:Solr v10.

**Comment by wolffc** [comment]
yes site handling is activated. so 9.0.x is incompatible with sitehandling?

**Comment by dkd-dobberkau** [comment]
Please read our Blogpost about the EXT:solr 9.x Release:
https://www.dkd.de/de/blog/latest-apache-solr-for-typo3-releases/

Additionally, check the Post about the EXT:solr 10.x Release:
https://www.dkd.de/de/blog/extsolr-10-and-addon-releases/

**Comment by wolffc** [comment]
Thanks for the Information. we simply missed that ext:solr 9.x is incompatible with site-handling.

**Comment by typoworx-de** [comment]
Had the same Problem on TYPO3 v9 and SOLR 9.x and did some X-Classing on ConnectionManager-Class to implement YAML Configuration for SOLR Connection. This solved the given issue and I was able to configure and get SOLR-Cores for multiple languages.

But still I have very strange Problems as in EN (secondary language in my Setup), there are only 11 Shortcut-Pages indexed instead of about 200 regular pages. Any idea on that?

**Comment by dkd-kaehm** [comment]
@typoworx-de 
Why not using EXT:Solr 10+ ?

**Comment by typoworx-de** [comment]
@dkd-kaehm just trying this. We have our own solr extension working on top of solr. So this might be a problem in short-term as we need to get this project done. But I'm actually looking if SOLR 10 may work without too much hazzle on that.

**Comment by typoworx-de** [comment]
@dkd-kaehm finally got it working by upgrading to most recent SOLR 11 Plugin (and more recent SOLR as well) and it wasn't that hard I expected to migrate.

**Comment by dkd-kaehm** [comment]
> @dkd-kaehm finally got it working by upgrading to most recent SOLR 11 Plugin (and more recent SOLR as well) and it wasn't that hard I expected to migrate.

that is fine, thanks for feedback

**Comment by typoworx-de** [comment]
@dkd-kaehm thanks for your quick response and helping :+1:
