### ISSUE TITLE
Autosuggest Problem on TYPO3 9.5.10 - "Required argument \"queryString\" is not set for"

### ISSUE THREAD

**Issue by andreaPress** [TYPO3-Solr/ext-solr#2506]
Hi,
thanks for the amazing works, I've installed the Solr Server in Plesk by using the offical Docker image and configured everything with the default cores.

I'm trying the autosuggest example, so in my template I've included just this element.

Unfortunately I'm getting this error:

`{"exception":"TYPO3\\CMS\\Extbase\\Mvc\\Controller\\Exception\\RequiredArgumentMissingException: Required argument \"queryString\" is not set for ApacheSolrForTypo3\\Solr\\Controller\\SuggestController->suggest.`

When I type something in the search box the requested url is this:
`https://dev2.comune.fano.pu.it/?type=7384&tx_solr[callback]=jQuery34108217373125945286_1574155542740&tx_solr%5BqueryString%5D=test&_=1574155542755`

I've tried to replace the %5B and %5D with real [] but nothing change.

Thank you very much for any suggestion.
Andrea

**Comment by dkd-kaehm** [comment]
No troubles on autosuggest on current master(upcoming 11) @ TYPO3 9.5.15.

**Comment by dkd-kaehm** [comment]
Please check the hint in #2706
The site config.yaml needs routing snippeds for all EX:Solr ajax requests.

Closing it to prevent duplicates. 
Please feel free to reopen if the topic of #2706 is wrong.

**Comment by schliesser** [comment]
_fyi_ This error also occurs when using the [PageTypeSuffix "ForceAppendingSlash"](https://stackoverflow.com/questions/53144596/how-can-i-add-a-trailing-slash-to-typo3-v9-urls)
