### ISSUE TITLE
[BUG] Documents associated to wrong language core

### ISSUE THREAD

**Issue by dkoether** [TYPO3-Solr/ext-solr#2508]
**Describe the bug**
In TYPO3 9 we use EXT:solr in version 9.0.2 and we define in Typoscript which solr core has to be used:

```
plugin.tx_solr {
    solr {
        scheme = http
        host = solrservice
        port = 8983
        path = /solr/core_en/    # default
    }
}
```

So basic, so far. We extend this default settings with conditions for application context and language:
```
# Language: GERMAN
# Development
[applicationContext == "Development"] && [globalVar = GP:L = 1]
    plugin.tx_solr {
        solr {
            path = /solr/core_de_development/
        }
    }
[end]

# Testing
[applicationContext == "Testing"] && [globalVar = GP:L = 1]
    plugin.tx_solr {
        solr {
            path = /solr/core_de_testing/
        }
    }
[end]

# Staging
[applicationContext == "Production/Staging"] && [globalVar = GP:L = 1]
    plugin.tx_solr {
        solr {
            path = /solr/core_de_staging/
        }
    }
[end]

# Production
[applicationContext == "Production"] && [globalVar = GP:L = 1]
    plugin.tx_solr {
        solr {
            path = /solr/core_de/
        }
    }
[end]

# -------------------
# Language: DUTCH
# Development
[applicationContext == "Development"] && [globalVar = GP:L = 2]
    plugin.tx_solr {
        solr {
            path = /solr/core_nl_development/
        }
    }
[end]

# Testing
[applicationContext == "Testing"] && [globalVar = GP:L = 2]
    plugin.tx_solr {
        solr {
            path = /solr/core_nl_testing/
        }
    }
[end]

# Staging
[applicationContext == "Production/Staging"] && [globalVar = GP:L = 2]
    plugin.tx_solr {
        solr {
            path = /solr/core_nl_staging/
        }
    }
[end]

# Production
[applicationContext == "Production"] && [globalVar = GP:L = 2]
    plugin.tx_solr {
        solr {
            path = /solr/core_nl/
        }
    }
[end]
```

We figured out that using only the new symfony expression language conditions with applicationContext and siteLanguage("id") lead to this misconfiguration of the solr cores:

![Bildschirmfoto 2019-11-20 um 11 36 59](https://user-images.githubusercontent.com/7765498/69231826-1d1c2e80-0b8a-11ea-8592-9efd117ec562.png)
Only with this mix of old and new typoscript configuration (see above) the cores are working:
![Bildschirmfoto 2019-11-15 um 15 54 02](https://user-images.githubusercontent.com/7765498/69225144-1ab3d780-0b7e-11ea-8fb7-b040c4cf68fa.png)

But we still face the problem that documents of the german language (pages, news etc.) are placed in the default core. We assume that this is a configuration problem. How do you handle this configuration in TYPO3 9 with EXT:solr 9.0.2? This worked in all projects with lower version before. 

**Expected behavior**
Each document should be associated by its language into the correct language specific core.

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.11
 - EXT:solr Version: 9.0.2
 - Used Apache Solr Version: 7.5
 - PHP Version: 7.2.24
 - MySQL Version: 5.7.0

**Comment by dkd-kaehm** [comment]
@dkoether 
Is site handling active on the site?
See #2499 and use EXT:solr 10+ for site handled sites.
