### ISSUE TITLE
[BUG] Cleancontent on index cause malformed utf8 string resulting in empty response

### ISSUE THREAD

**Issue by ruudsilvrants** [TYPO3-Solr/ext-solr#2513]
When the content contains the UTF8 nbsp character the clean content can cause this to an malformed UTF-8 string which leads to an false json_decode when parsing the page to index.

Steps to reproduce:
When the `$content` input for the function `public static function cleanContent($content)` 
 at file `Classes/HtmlContentExtractor.php`contains a UTF-8 string with the UTF-8 nbsp character and appended by a`<`or `>` tag .

In the cleanContent method an additional space is added between the opening and close tag
```
        $content = str_replace(['<', '>'], [' <', '> '], $content);
```

Afterwards the following preg_replace causes then a malformed character (question mark character) in the string.

```
$content = preg_replace('/\s{2,}/', ' ', $content);
```

Solution to this is to adjust the second preg_replace with the extra param `u` to the preg_replace.
For information of the `u` see PCRE_UTF8 at (https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php).

The solution preg_replace for this is:
```
$content = preg_replace('/\s{2,}/u', ' ', $content);
```

**Comment by lgescobar** [comment]
I experienced the same exact problem and I was flipping out until I made a string comparison by using a hexdump tool.
