### ISSUE TITLE
[BUG] TypeError  Return value of ApacheSolrForTypo3\Solr\System\Url\UrlHelper::getScheme() must be of the type string, null returned

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Solr/ext-solr#2518]
**Describe the bug**
Triggering "Index now" in "Index Queue" module can trigger:
```
TypeError

Return value of ApacheSolrForTypo3\Solr\System\Url\UrlHelper::getScheme() must be of the type string, null returned
```

**To Reproduce**
1. Use new Site Module for configuration
2. Use a `/` as `base`
3. Trigger indexing for pages

**Expected behavior**
Proper indexing of pages.

I guess the reason is that no absolute URL is built, therefore TYPO3 returns a relative url without scheme. This possibility is not handled by the code, so null is returned instead of a string. Providing schema with domain ans `/` will fix this. But there are cases when this is unhandy, e.g. if only a single website is served by the installation, and developers use different base urls.
The current situation enforces all possible setups to be configured.

**Screenshots**

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.11
 - Browser: Firefox
 - EXT:solr Version: 10.0.1
 - Used Apache Solr Version: 8.2.0
 - PHP Version: 7.2.25
 - MySQL Version: [e.g. 5.6.0]

**Additional context**

**Comment by dkd-kaehm** [comment]
The domain name is required for page indexing and must be defined.
Please see in reports module. 

There are multiple possibilities to set the base. I like the environment variables approach.
See: https://github.com/TYPO3-Solr/ext-solr/pull/2509/files

---

If you heve some idea for solving that, please comment this issue. We'll discuss about that.

**Comment by DanielSiepmann** [comment]
At least a note at https://docs.typo3.org/p/apache-solr-for-typo3/solr/10.0/en-us/GettingStarted/ConfigureExtension.html#site-handling-recommended would be helpful. Right now one follows the documentation and expects everything to work.

I would not expect an exception down in the process when following the documentation.

Together with that change, a hint regarding basic auth via site configuration would also be welcome.

I would need to have a deeper look regarding a workaround / fix. Maybe an absolute url can be generated through TYPO3 API.

**Comment by Figilano** [comment]
I agree with Daniel, a note in the docs would be useful. I, too, did everything "by the book" and only noticed this error due to sheer coincidence a day later. :-P

**Comment by dkd-kaehm** [comment]
A Pull Request is welcome.

**Comment by Figilano** [comment]
...there you go ;-)

**Comment by dkd-kaehm** [comment]
@Figilano Thanks.
