### ISSUE TITLE
Record indexing fails in solr 10.x

### ISSUE THREAD

**Issue by dmitryd** [TYPO3-Solr/ext-solr#2520]
**Describe the bug**

Indexing records fails in solr 10.x with the following stack trace:

```
1455530112: RuntimeException: The item indexing configuration "news" on root page uid 3 could not be found! in /var/www/html/html/typo3conf/ext/solr/Classes/IndexQueue/Indexer.php:295
Stack trace:
#0 /var/www/html/html/typo3conf/ext/solr/Classes/IndexQueue/Indexer.php(375): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->getItemTypeConfiguration(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), 0)
#1 /var/www/html/html/typo3conf/ext/solr/Classes/IndexQueue/Indexer.php(162): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->itemToDocument(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), 0)
#2 /var/www/html/html/typo3conf/ext/solr/Classes/IndexQueue/Indexer.php(134): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->indexItem(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), 0)
#3 /var/www/html/html/typo3conf/ext/solr/Classes/Domain/Index/IndexService.php(206): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->index(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item))
#4 /var/www/html/html/typo3conf/ext/solr/Classes/Domain/Index/IndexService.php(132): ApacheSolrForTypo3\Solr\Domain\Index\IndexService->indexItem(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), Object(ApacheSolrForTypo3\Solr\System\Configuration\TypoScriptConfiguration))
#5 /var/www/html/html/typo3conf/ext/solr/Classes/Task/IndexQueueWorkerTask.php(72): ApacheSolrForTypo3\Solr\Domain\Index\IndexService->indexItems(1000)
#6 /var/www/html/html/typo3/sysext/scheduler/Classes/Scheduler.php(179): ApacheSolrForTypo3\Solr\Task\IndexQueueWorkerTask->execute()
```

**To Reproduce**
Add news indexing configuration. Do **not** specify `additionalPageIds` there. Try to index.

Indexing config:
```
plugin.tx_solr.index.queue {
    news = 1
    news {
        table = tx_news_domain_model_news
        fields {
            title = title

            content = SOLR_CONTENT
            content {
                field = bodytext
            }
       }
    }
}
```

**Expected behavior**
Obvious...

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.13
 - Browser: Safari
 - EXT:solr Version: 10.0.1
 - Used Apache Solr Version: 8.2.0
 - PHP Version: 7.3.0

**Additional context**

I believe the problem is in [this commit](https://github.com/TYPO3-Solr/ext-solr/commit/c777f76dc6622f9eb16aa330124a3d0ebc927784#diff-c266740d2317aaf348833b4462fa6fbbR317), the code is:

```php
    protected function getFieldConfigurationFromItemRootPage(Item $item, $language, $indexConfigurationName)
    {
        $solrConfiguration = Util::getSolrConfigurationFromPageId($item->getRootPageUid(), true, $language);
        if (empty($solrConfiguration->getIndexQueueAdditionalPageIdsByConfigurationName($indexConfigurationName))) {
            return [];
        }

        return $solrConfiguration->getIndexQueueFieldsConfigurationByConfigurationName($indexConfigurationName, []);
    }
```
So if there is no `additionalPageIds`, there will be no fields to index in this configuration. So indexing will fail with this exception.

**Related issues**

#2493

**Comment by dmitryd** [comment]
Another strange piece of code that I found in `Indexer.php`:

```php
    protected function getItemTypeConfiguration(Item $item, $language = 0)
    {
        $indexConfigurationName = $item->getIndexingConfigurationName();
        $fields = $this->getFieldConfigurationFromItemRecordPage($item, $language, $indexConfigurationName);
        if (!$this->isRootPageIdPartOfRootLine($item) || count($fields) === 0) {
            $fields = $this->getFieldConfigurationFromItemRootPage($item, $language, $indexConfigurationName);
            if (count($fields) === 0) {
                throw new \RuntimeException('The item indexing configuration "' . $item->getIndexingConfigurationName() .
                    '" on root page uid ' . $item->getRootPageUid() . ' could not be found!', 1455530112);
            }
        }

        return $fields;
    }
```

Why would somebody call `$fields = $this->getFieldConfigurationFromItemRecordPage($item, $language, $indexConfigurationName);` twice with exactly same parameters outside of `if` and inside?

**Comment by dkd-kaehm** [comment]
> Another strange piece of code that I found in `Indexer.php`:
> 
> ```
>     protected function getItemTypeConfiguration(Item $item, $language = 0)
>     {
>         $indexConfigurationName = $item->getIndexingConfigurationName();
>         $fields = $this->getFieldConfigurationFromItemRecordPage($item, $language, $indexConfigurationName);
>         if (!$this->isRootPageIdPartOfRootLine($item) || count($fields) === 0) {
>             $fields = $this->getFieldConfigurationFromItemRootPage($item, $language, $indexConfigurationName);
>             if (count($fields) === 0) {
>                 throw new \RuntimeException('The item indexing configuration "' . $item->getIndexingConfigurationName() .
>                     '" on root page uid ' . $item->getRootPageUid() . ' could not be found!', 1455530112);
>             }
>         }
> 
>         return $fields;
>     }
> ```
> 
> Why `$fields = $this->getFieldConfigurationFromItemRecordPage($item, $language, $indexConfigurationName);` is called with exactly same parameters outside of `if` and inside? It changes nothing. The second call is useless.

---

Inside of `if` is 
`getFieldConfigurationFromItemRootPage()` and not 
`getFieldConfigurationFromItemRecordPage()`

**Comment by dkd-kaehm** [comment]
I have currently the same trouble on TYPO3 8.7 and EXT:solr 9.0.2, thought this was the Instance trouble...

**Comment by dmitryd** [comment]
@dkd-kaehm 

> Inside of if is getFieldConfigurationFromItemRootPage() and not getFieldConfigurationFromItemRecordPage()

Ah, I see. Probably was too tired yesterday to notice the difference.

**Comment by dmitryd** [comment]
More findings.

```php
    protected function getItemTypeConfiguration(Item $item, $language = 0)
    {
        $indexConfigurationName = $item->getIndexingConfigurationName();
        $fields = $this->getFieldConfigurationFromItemRecordPage($item, $language, $indexConfigurationName);
        if (!$this->isRootPageIdPartOfRootLine($item) || count($fields) === 0) {
            $fields = $this->getFieldConfigurationFromItemRootPage($item, $language, $indexConfigurationName);
            if (count($fields) === 0) {
                throw new \RuntimeException('The item indexing configuration "' . $item->getIndexingConfigurationName() .
                    '" on root page uid ' . $item->getRootPageUid() . ' could not be found!', 1455530112);
            }
        }

        return $fields;
    }
```
So `getItemTypeConfiguration` calls `getFieldConfigurationFromItemRecordPage`, which returns all proper fields in my case. But then there is a call to `$this->isRootPageIdPartOfRootLine($item)`, which suddenly returns `false`. Why? Because of a bad comparision:

![int-rootpageid](https://user-images.githubusercontent.com/306133/71248533-1cfb8400-232c-11ea-9731-c4cc2b2b0b13.png)

`$rootPageId` is a string and it is compared using `===` with `(int)`, which will always be false (type-strict comparison). So I "fall" inside `if` where the bug with `additionalPageIds` happen.

So this wrong comparison caused me to find a bug with `additionalPageIds` :)

**Comment by nimayneb** [comment]
We have the same problem and fix it with the patch from @dmitryd.

In our configuration we try to index "sys_file_metadata". There are no "additionalPageIds" for this records, of course.

**Comment by nimayneb** [comment]
We have the same problem.

In our configuration we try to index "sys_file_metadata". There are no "additionalPageIds" for this records, but the table have the field "pid"... so why?

It would be nice if the "additionalPageIds" option were not a mandatory setting now. If we set this option to somewhat, then it will be fixed.

```
plugin.tx_solr.index.queue.sys_file_metadata = 1
    sys_file_metadata {
        additionalPageIds = 0
    }
}
```

**Comment by jackd248** [comment]
Any updates on this so far?

**Comment by dmitryd** [comment]
Well, PR is open for half a year now and it fixes the problem.
