### ISSUE TITLE
Solr can't save site info in sys_registry

### ISSUE THREAD

**Issue by kartolo** [TYPO3-Solr/ext-solr#253]
Solr saves the sites information in sys_registry. Problem is that the field entry_value as BLOB defined. BLOB can only save 65536 character. If several sites (with multiple language) exist, the BLOB is not enough.

My workaround is, to set enty_value in sys_registry to LONGBLOB :)

should this be fixed in core or Solr redefines the sys_registry table?

**Comment by dkd-dobberkau** [comment]
i remember that we modified this in a clients project. lets look at this together if this would make sense to hook & add-on this behaviour.

**Comment by timoschmidt** [comment]
I'll check this and it think setting the datatype to longblob could be a quick fix, but normally a blob should be enough. I think we should check how the Site entries get serialized.

**Comment by kartolo** [comment]
@timoschmidt: but if I have 12+ sites with 12+ languages configured in TYPO3 and a really long solr path (e.g: /production/project-www.domain.tld-language), 65k characters is not enough :) 

currently following infos are serialized:
* connectionKey
* rootPageTitle
* rootPageUid
* solrScheme
* solrHost
* solrPort
* solrPath
* language
* label => this can be spared?

**Comment by timoschmidt** [comment]
Sounds reasonable, then id would be better to change the size in the solr extesion and address this as a core issue as well.

**Comment by irnnr** [comment]
alternatively evaluate storing only one site per record

**Comment by dkd-dobberkau** [comment]
+1 for @irnnr idea

**Comment by geraldaistleitner** [comment]
+1 for @irnnr idea

**Comment by timoschmidt** [comment]
I'll update the type to longblob for 4.0.0 and create a new task to split the sites in the registry to one entry for each site in the EXT:solr 5.0 release
