### ISSUE TITLE
[BUG] Deprecation notices in EXT:solr v9.0.2

### ISSUE THREAD

**Issue by davidlemaitre** [TYPO3-Solr/ext-solr#2539]
Deprecation notices after reloading configuration and clearing indexes.

Steps to reproduce the behavior :
1. Go to Index Administration module
2. Click on 'Clear Index' button or 'Reload configuration' button
3. This error occurs : An error occurred while trying to delete documents from the index: TYPO3\CMS\Core\Error\Exception: TYPO3 Deprecation Notice: AbstractSolrService::getCoreName is deprecated please use getCorePath() now. Will be dropped with EXT:solr 10 in /var/www/html/public/typo3conf/ext/solr/Classes/System/Solr/Service/AbstractSolrService.php line 150 

**Used versions :**
 - TYPO3 Version: 8.7.31
 - EXT:solr Version: 9.0.2
 - Used Apache Solr Version: 7.6.0

**Comment by seirerman** [comment]
Same here.

Using the scheduler task to clear the index works in the meantime, as does the button in the top bar to initialize the solr connection (Is that the same functionality?).

**Comment by dkd-kaehm** [comment]
That isn't a bug. 
Please configure exceptional errors in TYPO3 properly.

See: https://github.com/TYPO3-Solr/ext-solr/issues/2344#issuecomment-523327864

**Comment by davidlemaitre** [comment]
thanks @dkd-kaehm, $GLOBALS['TYPO3_CONF_VARS'][SYS][exceptionalErrors] was configured with 20480 value (is the default value according the help message in the Install Tool, but the TYPO3 Core AP doc, the default is 4341), I set it to 4341 and the error message has disappeared !

**Comment by seirerman** [comment]
Can confirm, 4341 works for me.

Thanks for the hint, @dkd-kaehm!
