### ISSUE TITLE
config.absRefPrefix = / causes file reference links to break

### ISSUE THREAD

**Issue by seirerman** [TYPO3-Solr/ext-solr#254]
When I use absRefPrefix = / instead of baseURL the file_referenced-links (the ones which say "file is linked on page XY, or something) start with // instead of /, making the browser mistake it for the protocol ("protocol relative URLs") and resulting in a 404 error.

In the solr index, the fields filePublicUrl and url start with "fileadmin/..." while fileReferenceUrl starts with "/pagetitle/...

I tried prepending ###RESULT_DOCUMENT.fileReferenceUrl### with ###RESULT_DOCUMENT.site###, but then again https wasn't recognized. It works, but this additional redirect isn't a clean workaround.

Any idea how to fix this properly?

**Comment by jloderhose** [comment]
Hi,

are you using ext realURL?
If so, disable *config.prefixLocalAnchors* in TypoScript setup and set *reapplyAbsRefPrefix* to 'true' in realurl_conf.php (or whatever file name it is on your system).

Hope this helps!

**Comment by seirerman** [comment]
No, reapplyAbsRefPrefix didn't help.
It's supposed to go in the init section, isn't it?

And to clarify:
* pages records start with / in the index, links work on solr webpage
* tt_news records start with / in the index, links work on solr webpage
* file URLs start with fileadmin/ in the index, links work on solr webpage
* file reference URLs  start with / in the index, links DO NOT work on solr webpage (only with ###RESULT_DOCUMENT.site######RESULT_DOCUMENT.fileReferenceUrl### in the results template as a workaround, without correct protocol)

**Comment by seirerman** [comment]
I could solve it by using type conditions in the template and add "/" if necessary.
No need to patch the solr extension.

**Comment by seirerman** [comment]
Another issue came up while using absRefPrefix = /.

Solr can index the URL of tt_news records correctly when the indexer runs for the first time. This means no / at the beginning of the URL.

But if I change a tt_news record, solr indexes it and puts a slash at the beginning of the URL. This breaks the URL in the search results.
A complete redindex solves the problem, but only temporarily.

**Comment by timohund** [comment]
I think this is fixed with #936 if not please reopen or open a new issue.
