### ISSUE TITLE
[BUG] query.sortBy not working

### ISSUE THREAD

**Issue by rintisch** [TYPO3-Solr/ext-solr#2541]
**Describe the bug**
If `plugin.tx_solr.search.query.sortBy = title asc` is set it's not taken into account when searching. It's always sorted by `relevance`.
(Indexer contains the field `title` and it's also given as sorting field.)

**Expected behavior**
If this parameter is set the result shall be sorted as written in the statement above.

**Used versions (please complete the following information):**
 - TYPO3 Version: 8.7.30
 - Browser: *
 - EXT:solr Version: 8.1.2
 - Used Apache Solr Version: [e.g. 6.6.0]
 - PHP Version: 7.0.33
 - MySQL Version: 5.6.0

**Additional context**
Just a short hint: `Classes > Search > SortingComponents.php > initializeSearchComponent()` -> `sortBy` is taken into account but in same function `setSorting` is used once more. Afterwards it's sorted by `relevance`

**Comment by 3l73** [comment]
Hi @rintisch 

this issue seems to be fixed with EXT:solr version 9. 
Version 9 introduce a advanced check on the sorting argument. This version is compatible with TYPO3 8.7.

Could you test if the upgrade to EXT:solr version 9 solve your problem?

Regards,

Lars

**Comment by rintisch** [comment]
Hi @3l73, hi @dkd-kaehm 

I am using EXT:solr **version 10.0.2** now. 

Unfortunately it's still not working as expected.

The option itself works. But the user cannot sort the results by relevance, it uses always the option which is set in TypoScript in this case because relevance does not add itself to the query and as result https://github.com/TYPO3-Solr/ext-solr/blob/54c25599a8cd1190e5513f9eca6b0acf830c024c/Classes/Search/SortingComponent.php#L83 is used...

**Comment by rintisch** [comment]
Hi @3l73 and @dkd-kaehm,

now am I using v. 11.0.3

The flag sortBy is working here. But unfortunately it's not possible to sort the events by date. 

I'm not that deep in the code to really understand how it works. But I guess the problem is, that sorting by relevance does not add a parameter to the url. So solr seems to believe: "No sorting is given? So I take the default sorting which is set with `query.sortBy`.

I works if I add `&tx_solr[sort]=relevance+asc` to the URL .

Is that the problem?

**Comment by rintisch** [comment]
One more finding:
Only when I add `&tx_solr[sort]=relevance+asc` to the url is the sorting label for relevance colored
![grafik](https://user-images.githubusercontent.com/44193208/106851741-18706700-66b7-11eb-91ae-955b4fad079f.png)

It's the somehow similar on [extensions.typo3.org](extensions.typo3.org) → the relevance button is never colored although that is the default value. But here it does not become active even with adding the query parameter

**Comment by dkd-kaehm** [comment]
> One more finding:
> Only when I add `&tx_solr[sort]=relevance+asc` to the url the sorting label for relevance is colored
> ![grafik](https://user-images.githubusercontent.com/44193208/106851741-18706700-66b7-11eb-91ae-955b4fad079f.png)
> 
> It's the somehow similar on [extensions.typo3.org](extensions.typo3.org) → the relevance button is never colored although that is the default value.
> (But here it does not become active even with adding the query parameter)

Hello @rintisch 
The link "extensions.typo3.org" is broken, which issue number is it? Just prepend the number with hash/number sign `#`.

**Comment by rintisch** [comment]
Hello @dkd-kaehm,
the linked referred to the TER in general. I just wanted to show that in the "Sort by" field the "relevance" is never active (only when you hover it) whereas the other options are in an active state if they are active.
![grafik](https://user-images.githubusercontent.com/44193208/107010722-0108ab00-6797-11eb-873f-2879c1d94088.png)

The screenshot from above was from a customer project where I have the problem of this issue.

I hope I have now been able to make it more understandable?

**Comment by dkd-kaehm** [comment]
Yes, now I understanding.

There is in EXT:Solrs sorting domain the trick with relevance, the catchword for this state is "isResetOption". 
The sorting by relevance is currently hardcoded default sorting, so if no sorting option is is set by URL, the relevance sorting will kick in.

So please see the Sorting partial part for `<f:if condition="{sorting.isResetOption}">`

https://github.com/TYPO3-Solr/ext-solr/blob/master/Resources/Private/Partials/Result/Sorting.html#L15-L20

And make something like this:

```
<f:if condition="{sorting.isResetOption}">
	<f:then>
		<li class="active"> <!-- class="active" does the trick on this place to mark "relevance" sorting option as active. -->
			<a href="{s:uri.sorting.removeSorting()}" class="solr-ajaxified">{sorting.label}</a>
		</li>
	</f:then>
...
```

Please close this issue, if the suggestion fixes youer needs.

**Comment by dkd-kaehm** [comment]
@rintisch 
Please checkout the PR #2852 and use the added snipped from Sorting partial.

**Comment by rintisch** [comment]
@dkd-kaehm thank you for the feedback. I had this snipped in the partial already. 

But it does not solve the problem which I have (which is not the initial problem of this issue). I will try to list all steps and the problem which results from it:
### In advance:
* Nearly everything works as expected when not making the following setup with `sortBy`
* The only issue is the fact that the relevance is not marked as `active` although it is active (that what your PR from above would solve)

### My setup
* `plugin.tx_solr.search.query.sortBy = startdate_dateS asc` where `startdate_dateS` is the start date of events 
(I know it makes not really sense, I tried to convince the customer...)

### The test
* Searching e.g. for `test` 
* the URL on the page with the search is something like `myurl.com/page-sluge?L=0&id=1&tx_solr[q]=test`

### Test results 
I made those tests without adding your additional lines in `ResultSetReconstitutionProcessor.php`.
* The search results are sorted by the start date as expected (so the initial issue of this ticket is solved) 
* Nothing is selected as active in the sorting field (neither `relevance` nor `startDate`)
* It is not possible to sort by `relevance` (the URL does not change when clicking this sorting)
* It is possible to sort by `startDate` (the URl changes, `&tx_solr[sort]=startdate+asc` (or `... desc`) is added. The sorting will be active in this case.

### My insights
* With the snippet for the `ResultSetReconstitutionProcessor.php` from your PR from above ...
    * the `relevance` is marked as active although it's not active!
    * it's still not possible to sort by `relevance`
    * it's possible to sort by `startDate`

I removed your additional lines from `ResultSetReconstitutionProcessor.php` and also removed `$isResetOption = $field === 'relevance';`
* the initial sorting is  `startDate` as expected
* now it is possible to sort by `relevance` (because the URL gets `&tx_solr[sort]=relevance+asc` attached
* The `relevance` is not a `resetOption` any longer so it gets an arrow when sorting with it

Maybe that helps?

**Comment by dkd-kaehm** [comment]
@rintisch 
As I can see you want to be able to set the default sorting option?

**Comment by rintisch** [comment]
@dkd-kaehm Yes, that's the goal. This is in general possible with `sortBy` but as I tried to explain: The end user cannot sort by relevance if `sortBy` is set in TypoScript to a field different than `relevance`.

**Comment by dkd-kaehm** [comment]
OK, 
I have a old issue #2184
We should refactor the sorting domain and switch the resolving of used sorting option from TYPO3 URL to Apache Solr used query. But this can't be a part of 11.0.x, but only of next major EXT:Solr v. 11.1.0, because the changes are to big.
Feel free to make a PR for #2184 against master branch.

For your current intention, please use and adapt following snipped:

```
<?php
declare(strict_types=1);

namespace ....Solr\Domain\Search\ResultSet\Sorting;

use ApacheSolrForTypo3\Solr\Domain\Search\Query\Query;
use ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\SearchResultSet;
use ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\SearchResultSetProcessor;
use ApacheSolrForTypo3\Solr\Query\Modifier\Modifier;
use TYPO3\CMS\Core\SingletonInterface;

/**
 * Sorting default option chooser makes it possible to define one of configured sorting options as default option.
 *
 * Requires declaration of "beforeSearch" Hook in ext_localconf.php
 * // Enable configuration for default sorting option.
 * $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['beforeSearch'][DefaultOptionChooser::class] = DefaultOptionChooser::class;
 *
 * Can be used in TypoScript:
 *
 * plugin.tx_solr.search.sorting.default {
 *   sortingName = someOfDeclaredSortingOptions
 *   sortingDirection = desc
 * }
 *
 * Processing sequence:
 * 1 'beforeSearch' -> DefaultOptionChooser::process() -> initializeDefaultSortingConfigurations()
 * 2 'modifySearchQuery' -> DefaultOptionChooser::modifyQuery()
 * 3 'afterSearch' -> DefaultOptionChooser::process() -> useDefaultSortingOptionInSortingComponent()
 *
 */
class DefaultOptionChooser implements Modifier, SearchResultSetProcessor, SingletonInterface
{

    /**
     * TypoScript Path used for this feature
     */
    const TS_CONTEXT_PATH = 'plugin.tx_solr.search.sorting';

    /**
     * @var SearchResultSet
     */
    protected $resultSet;

    /**
     * @var string
     */
    protected $defaultSortingOptionName;

    /**
     * @var string
     */
    protected $defaultSortingDirection;

    /**
     * @var string
     */
    protected $defaultSortingField;

    /**
     * @var Query
     */
    protected $query;

    /**
     * The implementation can be used to influence a SearchResultSet that is
     * created and processed in the SearchResultSetService.
     *
     * @param SearchResultSet $resultSet
     * @return mixed
     */
    public function process(SearchResultSet $resultSet)
    {
        if (!$resultSet->getHasSearched()) {
            $this->resultSet = $resultSet;
            $this->initializeDefaultSortingConfigurations();
        }

        if ($resultSet->getHasSearched()) {
            $this->useDefaultSortingOptionInSortingComponent();
        }
        return $resultSet;
    }

    /**
     * Initializes default sorting configuration values before searching.
     *
     * Fallback to sorting direction from sorting option.
     * Those are required for "modifySearchQuery"-Hook and then for "afterSearch"-Hook.
     */
    protected function initializeDefaultSortingConfigurations()
    {
        $this->defaultSortingOptionName = $this->getConfiguration()->getValueByPathOrDefaultValue(self::TS_CONTEXT_PATH . '.default.sortingName', null);
        if ($this->defaultSortingOptionName === null) {
            return;
        }
        $sortingExists = $this->getConfiguration()->getValueByPathOrDefaultValue(self::TS_CONTEXT_PATH . '.options.' . $this->defaultSortingOptionName . '.', false);
        if ($sortingExists === false) {
            throw new \InvalidArgumentException('No sorting configuration found for option name "' . $this->defaultSortingOptionName . '", which was used in plugin.tx_solr.search.sorting.default.sortingName TypoScript setting.', 1556577249);
        }

        $sortingDirectionBySortingOption = $this->getConfiguration()->getSearchSortingDefaultOrderBySortOptionName($this->defaultSortingOptionName);
        $this->defaultSortingField = $this->getConfiguration()->getValueByPathOrDefaultValue(self::TS_CONTEXT_PATH . '.options.' . $this->defaultSortingOptionName . '.field', null);
        if ($this->defaultSortingField === null) {
            return;
        }
        $this->defaultSortingDirection = $this->getConfiguration()->getValueByPathOrDefaultValue(self::TS_CONTEXT_PATH . '.default.sortingDirection', $sortingDirectionBySortingOption);

        $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['modifySearchQuery'][self::class] = self::class;
        $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['afterSearch'][self::class] = self::class;
    }

    /**
     * Modifies the given query and returns the modified query as result
     *
     * @param Query $query The query to modify
     * @return Query The modified query
     */
    public function modifyQuery(Query $query)
    {
        $this->query = $query;
        if ($this->resultSet->getUsedSearchRequest()->getHasSorting()) {
            return $query;
        }
        $this->query->setSorting($this->defaultSortingField . ' ' . $this->defaultSortingDirection);

        return $query;
    }

    /**
     * Modifies the state of sorting component in GUI.
     */
    protected function useDefaultSortingOptionInSortingComponent() {
        $sortings = $this->resultSet->getSortings();
        /* @var \ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\Sorting\Sorting $sorting */

        foreach ($sortings as $sorting) {
            $protectedSortingPropertySetter = \Closure::bind(function($prop, $value){$this->$prop = $value;}, $sorting, $sorting);

            if ($sorting->getName() === $this->defaultSortingOptionName) {
                $protectedSortingPropertySetter('isResetOption', true);
                if (!$this->resultSet->getUsedSearchRequest()->getHasSorting()) {
                    $protectedSortingPropertySetter('selected', true);
                    $protectedSortingsPropertySetter = \Closure::bind(function($prop, $value){$this->$prop = $value;}, $sortings, $sortings);
                    $protectedSortingsPropertySetter('selected', $sorting);
                }
            } else {
                $protectedSortingPropertySetter('isResetOption', false);
                if (!$this->resultSet->getUsedSearchRequest()->getHasSorting()) {
                    $protectedSortingPropertySetter('selected', false);
                }
            }
        }
    }

    /**
     * Returns Typoscript Configuration Object
     *
     * @return \ApacheSolrForTypo3\Solr\System\Configuration\TypoScriptConfiguration
     */
    protected function getConfiguration()
    {
        return $this->resultSet->getUsedSearchRequest()->getContextTypoScriptConfiguration();
    }
}
```

**Comment by rintisch** [comment]
@dkd-kaehm 
I say your Bugfix but it does not solve everything. My biggest problem is not what I [wrote above](https://github.com/TYPO3-Solr/ext-solr/issues/2541#issuecomment-775724802):

> 
> ...
> 
> ### My setup
> 
>     * `plugin.tx_solr.search.query.sortBy = startdate_dateS asc` where `startdate_dateS` is the start date of events
>       (I know it makes not really sense, I tried to convince the customer...)
> 
> ...
> 
> ### Test results
> 
> ...
> 
>     * It is not possible to sort by `relevance` (the URL does not change when clicking this sorting).
> 

So in short: 
If I set `plugin.tx_solr.search.query.sortBy` to something different than `relevance` it is **not possible any longer to sort by `relevance`**.

**Comment by rintisch** [comment]
@dkd-kaehm Thanks for your feedback. 
As you are not satified with my PR I will not transfer it. I will have a look [at your Proposal](https://github.com/dkd-kaehm/ext-solr/pull/2#issuecomment-845420377)  to use the `DefaultOptionChooser`.

**Comment by dkd-kaehm** [comment]
There is the version for EXT:solr v11.1+

```
<?php

declare(strict_types=1);

/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

namespace .......\Hooks\Solr;

use ApacheSolrForTypo3\Solr\Domain\Search\Query\Query;
use ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\SearchResultSet;
use ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\SearchResultSetProcessor;
use ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\Sorting\Sorting;
use ApacheSolrForTypo3\Solr\Query\Modifier\Modifier;
use ApacheSolrForTypo3\Solr\System\Configuration\TypoScriptConfiguration;
use Closure;
use InvalidArgumentException;
use TYPO3\CMS\Core\SingletonInterface;

/**
 * Sorting default option chooser makes it possible to define one of configured sorting options as default option.
 *
 * Requires declaration of "beforeSearch" Hook in ext_localconf.php
 * // Enable configuration for default sorting option.
 * $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['beforeSearch'][DefaultOptionChooser::class] = DefaultOptionChooser::class;
 *
 * Can be used in TypoScript:
 *
 * plugin.tx_solr.search.sorting.default {
 *   sortingName = someOfDeclaredSortingOptions
 *   sortingDirection = desc
 * }
 *
 * Processing sequence:
 * 1 'beforeSearch' -> DefaultOptionChooser::process() -> initializeDefaultSortingConfigurations()
 * 2 'modifySearchQuery' -> DefaultOptionChooser::modifyQuery()
 * 3 'afterSearch' -> DefaultOptionChooser::process() -> useDefaultSortingOptionInSortingComponent()
 *
 */
class DefaultOptionChooser implements Modifier, SearchResultSetProcessor, SingletonInterface
{
    /**
     * TypoScript Path used for this feature
     */
    const TS_CONTEXT_PATH = 'plugin.tx_solr.search.sorting';

    /**
     * @var SearchResultSet
     */
    protected SearchResultSet $resultSet;

    /**
     * @var string|null
     */
    protected ?string $defaultSortingOptionName = null;

    /**
     * @var string
     */
    protected string $defaultSortingDirection;

    /**
     * @var string|null
     */
    protected ?string $defaultSortingField = null;

    /**
     * @var Query
     */
    protected Query $query;

    /**
     * The implementation can be used to influence a SearchResultSet that is
     * created and processed in the SearchResultSetService.
     *
     * @param SearchResultSet $resultSet
     * @return SearchResultSet
     */
    public function process(SearchResultSet $resultSet): SearchResultSet
    {
        if (!$resultSet->getHasSearched()) {
            $this->resultSet = $resultSet;
            $this->initializeDefaultSortingConfigurations();
        }

        if ($resultSet->getHasSearched()) {
            $this->useDefaultSortingOptionInSortingComponent();
        }
        return $resultSet;
    }

    /**
     * Initializes default sorting configuration values before searching.
     *
     * Fallback to sorting direction from sorting option.
     * Those are required for "modifySearchQuery"-Hook and then for "afterSearch"-Hook.
     */
    protected function initializeDefaultSortingConfigurations(): void
    {
        $this->defaultSortingOptionName = $this->getConfiguration()->getValueByPathOrDefaultValue(self::TS_CONTEXT_PATH . '.default.sortingName', null);
        if ($this->defaultSortingOptionName === null) {
            return;
        }
        $sortingExists = $this->getConfiguration()->getValueByPathOrDefaultValue(self::TS_CONTEXT_PATH . '.options.' . $this->defaultSortingOptionName . '.', false);
        if ($sortingExists === false) {
            throw new InvalidArgumentException('No sorting configuration found for option name "' . $this->defaultSortingOptionName . '", which was used in plugin.tx_solr.search.sorting.default.sortingName TypoScript setting.', 1556577249);
        }

        $sortingDirectionBySortingOption = $this->getConfiguration()->getSearchSortingDefaultOrderBySortOptionName($this->defaultSortingOptionName);
        $this->defaultSortingField = $this->getConfiguration()->getValueByPathOrDefaultValue(self::TS_CONTEXT_PATH . '.options.' . $this->defaultSortingOptionName . '.field', null);
        if ($this->defaultSortingField === null) {
            return;
        }
        $this->defaultSortingDirection = $this->getConfiguration()->getValueByPathOrDefaultValue(self::TS_CONTEXT_PATH . '.default.sortingDirection', $sortingDirectionBySortingOption);

        $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['modifySearchQuery'][self::class] = self::class;
        $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['afterSearch'][self::class] = self::class;
    }

    /**
     * Modifies the given query and returns the modified query as result
     *
     * @param Query $query The query to modify
     * @return Query The modified query
     */
    public function modifyQuery(Query $query): Query
    {
        $this->query = $query;
        if ($this->resultSet->getUsedSearchRequest()->getHasSorting()) {
            return $query;
        }
        $this->query->clearSorts();
        $this->query->addSort($this->defaultSortingField, $this->defaultSortingDirection);

        return $query;
    }

    /**
     * Modifies the state of sorting component in GUI.
     */
    protected function useDefaultSortingOptionInSortingComponent(): void
    {
        $sortings = $this->resultSet->getSortings();
        /* @var Sorting $sorting */

        foreach ($sortings as $sorting) {
            $protectedSortingPropertySetter = Closure::bind(function ($prop, $value) {
                $this->$prop = $value;
            }, $sorting, $sorting);

            if ($sorting->getName() === $this->defaultSortingOptionName) {
                $protectedSortingPropertySetter('isResetOption', true);
                if (!$this->resultSet->getUsedSearchRequest()->getHasSorting()) {
                    $protectedSortingPropertySetter('selected', true);
                    $protectedSortingsPropertySetter = Closure::bind(function ($prop, $value) {
                        $this->$prop = $value;
                    }, $sortings, $sortings);
                    $protectedSortingsPropertySetter('selected', $sorting);
                }
            } else {
                $protectedSortingPropertySetter('isResetOption', false);
                if (!$this->resultSet->getUsedSearchRequest()->getHasSorting()) {
                    $protectedSortingPropertySetter('selected', false);
                }
            }
        }
    }

    /**
     * Returns Typoscript Configuration Object
     *
     * @return TypoScriptConfiguration
     */
    protected function getConfiguration(): TypoScriptConfiguration
    {
        return $this->resultSet->getUsedSearchRequest()->getContextTypoScriptConfiguration();
    }
}
```
