### ISSUE TITLE
[BUG] in 10.xx Connection has "core_en" at the end

### ISSUE THREAD

**Issue by p-view** [TYPO3-Solr/ext-solr#2545]
The connection that comes from site-configuration has "core_en" added. No connection possible .
/html/typo3/typo3conf/ext/solr/Classes/Domain/Site/SiteRepository.php:470 
`      SiteUtility::getConnectionProperty($typo3Site, 'core', $languageUid, 'read', 'core_en') . '/' ,`
change to        
`SiteUtility::getConnectionProperty($typo3Site, 'core', $languageUid, 'read', '') . '/' ,`

 /html/typo3/typo3conf/ext/solr/Classes/Domain/Site/SiteRepository.php:482
` SiteUtility::getConnectionProperty($typo3Site, 'core', $languageUid, 'read', 'core_en') . '/' ,`
change to 
` SiteUtility::getConnectionProperty($typo3Site, 'core', $languageUid, 'read', '') . '/' ,`

fixed this

**Comment by dkd-kaehm** [comment]
Hallo @p-view, 
please provide a little bit more information about steps to reproduce
> The connection that comes from site-configuration has "core_en" added. No connection possible

What did you do exactly? Is there no `core_en` in Apache Solr Server?

**Comment by p-view** [comment]
i have no core named core_en. 
the extension connect /my_core/core_en not  the necessary /my_core
the change above works for me

when i would used core_en in site Configuration the path would be   hosting.info:80/core_en/core_en

**Comment by dkd-kaehm** [comment]
### Will be fixed in #3043 by removing the splitting and re-concatenation of connection parts.
