### ISSUE TITLE
[BUG] Setup Solr with Docker fails

### ISSUE THREAD

**Issue by cdaecke** [TYPO3-Solr/ext-solr#2555]
**Describe the bug**
Setup of Solr with Docker fails using the shipped `Dockerfile`.

**To Reproduce**
As stated in the [documentation](https://docs.typo3.org/typo3cms/extensions/solr/stable/GettingStarted/Solr.html#docker) I try to setup Solr with Docker using the following command:

    cd typo3conf/ext/solr/Docker/SolrServer/
    docker build -t typo3-solr .

The command fails with the following output:

	Sending build context to Docker daemon  2.048kB
	Step 1/8 : FROM solr:8.2.0
	 ---> 52cddf1ea399
	Step 2/8 : MAINTAINER Timo Hund <?@dkd.de>
	 ---> Using cache
	 ---> 878b101177f3
	Step 3/8 : ENV TERM linux
	 ---> Using cache
	 ---> e416ec041868
	Step 4/8 : USER root
	 ---> Using cache
	 ---> c0d610e79a94
	Step 5/8 : RUN rm -fR /opt/solr/server/solr/*
	 ---> Using cache
	 ---> 4f5f9c56f31e
	Step 6/8 : USER solr
	 ---> Using cache
	 ---> ec6d096ec52f
	Step 7/8 : COPY Resources/Private/Solr/ /var/solr/data
	COPY failed: stat /var/lib/docker/tmp/docker-builder658450786/Resources/Private/Solr: no such file or directory

**Used versions:**
 - Docker Desktop 2.2.0.4 on a Mac.
 - EXT:solr Version: 10.0.1

**Comment by dkd-dobberkau** [comment]
Can you check with the latest documentation, that can be found here: 
https://docs.typo3.org/p/apache-solr-for-typo3/solr/10.0/en-us/GettingStarted/Solr.html

**Comment by cdaecke** [comment]
@dkd-dobberkau Thanks for your reply and the correct link to the documentation!

Just to make sure, that I don't miss something. That's what I am doing now:

    cd typo3conf/ext/solr/Docker/SolrServer/
    docker build -t typo3-solr Docker/SolrServer/Dockerfile .

Now it stops with the following message:

> "docker build" requires exactly 1 argument.
See 'docker build --help'.
>
> Usage:  docker build [OPTIONS] PATH | URL | -
>
> Build an image from a Dockerfile

**Comment by dkd-dobberkau** [comment]
Can you try with the dot?

docker build -t typo3-solr Docker/SolrServer/Dockerfile

**Comment by cdaecke** [comment]
> Can you try with the dot?
> 
> docker build -t typo3-solr Docker/SolrServer/Dockerfile

You mean **without** the dot?
So I switch to the root of the `solr` directory:

    cd typo3conf/ext/solr/

After that I enter the following command:

    docker build -t typo3-solr Docker/SolrServer/Dockerfile

... and get this message:

    unable to prepare context: context must be a directory: /xxx/htdocs/typo3conf/ext/solr/Docker/SolrServer/Dockerfile

I checked the above path and the `Dockerfile` is there.

**Comment by cdaecke** [comment]
After reading the "error" message again I tried this:

    docker build -t typo3-solr Docker/SolrServer/

But it stops again with the message I posted above:

    Step 7/8 : COPY Resources/Private/Solr/ /var/solr/data
    COPY failed: stat /var/lib/docker/tmp/docker-builder325929283/Resources/Private/Solr: no such file or directory

**Comment by dkd-kaehm** [comment]
The right syntax is with dot and from EXT:Solr's root path:
```
cd typo3conf/ext/solr/
docker build -t typo3-solr -f Docker/SolrServer/Dockerfile .
```

---

@cdaecke You do not need to build an own image, there is official images for each version available 
see: https://hub.docker.com/r/typo3solr/ext-solr/ 
So, following is enougth for running solr server:
`docker pull typo3solr/ext-solr:9.0.0`
`docker run -d -p 127.0.0.1:8983:8983 -v "$PWD/.solrdata:/opt/solr/server/solr/data/" typo3solr/ext-solr:9.0.0`

**Comment by dkd-kaehm** [comment]
We should adjust the docs for docker parts.

1. Add proper docs for running docker consuming official EXT:Solr docker image from docker hub.
2. Move the [docker build process](https://docs.typo3.org/typo3cms/extensions/solr/stable/GettingStarted/Solr.html#docker) to the development/contributing part of docs for using them by developing/testing of changes within the Solr Schemas.

**Comment by cdaecke** [comment]
@dkd-kaehm Thanks a lot, the following is working for me:

`docker pull typo3solr/ext-solr:10.0.0`
`docker run -d -p 127.0.0.1:8983:8983 -v "$PWD/.solrdata:/opt/solr/server/solr/data/" typo3solr/ext-solr:10.0.0`
