### ISSUE TITLE
[TASK] Metadata from pages record is in solr index, but is not recognized when searching for it

### ISSUE THREAD

**Issue by seirerman** [TYPO3-Solr/ext-solr#256]
The description from a pages record is being indexed just fine and can be searched for in the solr web interface.

But the solr TYPO3 plugin doesn't seem to include the description in the search results. The same goes for most the other fields from the pages record.

Searchable:
- Page title
- Keywords

Not searchable:
- Description
- Abstract
- Subtitle
- NavTitle
- Author
- (URL)

**Comment by sascha-egerer** [comment]
@seirerman Have you checked the queryfields setting?
https://forge.typo3.org/projects/extension-solr/wiki/Tx_solrsearch#queryqueryFields-queryfields

**Comment by timoschmidt** [comment]
@seirerman What is left for you here? Do you mean the default TypoScript setup could be improved? Or can we close thise issue?

**Comment by seirerman** [comment]
Yes, the default TS could be improved.
