### ISSUE TITLE
[TASK] Analyze bad build performance with TYPO3 10 & PHP 7.2

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#2567]
**What should be done in the scope of this task?**

It seems that the build take much more time with TYPO3 10. Especially in combination with php 7.2. the build take very long. We should analyze the reason for that.

**Comment by dkd-kaehm** [comment]
Current measures:

*  Ran for 54 min 16 sec
* Total time 2 hrs 55 min 37 sec
* TYPO3 9.5 ~20,5 Minutes
* TYPO3 10.4 ~33 Minutes

![Build_Performance_Travis](https://user-images.githubusercontent.com/25453927/83147460-fd952e00-a0f7-11ea-927a-c2f42aecf37c.png)
