### ISSUE TITLE
[TASK] Check and fix the things for skipped tests:

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#2587]
# Help wanted:

**Please indicate and point to existing issues according to desired test case.**

## All skipped tests must be double checked and fixed.

In some cases the tests must be just adjusted, in other the thing must be fixed:

- [x] `ApacheSolrForTypo3\Solr\Tests\Integration\Controller\SearchControllerTest::canRenderHierarchicalFacet`

- [x] `ApacheSolrForTypo3\Solr\Tests\Integration\Controller\SearchControllerTest::canFacetOnHierarchicalFacetItem`

- [x] `ApacheSolrForTypo3\Solr\Tests\Integration\Controller\SearchControllerTest::canFacetOnHierarchicalTextCategory`

- [x] `ApacheSolrForTypo3\Solr\Tests\Integration\Controller\SearchControllerTest::canSortByMetric`

- [x] `ApacheSolrForTypo3\Solr\Tests\Integration\Domain\Index\IndexServiceTest::canResolveBaseAsPrefix with data set "absRefPrefixIsFoo" ('foo', '/foo/en/?tx_ttnews%5Btt_news%...5a84a1')`

- [x] `ApacheSolrForTypo3\Solr\Test\Domain\Search\ResultSet\ResultSetReconstitutionProcessorTest::canApplyRenderingInstructionsOnOptions`

- [x] `ApacheSolrForTypo3\Solr\Test\Domain\Search\ResultSet\ResultSetReconstitutionProcessorTest::labelCanBeUsedAsCObject`

- [x] `ApacheSolrForTypo3\Solr\Tests\Integration\UtilTest::getConfigurationFromPageIdInitializesTsfe`

- [x] `ApacheSolrForTypo3\Solr\Tests\Integration\UtilTest::getConfigurationFromPageIdInitializesTsfeOnCacheCall`

**Comment by timohund** [comment]
@dkd-kaehm Util related tests will be fixed with #2593 we should have a look on the others as well.

**Comment by timohund** [comment]
@dkd-kaehm ResultSetReconstitutionProcessorTests will be fixed with #2594

**Comment by timohund** [comment]
For the tests in the SearchController we need to think about a fix and maybe require changes in the core. By now it seems to be not possible to fake the EnvironmentService in the test to fake a frontend context and therefore no url's get generated. I looks like, that this is related to the changes with the DI container, since the registered Singleton in fakeSingletonsForFrontendContext is not used during the link generation.
