### ISSUE TITLE
[BUG] SiteNotFoundException in reports module

### ISSUE THREAD

**Issue by cjanody** [TYPO3-Solr/ext-solr#2624]
**Describe the bug**
Having a TYPO3 multi-site instance with some of them not configured results in a TYPO3\CMS\Core\Exception\SiteNotFoundException in the reports module (maybe elsewhere)

**To Reproduce**
1. Create a page tree with multiple root pages
2. Configure one of them in the sites module
3. Go to the report module
4. ... 

**Expected behavior**
Sites should appear as unconfigured

**Screenshots**
![Screenshot_20200521_084118](https://user-images.githubusercontent.com/3030277/82560259-140f1880-9b3f-11ea-895d-41c061cbf33d.png)

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.18
 - EXT:solr Version: 11.0.1

**Comment by liayn** [comment]
maybe #2634 is related
