### ISSUE TITLE
[BUG] Not able to install Solr-Extension on 10 LTS

### ISSUE THREAD

**Issue by Freshmeat-ch** [TYPO3-Solr/ext-solr#2632]
**Describe the bug**
I was not able to install the newest version of apache-solr-for-typo3/solr. Composer conflicts with symfony/events-dispatcher (5.0.8) and solarium/solarium (4.2.0).
Check solarium requirement.

**To Reproduce**
1. Install TYPO3 LTS10 (Default)
2. try to add apache-solr-for-typo3/solr

**Expected behavior**
Should install.

**Used versions:**
 - TYPO3 Version: 10.4.3
 - EXT:solr Version: 11.0.1
 - PHP Version: 7.3.17

**Additional context**
Currently not very intense tested fix: composer require solarium/solarium:"5.2.0 as 4.2.0"

**Comment by dkd-kaehm** [comment]
@Freshmeat-ch 
try `composer req "symfony/console":"^4.4" "apache-solr-for-typo3/solr":^11.0`

see in #2574

Closing because of duplicate: #2574
