### ISSUE TITLE
[TASK] Upgrade Solarium to 6.x

### ISSUE THREAD

**Issue by ipf** [TYPO3-Solr/ext-solr#2636]
As the solarium library in version 5 fits the requirements of ext:solr (PHP 7.2) this should be updated.

https://github.com/solariumphp/solarium/blob/master/CHANGELOG.md#500-alpha1

The Connection is setup a little different in the solarium version 5, but this version is also tested for its compatibility to more recent Solr versions.

**Comment by pschirch** [comment]
This fix is really needed to solve #2574.

**Comment by dkd-kaehm** [comment]
This will be fixed in EXT:Solr v. 12+.
