### ISSUE TITLE
[BUG] SearchResultSetService ObjectManager Call to a member function get() on null

### ISSUE THREAD

**Issue by sevencode7** [TYPO3-Solr/ext-solr#2638]
**Describe the bug**
In the SearchResultSetService.php the ObjectManager can't get objects and throw following error message: "Call to a member function get() on null" on lines

287:  $resultSet = $this->objectManager->get($resultSetClass);
391:  $queryModifier = $this->objectManager->get($classReference);
451:  $afterSearchProcessor = $this->objectManager->get($classReference);

Replace the ObjectManager with GeneralUtility::makeInstance fix the problem

287:  $resultSet = GeneralUtility::makeInstance($resultSetClass);
391:  $queryModifier = GeneralUtility::makeInstance($classReference);
451:  $afterSearchProcessor = GeneralUtility::makeInstance($classReference);

**To Reproduce**
1. Call 
GeneralUtility::makeInstance(SearchResultSetService::class, $typoscriptConfiguration, $search)->search($searchRequest);

**Used versions (please complete the following information):**
 - TYPO3 Version: [10.3]
 - Browser: [ chrome]
 - EXT:solr Version: [11.0.1]
 - Used Apache Solr Version: [dev-master]
 - PHP Version: [7.4.0]
 - MariaDB Version: [10.2]

**Comment by timohund** [comment]
@sevencode7 you need to create the SearchResultSetService with the ObjectManager itself, to have the depencies injected.

**Comment by sevencode7** [comment]
@timohund thanks for the hint
