### ISSUE TITLE
[FEATURE] Optimize index

### ISSUE THREAD

**Issue by ulrike-cosmoblonde** [TYPO3-Solr/ext-solr#2649]
Hi,
I am missing the old planner task to optimize the solr index.
I read that it had been removed because it is no longer needed: https://docs.typo3.org/typo3cms/extensions/solr/stable/Solr/IndexMaintenance.html?highlight=optimizing

In most of my TYPO3 projects with solr, I am showing facet filters with the setting to also list empty facet values. The problem is, that it keeps listing facet values (with count=0), that no longer exist in the core because the data was deleted in TYPO3 (e.g. news with categories). I can only get rid of those "ghost" entries, if i fire an <optimize/> in the solr admin interface.
Would it be possible to re-add this planner task again or is there any other option to avoid displaying these non-existing entries?

Thank you!
Ulrike

**Comment by dkd-kaehm** [comment]
@ulrike-cosmoblonde thanks for creating issue for that.
Currently no other way is known by me. 
The pull request for that feature is welcome.
Please consume following for that PR https://solarium.readthedocs.io/en/stable/queries/update-query/building-an-update-query/optimize-command/
