### ISSUE TITLE
"Toggle All" button does not work in Index Queue Backend Module

### ISSUE THREAD

**Issue by sascha-egerer** [TYPO3-Solr/ext-solr#265]
Setup: TYPO3 7.6.4, Solr master (482f04da2f2301237d8320af13a6f1139173e1a5)

The "Toggle All" button in the backend module "index queue" does not work.

The Problem is that a part of FormEngine is used to create the checkboxes but FormEingine is not really initalized and used in a correct way here.
Required "requireJS" modules are not loaded and so the JavaScript part is missing there.

I could do a quick fix but it don't think that this is a good idea. 

```diff
diff --git a/Classes/Backend/IndexingConfigurationSelectorField.php b/Classes/Backend/IndexingConfigurationSelectorField.php
index 084df90..5b8f842 100644
--- a/Classes/Backend/IndexingConfigurationSelectorField.php
+++ b/Classes/Backend/IndexingConfigurationSelectorField.php
@@ -26,6 +26,7 @@ namespace ApacheSolrForTypo3\Solr\Backend;
 
 use ApacheSolrForTypo3\Solr\Site;
 use ApacheSolrForTypo3\Solr\Util;
+use TYPO3\CMS\Core\Page\PageRenderer;
 use TYPO3\CMS\Core\Utility\GeneralUtility;
 
 /**
@@ -244,6 +245,17 @@ class IndexingConfigurationSelectorField
             $options['parameterArray']['fieldTSConfig']['noMatchingValue_label'] = '';
             $selectCheckboxResult = $nodeFactory->create($options)->render();
 
+            if (!empty($selectCheckboxResult['requireJsModules'])) {
+                /** @var PageRenderer $pageRenderer */
+                $pageRenderer = GeneralUtility::makeInstance(PageRenderer::class);
+                $pageRenderer->loadRequireJsModule('TYPO3/CMS/Backend/FormEngine');
+
+                foreach ($selectCheckboxResult['requireJsModules'] as $moduleName) {
+                    $pageRenderer->loadRequireJsModule($moduleName);
+                }
+                $pageRenderer->addInlineSetting('FormEngine', 'not', 'required');
+                $pageRenderer->addInlineSetting('DateTimePicker', 'not', 'required');
+            }
             return $selectCheckboxResult['html'];
         } elseif (class_exists('TYPO3\\CMS\\Backend\\Form\\FormEngine')) {
             $formEngine = GeneralUtility::makeInstance('TYPO3\\CMS\\Backend\\Form\\FormEngine');
```

**Comment by timoschmidt** [comment]
@sascha-egerer 

This issue was solved with this commit:

https://github.com/TYPO3-Solr/ext-solr/commit/a6c2b8fb971d988244400a30bc232da24cf7e02f

Can you check if this is working for you? I did not see your approach before but i like it. I think we need to decided between adding the whole FormEngine functionallity or only the parts that we need. What do you think?

I think we can close this issue or you maybe add a pr with your changed and remove the Js snipped shipped with ext:solr.

**Comment by sascha-egerer** [comment]
I think it would be easier to use the core functionality in a correct way so that we don't have troubles with each TYPO3 update

**Comment by timoschmidt** [comment]
To summarize what is open here:

We need to initialize the FormEngine require js a it is done in other modules. E.g. the backend user module, but it is working at it is done now. So i would keep this issue open.
