### ISSUE TITLE
[BUG] Sorting and facet urls are broken because the link contains the `type` parameter

### ISSUE THREAD

**Issue by Mabahe** [TYPO3-Solr/ext-solr#2656]
Regression from #2633

**Comment by dkd-kaehm** [comment]
@Mabahe Hello, thanks for reporting.
Is the exact position in the source code known?

**Comment by Mabahe** [comment]
I guess the reason is, that the UriBuilder is reused now https://github.com/TYPO3-Solr/ext-solr/pull/2633/commits/de0bf01900064639d6d3c63831d4de8c15bee829#diff-12fa500b04ea9e7e8d08b8d0ce521464R61
Before the vh has it's own new UriBuilder instance.

**Comment by Mabahe** [comment]
Add @bmack

**Comment by bmack** [comment]
So we'd need a reset on the UriBuilder?

**Comment by Mabahe** [comment]
Yes, is the one idea to fix it. But why you reuse the UriBuilder now?

**Comment by bmack** [comment]
Otherwise it's impossible to make the Integration Tests work (or you have a better idea that I did not see?)

**Comment by Mabahe** [comment]
@dkd-kaehm @timohund @achimfritz please check if this is safe and does not cause the next regression. Let me know if you prefer a revert of #2633 and solve the integration tests a different way.

**Comment by markuskobligk** [comment]
I can confirm this PR works and I could not detect any side effects so far concerning link generation in other parts of the search.
