### ISSUE TITLE
[BUG] RenderType is missing in flexform definition 

### ISSUE THREAD

**Issue by dgorges** [TYPO3-Solr/ext-solr#2661]
If a form only is selected in the backend, the option section in the flexform displays an unknown type select.
Unknown type: select, render type: select

The fix is just to add in the form.xml in Line 36: 
`<renderType>selectSingle</renderType>` in the config section.

After that the template can be set correctly

**Comment by dkd-kaehm** [comment]
Backports merged as well. 
Can be closed.
