### ISSUE TITLE
[TASK] Use current Apache Solr 8.5.x release in next EXT:Solr release

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#2662]
See current Release https://lucene.apache.org/solr/downloads.html

**Comment by dkd-dobberkau** [comment]
Please check https://lucene.apache.org/solr/downloads.html for the latest available version.

**Comment by jacobsenj** [comment]
Just as a side node. Would'nt it make sense to set it to the minor version, i.e. instead of using the patch version `FROM solr:8.5.1` use `FROM solr:8.5`? I usually do this in the supplied docker-compose.yml files I add in our projects.
