### ISSUE TITLE
[BUG] Auto Suggest and Faccets leads to RequiredArgumentMissingException

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Solr/ext-solr#2670]
**Describe the bug**
I am using 
solr 11.0.2 on TYPO3 9.5.19 with Autosuggest and Facets. When I hit "Remove all Faccets" I will run into the following error each time:
1/1) #1298012500 TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException
Required argument "queryString" is not set for ApacheSolrForTypo3\Solr\Controller\SuggestController->suggest.

the url where this error is shown also looks strange to me: 
suche?tx_solr%5Bq%5D=%2A&type=7384

When I remove the Autosuggest template I run into the following error:
he page is not configured! [type=7384][].

**To Reproduce**
Search for *
filter for pages
hit remove all filters

**Expected behavior**
filter gets removed

**Used versions (please complete the following information):**
 - TYPO3 Version 9.5.19
 - Browser: chrome
 - EXT:solr Version: 11.0.2
 - Used Apache Solr Version: 8.5.1
 - PHP Version: [e.g. 7.2.23]
 - MySQL Version: ?

**Additional context**
Typoscript configuration:

plugin.tx_solr {
    search.faceting = 1
    search.faceting.facets {
        typeToggle {
            label = Type Toggle
            field = type
            partialName = OptionsToggle
        }
    }

}

page.includeJSFooterlibs {
    solr-jquery = EXT:solr/Resources/Public/JavaScript/JQuery/jquery.min.js
    solr-options = EXT:solr/Resources/Public/JavaScript/facet_options_controller.js
}

**Comment by dkd-kaehm** [comment]
Problem is known and fixed in current master, which will be available soon in 11.0.3.
See: #2659
