### ISSUE TITLE
[BUG] Indexing eats 100% CPU and up to 5 GB memory

### ISSUE THREAD

**Issue by klodeckl** [TYPO3-Solr/ext-solr#2679]
Hello,

when indexing documents (e.g. fe_users) I have 100 % CPU eating and between 4 and 5 GB memory usage. 
TYPO3 8.7.32
Solr 9.0.2. I’m not sure but I think it is a little better since I downgraded to 8.1.2. When using version 6.5 everything was fine (not sure if this is the cause).
Is that problem known?

**Comment by dkd-kaehm** [comment]
Hello @klodeckl,
thanks for reporting. That is not known. 
What exactly eats the time and memory? 
The Apache Solr Server or the PHP indexing process?

**Comment by klodeckl** [comment]
It’s the PHP indexing process (PHP FPM 7.3, Debian 10). Solr is okay. Do you have an idea what could cause the problem?

**Comment by dkd-kaehm** [comment]
@klodeckl 
Following could cause this behavior:
1. to many items per Schduler run
2. parallel execution checkbox is active in scheduler task
3. some infinite loop[s]

---

Could you setup PHP-Profiling with your setup to be able to identificate the source?

**Comment by klodeckl** [comment]
Thank you! I only have 10 items per run configured. Parallel execution is also disabled. I think it is a loop. I will have a look at xdebug (never needed before) and report back.

**Comment by klodeckl** [comment]
After upgrading to TYPO3 Version 9 memory consumption is much better, maximum 3.3 GB. At last it was up to 9.5 GB!
This is no back to normal, or is it still too much (8 documents per run, no parallel execution)?

**Comment by dkd-kaehm** [comment]
Hello @klodeckl 

thanks for your feedback.

> This is no back to normal, or is it still too much (8 documents per run, no parallel execution)?

I don't think that is normal, you could try our https://github.com/TYPO3-Solr/solr-ddev-site/ within the `release-10.0.x` branch, which is for TYPO3 9.5.

Just trigger "Force re-indexing" task and monitor it within `ddev ssh`.

I'll propose to profile your instance on indexing process, to be able to identify a memory hungry methods.

**Comment by dkd-kaehm** [comment]
@klodeckl 
I'll close this issue in favor of our direct contact.
