### ISSUE TITLE
Indexing files of a custom extension table which is having relation to another custome table

### ISSUE THREAD

**Issue by Georgyge** [TYPO3-Solr/ext-solr#2685]
I am using solr 6.5.1 and solrfal 4.1.1. I have a primary table "tx_table1", and a field "docsField" and this "docsField" is related to another table "tx_table2". And "tx_table2" has fields title, file. I have used SOLR_RELATION for indexing the title field of table2. But how can I index the attachment field? I had tried with
`plugin.tx_solr.index.queue.tx_table1.attachments.fields = docsField`
and
`plugin.tx_solr.index.queue.tx_table1.attachments.fields = docsField.file`

But none of these worked. Is there a way to index such related table files?

**Comment by dkd-kaehm** [comment]
No EXT:Solrfal support here, please contact us via solr-eb-support@dkd.de.
