### ISSUE TITLE
[BUG] Value of search term not available in solr_pi_search plugin

### ISSUE THREAD

**Issue by seirerman** [TYPO3-Solr/ext-solr#2686]
I've added a global search form to my site like it says in the manual: 
```
lib.searchbox < plugin.tx_solr_PiSearch_Search
lib.searchbox.search.targetPage = 4711
```
The form is shown correctly, and using this form to search the site works fine.
The request gets redirected to the search page, where the solr_pi_results plugin shows the expected results.

The search field from the solr_pi_results plugin has the search term prefilled as the input value.
The global search form, however, hasn't and is now empty.

Both forms use the same fluid partial (Search/Form.html):
```
<input type="text" class="..." name="{pluginNamespace}[q]" value="{q}" />
```
Using <f:debug> in Form.html didn't help, either. Am I missing something?

**Expected behavior**
The global search form should have the search term prefilled on the search page.

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.19
 - EXT:solr Version: 9.0.2
 - Used Apache Solr Version: 7.7.2
 - PHP Version: 7-2-31
 - MySQL Version: MySQL 5.5.5-10.1.45-MariaDB

**Comment by dkd-kaehm** [comment]
The global search form should be used for new searches by default. It should contain the placeholder only. See any site with global search form. Some sites disabling/hiding the global search form on results page.

---

Nevertheless the `formAction` does not care about query parameters. See the form action implementation -> 

https://github.com/TYPO3-Solr/ext-solr/blob/e674df2b4f2b9792d3cc117f7b996ee73a48eaaa/Classes/Controller/SearchController.php#L123-L137

To get the q parameter in global form, try to use `resultsAction` in `plugin.tx_solr_PiSearch_Search`

https://github.com/TYPO3-Solr/ext-solr/blob/e674df2b4f2b9792d3cc117f7b996ee73a48eaaa/Configuration/TypoScript/Solr/setup.txt#L410-L418

with own template/partials for that. Use the `resultsAction` for `plugin.tx_solr_PiSearch_Search` on results page only, to avoid performance implications on whole site and reduce search initializations on each page. 

Alternatively you can override our `SearchController`s `formAction` to fetch and relegate the q parameter to the view.

---

I'll close this issue. 
Please refer to our #ext-solr Slack channel on TYPO3s Slack for getting it working.
