### ISSUE TITLE
[BUG] Wrong facet links in combination with search form produce exception

### ISSUE THREAD

**Issue by utrotzek** [TYPO3-Solr/ext-solr#2687]
**Describe the bug**
When I click on a facet link the frontend produces the following exception

```
1298012500 TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException
Required argument "queryString" is not set for ApacheSolrForTypo3\Solr\Controller\SuggestController->suggest.
```

I'm using the solr_pi_results plugin with the search form and the facets on one page. The autocomplete feature is enabled as well. I'm currently migrating vom TYPO3 8.7 to TYPO3 10. Before the upgrade everything worked smoothly.

**To Reproduce**

1. Search for something (with facet results)
2. Click on one of the facets
3. See the above mentioned exception

**Expected behavior**
No exception and the search result should be filtered by the selected facet. 

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.6
 - Browser: chrome
 - EXT:solr Version: 11.0.2
 - Used Apache Solr Version: 8.5.1
 - PHP Version: 7.4

**Additional context**
Maybe the error is instance related but I really don't know what I could do to fix this. Maybe someone can reproduce this. I also did some debugging and find out that every facet link has the GET parameter &type=7384 appended which leads to the mentioned exception. But I don't know WHY this link is created. As far as I could see these links are generated once and stored with some kind of a hash and will then be reused. But I could not figure out the problem behind that.

My workaround now is to override the partial Partials/Search/Form.html and add the `addSuggestUrl="0"` option to the search form. This fixes the bug, but the autocomplete is obviously not working.

````
<s:searchForm id="tx-solr-search-form-pi-results" additionalFilters="{additionalFilters}" suggestHeader="{s:translate(key:'suggest_header',default:'Top Results')}" addSuggestUrl="0">
````

**Comment by dkd-kaehm** [comment]
> Problem is known and fixed in current master and release-11.0.x branches. It will be available soon in 11.0.3.
See: #2659
