### ISSUE TITLE
Fallback to archive.apache.org for downloads

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/ext-solr#27]
Need to adapt the install scripts to fall back to archive.apache.org if the requested version is not available on a mirror.

**Comment by irnnr** [comment]
http://superuser.com/questions/197009/wget-head-request

**Comment by dkd-dobberkau** [comment]
I wonder if we should not go for a lighter approach in general. What i mean is that we need to separate the solr server install from the configuration of the server itself. depending on the changes we introduce with the solr version we could offer a minimal setup working schema-less or provisioned by the ext:solr extension via the rest interfaces. just a thought.

**Comment by irnnr** [comment]
That's the plan for later. For now we just need to fix the scripts
