### ISSUE TITLE
[BUG] using empty string in notLike() issue SQL error on PostgreSQL

### ISSUE THREAD

**Issue by d3pendent** [TYPO3-Solr/ext-solr#2702]
**Describe the bug**
After loading the indexing configuration and selecting The Index Queue Modul an Doctrine\DBAL\Exception\SyntaxErrorException occurs.

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.6
 - Browser: chrome
 - EXT:solr Version: 11.0.2
 - Used Apache Solr Version: 8.5.1
 - PHP Version: 7.4.0
 - postgresql Version: 12.2
 - .ddev image: typo3solr/ext-solr:11.0.2

![solr_exception_02_screenshot](https://user-images.githubusercontent.com/3381225/91181776-a1877900-e6e9-11ea-98ae-a1aade1fc2b1.png)

**Comment by dkd-kaehm** [comment]
Wow, it seems there are multiple issues with PostgreSQL.
Can you use MySQL/MariaDB instead of Postgres?

**Comment by d3pendent** [comment]
I wish i could use MySQL/MariaDB. Unfortunately I am stuck with PostgreSQL

**Comment by dkd-kaehm** [comment]
Would propose to use single "epic" issue for Postgres stuff with check list of current issues.
So we could then merge the whole stuff in single PR. 
We could then add postgres in test matrix of travis.
PS: Please do not create back-ports into the 11 branch as I suggested in some of your PRs.

**Comment by dkd-kaehm** [comment]
@d3pendent 
I'll create milestone PostgreSQL-Support.
Would you like to take the lead role for the milestone?
