### ISSUE TITLE
Improve debugging possibilities of send solr query

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#271]
I think we could improve the debugging possibilities of a search query that was send to solr. 

Ideas to think about:

- When you are logged in as admin in the backend, see the query in fire_php 
- Log to the DEV::log
- Display with a ViewHelper, when logged in as admin

I think in the implementation we need to keep the frontend performence i mind to not slow down the existing implementation.

**Comment by DanielSiepmann** [comment]
If I'm not mistaking, that's already possible using:
![image](https://cloud.githubusercontent.com/assets/354250/15601478/db66de2a-23ef-11e6-931f-0ea7ee20190f.png)

You can send them to, e.g. TYPO3 logging using DevLog:
![image](https://cloud.githubusercontent.com/assets/354250/15601497/f6295bb6-23ef-11e6-9e66-38d09d814892.png)

I've provided an example on my blog: https://daniel-siepmann.de/Posts/2016-05-27-typo3-custom-devlog.html

There you can define the style of output your own, e.g.:
![image](https://cloud.githubusercontent.com/assets/354250/15602543/21e1e31c-23f6-11e6-9bb6-44ebfee0be6b.png)

**Comment by timohund** [comment]
@DanielSiepmann Nice article and approach. I've added the possibility to write the devLog output to the console or in the frontend (when enabled). Adding the messages to a log file is also nice, and i would implement it with a second devLog handler.
