### ISSUE TITLE
Profile EXT:solr with xhprof OR xdebug and improve indexing and searchpeformance

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#272]
We can profile the extension with XHProf or XDebug and check timeconsuming parts and improve them.
1. Create a cachegrind or do an xhprof session
2. Are there parts that could be skipped in the code (early return, unneeded loops)
3. Are there parts to cache, that bring a high boost
4. Add testcases for performance critical parts
5. Can we improve the curl ussage e.g. like described here: #141

**Comment by kasperligaard** [comment]
I think @thomashohn has been profiling solr (with blackfire.io) even more than this issue envisioned (in Nov. and Dec. 2016). This has led to several issues and pull requests, which has been merged. Maybe this issue can simply be resolved as "Done elsewhere"..?

**Comment by thomashohn** [comment]
At least this is true for the indexing part - I haven't profiled the search part in detail. But I think I could run it through the blackfire.io and spend an hour or 2 on the output

**Comment by timohund** [comment]
@kasperligaard 
@thomashohn 
Thanks true, i would propose to close it and open new issues for concrete specific tasks in the future. What do you think? Thanks for the effort you've spend on this guys

**Comment by thomashohn** [comment]
@timohund I'll create a new issue - where the focus will be to run the search through blackfire.io

**Comment by timohund** [comment]
@kasperligaard 
@thomashohn 
Ok so i'll close this issue
