### ISSUE TITLE
[BUG] Latest version can't be installed anymore with composer due conflict symfony/event-dispatcher

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Solr/ext-solr#2720]
This is *not* a duplicate of #2574 as the requirements of TYPO3 with 10.4.7 changed.

With https://github.com/TYPO3/TYPO3.CMS/commit/cb438b3c5ea8579d2c78feacd6ee9affbfbcda12#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780 the package `symfony/event-dispatcher-contracts` has been added.

Due to the limitation to solarium `solarium/solarium: ~4.2.0` this is not compatible anymore

How to reproduce:
```json
{
	"name": "typo3/project",
	"require": {
		"php": "^7.2",

		"typo3/cms-core": "^10.4",
			"typo3/cms-frontend": "^10.4",
				"typo3/cms-tstemplate": "^10.4",
			"typo3/cms-backend": "^10.4"
	}
}
```

and `composer req apache-solr-for-typo3/solr:dev-master`

Related to #2636

**Comment by sfsmfc** [comment]
We need the requirement for at least solarium/solarium: ~5.2.0, if it works.

**Comment by bmack** [comment]
upgrading to solarium 5 is a bit heavy for EXT:solr at the current moment (although long overdue).

I think it is important to require "symfony/event-dispatcher-contracts:^1.1 || ^2.0" in TYPO3 Core.

**Comment by dkd-kaehm** [comment]
I still beleave it is just the same as #2547

```
{
	"name": "typo3/project",
	"require": {
		"php": "^7.2",

		"typo3/cms-core": "^10.4",
		"typo3/cms-frontend": "^10.4",
		"typo3/cms-tstemplate": "^10.4",
		"typo3/cms-backend": "^10.4"
	}
}
```

Following command with composer.json from above explains the troubles.

```
composer why symfony/event-dispatcher
```
says: 
```
symfony/mailer  v5.1.5  requires  symfony/event-dispatcher (^4.4|^5.0)
```

So before running `composer install` on fresh installation add `"symfony/event-dispatcher":"^4.4"` to your root composer.json

```
{
        "name": "typo3/project",
        "require": {
                "php": "^7.2",

                "typo3/cms-core": "^10.4",
                "typo3/cms-frontend": "^10.4",
                "typo3/cms-tstemplate": "^10.4",
                "typo3/cms-backend": "^10.4",
                "symfony/event-dispatcher":"^4.4"
        }
}

```
then 
`composer req apache-solr-for-typo3/solr:dev-master` works.

---

The upgraders must kill the broken state of composer installation(remove composer.lock and directories with packages and vendors), then do the thing from above and run `composer install`. Then commit and push your new composer.json and composer.lock in VCS.

---

The solarium must be upgraded to newer version, but we can't do it in release-11.0 branch.
We planing to do it. But everyone can begin with migration to newest solarium.

**Comment by dkd-kaehm** [comment]
If somebody knows how to force downgrade of "symfony/event-dispatcher" with pure composer commands -> please post it in this and other issues.

**Comment by georgringer** [comment]
@dkd-kaehm currently we will fix that in core https://review.typo3.org/c/Packages/TYPO3.CMS/+/65635

**Comment by georgringer** [comment]
@dkd-kaehm sorry your assumption is wrong. regression release of typo3 10.4.8 works now.
