### ISSUE TITLE
[TASK] Migrate cHash handling

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Solr/ext-solr#2725]
cHash handling was disabled with some code as it wasn't compatible, see #2211.
The mentioned "issue" or missing feature inside of TYPO3 is fixed since v10 LTS: https://review.typo3.org/c/Packages/TYPO3.CMS/+/63062.

Therefore this workaround should be removed, and a proper example configuration should be provided instead.

Right now we apply the following patch to EXT:solr:

```patch
diff --git a/Classes/Domain/Search/Uri/SearchUriBuilder.php b/Classes/Domain/Search/Uri/SearchUriBuilder.php
index 81eb4321..7fc5246a 100644
--- a/Classes/Domain/Search/Uri/SearchUriBuilder.php
+++ b/Classes/Domain/Search/Uri/SearchUriBuilder.php
@@ -310,36 +310,22 @@ class SearchUriBuilder
      */
     protected function buildLinkWithInMemoryCache($pageUid, array $arguments)
     {
-        $values = [];
-        $structure = $arguments;
-        $this->getSubstitution($structure, $values);
-        $hash = md5($pageUid . json_encode($structure));
+        $hash = md5($pageUid . json_encode($arguments));
         if (isset(self::$preCompiledLinks[$hash])) {
             self::$hitCount++;
             $uriCacheTemplate = self::$preCompiledLinks[$hash];
         } else {
             self::$missCount++;
-            $this->uriBuilder->setTargetPageUid($pageUid);
-            $uriCacheTemplate = $this->uriBuilder->setArguments($structure)->setUseCacheHash(false)->build();
-
-            // even if we call build with disabled cHash in TYPO3 9 a cHash will be generated when site management is active
-            // to prevent wrong cHashes we remove the cHash here from the cached uri template.
-            // @todo: This can be removed when https://forge.typo3.org/issues/87120 is resolved and we can ship a proper configuration
-            $urlHelper = GeneralUtility::makeInstance(UrlHelper::class, $uriCacheTemplate);
-            $urlHelper->removeQueryParameter('cHash');
-            $uriCacheTemplate = $urlHelper->getUrl();
+            $uriCacheTemplate = $this->uriBuilder
+                ->setTargetPageUid($pageUid)
+                ->setArguments($arguments)
+                ->setUseCacheHash(true)
+                ->build();
 
             self::$preCompiledLinks[$hash] = $uriCacheTemplate;
         }
 
-        $keys = array_map(function($value) {
-            return urlencode($value);
-        }, array_keys($values));
-        $values = array_map(function($value) {
-            return urlencode($value);
-        }, $values);
-        $uri = str_replace($keys, $values, $uriCacheTemplate);
-        return $uri;
+        return $uriCacheTemplate;
     }
 
     /**
```
Also `getSubstitution()` could be removed.

Possible example configuration:
```php
\TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule($GLOBALS['TYPO3_CONF_VARS'], [
    'FE' => [
        'cacheHash' => [
            'excludedParameters' => [
                'solr' => '^tx_solr',
            ],
        ],
    ],
]);
```

**Comment by dkd-kaehm** [comment]
@3l73 @dkd-friedrich 
Current [master state on 5c27dd7](https://github.com/TYPO3-Solr/ext-solr/commit/5c27dd792fd2435377532680571587dc42f6dfca)
assigns the cHash on all EXT:Solr links/facets/components.
There is the time to go the way proposed in this issue.

**Comment by dkd-friedrich** [comment]
I've prepared a PR (#2972) to fix this issue, changes are based on the patch kindly provided by @DanielSiepmann. I just added a `reset()` to the UriBuilder to avoid invalid settings and skipped the call of `setUseCacheHash()` since this has no effect anymore and will just trigger a notice.

I will do some more tests in the next days and check the integration tests if necessary.

**Comment by dkd-friedrich** [comment]
Rafael and I have taken a closer look at the problem and have now chosen a slightly different path.

Since no cHash calculation is possible for the links of the range facets generated via JavaScript and a more extensive caching was possible in the old variant, we decided to exclude the tx_solr parameters. Configuration options for namespaces and parameters is added and a default cHash configuration provided.
