### ISSUE TITLE
[TASK] Log SolrUnavailableException in SearchController

### ISSUE THREAD

**Issue by saitho** [TYPO3-Solr/ext-solr#2728]
**What should be done in the scope of this task?**

In `\ApacheSolrForTypo3\Solr\Controller\SearchController` the exception `SolrUnavailableException` is caught and frontend will display the "Search is not available" error. The exception itself however is ignored.

* https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/Controller/SearchController.php#L118
* https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/Controller/SearchController.php#L173

In my opinion it should be logged in TYPO3 error log to allow easier debugging.

**Comment by 3l73** [comment]
Hi Mario,

a log is written in case this is activated.

Can you check if following configuration is enabled inside of your TypoScript configuration?

- `plugin.tx_solr.logging.exceptions'`

See: https://docs.typo3.org/p/apache-solr-for-typo3/solr/master/en-us/Configuration/Reference/TxSolrLogging.html#exceptions

If it's activated, the message `Solr server is not available` will added to the log file.

- https://github.com/TYPO3-Solr/ext-solr/blob/54c25599a8cd1190e5513f9eca6b0acf830c024c/Classes/Controller/AbstractBaseController.php#L259

However this is a generic message not the message inside of the exception.

Regards

Lars
