### ISSUE TITLE
[BUG] Documents shown in wrong core in Info Module

### ISSUE THREAD

**Issue by smichaelsen** [TYPO3-Solr/ext-solr#2731]
**Describe the bug**
In the _Index Documents_ tab in the solr info module documents can appear for the wrong core. e.g. documents from _core_fr_ are listed in _core_it_. This is a bug with this view. The documents within solr itself are indexed correctly. It happens when your system language uids are not sequential (not 0, 1, 2, 3, 4, ..)

**To Reproduce**
* Make your system language uids not sequential, e.g. by deleting a language so you end up with a "gap" like (0, 2, 3, 4).
* Index documents in all languages
* Open the _Index Documents_ tab in the solr info module

**Expected behavior**
Documents appearing in their corresponding core.

**Screenshots**
<img width="503" alt="Screenshot 2020-09-24 at 07 31 20" src="https://user-images.githubusercontent.com/912435/94104730-f678f500-fe37-11ea-951e-74dca4dfd784.png">

**Used versions (please complete the following information):**
 - TYPO3 Version: 8.7, but should be independent
 - EXT:solr Version: 9.0.2. From looking at the code the problem is still in master
 - Used Apache Solr Version: 7.6.0, but should be independent

**Additional context**
The bug occurs here IMO:
https://github.com/TYPO3-Solr/ext-solr/blob/8f8ac6a979123da90373f712d899b3ffa9476163/Classes/Controller/Backend/Search/InfoModuleController.php#L260
When iterating over the solr connections it is assumed that the key is the language uid. But is just the numeric index of connections. So when it works it's purely by chance.

**Comment by 3l73** [comment]
@smichaelsen This problem solved with issue #2553 which is part of EXT:solr v11. This verson is compatible with TYPO3 9.5.16 and above.

Did you have any plans to upgrade to TYPO3 10 LTS?

**Comment by dkd-kaehm** [comment]
The backport onto 10 was not created.

https://github.com/TYPO3-Solr/ext-solr/blob/release-10.0.x/Classes/ConnectionManager.php#L293-L295

After back porting onto 10 we'll close this issue, because we support master + two latest major releases.

**Comment by dkd-kaehm** [comment]
@smichaelsen 
Thanks for reporting this issue.
You must upgrade to EXT:Solr 10.0.4+|11.0.4+, which will be released soon.
