### ISSUE TITLE
[BUG] Record indexing doesn't work anymore if page queue is disabled

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Solr/ext-solr#2742]
Since #2683 the method `Site::getPages()` doesn't collect the pages anymore if no index configuration for `pages` is found.  This change breaks filling the queue via backend module or scheduler if no page configuration is available.

In a lot of projects I don't index pages but records only.

**Comment by dkd-kaehm** [comment]
Thanks for reporting.
@georgringer 
Also following should be enough to reproduce?:

1. unset pages queue
```
plugin.tx_solr.index.queue.pages >
``` 
2. Try to initialize the records queue
