### ISSUE TITLE
[BUG] Deprecated second parameter for BackendUserAuthentication->modAccess is used

### ISSUE THREAD

**Issue by NamelessCoder** [TYPO3-Solr/ext-solr#2746]
**Describe the bug**
Deprecated second parameter for BackendUserAuthentication->modAccess is used in IfHasAccessToModuleViewHelper.

**To Reproduce**
1. Be on at least TYPO3 9.5
2. Enable reporting of deprecation errors (trigger_error + E_USER_DEPRECATED)
3. Visit the Solr "Info" backend module
4. An error is triggered

**Expected behavior**
No error should be triggered; the return value from modAccess() can be cast to boolean which results in identical behavior.

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.21
 - Browser: Chrome (but irrelevant)
 - EXT:solr Version: 11.0.2
 - Used Apache Solr Version: irrelevant, triggers on any version
 - PHP Version: irrelevant, triggers on any version (if configured to not suppress E_USER_DEPRECATED)
 - MySQL Version: irrelevant

**Comment by 3l73** [comment]
A fix for the master branch is ready to review.

Backports will be available after review and test.
