### ISSUE TITLE
[BUG] "print() expected bool, int given" after adding pages to the index queue

### ISSUE THREAD

**Issue by PhilippKuhlmay** [TYPO3-Solr/ext-solr#2753]
**Describe the bug**
When adding something to the index queue (like pages or news) an error is shown after i clicked on "Queue selected content for indexing"

**To Reproduce**
1. Go to module 'Index Queue'
2. Select any items like pages or news in the list "Index Queue Initialization"
3. Click on "Queue selected content for indexing"

**Expected behavior**
No error should be shown

**Screenshots**
This error is shown:
<img width="753" alt="Index-Queue-Error" src="https://user-images.githubusercontent.com/57705869/96857255-10215280-145f-11eb-9299-494bfa991fbc.png">

But adding to the queue worked.
<img width="1074" alt="Index-Queue" src="https://user-images.githubusercontent.com/57705869/96857288-1a435100-145f-11eb-86b4-653e15cb4403.png">

**Used versions:**
 - TYPO3 Version: 10.4.8
 - Browser: Chrome
 - EXT:solr Version: 11.0.2
 - Used Apache Solr Version: 8.5.1
 - PHP Version: 7.4.11
 - MySQL Version: 5.7.31

**Comment by PhilippKuhlmay** [comment]
Error message within TYPO3 Log is 
Core: Exception handler (WEB): Uncaught TYPO3 Exception: print_r() expects parameter 2 to be bool, int given | TypeError thrown in file .../public/typo3conf/ext/solrfal/Classes/Queue/ConsistencyAspect.php in line 391. Requested URL: https://URL/typo3/index.php?route=%%2Fmodule%%2Fsearchbackend%%2FSolrIndexqueue&token=--AnonymizedToken--&id=1&tx_solr_searchbackend_solrindexqueue%%5Baction%%5D=initializeIndexQueue&tx_solr_searchbackend_solrindexqueue%%5Bcontroller%%5D=Backend%%5CSearch%%5CIndexQueueModule

**Comment by dkd-kaehm** [comment]
Thanks for reporting, that is solrfal bug, which is already queued as issue for next Bugfix release.
See dkds 128084
