### ISSUE TITLE
Solr doesn't support config.absRefPrefix = auto

### ISSUE THREAD

**Issue by GuillaumeG22** [TYPO3-Solr/ext-solr#276]
Hello,

I use the extension solr(v3.1.1) in TYPO3 7 LTS.

Since TYPO3 7.1, there is the value "auto" for "config.absRefPrefix".

In the extension solr, this value is not taken into consideration and generates a bad URL. 

Guillaume

**Comment by timoschmidt** [comment]
@GuillaumeG22 

Thx for your report:

Where do you think config.absRefPrefix auto is not supported? We are using EXT:solr with 7.6 LTS in the DEV Box also with config.absRefPrefix = auto and for me this is working fine. 

Can you please provide a setup where it is not working and also what it not workingß

**Comment by GuillaumeG22** [comment]
@timoschmidt 

I index the news record. 
When I generate an url with typolink, my link is prepended with "auto" like "autoindex.php?id=10".

**Comment by abvdveen** [comment]
Am having the same issue, and has been reported by Sascha Egerer, see https://forge.typo3.org/issues/72164

**Comment by timoschmidt** [comment]
@GuillaumeG22 
@abvdveen 

Did you had the chance to debug this or maybe allready have a patch or the time to investiage?

**Comment by abvdveen** [comment]
I spent quite a bit of time trying to debug this, but not succesfull yet. Urls for pages are generated ok (and have realurl paths). But urls for records (generated in resolveFieldValue in AbstractIndexer.php) have autoindex.php as prefix when absRefPrefix=auto. When absRefPrefix=/ urls are working (index.php as prefix) but not processed by realurl. Maybe a CLI issue? I use realurl 2 and typo3 7.6.4
Do you have it working with realurl?

**Comment by timoschmidt** [comment]
@abvdveen 
@GuillaumeG22 

I've created a bugfix for this. And now the absRefPrefix during indexing is getting resolved. Can you please check this? The Issue with Realurl could also be another topic.

Can you check the PR and give a :+1:  when this is fixing the absRefPrefix = auto issue?

**Comment by abvdveen** [comment]
Update: the reason realurl wasn't generating speaking urls when indexing records with solr, was that in realurl 2 in the file Classes/Encoder/UrlEncoder.php there's a check canEncoderExecute() which in turn consists of 5 checks, one of which is isBackendMode(). As solr indexers are run from cli or manually from backend this condition is true and therefore no encoding is done. I hacked this file for now, removing the  check and now speaking urls are generated when indexing records...

**Comment by timoschmidt** [comment]
We should also backport this to 3.1.x after review

**Comment by abvdveen** [comment]
Hi Timo, just tested your fix in my solr 3.1.1 and it indeed fixes the problem. Without the fix and 'absRefPrefix = auto' urls are prefixed with 'auto', with the fix they are fine. Thanks for the fast response!

Best,
Albert

**Comment by timoschmidt** [comment]
Ok, thx! i'll merge the PR to dev-master and release-3.1.x and close the issue

**Comment by GuillaumeG22** [comment]
Hello,

I index currently an entity like news (tx_news_domain_model_news). 

When the _cli_scheduler indexes my record, "GeneralUtility :: getIndpEnv ( 'TYPO3_SITE_PATH)" return back the path from the server '/var/www/.../httpdocs/ '.
