### ISSUE TITLE
[FEATURE] Use semantic versioning, when publishing docker image typo3solr/ext-solr

### ISSUE THREAD

**Issue by brandung-sjorek** [TYPO3-Solr/ext-solr#2766]
Hi folks,

while using the typo3solr/ext-solr docker-image currently one can pull the latest or a specific “major.minor.patch” version only. This is not optimal, if you want to stick to a certain major-Version, because you can only use a specific version and you have to check for newer versions manually. Not very docker-a-like.

As [the article about using semantic versioning when publishing docker images](https://medium.com/@mccode/using-semantic-versioning-for-docker-image-tags-dfde8be06699) states, it would be ideal if you could release semantic-versioned tags for major and minor versions. So, when pushing a new version of an image:

- Create a new patch tag. (This is already done)
- Overwrite the existing minor and major tags.
- Always update the latest tag when pushing new versions. (This is already done)
- Never overwrite patch tags. (This is already done)

In detail it means, that when you build a new **latest** tag-version for ie. version 11.0.4, you do the following steps:

```bash
$ docker build -t typo3solr/ext-solr:latest .
$ docker push typo3solr/ext-solr:latest
$ docker tag typo3solr/ext-solr:latest typo3solr/ext-solr:11
$ docker push typo3solr/ext-solr:11
$ docker tag typo3solr/ext-solr:latest typo3solr/ext-solr:11.0
$ docker push typo3solr/ext-solr:11.0
$ docker tag typo3solr/ext-solr:latest typo3solr/ext-solr 11.0.4
$ docker push typo3solr/ext-solr:11.0.4
```

As a result one can pull the image and define which version to stick to:

```bash
# pull latest and use bleeding edge version
$ docker pull typo3solr/ext-solr:latest

# pull and use latest version 11.x.y
$ docker pull typo3solr/ext-solr:11

# pull and use latest version 11.0.y
$ docker pull typo3solr/ext-solr:11.0

# pull and use specific version 11.0.4
$ docker pull typo3solr/ext-solr:11.0.4
```

Thanks,
Stephan

Btw. I really appreciate your work done so far!

**Comment by dkd-kaehm** [comment]
Nice catch.
Thanks for reporting and the hint.

**Comment by LiohMoeller** [comment]
It seems that you have applied the model already, which is great, thanks. I just noticed that the latest tag currently points to an old version. If you relate to the semantic model, it should probably point to the most recent non-dev version.

**Comment by dkd-kaehm** [comment]
> It seems that you have applied the model already, which is great, thanks. I just noticed that the latest tag currently points to an old version. If you relate to the semantic model, it should probably point to the most recent non-dev version.

There is some limitation, we can't guarantee that the latest tag is the latest if we release the previous major Version bug fixes release.
Just imaginge:
We release now the 11.1.2, then a few weeks later then the 11.0.6, then the latest will be 11.0.6 and not the 11.1.2.
Currently I do not know how to achieve that on Dockers Hub GUI.
So the trouble is our pledge of supporting two major releases at same time.
Apart from this, you should not use the latest tag in your setup to prevent you to upgrade to unsupported version, so you want to require either 11.0 or 11.1, which will match the right "latest" version of desired image. 
Please refer to https://raw.githubusercontent.com/TYPO3-Solr/ext-solr/master/Documentation/Appendix/VersionMatrix.rst

---

I'll delete all images pointing to 'latest' tag.
