### ISSUE TITLE
[TASK] Replace Dispatcher with PSR-14 based events and EventDispatcherInterface

### ISSUE THREAD

**Issue by 3l73** [TYPO3-Solr/ext-solr#2773]
Class `\TYPO3\CMS\Extbase\SignalSlot\Dispatcher` will be removed with TYPO3 12 and have to replace with PSR-14 based events and EventDispatcherInterface.

Effected classes:
- \ApacheSolrForTypo3\Solr\Domain\Index\IndexService
- \ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\Facets\OptionBased\Options\OptionsFacetParser
- \ApacheSolrForTypo3\Solr\Tests\Unit\Domain\Index\IndexServiceTest

**Comment by dkd-kaehm** [comment]
Done in 12.0.0 in #3452
