### ISSUE TITLE
[TASK] Backend: PageLayoutView is deprecated and will be removed with TYPO3 11 LTS

### ISSUE THREAD

**Issue by 3l73** [TYPO3-Solr/ext-solr#2775]
Class `\TYPO3\CMS\Backend\View\PageLayoutView` is deprecated and will be removed with TYPO3 11 LTS.

This deprecation effects following classes:
- \ApacheSolrForTypo3\Solr\Controller\Backend\PageModuleSummary
- \ApacheSolrForTypo3\Solr\Tests\Integration\Controller\Backend\PageModuleSummaryTest

The effected classes need to checkd and switched to the new fluid based layout.

## Releated ChangeLog entries

- https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Deprecation-90348-PageLayoutViewClass.html
- https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-90348-NewFluid-basedReplacementForPageLayoutView.html

**Comment by georgringer** [comment]
FYI we won't remove it in 11 because there is no benefit by removing a class used so often by extension authors

**Comment by bmack** [comment]
The class is removed in v12 branch already.
