### ISSUE TITLE
Solr doens't index content elements where caching is disabled

### ISSUE THREAD

**Issue by DomsaNN** [TYPO3-Solr/ext-solr#278]
Just figured out that solr wont index e.g. content elements / plugins with disabled caching. Is this behavior intended or a bug? I think this should be documented / fixed.

Greetings

t3 6.2.15 with ext_solr 3.0.1

**Comment by timoschmidt** [comment]
@DomsaNN 

Do you have the possiblity to test this with the latest release 3.1.1? Can you analyze this and provide a patch?

**Comment by timoschmidt** [comment]
@DomsaNN This behaviour is wanted, because you do not want to index uncachable content.
