### ISSUE TITLE
[TASK] Update to Solarium 6

### ISSUE THREAD

**Issue by dkern** [TYPO3-Solr/ext-solr#2787]
Is there any plans for Updates? The SOLR extension still uses a nearly three years old version 4.2.0 of solarium. We now have the problem that we need to downgrade multiple Symfony dependencies because of that.

**Comment by dkd-kaehm** [comment]
Yep, see https://github.com/TYPO3-Solr/ext-solr/issues/2636#issuecomment-644012518
We planing to do that within current master branch.

**Comment by dkern** [comment]
Thanks for your reply. Is there any timing or something? I saw the ticket, but it was a bit older too, and as said Solarium is even older. 😉 We actually have the problem that we can't user the Solr extension because of this. So we evaluate our options currently ...

**Comment by dkd-kaehm** [comment]
Thanks for reply.
Are you on TYPO3 10 LTS?
Do you have possibility to kick a PR with solrium 6?

**Comment by dkern** [comment]
Yes. You mean, just a PR updating the composer file to use solarium 6.x? I can do this if it helps.

**Comment by dkd-kaehm** [comment]
> Yes. You mean, just a PR updating the composer file to use solarium 6.x? I can do this if it helps.

I think that is not so easy, I mean incl. beginning of refactoring to new API.
