### ISSUE TITLE
[BUG] Language overlay for records is not retrieved since solr Version 11.x

### ISSUE THREAD

**Issue by ulrike-cosmoblonde** [TYPO3-Solr/ext-solr#2788]
Hi, 
since the solr extension update from the latest 10.x to version 11, the indexing of records does not work for translated records anymore.
I could reproduce the error for news and custom record types on 2 separate servers. Only referenced data (like categories) got indexed in the correct language, the basic records were always indexed with their default language data.
Switching the extension back to 10 fixed the issue.

I think the error is due to the changes in the ApacheSolrForTypo3\Solr\IndexQueue\Indexer class.

When I change line 243 from:
`$itemRecord = $page->getLanguageOverlay($item->getType(), $itemRecord);`
into:
`$itemRecord = $page->getRecordOverlay($item->getType(), $itemRecord, $language);`
(which was the funtion call in solr version 10) the indexing works again as expected.

If you can reproduce this problem and think this is a valid solution, can you please add this change to the next release?

Thank you!
Ulrike

Additional information: TYPO3 Version 9.5.23

**Comment by lamp-te** [comment]
I currently have a issue that might be related. I have news records in two different languages (german and english) and a different solr indexed for each language.
But all records are put in both inexes. 
When I add a snipped like
```
if($item->getRecord()["sys_language_uid"]!=$language){
  return true;
}
```
into indexItem(...) function of ApacheSolrForTypo3\Solr\IndexQueue\Indexer .
Everything works like expected.

**Comment by dkd-kaehm** [comment]
@ulrike-cosmoblonde and @lamp-te I assume you are in TYPO3 9.5 currently but anyway please provide TYPO3 Version informations.

PS: Please use the issue Template assist for future issues.

**Comment by lamp-te** [comment]
> @ulrike-cosmoblonde and @lamp-te I assume you are in TYPO3 9.5 currently but anyway please provide TYPO3 Version informations.

Yes, I am in TYPO3 9.5.23

**Comment by ulrike-cosmoblonde** [comment]
Hi,

I have now migrated my website to TYPO3 10.4.11, still using solr 11 (11.0.3) and still experiencing the issue that all english records (having sys_language_uid=1)  are indexed with the content of the default language (sys_language_uid = 0).

I have to keep my bugfix in the ApacheSolrForTypo3\Solr\IndexQueue\Indexer class.

in line 243 from:
`$itemRecord = $page->getLanguageOverlay($item->getType(), $itemRecord);`
into:
`$itemRecord = $page->getRecordOverlay($item->getType(), $itemRecord, $language);`
(which was the funtion call in solr version 10) the indexing works again as expected.

**Is nobody experiencing problems with non-default-language records in solr cores?**

Regards, Ulrike

**Comment by sneopu** [comment]
I have also a problem with records in "free-mode" translation.

I have following Records:
x (default language 0)
x1 (translated in language 1, parent is record x)
y (default language 0)
z (language 1, no parent record)

After indexing i got following items:
Core default language 0 : x, y, z
Core language 1: x1, z

Record "z" should not be indexed in the core "default language 0", all other items are correct.

TYPO3 10.4.10
Solr 11.0.3

**Comment by 3l73** [comment]
As far as I can see, there need a adjustment how to instantiate the class PageRepository in line 242 of class `\ApacheSolrForTypo3\Solr\IndexQueue\Indexer`.

For a different language a new context required for the page repository.

**Comment by 3l73** [comment]
@ulrike-cosmoblonde  @lamp-te @sneopu
Could you check if the test case described in #2841 fits your use case?

If you have any suggestion, I would add them to the description.

**Comment by lamp-te** [comment]
>@lamp-te 
> Could you check if the test case described in #2841 fits your use case?
Yes, it fits one use case. I may ad, that the bug also affects translated domain objects like news entries. I am not sure if the test covers that usecase.

**Comment by sneopu** [comment]
I have following addtion to the testcase description:

10. Add a News-Record change the language to german (exists only in german, no translation)
Title: 'Neuigkeit Deutsch'
Language: German

**Comment by 3l73** [comment]
@lamp-te Added an test case for news with translations.

@sneopu added that step to the list.

Currently the bugfix looks good, but needs more testing.

**Comment by sneopu** [comment]
I did a quick check with the ddev environment and added your bugfix manually.
In my test the only german news (step 10) is still indexed in den english solr core.

**Comment by ulrike-cosmoblonde** [comment]
I checked and it did not solve the issue for me.

I tested by replacing my Indexer.php with your Indexer.php file, creating a new record (news record in default language DE), translating that record (to EN) and running the indexer task. The new record is listed in its default language in the DE and EN listing.
Why is my suggested fix not a valid option?

Indexer.php in line 243 from:
`$itemRecord = $page->getLanguageOverlay($item->getType(), $itemRecord);`
into:
`$itemRecord = $page->getRecordOverlay($item->getType(), $itemRecord, $language);`

As this is just re-adding a lost setting?


Regards!
Ulrike

**Comment by sneopu** [comment]
> @ulrike-cosmoblonde 
> I checked and it did not solve the issue for me.

It seems to depend on the TYPO3 Version. In my test step 8 and 9 works as expected (which is your described case)
TYPO3 v10.4.10 
Solr 11.1.0-dev (8afcace302d13a59e087c17f554310b2c293a54c) + patched Classes/IndexQueue/Indexer.php

**Comment by ulrike-cosmoblonde** [comment]
> @sneopu 
> It seems to depend on the TYPO3 Version 

I assume it is more related to the language mode? I am using free mode.
Because I experience the same issue for T3 v9 and v10.

**Comment by sneopu** [comment]
@ulrike-cosmoblonde 
Sorry, seems i got it wrong, you have also tested step 10 and not 8/9
![image](https://user-images.githubusercontent.com/1940935/105504355-f4c91c00-5cc7-11eb-8bdf-5590ba38a100.png)
As i said before step 10 fails, it go also indexed in default language.

**Comment by ulrike-cosmoblonde** [comment]
@sneopu 
Actually, before I had only tested step 8/9. But I have now tested step 10 as well and I also checked a non-translated record.
For all cases, my EN and DE news lists from solr are identical - testing with todays fix [3ef2458](https://github.com/3l73/ext-solr/commit/3ef2458696f6c94e461595de86769e846d592bb1)

News in T3 Backend:
![t3_BE_news_listing](https://user-images.githubusercontent.com/30321293/105508865-2c869280-5ccd-11eb-8a3f-81747bd21ba7.PNG)

Frontend snippet listing those news via the solr plugin for both - DE and EN. They look exactly the same:
![solr_news_listing_EN_and_DE](https://user-images.githubusercontent.com/30321293/105509005-56d85000-5ccd-11eb-82b5-e16e5fef19ce.PNG)

**Comment by 3l73** [comment]
@ulrike-cosmoblonde In the first implementation I did not check for the language mode wenn i try it.

@sneopu Which language mode are you using.

**Comment by 3l73** [comment]
Currently the extension supports translations with content fallback mode.

This leads to the issue that the news (step 10) is stored within the index queue. From the perspective that this item need to be indexed it fits. On the other hand from the fallback mode perspective that's an issue.

Currently the items inside the item queue means to be connected to the default language, what is not the case in step 10.

We need a full implementation of the free mode to solve this issue completly.

How ever, I added a small change to solve this issue for this special case.

@sneopu @ulrike-cosmoblonde  Please test the latest version of the pull request.

**Comment by sneopu** [comment]
@3l73 
The customer with this problem use `fallbackType: strict` and `fallbacks: ''` for the translated records.
But the behaviour is the same in the solr-ddev-site installation which use  `fallbackType: fallback` and `fallbacks: '0'`

The latest version works for me as expected, after I changed the fieldname in the temporary bugfix from `sys_language_id` to `sys_language_uid`

**Comment by sneopu** [comment]
The fix maybe should be like this, otherwise records with "all languages (-1)" dont get indexed.
`if ((int)$itemRecord['sys_language_uid'] > 0 && (int)$itemRecord['sys_language_uid'] !== $language) {`

**Comment by 3l73** [comment]
@sneopu Thank you for the hint of the wrong language field. Now the field from the TCA configuration is used.

If no language is configured, the behaviour is deactivated.

Could you check the fix again?

**Comment by sneopu** [comment]
@3l73 
This fix works for me like expected. Thanks for your effort.

**Comment by JBlocks** [comment]
+1 , please bring the fix into the solr core. :-)

**Comment by jproy418** [comment]
+1, We have the same issue in Typo3 10.4 and Solr 11. It would be great to have the fix merged into the core. 
Thanks!
