### ISSUE TITLE
[BUG] Filtering remove all in column

### ISSUE THREAD

**Issue by UNI49** [TYPO3-Solr/ext-solr#2792]
**Describe the bug**
When we filtered the item with Solr facets, all the other contents (text, media…) are remove on the Solr's result column

**To Reproduce**
1. Add Solr to a page
2. Add another content, on same column as Solr
3. Go front and filter result
4. See that only Solr result are present

**Expected behavior**
Don't remove all other content in the column

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.22
 - Browser: Firefox + Chrome
 - EXT:solr Version: 11.0.3
 - Used Apache Solr Version: 7.6.0
 - PHP Version: 7.2.12

**Comment by dkd-kaehm** [comment]
Hello @UNI49,
thanks for reporting this issue.
I didn't get you. Could you please provide some Screenshots?

**Comment by UNI49** [comment]
When I load the page : ![Screen Shot 2020-11-16 at 09 01 19](https://user-images.githubusercontent.com/58041122/99226894-d12ab680-27ea-11eb-8c85-5b4e0594360f.png)


After activate a filter : ![Screen Shot 2020-11-16 at 09 01 10](https://user-images.githubusercontent.com/58041122/99226774-9b85cd80-27ea-11eb-814a-6849ec26737d.png)

It lacks the "Carrousel" before Solr results and text after Solr results.
Hope it's clearer now

**Comment by dkd-kaehm** [comment]
It seems the page is ajaxified and replaces tho whole "content" div container.
Please check this supposition.

**Comment by UNI49** [comment]
I've checked, and it's the same for both of them… So it's not because of Ajax…

**Comment by UNI49** [comment]
Problem solved, because of modified overide JS
