### ISSUE TITLE
[BUG] Sites with no Solr Configuration should not be considered

### ISSUE THREAD

**Issue by achimfritz** [TYPO3-Solr/ext-solr#2795]
**Describe the bug**

* sites with solr disabled (`solr_enabled_read: false`) are also returned from `SiteRepository->getAvailableSites()` but should not considered. 

This ends in:
* They are listed on the Solr Scheduler Tasks as option for Site. (makes no sence)
* EXT:solrfal insert a record for each site returned from this Method into the `tx_solr_indexqueue_file` table, when edit a file. This leads to errors in Queue, when try to index them

**To Reproduce Scheduler Bug**
1. create two sites, one with `solr_enabled_read: false`, other with valid Solr-Configuration
2. go to Scheduler Module
3. select task "Index Queue Worker"
4. both Sites are listed in the "Site" Select-Box

**Expected behavior**
the disabled site should not appear

**To Reproduce EXT:solrfal Bug**
1. create two sites, one with `solr_enabled_read: false`, other with valid Solr-Configuration
2. configure EXT:solrfal to index sys_files
2. edit a sys_file record
3. create and run solrfal Scheduler Task
5. task stays on 50% with "Errors: 1"

**Expected behavior**
task stays on 100% with "Errors: 0"

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4
 - EXT:solr Version: dev-master

**Comment by dkd-kaehm** [comment]
@achimfritz Thanks for reporting and fixing this issue.
