### ISSUE TITLE
[BUG] garbage collector with translations

### ISSUE THREAD

**Issue by achimfritz** [TYPO3-Solr/ext-solr#2797]
**Describe the bug**

delete a translated page, (or set it to hidden), deletes solr-documents in all languages and delete index queue item

**To Reproduce**
1. Solr-Configuration with two languages and two cores
2. page with translation
3. page-document indexed in both cores
4. set translation to hidden
5. index queue item is deleted
6. page-document is deleted in both cores

**Expected behavior**

* should not remove IndexQueue Item
* should not remove Pages of other languages

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4
 - EXT:solr Version: dev-master

**Comment by dkd-kaehm** [comment]
Backports in 10 and 11 must be created.

**Comment by dkd-kaehm** [comment]
PR incl. backports onto 10 and 11 is merged.
