### ISSUE TITLE
[TASK] Option to prevent using default proxy settings for page indexing

### ISSUE THREAD

**Issue by dkoether** [TYPO3-Solr/ext-solr#2805]
Hello everyone,

EXT:solr is using the TYPO3 RequestFactory for Page Indexing in the PageIndexerRequest (line 411). By using the RequestFactory the configured proxy settings in $GLOBALS['TYPO3_CONF_VARS']['HTTP']['proxy'] are used to. What is fine for some project is a problem for others. When TYPO3 is trying to crawl pages of itself it should go the shortest internal possible way but by using the RequestFactory this is not given when a proxy is configured.

What do you think about this?

Thanks in advance and keep up the good work!

**Comment by dkd-kaehm** [comment]
Hi,
did you seen https://github.com/TYPO3-Solr/ext-solr/issues/2155#issuecomment-439332925?
May be it can help? 

@dkoether please connect your thoughts and ideas with @jackd248 and may be draw up the short solution to our FAQ file in the docs: https://github.com/TYPO3-Solr/ext-solr/blob/master/Documentation/FAQ/Index.rst

**Comment by dkd-kaehm** [comment]
@dkoether May be not documented feature `plugin.tx_solr.index.queue.pages.indexer.frontendDataHelper.headers` could be useful for that #2807

**Comment by dkoether** [comment]
@dkd-kaehm the following line is doing it! 👍 Thank you for your hint.

`plugin.tx_solr.index.queue.pages.indexer.frontendDataHelper.headers.proxy = proxy:`

This overwrites the proxy settings in the options array with an empty string. I wanted to set boolean or null but unfortunately it seems that it is only possible to use a string.
