### ISSUE TITLE
Solr indexes workspace records in TYPO3 10.4

### ISSUE THREAD

**Issue by bfzgaier** [TYPO3-Solr/ext-solr#2847]
Before workspace records were place on pid -1. With 10.4 this behaviour changed.

Now workspace records are placed on the corresponding page. Solr still uses `pid != 1` to filter workspace records

https://github.com/TYPO3-Solr/ext-solr/blob/b6ff0f2314bccf20658688baa04ea3c33e7a5ba4/Classes/IndexQueue/Initializer/AbstractInitializer.php#L304

On possible solution is, to instead check for the workspace id of a record.
```php
$conditions['versioningWS'] = 't3ver_wsid = 0'; 
```
The same approach is used in `TYPO3\CMS\Core\Database\Query\Restriction\WorkspaceRestriction`

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Important-89555-Workspace-relatedDatabaseRecordsContainTheProperPageID.html

**Comment by dkd-kaehm** [comment]
@bfzgaier 
Thanks for reporting. We'll fix it in release-11.0.x and master.
