### ISSUE TITLE
[BUG] Can't create synonyms

### ISSUE THREAD

**Issue by mschwemer** [TYPO3-Solr/ext-solr#2851]
It is not possible to create synonyms via the backend. 

**How to reproduce**

1) Goto to Apache Solr => Core Optimization
2) Fill in both fields & click on "Add synonym"
3) the success flash message is shown
4) in the list of synonyms the recently added synonym is missing

**Expected behavior**

The synonym is added successfully.

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.12
 - Browser: independet
 - EXT:solr Version: 11.0.3
 - Used Apache Solr Version: 8.5
 - PHP Version: 7.4
- Solarium Client: 4.2.0 / 5.2.0

**Reason**

The underlying reason is the version of the solarium php client. If using a post request, the guzzle adapter "deletes" the content of the request body. 

see: /vendor/solarium/solarium/src/Core/Client/Adapter/Guzzle.php Line 113

The logs of the solr container then show the following message

`null:org.restlet.resource.ResourceException: Bad Request (400) - Empty request body!`

BTW: adding synonyms via the cli with post method works fine: 

`curl -X POST -H 'Content-type:application/json' --data-binary '{"mad":["angry","upset"]}' "http://<myserver>:<myport>/solr/core_de/schema/analysis/synonyms/german" `

**Solution**

Use the method "PUT" for the transfer of synonyms

I will come a with a PR in the next days.

**Outlook**

The guzzle-adapter is not available any more in solarium version 6 and master. The adapter handling changed completly.

**Comment by dkd-kaehm** [comment]
@mschwemer 
I can't reproduce the issue. 
Some context is missing on my own?
Just tested in our solr-ddev-site env with dev-master, release-11.0.x and 11.0.3 tag.

Please make sure the apache Solr Server hass write permissions to the json files.

**Comment by dkd-kaehm** [comment]
Moreover the tests are green for `\ApacheSolrForTypo3\Solr\Tests\Integration\System\Solr\Service\SolrAdminServiceTest::canAddSynonym`.

**Comment by mschwemer** [comment]
Write permissions are available on the solr server. 

The manually (via curl) added synonyms show up in the backend. 

Which solarium client are you using?

**Comment by dkd-kaehm** [comment]
> Which solarium client are you using?

All standard things required by EXT:Solr, checkout the https://github.com/TYPO3-Solr/solr-ddev-site

**Comment by mschwemer** [comment]
Hi, 
here is the screenshot after "creating" a synonym.

![solr_add-synonym_2021-01-29_15-52](https://user-images.githubusercontent.com/103594/106289910-1dae5b80-624a-11eb-8c08-5831ffd0a63d.png)

Furthermore .. I rebuild the container based on your ddev setup. The synonym are as in the default configuration, without any custom characters. 

The solr container seems to be fine, because I am able to put synonyms via a plain curl request coming from the TYPO3 hosting server.  

Permissions: 
```
# ls -al  _schema_analysis_synonyms_german.json 
-rw-rw-rw- 1 solr solr 93 Oct 26 13:04 _schema_analysis_synonyms_german.json
```

Content of the file:
```
cat  _schema_analysis_synonyms_german.json 
{"initArgs":{"ignoreCase":false},"initializedOn":"2020-04-22T13:10:36.456Z","managedMap":{}}
```

**Comment by dkd-kaehm** [comment]
@mschwemer 
Strange behavior, could you check the TYPO3 configs for Guzzle/Browser(Please refer to the TYPO3 docs)?

**Comment by mschwemer** [comment]
@dkd-kaehm 

I think, I found the issue. 

The difference between the instances is that my local instance and ddev have php-curl available, the testing instance not.

I asked to install php-curl and will see, whether it will work afterwards. 

I'll keep you updated.

**Comment by rintisch** [comment]
@mschwemer I had a similar problem with a falsy setup. Do you have a docker setup? 
If that's the case, you might want to have a look at https://github.com/drud/ddev-contrib/issues/113 (all explanaintions in the slack thread)

**Comment by mschwemer** [comment]
Finally solved the issue. :-)

Reason was the missing curl module in php. After installing it, synonyms are working as expected.
