### ISSUE TITLE
[BUG] ConnectionManager::getConnectionByRootPageId() alters TYPO3 Context

### ISSUE THREAD

**Issue by robert-heinig** [TYPO3-Solr/ext-solr#2861]
**Describe the bug / To Reproduce**
I'm using the ConnectionManager to fetch a connection to Solr by root page ID and language ID within a custom controller.
The language ID is provided by the language aspect of the TYPO3 context and is correct when fetching the connection.
Directly after fetching the connection the language ID if the language aspect of the TYPO3 context is always 0, no matter which language ID was used to fetch the connection with.

**Expected behavior**
The language aspect of the TYPO3 context does not change when using ConnectionManager::getConnectionByRootPageId().

**Analysis**
I've debugged the problem, but I'm not sure how to solve it correctly.
Several method calls within ConnectionManager::getConnectionByRootPageId() the method FrontendEnvironment::changeLanguageContext() is called which changes the context. The language ID provided with ConnectionManager::getConnectionByRootPageId() is not passed through to this method. To achieve this several methods would have to be changed - and I'm not sure about the implications when these methods are used elsewhere.
For my usecase I was able to solve the problem with a composer patch that changes the call of FrontendEnvironment::getSolrConfigurationFromPageId() within SiteRepository::buildTypo3ManagedSite() to include the current language ID provided by the context.

**Conceptual ideas**
1. The feature that FrontendEnvironment::changeLanguageContext() provides should be implemented with a "switch back mode" to ensure that the context will only be changed temporarily.
2. My patch file solution only works because the connection uses the language of the current context, but it should work correctly with every language independently of the current context. So the language ID of ConnectionManager::getConnectionByRootPageId() should be passed to every method where the language is used.

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.12
 - EXT:solr Version: 11.0.3

**Comment by infabo** [comment]
yeah, can confirm.

**Comment by infabo** [comment]
Basically all starts at `AbstractBaseController->initializeSearch`

https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/Controller/AbstractBaseController.php#L224

`getConnectionByPageId` is the root ov all evil, bcause it calls `$this->siteRepository->getSiteByPageId($pageId, $mount)`.

On the long way down the stack, it finally lands at: `Tsfe->changeLanguageContext()`. There it - for whatever reason - overrides the current language aspect with a new one. I would at least call it hacky. Maybe even dirty. Manipulating/Altering the current LanguageAspect is for me like messing around with TYPO3 INTERNAL APIs. That's a nogo IMHO.

**Comment by dkd-kaehm** [comment]
> Basically all starts at `AbstractBaseController->initializeSearch`
> 
> https://github.com/TYPO3-Solr/ext-solr/blob/e674df2b4f2b9792d3cc117f7b996ee73a48eaaa/Classes/Controller/AbstractBaseController.php#L224
> 
> `getConnectionByPageId` is the root ov all evil, bcause it calls `$this->siteRepository->getSiteByPageId($pageId, $mount)`.
> 
> On the long way down the stack, it finally lands at: `Tsfe->changeLanguageContext()`. There it - for whatever reason I actually do not want to understand - overrides the current language aspect with a new one. I would at least call it hacky. Maybe even dirty. Manipulating/Altering the current LanguageAspect is for me like messing around with TYPO3 INTERNAL APIs. That's a nogo IMHO. However: I see no reason to do that anyway. It starts with `I lookup to the SOLR connection from current site-language config`. It ends with: `Yeah, love messing around with the whole FE-environment. Bootstrapping some pseudo-env and stuff.`

The code is reused on search and on indexing contexts. On indexing each translation is indexed in same process, therefore the context switches. 
@infabo did you observed the both stacks(the searching and indexing) on your analysis?

@robe

**Comment by dkd-kaehm** [comment]
> Basically all starts at `AbstractBaseController->initializeSearch`
> 
> https://github.com/TYPO3-Solr/ext-solr/blob/e674df2b4f2b9792d3cc117f7b996ee73a48eaaa/Classes/Controller/AbstractBaseController.php#L224
> 
> `getConnectionByPageId` is the root ov all evil, bcause it calls `$this->siteRepository->getSiteByPageId($pageId, $mount)`.
> 
> On the long way down the stack, it finally lands at: `Tsfe->changeLanguageContext()`. There it - for whatever reason I actually do not want to understand - overrides the current language aspect with a new one. I would at least call it hacky. Maybe even dirty. Manipulating/Altering the current LanguageAspect is for me like messing around with TYPO3 INTERNAL APIs. That's a nogo IMHO. However: I see no reason to do that anyway. It starts with `I lookup to the SOLR connection from current site-language config`. It ends with: `Yeah, love messing around with the whole FE-environment. Bootstrapping some pseudo-env and stuff.`

The code is reused on search and on indexing contexts. On indexing each translation is indexed in same process, therefore the context switches. 
@infabo did you observed the both stacks(the searching and indexing) on your analysis?

@robert-heinig
> The language aspect of the TYPO3 context does not change when using ConnectionManager::getConnectionByRootPageId().

The switches or looking in other languages was never considered as design of EXT:solr.

If you want to do something in different languages on searching/frontend context, you can implement some other logic for that.

Please create a new feature issue and describe the purposes of cross-language usage of Solr connections on searching/frontend context.
