### ISSUE TITLE
[BUG] content of indexed custom field placed inside queryFields is not searched

### ISSUE THREAD

**Issue by abohntek** [TYPO3-Solr/ext-solr#2863]
I use the preAddModifyDocuments Hook to set additional custom fields to the solr documents via $document->__set method from the class Solarium\QueryType\Update\Query\Document. Those fields are indexed correctly and I can use them inside the search results and display there content, but I can´t search for the content of those custom fields. I added them inside the queryFields array as well with: 

`plugin.tx_solr.search.query.queryFields = titleExact^7.0, title^7.0, abstract^6.0, content^5.0, tagsH1^4.0, description^4.0, tagsH2H3^3.0, keywords^2.0, tagsH4H5H6^2.0, tagsInline^1.0, abstract^1.0, subtitle^1.0, navtitle^1.0, author^1.0, customA_stringS^1.0, customB_stringS^1.0 `

I am something missing? I didnt reindex it after adding the fields to the queryFields Array but I dont thing it should be necessary, right? I just cleared the BE and FE Caches.

I am also using another custom Field as sorting option, added same way and for the sorting logic the custom field is used.

**Used versions:**
 - TYPO3 Version: 9.5.24
 - EXT:solr Version: 10.0.2

**Comment by dkd-kaehm** [comment]
Please make sure those fields are in Solr documents indexed properly, via EXT:Solr Info module.
We have tests for queryFields, which are green.

**Comment by abohntek** [comment]
They are indexed properly as described in my issue, I checked it via the info module...

**Comment by dkd-kaehm** [comment]
@abohntek 
Please ask in TYPO3 Slack #ext-solr channel.
Thats definitely not a bug.
