### ISSUE TITLE
[BUG] Force Re-Index Task not working?

### ISSUE THREAD

**Issue by timoschmidt** [TYPO3-Solr/ext-solr#288]
Check if force Re-Index Task ist working?

- Add integration test for it.

**Comment by dkd-friedrich** [comment]
Force Re-Indexing task is currently failing 

`Execution of task "Force Re-Indexing of a site (solr)" failed with the following message: PHP Catchable Fatal Error: Argument 1 passed to ApacheSolrForTypo3\Solr\IndexQueue\Queue::getTableToIndexByIndexingConfigurationName() must be of the type array, object given, called in ../solr/Classes/Task/ReIndexTask.php on line 99 and defined in ../solr/Classes/IndexQueue/Queue.php line 202`
