### ISSUE TITLE
[BUG] RecordMonitor has bug for records updating hidden-flag

### ISSUE THREAD

**Issue by typoworx-de** [TYPO3-Solr/ext-solr#2882]
**Describe the bug**
I noticed this bug updating records "hidden" state. The Index-Queue will not be updated as expected. The RecordMonitor reacts to the FieldArray, but the recordMonitor will completly fetch the actual record-state from Database and completly ignores the state given by $fields-array argument.

Then the tcaService->isEnabledRecord($recordTable, $record) method will result in a faulty result. Whereas the Hooks will handle the "current" state giving f.e. "hidden = 1", the current record still has "hidden = 0". The result is, that RecordMonitor::processCmdmap_preProcess() will delete the record from index, but processCmdmap_postProcess() will re-enable the record as the changes ($fields-array) is not yet persisted to database.

**To Reproduce**
1. Edit any record monitored & indexed by SOLR . The record should be already indexed before.
2. Click on "disable" record in Backend & Save the record.
3. Check database table 'tx_solr_indexqueue_item' for the given record item_type and item_uid. 
4. You should notice that the record re-appears for indexing.

**Expected behavior**
The record should be removed from indexing (which works) and should not be re-added afterwards.

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.22
 - EXT:solr Version: 11.0.3
 - Used Apache Solr Version: 8.6.2
 - PHP Version: 7.2

This is now I patched the RecordMonitor::processRecord method:

All I've done is adding array_merge right after fetching the record
```
        $record = $this->configurationAwareRecordService->getRecord($recordTable, $recordUid, $solrConfiguration);
        $record = array_merge($record, $fields);
```

Patch for \ApacheSolrForTypo3\Solr\IndexQueue\RecordMonitor
```
    /**
     * Bugfix in original Method ignoring changed enable-fields
     *
     * Process the record located in processDatamap_afterDatabaseOperations
     *
     * @param string $recordTable The table the record belongs to
     * @param int $recordPageId pageid
     * @param mixed $recordUid The record's uid, [integer] or [string] (like 'NEW...')
     * @param array $fields The record's data
     */
    protected function processRecord($recordTable, $recordPageId, $recordUid, $fields)
    {
        $configurationPageId = $this->getConfigurationPageId($recordTable, $recordPageId, $recordUid);

        if ($configurationPageId === 0)
        {
            // when the monitored record doesn't belong to a solr configured root-page and no alternative
            // siteroot can be found this is not a relevant record
            return;
        }

        $solrConfiguration = $this->getSolrConfigurationFromPageId($configurationPageId);
        $isMonitoredRecord = $solrConfiguration->getIndexQueueIsMonitoredTable($recordTable);

        if (!$isMonitoredRecord)
        {
            // when it is a non monitored record, we can skip it.
            return;
        }

        $record = $this->configurationAwareRecordService->getRecord($recordTable, $recordUid, $solrConfiguration);
        $record = array_merge($record, $fields);

        if (empty($record))
        {
            // TODO move this part to the garbage collector
            // check if the item should be removed from the index because it no longer matches the conditions
            $this->removeFromIndexAndQueueWhenItemInQueue($recordTable, $recordUid);
            return;
        }

        // Clear existing index queue items to prevent mount point duplicates.
        // This needs to be done before the overlay handling, because handling an overlay record should
        // not trigger a deletion.
        $isTranslation = !empty($record['sys_language_uid']) && $record['sys_language_uid'] !== 0;
        if ($recordTable === 'pages' && !$isTranslation)
        {
            $this->indexQueue->deleteItem('pages', $recordUid);
        }

        // only update/insert the item if we actually found a record
        $isLocalizedRecord = $this->tcaService->isLocalizedRecord($recordTable, $record);
        $recordUid = $this->tcaService->getTranslationOriginalUidIfTranslated($recordTable, $record, $recordUid);

        if ($isLocalizedRecord && !$this->getIsTranslationParentRecordEnabled($recordTable, $recordUid))
        {
            // we have a localized record without a visible parent record. Nothing to do.
            return;
        }

        if ($this->tcaService->isEnabledRecord($recordTable, $record))
        {
            $this->indexQueue->updateItem($recordTable, $recordUid);
        }

        if ($recordTable === 'pages')
        {
            $this->doPagesPostUpdateOperations($fields, $recordUid);
        }
    }
```

**Comment by dkd-kaehm** [comment]
@typoworx-de Thanks for reporting,
we'll check this. 
Feel free to update this issue with news.

**Comment by 3l73** [comment]
@typoworx-de Doing the steps as you describe, I wasn't able to reproduce this problem yet.

May be you can check this test setup.

This test uses the Solr development environment: https://github.com/TYPO3-Solr/solr-ddev-site

1. Enable/install Solr
  - With solr-ddev-site 11 (master): `ddev composer req georgringer/news`
  - With solr-ddev-site 10: replace this step with `ddev enable-news`
2. Include the indexer configuration from `@import 'EXT:solr/Configuration/TypoScript/Examples/IndexQueueNews/setup.typoscript'` into `EXT:apache_solr_for_typo3_sitepackage/Configuration/TypoScript/Extensions/solr/setup.typoscript` 
  - With solr-ddev-site 10 add it directly to setup within the sys template
3. Create a sample data of News within folder `Shared Content`
  - With solr-ddev-site 10 replace this step with `ddev enable-news`
4. Initialize indexer for news
5. Check news within table `tx_solr_indexqueue_item` ... should be there
6. Disable sample news
7. Check news within table `tx_solr_indexqueue_item` ... should not be there

In this scenario the item disappear from the table `tx_solr_indexqueue_item`.

I checked it with TYPO3 10 LTS, as well with TYPO3 9.5.
  - Ext:solr Master (https://github.com/TYPO3-Solr/ext-solr/commit/5c27dd792fd2435377532680571587dc42f6dfca)
  - Ext:solr 11.0.3 (https://github.com/TYPO3-Solr/ext-solr/commit/72e46df4c4a99f8cf3fdd7d9e5b89e9b9b044ca6)

**Comment by dkd-kaehm** [comment]
@typoworx-de We could not reproduce that, 
are we missing something here?

---

Will close that Issue after lack of response for 28 days.

**Comment by dkd-kaehm** [comment]
Closing because of lack of response.
