### ISSUE TITLE
Content-length mismatch when using javascriptFiles loadIn footer

### ISSUE THREAD

**Issue by Rejaku** [TYPO3-Solr/ext-solr#29]
At the time of the Content-length header processing @ typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php:3905, the Javascript files added by solr are not within $this->content.

They are added after the fact, resulting in cut-off content with all clients respecting the Content-length header.

**Comment by dkd-dobberkau** [comment]
Is this really a ext:solr issue?

**Comment by Rejaku** [comment]
You could aruge that it is a core problem as hook_eofe is called after processOutput which determines the content-length.

**Comment by kuehnberger** [comment]
> ext:solr issue
Yes it is, as without  ext:solr  the T3core Content-length header is working OK.

**Comment by dkd-dobberkau** [comment]
Can you pinpoint me to the place in the code of ext:sor where this is happening?

**Comment by Rejaku** [comment]
In ext/solr/Classes/JavascriptManager.php::registerForEndOfFrontendHook Tx_Solr_JavascriptManager->addJavascriptToPageFooter gets added to 2 hooks.

The first one, contentPostProc-cached, poses no problem, as that gets called before typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php::processOutput.

It is the second hook, hook_eofe, which gets executed at a time in the flow where modifying the content is no longer possible without error.

Looking through the the TYPO3 core code, the right hook to replace hook_eofe with would be contentPostProc-output in my opinion. That hook gets called directly within TypoScriptFrontendController.php::processOutput.

**Comment by dkd-dobberkau** [comment]
@irnnr what do you think of this?

**Comment by kuehnberger** [comment]
Suggestion: use TS for "... gets included at the bottom of the page (just before the closing body tag)."
see:
http://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Page/Index.html#includejsfooter-array

**Comment by Rejaku** [comment]
On that note, instead of using a str_replace to add the JS to the footer, why not use $GLOBALS['TSFE']->getPageRenderer()->addJsFooterFile() ?

**Comment by irnnr** [comment]
might not have been available back then

**Comment by Rejaku** [comment]
Understandable, but as 4.5 support will be outphased anyway there shouldn't be an issue with making use of that function.

**Comment by irnnr** [comment]
Fixed
