### ISSUE TITLE
[BUG] Incomplete icon rendering for queues

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Solr/ext-solr#2900]
The screenshot shows it best

![image](https://user-images.githubusercontent.com/1905663/111633089-6bc8ef80-87f5-11eb-8b2e-5eaefd942c06.png)

Problem is that the current code does not respect icons configured via 
```php
        'typeicon_classes' => [
            'default' => 'ext-plainfaq-faq'
        ],
 ```

**Comment by dkd-kaehm** [comment]
@georgringer 
Thanks for contributing.
I'll merge this fix in 
* master
* release-11.0.x
* release-10.0.x
