### ISSUE TITLE
Question about new folders filestore, userfiles in actual used solr 8.8

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Solr/ext-solr#2911]
The actual solr server creates the folders `{filestore,userfiles}` in the "$SOLRHOME" under `/var/solr/data`:

![image](https://user-images.githubusercontent.com/2861556/113382475-cf205900-9381-11eb-9e22-7b3cd7a15322.png)

Is this something we can safely can ignore (in development context via .gitignore for example) and exclude from backups on productive solr environments? I didn't found any real documentation about the two folders in the solr reference for 8.8.

Maybe someone of you has already checked it?

**Comment by dkd-friedrich** [comment]
Directories are related to the PackageStoreAPI and the SolrResourceLoader, the constant overviews shows the settings and default values:
* https://solr.apache.org/docs/8_8_1/solr-core/constant-values.html#org.apache.solr.filestore.PackageStoreAPI.PACKAGESTORE_DIRECTORY
* https://solr.apache.org/docs/8_8_1/solr-core/constant-values.html#org.apache.solr.core.SolrResourceLoader.USER_FILES_DIRECTORY

By default the directories are not used by EXT:solr and can be ignored.

@josefglatz I'm closing this issue for now, if there are further questions or problems, feel free to reopen it.
