### ISSUE TITLE
[BUG] Hidden Default Language Page with PageContentErrorHandler throws Exceptions

### ISSUE THREAD

**Issue by achimfritz** [TYPO3-Solr/ext-solr#2914]
**Describe the bug**
Status Report throws Exception if root-page.l18n_cfg=1 and SiteConfiguration has PageContentErrorHandler configured

```
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=<id>'
```
This is due initializeTsfe builds an fake Request-Object without an url (but the url is accessed in the PageContentErrorHandler resolveUrl-Method

**To Reproduce**
1. set "Hide default language of page [0]" to 1 on your root-page
2. Go to Report Module
3. Click "Status Report"
4. an Exception is thrown: "Call to a member function getUserInfo() on null"

**Expected behavior**
Exception should not be thrown

**Screenshots**
![image](https://user-images.githubusercontent.com/2152991/113979703-df36ad80-9845-11eb-8a04-227d351451b0.png)

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.14
 - Browser:  ff
 - EXT:solr Version: 11.0.3, dev-master
 - Used Apache Solr Version: 8.2.0
 - PHP Version: 7.3.27
 - MySQL Version: 5.7.33

**Additional context**
Same Exception occures on FAL-File-Indexing (with EXT:solrfal), having pages with l18n_cfg=1 set.

**Comment by dkd-kaehm** [comment]
Leave it open until backports are merged.
