### ISSUE TITLE
[BUG] Faked TSFE does not set applicationType in request

### ISSUE THREAD

**Issue by sascha-egerer** [TYPO3-Solr/ext-solr#2932]
**Describe the bug**
When initializing the TSFE a TYPO3_REQUEST is also initialized.
A request must always have a applicationType attribute.
If no applicationType is given `ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])`
can't bee used and throws an exception.

**To Reproduce**
Call `ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])` on the 
`$GLOBALS['TYPO3_REQUEST']` that is initialized in
`Classes/FrontendEnvironment/Tsfe.php`

This happens for example in https://github.com/networkteam/sentry_client/blob/master/Classes/Client.php#L78

**Expected behavior**
A valid TYPO3_REQUEST should be initialized

**Screenshots**

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.16
 - EXT:solr Version: 11.0.3

**Comment by dkd-kaehm** [comment]
@sascha-egerer 
Thanks for fixing that issue, we want a back port on release-11.0.x.
