### ISSUE TITLE
[TASK] Limit table key column length

### ISSUE THREAD

**Issue by Mabahe** [TYPO3-Solr/ext-solr#2969]
Since v10 utf8mb4 is recommended but some key columns on table tx_solr_indexqueue_item are too long. Fix:
`KEY item_id (item_type(191),item_uid),`
`KEY pages_mountpoint (item_type(191),item_uid,has_indexing_properties,pages_mountidentifier(191))`

**Comment by dkd-friedrich** [comment]
Done with #3014
