### ISSUE TITLE
[FEATURE] Danish language analysis

### ISSUE THREAD

**Issue by leslawp** [TYPO3-Solr/ext-solr#2974]
Some time ago a Danish customer asked me to add more language features / analysis in relation to Danish language (actually it was a Drupal project). I thought I can prepare version for Typo3 so here just want to discuss it, before I will finalise this feature and do a pull request.

1. Compound words.
I was able to find and adjust list of Danish compounds list. I adjusted it to Solr format and added it to index part of filters in schema.xml for text fields. In a similar way as we have already German common nouns. We shouldn't add this to query analysers as it will make results quite noisy.
Here goes the list [danish_compounds.txt](https://github.com/TYPO3-Solr/ext-solr/files/6740151/danish_compounds.txt)

How it can help? For example document with word "projektudvikling" can be found when searched using "projekt" or "udvikling".

2. Normalisation and folding
Solr/lucene has 2 other nice filters that can be helpful for searching trough Danish texts. Namely ScandinavianNormalizationFilterFactory and ScandinavianFoldingFilterFactory. This can be added to both index and query analysers.
See how different versions of word blåbærsyltetøj (bluebarry jam) are converted to blabarsyltetoj when stored in index and matched when searched:
[scandinavian_folding_and_normalisation](https://user-images.githubusercontent.com/11993116/123946331-61df8c80-d99f-11eb-9d21-c82c5ad53b82.png)

What you think about it, do you have any ideas or concerns? Danish speaking people are especially welcome! :)

Target versions
11.x and 10.x

**Comment by leslawp** [comment]
I just realised that normalisation filter should be applied at the beginning of analysis, and folding filter at the end.
Scandinavian normalisation filter is turning aa, ae and oe (common replacements for diacritics) into å, æ and ø. Then DictionaryCompoundWordTokenFilter and SnowballPorterFilterFactory should be used as it uses diacritics (å, æ and ø). Then tokens can be again "folded" to simplest version (as å, æ is turned into a and ø into o).

More details here: https://solr.apache.org/guide/7_6/language-analysis.html#scandinavian

**Comment by dkd-friedrich** [comment]
Hi @leslawp 

> 1. Compound words

Currently we do not use the Dictionary Compound Word Token Filter for Danish, I think this could be useful, but I don't speak Danish and can not evaluate this in detail. We are open to any suggestions for improvement, a pull request would be optimal.

> 2. Normalisation and folding

We have recently integrated Scandinavian Normalization Filter and Scandinavian Folding Filter as part of #2270. Since, as mentioned, we do not speak Danish, we are of course thankful for any hints on problems with the new integration.

**Comment by dkd-kaehm** [comment]
@leslawp 
Please create a pull request for point 1. asap to become this feature in Release 11.1.

To be able to use the words with "Danish umlauts"(Scandinavian characters æÆäÄöÖøØ) in `danish-common-nouns.txt`(please use this file name) file, like on german core.
Please put the `DictionaryCompoundWordTokenFilterFactory` with `danish-common-nouns.txt` directly after FlattenGraphFilterFactory
https://github.com/TYPO3-Solr/ext-solr/blob/45d20bd258a191bbcb2e476147c6c73bc1c18df3/Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/danish/schema.xml#L60-L67
like it is done for german core on different places:
https://github.com/TYPO3-Solr/ext-solr/blob/d74d290f704cf9b98d21476ff74be89537a1d827/Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/german/schema.xml#L63-L71

---

As @dkd-friedrich said the point 2. already done in https://github.com/TYPO3-Solr/ext-solr/commit/45d20bd258a191bbcb2e476147c6c73bc1c18df3#diff-c8031bfc7b7c2ca1d35203777146194c0250de0fc8e5d19910cc54ff802b76beR60, it is not needed to be handled in this issue.

**Comment by leslawp** [comment]
Thank you Markus (@dkd-friedrich) and Rafael (@dkd-kaehm) for quick response and details!
So yes, I added only point 1 to my PR. Regarding point 2 I was so focused on version 11.0 that I didn't noticed it is already in version 11.1. But anyway is see it's quite fresh thing.

My only concern is that normalisation and folding is applied also for type "textExact" that should be less processed, but it's discutable. I was not adding this new filter to this type to preserve this "exactness" :) The same may be related to German schema.

So I'm not expert in Danish too, but I'm tryng to ask some Danish Solr users to say more. It was tested for a big Danish online shop and it was working quite well.
