### ISSUE TITLE
[BUG] Configuring tx_solr[q] as speaking URL part crashes faceting

### ISSUE THREAD

**Issue by calien666** [TYPO3-Solr/ext-solr#2984]
Our customer wanted to have the search param as part of the uri speaking. After introducing the faceting didn't work and produced bad link requests.

Configure a page with a Route enhancement for search query:
```yaml
  Search:
    type: Plugin
    namespace: tx_solr
    routePath: '/{q}'
    limitToPages: [{your search page}]
    defaults:
      q: ''
    requirements:
      q: '^.*$'
```
Search is now callable like
```
https://example.com/search/my%20Search%20word
```
With active faceting the generated links for toggling will look like this:

```
https://example.com/search/%23%23%23tx_solr:q%23%23%23/?tx_solr%5Bfilter%5D%5B0%5D=keywords%3AWaste+plastics
```
As you see, the building structure and replacement of the placeholders could not work, because of url encoding the # to %23.

**Expected behavior**
Clean search URLs with speaking parameters like:

```
https://example.com/search/recycling/?tx_solr%5Bfilter%5D%5B0%5D=keywords%3AWaste+plastics
```

**Used versions:**
 - TYPO3 Version: 9.5.27
 - Browser: All browsers, server side problem
 - EXT:solr Version: 11.0.4
 - Used Apache Solr Version: 8.5.2
 - PHP Version: 7.4.21
 - MySQL Version: 5.7.34

**Additional context**

After debugging I found one line changing could solve the problem, but I am not sure, if this will fit to all cases.

Inside solr/Classes/Domain/Search/Uri/SearchUriBuilder.php, method buildLinkWithInMemoryCache the xtbase URI-Builder gets $structure as arguments, but $arguments is useful, too, since Extbase UriBuilder can accept multiple associative arrays, too.

changing

```php
            self::$missCount++;
            $this->uriBuilder->reset()->setTargetPageUid($pageUid);
            $uriCacheTemplate = $this->uriBuilder->setArguments($structure)->setUseCacheHash(false)->build();
```

to 

```php
            self::$missCount++;
            $this->uriBuilder->reset()->setTargetPageUid($pageUid);
            $uriCacheTemplate = $this->uriBuilder->setArguments($arguments)->setUseCacheHash(false)->build();
```

solved the problem for me.

**Comment by trokohl** [comment]
I have a similar problem and this BugFix works

**Comment by trokohl** [comment]
But i think you must also change
$hash = md5($pageUid . json_encode($structure));

to 

$hash = md5($pageUid . json_encode($structure). json_encode($values));
