### ISSUE TITLE
[BUG] Language cache in SiteUtility should respect root page uid

### ISSUE THREAD

**Issue by markuskobligk** [TYPO3-Solr/ext-solr#2986]
**Describe the bug**
The language cache that was implemented in SiteUtility.php (see https://github.com/TYPO3-Solr/ext-solr/commit/c3ed93df060b3ab9e8cb052bde13dd0663f27bba) does not work properly with multisite setups when the different root pages share sys_languages. The language cache should save the languages with the root page uid as an array key.

**To Reproduce**
RootPage Foo (uid 1)
  -> uses sys_language 0 and 1
RootPage Bar (uid 2)
  -> uses sys_language 0, 1 and 2

The SiteUtility returns the same config/values in getConnectionPropertyOrFallback() for sys_language 0 and 1 for both root pages. Thich is wrong, since they can have totally different core configurations. In my case the configuration for solr_core_read was taken from the wrong root page/wrong site configuration.

**Expected behavior**
The language cache should work with root page uids AND language id to keep this working with multi site setups.

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.18
 - Browser: all
 - EXT:solr Version: dev-master
 - Used Apache Solr Version: 8.8.2 and 8.7
 - PHP Version: 7.4

**Comment by dkd-kaehm** [comment]
Leave it open until backports are merged.
