### ISSUE TITLE
Namespace all the classes

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/ext-solr#30]
Move all classes into namespaces. Namespace root is "ApacheSolrForTypo3\Solr". 

* Class names should not be changed
* Priority is to have this work with TYPO3 6.2 first as a strict requirement. 
* If things work with TYPO3 7.x, that's cool, but optional and. 
* TYPO3 4.5 specific code, class footers, and php end tags can be removed.

PRs should be roughly one per folder/namespace and 1 commit per class to keep reviews managable.

Currently set a goal for 3.5, but 3.1 would be fine, too.

**Comment by irnnr** [comment]
FYI @gordon81

**Comment by markusguenther** [comment]
Can try to help out. But i am busy at the moment so i can't make promises.

**Comment by gordon81** [comment]
I start today evening, as discussed with the first class per commit.
I begin with the first class of Access, and so on.

**Comment by markusguenther** [comment]
Maybe we should ask Tom Maroschik if his script is public. The Script that introduced the namespaces in the core would also helpful for extensions.

Then you just need to fix issues in the namespaced extension.

**Comment by gordon81** [comment]
Ask you Tom Maroschik , I have no contact infos from him

**Comment by gordon81** [comment]
@markusguenther last massage for you thanks

**Comment by gordon81** [comment]
Tx_Solr_Access_Rootline  -> ApacheSolrForTypo3\Solr\Access\Rootline

**Comment by gordon81** [comment]
Tx_Solr_Access_RootlineElementFormatException -> ApacheSolrForTypo3\Solr\Access\RootlineElementFormatException
Tx_Solr_Access_RootlineElement -> ApacheSolrForTypo3\Solr\Access\RootlineElement

next Backend subfolder has namespace

**Comment by gordon81** [comment]
Tx_Solr_Backend_ContentElementWizardIconProvider -> ApacheSolrForTypo3\Solr\Backend\ContentElementWizardIconProvider
Tx_Solr_Backend_IndexingConfigurationSelectorField -> ApacheSolrForTypo3\Solr\Backend\IndexingConfigurationSelectorField
Tx_Solr_Cli_Dispatcher -> ApacheSolrForTypo3\Solr\Cli\Dispatcher

next ContentObject

**Comment by gordon81** [comment]
Tx_Solr_ContentObject_Content -> ApacheSolrForTypo3\Solr\ContentObject\Content
Tx_Solr_ContentObject_Multivalue -> ApacheSolrForTypo3\Solr\ContentObject\Multivalue
Tx_Solr_ContentObject_Relation -> ApacheSolrForTypo3\Solr\ContentObject\Relation

next Facet

**Comment by gordon81** [comment]
[WIP] fehlt in commits

**Comment by AndreasA** [comment]
Regarding namespace rename, in order to be psr-4 compliant all classes should also be moved into one main folder like Classes which would include Plugin classes, Scheduler classes etc.
Like FeLogin was moved into Classes/Controller

**Comment by irnnr** [comment]
Let's do that separately. Probably not even for 3.1

**Comment by AndreasA** [comment]
Well, you can keep the namespace autoload section for all classes not in the "Classes" folder and add psr-4 for Classes, so that would work in the beginning too.
Moving classes elsewhere can always be done in e.g. 3.2

**Comment by AndreasA** [comment]
Although it is also possible to have additional psr-4 prefixes for those folders actually, like tests which is often extra.
It should work by just Having something like:
"ApacheSolrForTypo3\\Solr\\": "Classes/",
"ApacheSolrForTypo3\\Solr\\Scheduler": "Scheduler/",

That way it might not be necessary to move it in the first instance at all. Still would be a good idea in the long run.

**Comment by AndreasA** [comment]
Regarding addPi43 another possibility would be to use addPi43 and then add TypoScript afterwards manually, to modify the userFunc call to the correct class - everything else would be done correctly by addPi43. That way migrations is not necessary.

**Comment by irnnr** [comment]
Currently doing the Classes/ folder

**Comment by irnnr** [comment]
doing viewhelpers

**Comment by irnnr** [comment]
doing query

**Comment by irnnr** [comment]
doing IndexQueue

**Comment by markusguenther** [comment]
I don`t want to blame someone, but why the whole namespacing stuff will not happen in a separate branch?

**Comment by dkd-dobberkau** [comment]
isnt master branch for that? :-)

**Comment by markusguenther** [comment]
I would prefer a special feature branch and merge that later in the master. The namespacing take some time if you commit each file and until it is finished the master is a bit instable.

The commit history is also blown up by this little commits.

But it is just my personal opinion ;)

**Comment by irnnr** [comment]
Since we don't have a dev branch it's happening in master. I'm aware that things might be unstable, but we're trying to keep things running whenever these changes are being merged. Currently the only downside is that there are (almost) no backwards compatibility class mappings. Those will probably be added later. Other than that things seem to work pretty well.

I don't care too much about how many commits there are, in the end it's easier to review and roll back if needed.

All in all, if you're using master, you should know you're living on the edge :)

**Comment by irnnr** [comment]
If you want to help finish namespacing and stabilizing things faster, you're more than welcome to do so of course! :)

**Comment by irnnr** [comment]
Doing fieldprocessor

**Comment by AndreasA** [comment]
Regarding Migrations: Wouldn't it make more sense to always add the migrated classes also to the migrations PHP file? 
Because otherwise one has to go through all classes again once everything is done.
Or is there a autogenerate script?

**Comment by irnnr** [comment]
Yes, will have to generate a migration file once everything is done.

**Comment by irnnr** [comment]
continuing here...
doing facets

**Comment by AndreasA** [comment]
Is there already a code / script that does generate those files?
Would like to know for own projects.

**Comment by irnnr** [comment]
> On Sep 15, 2015, at 11:53 AM, Andreas Allacher <notifications@github.com> wrote:
> 
> Is there already a code / script that does generate those files?
> Would like to know for own projects.


Not that I know of, but my plan is to simply read the old autoload file and move underscores to slashes. That should roughly do it, plus some manual editing since we moved a couple files around.

**Comment by irnnr** [comment]
All classes have been moved to namespaces.

Still needs some migration files for backwards compatibility.

**Comment by irnnr** [comment]
migration files are in place now.

Namespaces done! 🎉

**Comment by AndreasA** [comment]
The composer.json still needs to be updated to reflect the new classes for autoload.
Should only be one psr-4 entry for classes and one classmap for lib.
Also a questiong is if you want to add the classaliasmap to the composer.json too (extra section see typo3 core) or if that one should be manually added if the corresponding project need it.

**Comment by AndreasA** [comment]
I just saw that you removed unnecessary entries. 
However, I think that Classes should be added via psr-4 (that way you don't have to call composer install if you add new classes during development) and Lib should stay classmap.
