### ISSUE TITLE
Only the rootpage is indexed

### ISSUE THREAD

**Issue by NiklasLazinbee** [TYPO3-Solr/ext-solr#3001]
Solr indexes my rootpage correctly but all subpages are not indexed. The index queue shows the message "Initialized indexing configurations: pages (3 records)" but only one page, the rootpage, is indexed. I think my configuration is correct. 
What could be the reason?

**Comment by dkd-kaehm** [comment]
@NiklasLazinbee 
Hello,
We want the versions stack like on issue assist
```
**Used versions (please complete the following information):**
 - TYPO3 Version: [e.g. 10.4.13]
 - Browser: [e.g. chrome, safari]
 - EXT:solr Version: [e.g. 11.0.2]
 - Used Apache Solr Version: [e.g. 8.8.0]
 - PHP Version: [e.g. 7.4.0]
 - MySQL Version: [e.g. 8.0.0]
```

**Comment by NiklasLazinbee** [comment]
Here are the informations about the versions:
 - TYPO3 Version: 8.7.24
 - Browser: chrome
 - EXT:solr Version: 8.1.2
 - Used Apache Solr Version: 6.6.0
 - PHP Version: 7.1.33-39
 - MySQL Version: 5.0.12

**Comment by dkd-kaehm** [comment]
@NiklasLazinbee 
Sorry, we do not support this versions(Currently only EXT:Solr 10.0.x + 11.0.x + prospective 11.1.x). 
There could be any reason for that. Please upgrade to EXT:Solr 9.0.2 and use TYPO3s Slack ext-solr channel to get help on that trouble.
