### ISSUE TITLE
[TASK] Integer TypeCast for modifyDocuments in the PageIndexerDocumentsModifier interface

### ISSUE THREAD

**Issue by ayacoo** [TYPO3-Solr/ext-solr#3010]
The function header already contains an integer. We could probably also adopt and use this.

Code:
https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/IndexQueue/PageIndexerDocumentsModifier.php#L47

Hint: Small change, but would be breaking!

**Comment by dkd-kaehm** [comment]
@ayacoo 
We can do that on master branch, this will be future Release for TYPO3 11 LTS only.
Please create a Pull Request.

**Comment by dkd-friedrich** [comment]
Already merged /done in 2001 (#3013 ), I'm closing this issue
