### ISSUE TITLE
[BUG] SolrNotAvailable.html template not using locallang.xlf translation

### ISSUE THREAD

**Issue by jonirouAtTalan** [TYPO3-Solr/ext-solr#3020]
**Describe the bug**
Solr extension have translation file but in this fluid template, the translation is not used.
The string "Search is currently not available." is hard coded

**To Reproduce**
Breack your solr config, for exemple
1. put a wrong port on your solr site config
2. load your search page
3. You will see "Search is currently not available." whatever your frontend language is

**Expected behavior**
If the solr extension is translated in your frontend language you should see the rigth version

**Screenshots**

**Used versions (please complete the following information):**
 - EXT:solr Version: 11.0.4, but also other version with this template file
 
 ** Solution : 
Make use of <f:translate
			key="LLL:EXT:solr/Resources/Private/Language/locallang.xlf:searchUnavailable"/>

**Comment by dkd-kaehm** [comment]
@jonirouAtTalan 
Thanks for reporting and fixing that.
Currently we Support following branches and want ports for those branches:
* release-11.0.x
* release-11.1.x
* master

**Comment by jonirouAtTalan** [comment]
> @jonirouAtTalan
> Thanks for reporting and fixing that.
> Currently we Support following branches and want ports for those branches:
> 
>     * release-11.0.x
> 
>     * release-11.1.x
> 
>     * master

Ok, i will propose patch for 11.0.x and 11.1.x version
