### ISSUE TITLE
[BUG] EverythingOn breaks page indexing. JSON response is overruled with debug message (debugOutput=1)

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#3030]
**Describe the bug**
By activating the TypoScript Configuration/TypoScript/Examples/EverythingOn/setup.typoscript the page indexing is broken, because the JSON response is overruled with output of DebuggerUtility::var_dump.
The page is indexed anyway but newer marked as indexed, due of invalid response message.

**To Reproduce**
1. Activate Configuration/TypoScript/Examples/EverythingOn/setup.typoscript 
2. Try to index pages.

**Expected behavior**
Page indexing is not affected by `plugin.tx_solr.logging.debugOutput = 1`

**Used versions (please complete the following information):**
 - TYPO3 Version: [e.g. 10.4.20]
 - EXT:solr Version: [e.g. 11.1.1]

**Comment by Apen** [comment]
I can confirm this "bug" but in my case "plugin.tx_solr.logging.debugOutput = 0" do the trick and everything is fine.

**Comment by dkd-kaehm** [comment]
Ported to:
* 11.2 91259e02d124964a5cf0dba647ad22f5bc56bb21
* 11.5 56203dfa00e7bb920275a6232c0c3afa1caaac9b
* main b53f93f3257b79e692f0600361b4f41b5c9969e6
