### ISSUE TITLE
[BUG] Remove requirement for Solr path in site configuration

### ISSUE THREAD

**Issue by froemken** [TYPO3-Solr/ext-solr#3041]
**Describe the bug**
In your Upgrade notes you write `Solr path mustn't be prepended with "/solr/"`. So I have removed that path from all our sites configuration files. But now customer can not save a site configuration in backend module anymore, because sorl path is a required column.
Further you have following in your code:

`SiteUtility::getConnectionProperty($typo3Site, 'path', $languageUid, 'read', '/solr/')`

If empty, the path will be set to "/solr/" automatically. So there is no need to have that field marked as required.

Link:
https://github.com/TYPO3-Solr/ext-solr/blob/master/Documentation/Releases/solr-release-11-1.rst

**Expected behavior**
I can save site configuration without a given solr path without errors.

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.21
 - Browser: Chrome
 - EXT:solr Version: 11.1.1
 - Used Apache Solr Version: I don't find the INformation in Solr Info module
 - PHP Version: 7.3
 - MySQL Version: MariaDB 10.2

**Comment by dkd-kaehm** [comment]
There are a little bit more things todo:

We should remove the thing from:
https://github.com/TYPO3-Solr/ext-solr/blob/c7a07832989e01111b8cf8416624a70d6dde0ef0/Classes/System/Solr/Node.php#L47-L54

and concatenation to "path":
https://github.com/TYPO3-Solr/ext-solr/blob/c7a07832989e01111b8cf8416624a70d6dde0ef0/Classes/Domain/Site/SiteRepository.php#L295-L297

and propagate the path and core as is without any processing.

---

We'll resume this topic on TYPO3 11 LTS readiness sprint and port it back to 11.1.
@froemken Please backport #3042 into 11.1 branch and use `Fixes: #3041` in commit message body.
