### ISSUE TITLE
configsets in docker image

### ISSUE THREAD

**Issue by LiohMoeller** [TYPO3-Solr/ext-solr#3044]
I have tried to update the docker image, e.g. from:
    image: typo3solr/ext-solr:11.0
to:
    image: typo3solr/ext-solr:11.1
and did a docker-compose pull && docker-compose up -d afterwards. The new image gets pulled, but the configset for the upgraded extension does not seem to be included
.solrdata/data/configsets/ext_solr_11_0_0 is the only configset available in the datadir after the upgrade.
Do I have to upgrade the configset in the docker datadir manually after pulling the new image?

**Comment by dkd-kaehm** [comment]
@LiohMoeller 
Our Docker image is not suitable for upgrades on this matter.
Background: The docker volume operates as you described. It does not propagate/fill the new contents from image into the volume of container if the target is not empty, therefore you see only the old schemas in your container.

If you have had some changes in schemas, then you must port them to schemas of 11.1 and apply them manually in your volume. So if you did not change anything in schemas, just empty or delete the defined volume and start then the container.


Related: #2710
