### ISSUE TITLE
Required java version ist higher than needed in install-solr.sh

### ISSUE THREAD

**Issue by Mabahe** [TYPO3-Solr/ext-solr#3045]
Version 11 is required in install-solr.sh.

Minimum requirement for Solr 8.9 is still java 8.

https://solr.apache.org/guide/8_9/solr-system-requirements.html#java-requirements

**Comment by dkd-kaehm** [comment]
That script is for our CI not for production usage. 
Highly possible, that this script will be removed soon.

**Comment by Mabahe** [comment]
So sad, *snif. useful to install the new version on the local machine, too.
"But docker" jaja :)
