### ISSUE TITLE
[BUG] Indexing records with SOLR_RELATION via backend considers hidden relation records

### ISSUE THREAD

**Issue by saitho** [TYPO3-Solr/ext-solr#3046]
**Describe the bug**
In [Backend context](https://github.com/TYPO3/typo3/blob/master/typo3/sysext/backend/Classes/Http/Application.php#L91) TYPO3 will set a VisibilityAspect that allows showing hidden pages and content. When a record is translated and the translation is then hidden, the hidden translation will still get indexed in SOLR_RELATION. This only happens when indexing is done via the TYPO3 backend, so there is a different behaviour from indexing via CLI.

The suggested approach is to reset the VisibilityAspect in `Ext:solr`s Tsfe class to make sure hidden elements are not shown.

Also, I was not able to reproduce this with SOLR_RELATION fields with the PageIndexer. For some reason indexing via CLI is fine even though it is also allows hidden pages and content elements (see [CLI context](https://github.com/TYPO3/typo3/blob/master/typo3/sysext/core/Classes/Console/CommandApplication.php#L185)).

---

**To Reproduce**

While this error was found in our internal extension, I tried my best to reproduce this with Ext:news.
This test assumes English as the main language (Index: `core_en`) and German as the second language (Index: `core_de`)

1. Create two sys_categories "Category 1" and "Category 2". Create a German translation for both of them ("Kategorie 1" and "Kategorie 2") and disable the translation of "Category 2"
2. Create a Ext:news record and assign both categories to it. Then create a German translation. Make sure both categories are selected there as well.
3. Add News indexer in TypoScript setup:
```typoscript
@import 'EXT:solr/Configuration/TypoScript/Examples/IndexQueueNews/setup.typoscript'
```
3. Index the news record via the TYPO3 backend.
4. Look at the index entries.
In `core_en` the entry has: `"category_stringM":["Category 1", "Category 2"],`
In `core_de` the entry has: `"category_stringM":["Kategorie 1", "Kategorie 2"],`

**Expected behavior**

In German index, "Kategorie 2" should not show up as it is disabled.
It should behave the same as when indexing via CLI, i.e. it should index the original record.

In `core_en` the entry has: `"category_stringM":["Category 1", "Category 2"],`
In `core_de` the entry has: `"category_stringM":["Kategorie 1", "Category 2"],`

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.21
 - EXT:solr Version: 11.0.2
 - Used Apache Solr Version: 8.5.1, 8.9.0
 - PHP Version: 7.4.20

**Comment by dkd-kaehm** [comment]
@saitho 
Thanks for reporting and fixing that Issue Mario!
Nice Catch :100: !

**Comment by dkd-kaehm** [comment]
Done in https://github.com/TYPO3-Solr/ext-solr/commit/d50947375522db71ecc0600bb35ded395600c296
