### ISSUE TITLE
[TASK] Migrate to Bootstrap 5 

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#3069]
**What should be done in the scope of this task?**
The EXT:solr must support [bootstrap v5](https://getbootstrap.com/docs/5.0/getting-started/introduction/) like 
[EXT:bootstrap_package](https://github.com/benjaminkott/bootstrap_package)

**Comment by dkd-friedrich** [comment]
done with #3112
