### ISSUE TITLE
[TASK-11.5C] Refactor Widgets to TYPO3s new Pagination API

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#3091]
**What should be done in the scope of this task?**
All Widgets must be refactored to https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Pagination

Todo:

- [ ] Refactor [GroupItemPaginateViewHelper](https://github.com/TYPO3-Solr/ext-solr/blob/39129843e0b99d56ab74abedc8fcc84c6a9d7abe/Classes/ViewHelpers/Widget/GroupItemPaginateViewHelper.php#L35) 
   https://github.com/TYPO3-Solr/ext-solr/blob/39129843e0b99d56ab74abedc8fcc84c6a9d7abe/Classes/ViewHelpers/Widget/GroupItemPaginateViewHelper.php#L35

**Comment by dkd-kaehm** [comment]
@FamousWolf
Thanks for taking over this issue.

**Comment by FamousWolf** [comment]
I'll take a quick look at it this week to see if I have any questions and will work on it next week.

**Comment by dkd-kaehm** [comment]
@FamousWolf 
The search does not work currently, because of couple of Widgets used in EXT:solr.
See: 
* https://github.com/FamousWolf/ext-solr/tree/task/2976_TYPO3.11_compatibility/Classes/Widget
* https://github.com/FamousWolf/ext-solr/tree/task/2976_TYPO3.11_compatibility/Classes/ViewHelpers/Widget
* https://github.com/TYPO3/typo3/commit/e400229aae16bc4a633e04791a6f11801c4a06f5 


Do you want to continue with the rest of widgets? Or should someone else take it over?

**Comment by FamousWolf** [comment]
Yes, I only replaced the pagination widget. I removed the other widgets from the template to test it. I'd love to tackle the other widgets as well, but I won't have time for it this week. If nobody else has time to work on it this week I can spend a few hours on it next week.

**Comment by FamousWolf** [comment]
After discussing it with my team I've managed to free up some time this week. I've got 4 hours tomorrow or Wednesday to work on the widgets.

**Comment by dkd-kaehm** [comment]
@FamousWolf 
Thanks for fixing the pagination part.
I've cherry-picked that PR in the target branch. Please use new pull request for rest of widget stuff.

**Comment by bmack** [comment]
See my branch here https://github.com/bmack/ext-solr/tree/grouping-pagination-widgets that works with grouped search results and the new Pagination API. No tests or template adaptions are done. But the branch works for our current project.
In addition, the "old" WidgetControllers* things in EXT:solr could now be removed at the same time as they depend on EXT:fluid v10.
