### ISSUE TITLE
[BUG] Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::getApplicationContext()

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Solr/ext-solr#3104]
**Describe the bug**
On including the main branch in TYPO3 11.5.3 I get the error

Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::getApplicationContext()
in /var/www/html/private/typo3conf/ext/solr/ext_localconf.php line 203

**To Reproduce**
ddev composer req apache-solr-for-typo3/solr:"main-dev"
open TYPO3 Backend
see error

**Expected behavior**
No error

**Screenshots**

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.3
 - EXT:solr Version: main

**Additional context**
The function has been deprecated with 10 and removed with 11, use

$context = \TYPO3\CMS\Core\Core\Environment::getContext();

instead

**Comment by typoniels** [comment]
@linawolf

Solr is not fully compatible with v11 at this time. The current state could be found in the task/2976_TYPO3.11_compatibility branch. I think the described problem has already been fixed there. To test, just install with
`ddev composer req apache-solr-for-typo3/solr:"dev-task/2976_TYPO3.11_compatibility"`
