### ISSUE TITLE
[BUG] SolrFacetMaskAndCombineEnhancer overrides other routeEnhancers

### ISSUE THREAD

**Issue by Nicola-Widmer** [TYPO3-Solr/ext-solr#3107]
**Describe the bug**
Other routeEnhancers don't work when SolrFacetMaskAndCombineEnhancer is acitve

**To Reproduce**
1. Add and SolrFacetMaskAndCombineEnhancer and an ExtBasePluginEnhancer (for example for the news detail page) to config.yaml
2. Open News Detail Page
3. _news not available_ message appears

**Expected behavior**
News Detail-Page gets shown normally

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4
 - Browser: All
 - EXT:solr Version: 11.1.2
 - PHP Version: 7.4.0

**Additional context**
If the SolrFacetMaskAndCombineEnhancer isn't enabled, everything works as expected

**Comment by dkd-kaehm** [comment]
Do you want to use EXT:solr plugin together with other plugins on same page?
Does it work with mixing third party enhancers together? And if then, how?

---

Is `limitToPages:` set on `type: SolrFacetMaskAndCombineEnhancer`?
See: 
* https://docs.typo3.org/p/apache-solr-for-typo3/solr/master/en-us/Routing/ConfigureRouting.html
* https://docs.typo3.org/p/apache-solr-for-typo3/solr/master/en-us/Routing/ConfigureRouting.html

**Comment by Nicola-Widmer** [comment]
No, theres only the Solr plugin on the page. The problem was, that no other routeEnhancer that the one for solr worked. `limitToPages` solves that problem

**Comment by dkd-kaehm** [comment]
:+1:
