### ISSUE TITLE
[BUG] In \ApacheSolrForTypo3\Solr\FrontendEnvironment\Tsfe typoscript parsed twice leading to bug

### ISSUE THREAD

**Issue by Apen** [TYPO3-Solr/ext-solr#3130]
**Describe the bug**
In \ApacheSolrForTypo3\Solr\FrontendEnvironment\Tsfe;;initializeTsfe() we use `$globalsTSFE->tmpl->start($globalsTSFE->rootLine);`.
This method is implicity call by the next `$globalsTSFE->getConfigArray($serverRequest);`.

This leading to some bugs regarding the parsing, and particulary, the include of external files.
The first "start()" call will put the flash "processIncludesHasBeenRun" to true. All the typoscript is fine in "config". But, the second time the typoscript is parsed, it will not include any typoscript file (@import or INCLUDE_TYPOSCRIPT) because of this flag. So the config array is reinitialize without all the config.

**To Reproduce**
1. Go to Index Queue module
2. Debug any infos of typoscript array who are in a include file

**Expected behavior**
Call one time the parser and delete `$globalsTSFE->tmpl->start($globalsTSFE->rootLine);`

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.4
 - EXT:solr Version: last branch release-11.5.x
 - Used Apache Solr Version: 8.9.0
 - PHP Version: 7.4

**Comment by dkd-kaehm** [comment]
@Apen 
thanks for reporting this nice catch.
Could you please provide some scenario or a little bit more infos regarding to:
> This leading to some bugs regarding the parsing, and particulary, the include of external files.

I want to implement the unit or functional test cases for that behaviour.

**Comment by Apen** [comment]
You could test with a very basic scenario :
- 1 root page with 1 sys_template
- In this sys_template include 2 statics :
    - Search - Base Configuration (solr)
    - A custom typoscript file wich include "Everything On" like that "@import 'EXT:solr/Configuration/TypoScript/Examples/EverythingOn/setup.typoscript'"

- First call of "start()", you can check `plugin.tx_solr.enableDebugMode` (it will be = 1)
- On the second call, the include doesnt work, so `plugin.tx_solr.enableDebugMode` will be equal to 0

Is it enough for you to write tests?

**Comment by dkd-kaehm** [comment]
@Apen 
Thanks for the reply.
Is something different as you meant on this place?:

https://github.com/TYPO3-Solr/solr-ddev-site/blob/5b979f76b327b39d8004e560a571ad847626cd15/packages/apache_solr_for_typo3_sitepackage/Configuration/TypoScript/setup.typoscript

**Comment by Apen** [comment]
No its exactly like that :-)

**Comment by dkd-kaehm** [comment]
Still can't reproduce any issue with that state, nevertheless removed that call.
Without test case.

**Comment by Apen** [comment]
Good for me 👍

**Comment by dkd-kaehm** [comment]
Fixed in #3136
