### ISSUE TITLE
[BUG] Call to undefined method TYPO3\CMS\Core\Http\ResponseFactory::createJsonResponse()

### ISSUE THREAD

**Issue by michaelsemle** [TYPO3-Solr/ext-solr#3138]
**Describe the bug**
When calling the suggestAction in the SuggestController an Exception gets thrown with the message:
"Call to undefined method TYPO3\CMS\Core\Http\ResponseFactory::createJsonResponse()"

**To Reproduce**

- Create an user object that calls the action
- or create a pageType that loads the action
```
10 = USER
  10 {
    userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
    extensionName = Solr
    pluginName = pi_suggest
    vendorName = ApacheSolrForTypo3
    controller = Suggest
    action = suggest
  }
```
- when calling the page an exceptions gets thrown

**Expected behavior**
A json response with the suggestions should be returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/23473071/146784959-8c75c394-4eb5-42a7-bf1b-4bd3a6c96ee9.png)

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.4
 - Browser: all
 - EXT:solr Version: 11.5.0-pre-alpha-1
 - Used Apache Solr Version: 8.5.2
 - PHP Version: 7.4
 - MySQL Version: mariadb 10.3

Relates: #3158

**Comment by dkd-kaehm** [comment]
Added test case for scenario without defined "callback", to achieve that row.
