### ISSUE TITLE
[BUG] "TypeError" in <s:translate> viewhelper

### ISSUE THREAD

**Issue by dmitryd** [TYPO3-Solr/ext-solr#3141]
**Describe the bug**

The following exception is displayed in `release-11.5.x` and PHP 8 (!!!) (using commit a2988d2ff699b69ae571f1934e37a8c17255fb7f):

```
(1/1) TypeError
vsprintf(): Argument #2 ($values) must be of type array, null given
in /var/www/html/web/typo3conf/ext/solr/Classes/ViewHelpers/TranslateViewHelper.php line 42
    public function render()
    {
        $result = parent::render();
        $result = self::replaceTranslationPrefixesWithAtWithStringMarker($result);
        $result = vsprintf($result, $this->arguments['arguments']);
        return $result;
    }

    /**
```

It comes from `EXT:solr/Resources/Private/Partials/Search/Form.html`:

```html
<s:searchForm id="tx-solr-search-form-pi-results" additionalFilters="{additionalFilters}" suggestHeader="{s:translate(key:'suggest_header',default:'Top Results')}">
```

There `arguments` are missing, hence `NULL` is sent.

Also this should cause the error:

```html
<s:translate key="submit">Search</s:translate>
```

Since php 8 is very strict regarding missing array keys and other missing data.

**To Reproduce**
1. Use php 8
2. Search for `*`
3. See the exception

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.4
 - EXT:solr Version: release-11.5.x
 - **PHP Version: 8.0**

**Comment by dkd-kaehm** [comment]
Done in #3142
