### ISSUE TITLE
[FEATURE] Improve search with variants by sorting user groups

### ISSUE THREAD

**Issue by dmitryd** [TYPO3-Solr/ext-solr#3143]
**Is your feature request related to a problem? Please describe.**

When using variants, the main variant will be the one indexed first. I am not sure if this is documented anywhere but this is what I found from practice. When indexing pages, the first indexed variant is the one for FE group "0" (anonymous visitor), then for FE group "-1" (anonymous as well) and only then it indexes other user groups.

Therefore when using variants and the user is logged in, the user will see content for the main variant, which is for the anonymous user. So the user will not see highlighted content available for the user's group.

**Describe the solution you'd like**

This can be improved by sorting user groups in reverse order. In that case if there are multiple variants, chances are higher that better variant will be displayed in search results. It is still not 100% guarantee if the user is in multiple groups but still better than the current approach.

**Describe alternatives you've considered**

There is no real alternative that I can see.

**Target versions**

11.5.x

**Comment by dkd-kaehm** [comment]
done in #3144
