### ISSUE TITLE
[BUG] Error in scheduler with PHP 8

### ISSUE THREAD

**Issue by dmitryd** [TYPO3-Solr/ext-solr#3145]
**Describe the bug**

Clicking "+" in the scheduler in TYPO3 v11 + PHP 8 does not result in the add action. An error message is displayed instead:

> PHP Runtime Deprecation Notice: Required parameter $schedulerModule follows optional parameter $taskInfo in /var/www/html/web/typo3conf/ext/solr/Classes/Task/ReIndexTaskAdditionalFieldProvider.php line 101

According to the language reference default parameters must be after non-default parameters.

**To Reproduce**

See the above.

**Expected behavior**

No error obviously.

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.4
 - EXT:solr Version: release-11.5.x
 - PHP Version: 8

**Comment by dkd-kaehm** [comment]
Done in #3146
