### ISSUE TITLE
[BUG] Errors are not always evaluated correctly

### ISSUE THREAD

**Issue by Smove** [TYPO3-Solr/ext-solr#3161]
**Describe the bug**
In the commit a2988d2ff699b69ae571f1934e37a8c17255fb7f, care was taken to catch all \Throwables. However, the method to generate the error log was not adjusted.

**Expected behavior**
The error should be logged correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/3686891/149762332-85c3ec8b-14da-4765-8f3c-c6a1001a0046.png)

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.5
 - EXT:solr Version: 11.5-dev
 - PHP Version: 7.4

**Comment by dkd-kaehm** [comment]
done in #3162
