### ISSUE TITLE
[BUG] Isolated TSFE removes backendUser globally

### ISSUE THREAD

**Issue by phth** [TYPO3-Solr/ext-solr#3167]
The method \ApacheSolrForTypo3\Solr\FrontendEnvironment\Tsfe::initializeTsfe() builds its own tsfe without taking an existing backend user into account. This has the side effect, that after rendering of a Solr-related action in frontend the $GLOBALS['BE_USER'] is empty.
This is especially a problem when working with ext:frontend_editing on hidden pages, as it relies on the correct setting of $GLOBALS['BE_USER'] (and maybe other extensions, too).

**To Reproduce**
1. install and configure frontend_editing in a installation with a (for example) solr search plugin on each page
2. edit a hidden page with a non-admin-user

**Expected behavior**
$GLOBALS['BE_USER'] should not be changed by \ApacheSolrForTypo3\Solr\FrontendEnvironment\Tsfe::initializeTsfe() 

**Screenshots**
Call of hidden page from backend in Frontend editing module:
![image](https://user-images.githubusercontent.com/1274061/150532890-98f47421-b312-40fa-be2d-4eee3c394a14.png)

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.5
 - Browser: all
 - EXT:solr Version: 11.5.0-pre-alpha-1
 - Used Apache Solr Version: docker image typo3solr/ext-solr:11.5.x-dev
 - PHP Version: 7.4.0
 - MySQL Version: MariaDB 10.2

**Additional context**
My workaround was to disable Solr-related plugins when frontend is called with frontend_editing=1 via TypoScript condition, but this solution may not fit other use-cases.

**Comment by dkd-kaehm** [comment]
@phth 
Thanks for reporting that issue.

We should try to avoid using `\ApacheSolrForTypo3\Solr\FrontendEnvironment\Tsfe` class methods in search context.

**Comment by dkd-kaehm** [comment]
@phth 
Please check this with current state of `@dev-release-11.5.x`.
There are no occurrences of `$GLOBALS['BE_USER'] = ` in EXT:solr code base at all.
If that still not work, I want to know the exact place in EXT:solr code base.
Thanks.

**Comment by phth** [comment]
@dkd-kaehm thank you for your fast feedback

i did `composer update apache-solr-for-typo3/solr`

`Upgrading apache-solr-for-typo3/solr (dev-release-11.5.x 05ae55e => dev-release-11.5.x 4be1ccc)`

Issue persist also in 4be1ccc

> There are no occurrences of $GLOBALS['BE_USER'] = in EXT:solr code base at all.
This is true. I believe it is an unintentional side effect of reinitalizing / initializing an own TSFE. 
I will try to provide a better explanation of the behaviour / will debug this further.

**Comment by dkd-friedrich** [comment]
Done with #3210
