### ISSUE TITLE
[BUG] PHP Warning: Undefined array key "TSFE" in RootPageResolver.php line 161

### ISSUE THREAD

**Issue by DrWh0286** [TYPO3-Solr/ext-solr#3173]
**Describe the bug**
In case of saving records with pid=0 with php 8 a warning appears:

PHP Warning: Undefined array key "TSFE" in /var/www/html/public/typo3conf/ext/solr/Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php line 161

**To Reproduce**
1. Go to page with uid=0
2. Open a record for editing (e.g. be_groups, be_users)
3. Save the record

**Expected behavior**
Having no php warning after saving a record.

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.5
 - Browser: Chrome
 - EXT:solr Version: task/2976_TYPO3.11_compatibility (0e8702a1a6e685b5df17b2ab489db67b41f3d47a)
 - Used Apache Solr Version: 8.5.2 (typo3solr/ext-solr:11.0.3 image with ddev)
 - PHP Version: 8.0
 - MySQL Version: MariaDB 10.3

**Comment by dkd-kaehm** [comment]
Fixed in: 6800394c02414aa6e22b47bd3c7d4fbf3921e533
