### ISSUE TITLE
Automatic wildcard search in custom fields

### ISSUE THREAD

**Issue by haraldwitt** [TYPO3-Solr/ext-solr#3181]
Hi,
I've defined a custom multivalue field with a SOLR_RELATION. The field is properly filled into the core.
Example: `"mobiles_stringM": ["0170 1234567", "0151 2 987654"],`

I also added that field to the queryFields.
`plugin.tx_solr.search.query.queryFields := addToList(mobiles_stringM^2.0)`

Now the search for `1234567` will have no result. But the search for `*1234567*` will have the expected result.

This is a contrast to the search in other fields like `content` or `keywords` where the wildcards are added automatically. How can I change this behavior? Or is it possible to add the `*` at the beginning and the end of the search string automatically?

My workaround at the moment: 
I use the field `keywords` in my queue as a COA. And the COA's elemets are all my SOLR_RELATIONs with `multiValue = 0` and `singleValueGlue = |, |`.

Thanks
Harald

**Comment by dkd-kaehm** [comment]
Please do not use this tracker for questions, use TYPO3s slack #ext-solr channel or solr-eb-support@dkd.de.

Please read the docs about dynamic field types, your choice is probably `_textNgramM`: 
https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Appendix/DynamicFieldTypes.html

**Comment by haraldwitt** [comment]
Oh, sorry for that. 
And thanks @dkd-kaehm
