### ISSUE TITLE
[BUG] Incorrect handling of raw response in Page Indexer Request

### ISSUE THREAD

**Issue by cundd** [TYPO3-Solr/ext-solr#3208]
**Describe the bug**
Erroneous raw responses are not handled correctly.

**To Reproduce**
https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/IndexQueue/PageIndexerRequest.php#L208:

The check `$rawResponse === false` is too late here. The program would already have crashed in line 206.

Additionally `raw response body` is always empty, because it has already been consumed in line 206
https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/IndexQueue/PageIndexerRequest.php#L217

**Expected behavior**

**Screenshots**

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.24
 - Browser: not relevant
 - EXT:solr Version: 11.2.0
 - Used Apache Solr Version: 8.11.1
 - PHP Version: 7.4.0
 - MySQL Version: MySQL 5.5.5-10.3.31-MariaDB

**Comment by dkd-kaehm** [comment]
@cundd 
Nice catch. 
Would you like to fix that and provide a pull-request for release-11.2.x?
