### ISSUE TITLE
[BUG] PHP Warning: Undefined array key "overrideParserVariables" (bootstrap_package)

### ISSUE THREAD

**Issue by DrWh0286** [TYPO3-Solr/ext-solr#3226]
**Describe the bug**
With PHP 8.0, TYPO3 11 and the current beta version 11.5.x-dev of ext:solr we get the following message in FE:

PHP Warning: Undefined array key "overrideParserVariables" in /var/www/deploy/releases/176/public/typo3conf/ext/bootstrap_package/Classes/Service/CompileService.php line 58

This happens, because ext:bootstrap_package is not PHP 8 ready.

**To Reproduce**
Install current 11.5.x-dev with TYPO3 11 and PHP 8.

**Expected behavior**
No PHP-Warning. And I guess ext:solr should not require bootstrap_package at all.

**Screenshots**
![Bildschirmfoto 2022-03-14 um 11 52 08](https://user-images.githubusercontent.com/12473862/158158118-76e676a6-eb92-4c30-895a-18458e918f6c.png)

**Used versions (please complete the following information):**
 - TYPO3 Version: 11
 - Browser: Chrome
 - EXT:solr Version: 11.5.x-dev (41ac7ffd5ec5da207f169b8cc9964ea177dd5760)
 - Used Apache Solr Version: 8.11.1
 - PHP Version: 8.0
 - MySQL Version: mariadb 10.3

**Additional context**
I guess, that the bootstrap_package was required by mistake. It does not seem to be used. So removing this requirement from composer.json would fix this issue.
If it is necessary, the bootstrap_package needs to be PHP 8 ready.

**Comment by dkd-kaehm** [comment]
We'll remove bootstrap_package from dependencies today and roll RC1.
