### ISSUE TITLE
[BUG] PHP 8.0 warnings in ApacheSolrForTypo3\Solr\Domain\Site\Site

### ISSUE THREAD

**Issue by DenisMir** [TYPO3-Solr/ext-solr#3232]
**Describe the bug**
The following PHP 8.0 related warnings are thrown in `ApacheSolrForTypo3\Solr\Domain\Site\Site`:

![Bildschirmfoto 2022-03-15 um 11 48 15](https://user-images.githubusercontent.com/157281/158363300-39eb2e08-466d-495b-9b39-3198ee7a9e1a.png)

This is related to the following line not checking if the array key exists: 

```
if (!is_array($this->solrConnectionConfigurations[$language])) {
```

**To Reproduce**
To reproduce just open up the different solr related backend modules with `'exceptionalErrors' => 12288,`

**Expected behavior**
No warnings.

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.8
 - EXT:solr Version: 11.5.0-rc-1
 - Used Apache Solr Version: 8.11.1
 - PHP Version: 8.0
 - Maria DB: 10.3

**Comment by dkd-kaehm** [comment]
Ported to:
* 11.5 8e1d5ed0e604eb4ff7eb9fae958db2f1f477300a
* main 5e381ff3712e4a4b27e2e85b00c614652b0953ba
