### ISSUE TITLE
[BUG] EXT:solrfal doesnt allow indexation of files cause of deprecated signalslot

### ISSUE THREAD

**Issue by Apen** [TYPO3-Solr/ext-solr#3233]
**Describe the bug**
solrfal correctly grab files on pages in "PageContextDetector" but doesnt allow indexation of them.
Seems that the `$allowedFileUids` var is initialized by a deprectaed signal slot "preGeneratePublicUrl" defined in ext_localconf.php
In the `PageContextDetector->addDetectedFilesToPage` if put ` $linkedFiles= $attachedFileUids;` (to test) everything is correctly index.

**To Reproduce**
1. In my page, i have a tt_content with a file in "header_link"
2. This file is correctly detected by the PageContextDetector (example in log : Found-Files: 5808)
3. The PageContextDetector check that this uid is allowed
4. It failed and in logs i have "All files: []" on this page, and of course, nothing in the queue

**Used versions :**
 - TYPO3 11.5 
 - Solr 11.5 RC1

**Comment by dkd-friedrich** [comment]
@apen Thanks for reporting, indeed this place was overlooked until now. The signal was removed with TYPO3 11 and must be replaced by an EventListener:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Breaking-91473-DeprecatedFunctionalityRemoved.html

We will take care of this in TYPO3-Solr/ext-solrfal/issues/170

I am closing this ticket as this is the tracker for EXT:solr.

**Comment by dkd-friedrich** [comment]
> We will take care of this in [TYPO3-Solr/ext-solrfal/issues/170](https://github.com/TYPO3-Solr/ext-solrfal/issues/170)

@Apen Issue is fixed and part of recently published solrfal 11.0.0-rc-2
