### ISSUE TITLE
[BUG]  Debugging facets in Fluid fails: AbstractFacet::$objectManager must not be accessed before initialization

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Solr/ext-solr#3235]
**Describe the bug**
 Debugging facets in Fluid fails with error message.

**To Reproduce**
1. Override the facet template 
2. enter a debug output `<f:debug inline="1">{facet}</f:debug>`
3. Show facet in frontend
4. See error `Typed property ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\Facets\AbstractFacet::$objectManager must not be accessed before initialization`

**Expected behavior**
A debug output of the objects content

**Used versions (please complete the following information):**
 - TYPO3 Version: [e.g. 11.5.8]
 - Browser: chrome
 - EXT:solr Version: 11.5.0-rc-1
 - Used Apache Solr Version: 8.11
 - PHP Version: 7.4.26
 - mariadb_version: "10.2"

**Additional context**

**Comment by dkd-kaehm** [comment]
@linawolf 
thanks for reporting that issue.

The property must be nullable or injection moved to constructor:

https://github.com/TYPO3-Solr/ext-solr/blob/61076e3ed99ba2c4b9f17d44c2e50f278218780d/Classes/Domain/Search/ResultSet/Facets/AbstractFacet.php#L79-L82

**Comment by linawolf** [comment]
The object manager Is deprecated and only used in very few places. So injecting it in the abstract class doesn't really make sense. 

Also Models are usually excluded from DI for good reasons. Haven't checked what is the case here. But it seems at least form a debugging context DI does not happen here.

**Comment by juergen-venne** [comment]
As a quick fix, as long as ObjectManager wasn't removed, I instantiated ObjectManger in the constructor:
https://github.com/juergen-venne/ext-solr/commit/9e63b01b8abfef1bc985077facd9305938bfcda8

**Comment by dkd-friedrich** [comment]
Fixed with #3243
