### ISSUE TITLE
[BUG] LOAD_REGISTER cannot be used in indexing configuration

### ISSUE THREAD

**Issue by dkd-friedrich** [TYPO3-Solr/ext-solr#3239]
**Describe the bug**
Upcoming EXT:solr 11.5 intends to use local TSFE object to avoid conflicts and to ensure a clean environment, unfortunately `LOAD_REGISTER` isn't using the prepared locally available object. So different objects are used for setting and reading the registers and the required content is not available.

I think this is probably not an issue of EXT:solr and should be fixed in the TYPO3 core, but we should be aware of this and should explicitly mention it in the release notes or documentation.

**To Reproduce**
Use `LOAD_REGISTER` in your indexing configuration and try to read the set value, e.g. via `register:xyz`

**Expected behavior**
`LOAD_REGISTER` should be usable or this issue should at least be documented.

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5
 - EXT:solr Version: 11.5.0-rc-1

**Comment by dmitryd** [comment]
This should be solvable by providing own implementation of load & restore via `$GLOBALS['TYPO3_CONF_VARS']['FE']['ContentObjects']` while indexing. Quite easy I think.

**Comment by dkd-friedrich** [comment]
We are in touch with the TYPO3 core team about this and hope that an adjustment in TYPO3 is possible and the problem can be fixed this way, see https://forge.typo3.org/issues/97638

**Comment by dkd-friedrich** [comment]
With TYPO3 11.5.14, using of local TypoScriptFrontendController objects should no longer be a problem, we now require this version and close this issue.

We will provide a new RC soon, testing and feedback on the current status is appreciated.
