### ISSUE TITLE
[BUG] TSFE not available for Typoscript based field rendering in Indexer

### ISSUE THREAD

**Issue by mrk131324** [TYPO3-Solr/ext-solr#3244]
**Describe the bug**

When building your `Document` with `addDocumentFieldsFromTyposcript()` the initialized TSFE is not accessible by all cObject renders. 

**To Reproduce**
1. Make you own TS based Indexing Configuration
2. Use a `CONTENT` cObject in it. 
3. Try to index from the BE

**Expected behavior**
Content object rendering should be unlimited and as documented.

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5
 - EXT:solr Version: 11.5.0-rc-1
 - PHP Version: 8.1

**Additional context**

Quick fix:

`Classes/IndexQueue/Indexer.php:401` should read:

```php
if (!isset($GLOBALS['TSFE'])) {
    $GLOBALS['TSFE'] = GeneralUtility::makeInstance(Tsfe::class)->getTsfeByPageIdAndLanguageId($this->getPageIdOfItem($item), $language, $item->getRootPageUid());;
}
if (!isset($GLOBALS['TYPO3_REQUEST'])) {
     $GLOBALS['TYPO3_REQUEST'] = ServerRequest::fromGlobals();
}
```

This quick fix is most likely not perfect. E.g. is can override the Backenuser Session when indexing manually from the BE (which raises question about runtime isolation from the solr module). But otherwise it does the trick. 

The request is technically not needed, but `ContentObjectRenderer` fails for certain objects if it is not set (more a bug there, actually). 

My personal opinion: Discontinue the typoscript based rendering of index documents. Only us veterans know how to properly use typoscript anyways.

**Comment by abvdveen** [comment]
I can confirm this and is pretty annoying, as it breaks my indexing when upgrading to Typo3 11. Using this TS in de indexer config:
```

					registration_intS = CONTENT
					registration_intS {
					    table = tx_sfeventmgt_domain_model_event
					    select {
					    	uidInList.field = uid
					    	pidInList = {$pages.eventStorage}
						}
						renderObj = CONTENT
						renderObj {
						  table = tx_sfeventmgt_domain_model_registration
						  select {
						    pidInList.field = pid
						    where = event = ###contentuid### AND waitlist = 0 AND hidden=0 AND deleted=0
						    selectFields = count(*) AS count
						    markers {
						      contentuid.field = uid
						    }
						  }
						  renderObj = TEXT
						  renderObj {
						    data = field:count
						  }
						}
					}

```
leads to the error: 'PHP Warning: Creating default object from empty value' when indexing items.

Alas the quick fix indeed gives the error: Call to a member function set() on null in sysext/core/Classes/Authentication/AbstractUserAuthentication.php when indexing manually from the BE.

What would you recommend as a replacement for using CONTENT in the indexer config?

**Comment by dkd-friedrich** [comment]
With TYPO3 11.5.14, using of local TypoScriptFrontendController objects should no longer be a problem, we now require this version and close this issue.

We will provide a new RC soon, testing and feedback on the current status is appreciated.
