### ISSUE TITLE
[BUG] Failed to execute Page Indexer Request 

### ISSUE THREAD

**Issue by intertain** [TYPO3-Solr/ext-solr#3247]
**Describe the bug**
Indexing of "pages" is not possible. Indexing of "news" entries is successful.
The error after trying to index a page:
```
1319116885: RuntimeException: Failed to execute Page Indexer Request. See log for details. Request ID: 6267073aecae4 in ###/htdocs/public/typo3conf/ext/solr/Classes/IndexQueue/PageIndexerRequest.php:221
Stack trace:
#0 ###/htdocs/public/typo3conf/ext/solr/Classes/IndexQueue/PageIndexerRequest.php(170): ApacheSolrForTypo3\Solr\IndexQueue\PageIndexerRequest->getUrlAndDecodeResponse()
#1 ###/htdocs/public/typo3conf/ext/solr/Classes/IndexQueue/PageIndexer.php(168): ApacheSolrForTypo3\Solr\IndexQueue\PageIndexerRequest->send()
#2 ###/htdocs/public/typo3conf/ext/solr/Classes/IndexQueue/PageIndexer.php(64): ApacheSolrForTypo3\Solr\IndexQueue\PageIndexer->getAccessGroupsFromContent()
#3 ###/htdocs/public/typo3conf/ext/solr/Classes/Domain/Index/IndexService.php(201): ApacheSolrForTypo3\Solr\IndexQueue\PageIndexer->index()
```

**To Reproduce**
Apache Solr Server is successfully contacted in Modul "Info"
1. Go to Index Queue Modul in Backend
2. Select "pages" to initialize
3. Start Indexing with "Index Now"

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.9
 - Browser: Chrome
 - EXT:solr Version: 11.5.0-rc-2
 - PHP Version: 8.0

**Comment by dkd-kaehm** [comment]
@intertain 
I can not reproduce the issue. 
Is the base set in site config yaml, like described in the docs? https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/GettingStarted/ConfigureExtension.html

"EXT:Solr needs a proper domain as base for the site. If the base is set to “/” or a similar relative path, the Indexing will throw an error, so please make sure that “base” is a fully qualified domain like https://my.project.tld/”

**Comment by brannow** [comment]
had the same problem, but i could track it down to my DDEV setup.

Every request send from the ddev web container to itself, will end as HTTPS => OFF even sended as https://....
this is not an solr oder extsolr problem is more over an ddev / config problem

the siteconfig required https to work on my end, so the routeMatcher was not able to find the correct route/siteconfig

im still debugging to find the root-problem.

**Comment by intertain** [comment]
In my case the problem was simple: We had a basic auth on dev system and I didn't insert the basic auth credentials into the solr ext typoscript. Then it worked...
