### ISSUE TITLE
[BUG] Garbage collection removes temporally updated records from index 

### ISSUE THREAD

**Issue by balasch** [TYPO3-Solr/ext-solr#3249]
**Describe the bug**
In a record like tx_news_domain_model_news, fe_groups is empty: fe_group = ""
When saving, TCA::normalizeFrontendGroupField replaces this with fe_group = "0".

Then in GarbageCollector::hasFrontendGroupsRemoved fe_group = "" of the old record in the database is compared to the changed "fe_group = "0", so [] is compared to [0], so this function returns true.

In the following process the news disappears from the index by the garbage collection until re-indexing. This can take up to 5 minutes in my case.

I think it makes more sense to use "GeneralUtility::intExplode" instead of "explode". Then both values for fe_group = [0].

The TCA:normalizeFrontendGroupField would then perhaps no longer be needed. 

**To Reproduce**
A TYPO3 v10.4.26 with tx_news:8.6.0 and solr:11.2.0. IndexQueue is config like
```
@import 'EXT:solr/Configuration/TypoScript/Examples/IndexQueueNews/setup.typoscript'
plugin.tx_solr.index.queue {
  news = 1
  news.additionalWhereClause = pid IN ({$general.folder.news})
} 

```

Take an existing news entry, press save and the news disapears from the solr index until reindexing. 

**Expected behavior**

The news entry does not disapear from the index.

**Used versions (please complete the following information):**
Typo3: 10.4.62
apache-solr-for-typo3/solr: 11.2.0
georgringer/news: 8.6.0

**Comment by dkd-kaehm** [comment]
Ported to:
* 11.5 #3253
* main #3280
* 11.2 #3281
