### ISSUE TITLE
[BUG] Return value of OptionsFacetQueryBuilder::buildMincountForJson() must be of the type int, string returned

### ISSUE THREAD

**Issue by DrWh0286** [TYPO3-Solr/ext-solr#3260]
**Describe the bug**
The following type error occurs when using 'minimumCount' in facet configuration (plugin.tx_solr.search.faceting.facets.[facetName].minimumCount)

Return value of ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\Facets\OptionBased\Options\OptionsFacetQueryBuilder::buildMincountForJson() must be of the type int, string returned

I assume, that the same happens for 'facetLimit' (plugin.tx_solr.search.faceting.facets.[facetName].facetLimit) in 

\ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\Facets\OptionBased\Options\OptionsFacetQueryBuilder::buildLimitForJson()

**To Reproduce**
Configure a facet with one of the options 'minimumCount' or 'facetLimit' and use it in FE.

**Expected behavior**
No Exception. A type cast needs to be done here.

**Screenshots**

![Bildschirmfoto 2022-05-31 um 10 23 40](https://user-images.githubusercontent.com/12473862/171128129-20840b35-0a18-4367-93cd-d8e03533d304.png)

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.10
 - Browser: Chrome
 - EXT:solr Version: dev-release-11.5.x (31ba843a13f4c8171a960b8b4ded30954dae6b68)
 - PHP Version: 7.4
 - MySQL Version: mariadb 10.3

**Comment by dkd-friedrich** [comment]
Fixed with #3261
