### ISSUE TITLE
[BUG] Possibly wrong detection of free mode for records / indexed to multiple cores (11.5)

### ISSUE THREAD

**Issue by akiessling** [TYPO3-Solr/ext-solr#3264]
**Describe the bug**
"Standalone" records with sys_language_ uid > 0 and without a parent record get indexed to the core for the default language and the one for the configured language.

I have a standard multilanguage setup with multiple languages and a core for each language (e.g. de = default, en = 1, fr = 2).
The languages are all set  to _Fallback Type Strict_ and have no fallbacks configured. 

The requirement for news records is however to also allow them without a default record. This worked fine in previous versions, but with 11.5.0-rc-2 the _standalone_ record is indexed to the default core and e.g. the en core.

I tracked this down to https://github.com/TYPO3-Solr/ext-solr/blob/4e1d79e7910aeec1591f3e42ef2f77a5bcb7962c/Classes/IndexQueue/Indexer.php#L280
#2788 also looks related but is already closed. 
Only the language field and language config of the site is checked, but not if the record itself is depending on a default record. Previously there was code to handle these cases https://github.com/TYPO3-Solr/ext-solr/blame/ab955c4f0172d58257ee4d78f336b747cd67c8c3/Classes/IndexQueue/Indexer.php#L224

While the item meets the requirements, the site check fails. Thus getItemRecordOverlayed now also skips the check in https://github.com/TYPO3-Solr/ext-solr/blob/4e1d79e7910aeec1591f3e42ef2f77a5bcb7962c/Classes/IndexQueue/Indexer.php#L254, the following check also depends on the site config and is skipped --> the indexer runs

Overriding the method with a check for sys_language_uid and the l10n_parent field seems to work for me and i put this to a custom indexer that just inherits from the default one.

```
    /**
     * @param Item $item
     *
     * @return bool
     */
    protected function isAFreeContentModeItemRecord(Item $item): bool
    {
        $languageField = $GLOBALS['TCA'][$item->getType()]['ctrl']['languageField'] ?? null;
        $itemRecord = $item->getRecord();

        $l10nParentField = $GLOBALS['TCA'][$item->getType()]['ctrl']['transOrigPointerField'] ?? null;
        if (null === $languageField || null === $l10nParentField) {
            return true;
        }
        $languageOfRecord = (int)($itemRecord[$languageField] ?? null);
        $l10nParentRecordUid = (int)($itemRecord[$l10nParentField] ?? null);

        if ($languageOfRecord > 0 && $l10nParentRecordUid === 0) {
            return true;
        }

        return false;
    }
```

**To Reproduce**
1. Multilanguage TYPO3 setup, strict language handling, no fallbacks
2. Use indexer config for tx_news from the examples
3. Create a news record with sys_language_uid 1 (hint: to actually output this news record, https://github.com/georgringer/extbase_with_no_l10n_parent is also required)
4. Index this record
5. A solr document is created in the core for language 0 and language 1

**Expected behavior**
The document should only be created in the core for language 1

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.10
 - EXT:solr Version: 11.5.0-rc-2
 - Used Apache Solr Version: 8.11.1
 - PHP Version: 8.1
 - MySQL Version: 8.0.26

**Additional context**
Since also https://github.com/georgringer/extbase_with_no_l10n_parent is needed for news to actually display the news, i'm not sure what the core concept for handling this "mixed free/strict mode" is. I needed that setup for almost every project to allow standalone records.

**Comment by raf-ch** [comment]
This correction works for the strict mode but no longer works for the free mode. In free mode the elements (news) are mixed and if I remove the correction it works perfectly with free mode.
