### ISSUE TITLE
[BUG] OptimizeIndexTask $rootPageId must be of type int, string given

### ISSUE THREAD

**Issue by cschnell** [TYPO3-Solr/ext-solr#3267]
**Describe the bug**
The Task can't be saved because the value of $rootPageId is not casted to int.

**Additional context**
Has been already fixed for the other AdditionalFieldProviders, this one was a leftover.

**Comment by dkd-kaehm** [comment]
Ported to:
* 11.2 40a997cb4eed76aceb9a9c70be44abd14210ab4b
* 11.5 506b540e4ce545086493ead06fedfd7ed1a685d1
* main b5a1febe21deb03a8c02b6d2ef249187919ae5f3
