### ISSUE TITLE
[BUG] Pagination broken when resultsPerPage is set

### ISSUE THREAD

**Issue by codemonkey1988** [TYPO3-Solr/ext-solr#3272]
**Describe the bug**
When using the option **resultsPerPage** for search results, the user can only access page 1 of the search results.

**To Reproduce**
1. Add solr result plugin to a page 
2. Do a search with mutliple pages in result
3. Choose a resultPerPage amount (the parameter needs only be set in the url, the value is not important as long as it is an integer)
4. Try to access page 2 via the pagination

**Expected behavior**
The user should get the results from page 2, starting with an offset equal to resultsPerPage.

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.30
 - Browser: Firefox
 - EXT:solr Version: 11.2.0

**Additional context**
I think the problem is related to this line https://github.com/TYPO3-Solr/ext-solr/blob/645f307383aa26e056131a6be63cc7be3a5624d2/Classes/Domain/Search/SearchRequestBuilder.php#L82
When removing this line, the pagination works.

**Comment by dkd-kaehm** [comment]
@codemonkey1988 
I can not reproduce the issue on solr-ddev-site@release-11.2.x.
Choose per per-page in browser and call:
https://solr-ddev-site.ddev.site/content-examples/form-elements/search?tx_solr[page]=2&tx_solr[q]=*

---
We want more information:

* is custom tmplate applied?
* what happens exactly(Exception trace, what happens?)
* is the used value for PerPage in a list of TypoScript config -> https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Configuration/Reference/TxSolrSearch.html#results-resultsperpageswitchoptions
* how to reproduce this bug on solr-ddev-site

---

PS: Please close this issue if you can not reproduce this on solr-ddev-site@release-11.2.x

**Comment by codemonkey1988** [comment]
Thanks for that super fast response.
I checked your demo site and indeed, the error is not reproducible there.

We have custom templates, but that's only half of the story. In our case, the JavaScript is the problem.
We are sending the `resultsPerPage` argument with every request when it differs from default. And when calling https://solr-ddev-site.ddev.site/content-examples/form-elements/search?tx_solr[page]=2&tx_solr[resultsPerPage]=50&tx_solr[q]=* the user end up on page 1.

But this is more of a questionable feature request than a bug I think.

Sorry for the inconvenience and a big thanks for your quick reply and help.
