### ISSUE TITLE
[BUG] SearchUriBuilder::$routingService must not be accessed before initialization

### ISSUE THREAD

**Issue by goldi42** [TYPO3-Solr/ext-solr#3288]
**Describe the bug**
If I open a page a firt time with the Solr SearchResults Plugin which have a static facet link created by SearchUriBuilder, I get an excepetion from TYPO3

```
ext/solr/Classes/Domain/Search/Uri/SearchUriBuilder.php line 385
Typed property ApacheSolrForTypo3\Solr\Domain\Search\Uri\SearchUriBuilder::$routingService must not be accessed before initialization
```

**To Reproduce**
1. Create a Viewhelper, which create a link to a facet
2. Add the Viewhelper to the resultpage Template
3. Empty all TYPO3 Caches
4. Open the resultpage and see the error

**Expected behavior**
No Error while open the page for first time

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.12
 - Browser: chrome
 - EXT:solr Version: 11.5.0-rc-2
 - Used Apache Solr Version: 8.11.1
 - PHP Version: 8.1

**Comment by dkd-kaehm** [comment]
@goldi42 
Thanks for reporting, please check and review #3290.

**Comment by goldi42** [comment]
Thanks @dkd-kaehm
