### ISSUE TITLE
Indexing of pages failes: Could not create a valid URL to get frontend data ...

### ISSUE THREAD

**Issue by intertain** [TYPO3-Solr/ext-solr#3301]
Hi, I have a problem indexing pages in Backend. Indexing of news is working. 

TYPO3 11.5.12
PHP 8.1 (too high? It worked with PHP 8.0 on DEV Server )

`1311080805: RuntimeException: Could not create a valid URL to get frontend data while trying to index a page. Created URL: (...)/kontakt-formular in /var/www/(...)/typo3conf/ext/solr/Classes/Domain/Index/PageIndexer/Helper/UriBuilder/AbstractUriStrategy.php:111
Stack trace:
#0 /var/www/rw_bodensee_p/releases/0/public/typo3conf/ext/solr/Classes/IndexQueue/PageIndexer.php(253): ApacheSolrForTypo3\Solr\Domain\Index\PageIndexer\Helper\UriBuilder\AbstractUriStrategy->getPageIndexingUriFromPageItemAndLanguageId()`

Any idea?

**Comment by dmitryd** [comment]
It usually means that your site configuration is not good enough for solr. For example, this is wrong for solr:

```yaml
base: example.com
```

or this:

```yaml
base: '//example.com/'
```

or this:

```yaml
base: '/'
```

or this:

```yaml
base: 'https://example.com'
```

You need a FQDN with a slash in the end:

```yaml
base: 'https://example.com/'
```

Same for `baseVariants`.

By the way, you should not ask here, you should ask in the Slack support channel: https://typo3.slack.com/archives/C02FF05Q4

**Comment by intertain** [comment]
You where right, that solved it. Thanks a lot.
