### ISSUE TITLE
[BUG] Infinite loop/recursion in Indexer if root page is a sysfolder having a ts template

### ISSUE THREAD

**Issue by BrandSven** [TYPO3-Solr/ext-solr#3306]
**Describe the bug**
\ApacheSolrForTypo3\Solr\FrontendEnvironment\Tsfe -> getPidToUseForTsfeInitialization() runs into an infinite recursion loop if the root page is a sysfolder with a ts template, resulting in a Fatal Error due to exceeded memory limit.

**To Reproduce**
Consider the following site structure:

[Root]
- [FOLDER] General storage folder (containing a TS template)
- - [FOLDER] News
- [PAGE] Home (containing a TS template)

News records (or other records, like contacts, events, ...) are stored in a subfolder under the "General storage folder". 
The default TS indexing configuration for news is used.

In this setup, the indexer runs into an infinite loop (recursion) in:
\ApacheSolrForTypo3\Solr\FrontendEnvironment\Tsfe -> getPidToUseForTsfeInitialization()

**Expected behavior**
The recursion should be detected and handled with a meaningful exception message.

This can be done by checking $pidToUse and $rootPageId before making the recursive call in line 380.

```
protected function getPidToUseForTsfeInitialization(int $pidToUse, ?int $rootPageId = null): ?int
{
    $incomingPidToUse = $pidToUse;
    $incomingRootPageId = $rootPageId;
    [...]
    if ($pidToUse == $incomingPidToUse && $rootPageId == $incomingRootPageId) {
       throw new Exception\Exception(
                "Infinite recursion detected while looking for the closest page with active template to page \"$askedPid\" . Please note that the page with active template (usually the root page of the current tree) MUST NOT be a sysfolder.",
                1637339476
        );
    }
    return $this->getPidToUseForTsfeInitialization($pidToUse, $rootPageId);
}
```

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.13
 - Browser: any
 - EXT:solr Version: 11.5.0-rc-2
 - Used Apache Solr Version: doesn't matter
 - PHP Version: 7.4
 - MySQL Version: 5.7

**Comment by dkd-kaehm** [comment]
@BrandSven 
Please provide a pull request with your suggestion.

**Comment by BrandSven** [comment]
There you got, pull request submitted
