### ISSUE TITLE
Adding the possibility to enrich 'foreignMatchFields'

### ISSUE THREAD

**Issue by AissamHamdi** [TYPO3-Solr/ext-solr#331]
Hi,

I'd like to contribute to EXT:solr by adding the possibility to enrich 'foreignMatchFields'.
My need was that I wanted to be able to index the media but only those who have the "showinpreview" box checked

This is the proposition :

- TS

```
plugin.tx_solr.index.queue.news.fields{
	media_stringM = SOLR_RELATION
	media_stringM {
		localField = media
		multiValue = 1
		foreignLabelField = image
		foreignMatchFields {
			showinpreview = 1
		}
	}
}
```

- Add in Classes/ContentObject/Relation.php line 132

` $foreignMatchFields = $this->configuration['foreignMatchFields.'];`

- Replace by Classes/ContentObject/Relation.php line 140-141 

`$relatedItems = $this->getRelatedItemsFromForeignTable($localFieldName,$localRecordUid, $localFieldTca, $parentContentObject, $foreignMatchFields);`

- Add param to function getRelatedItemsFromForeignTable Classes/ContentObject/Relation.php line 288 add 

```
/**
 * Gets the related items from a table using a 1:n relation.
 *
 * @param string $localFieldName Local table field name
 * @param integer $localRecordUid Local record uid
 * @param array $localFieldTca The local table's TCA
 * @param ContentObjectRenderer $parentContentObject parent content object
 * @param array $foreignMatchFields Foreign match fields
 * @return array Array of related items, values already resolved from related records
 */
protected function getRelatedItemsFromForeignTable(
	$localFieldName,
	$localRecordUid,
	array $localFieldTca,
	ContentObjectRenderer $parentContentObject,
	$foreignMatchFields
) {
```

- Add Classes/ContentObject/Relation.php line 327 

```
if(!empty($foreignMatchFields)){
	$matchFieldQueryParts = array();
	foreach ($foreignMatchFields as $fieldName => $value) {
		$matchFieldQueryParts[] = $foreignTableName . '.' . $fieldName . '=' . $GLOBALS['TYPO3_DB']->fullQuoteStr($value,$foreignTableName);
	}
	$whereClause .= ' AND (' . implode('AND ',$matchFieldQueryParts) . ')';
}
```

Do you think it would be possible to integrate it into the EXT:solr ?

Forgive me but this is the first time I proposed a contribution. 
I hope you will be understanding

Best regards,

Aissam

**Comment by timoschmidt** [comment]
@AissamHamdi 

Hi Aissam, the Feature you desribed sounds reasonable. Are you able to create a pull request? Otherwise i would integrate it as soon as i have time.

**Comment by AissamHamdi** [comment]
Hi Timo,

I prefer that you integrate it when you have time.

Thanks a lot.

2016-04-08 8:52 GMT+02:00 Timo Schmidt <notifications@github.com>:

> @AissamHamdi <https://github.com/AissamHamdi>
>
> Hi Aissam, the Feature you desribed sounds reasonable. Are you able to
> create a pull request? Otherwise i would integrate it as soon as i have
> time.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/TYPO3-Solr/ext-solr/issues/331#issuecomment-207252063>
>



-- 
Aissam Hamdi

**Comment by timohund** [comment]
Hi @AissamHamdi ,

should work with https://github.com/TYPO3-Solr/ext-solr/pull/460. Can you please open a new issue if you need something else?
