### ISSUE TITLE
[BUG] make sure that $currentPageNumber in resultsAction is always >= 1

### ISSUE THREAD

**Issue by bigahuna** [TYPO3-Solr/ext-solr#3323]
**Is your feature request related to a problem? Please describe.**

We run a large TYPO3 project with about 60 different Sites, most of them use solr for search.
In our logs we see lots of entries like this:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1573047338: Argument $currentPageNumber must be greater than 0 | InvalidArgumentException thrown in file /var/www/xyz.de/typo3/public/typo3/sysext/core/Classes/Pagination/AbstractPaginator.php in line 177. Requested URL: https://xyz.de/suche?tx_solr%5Bfilter%5D%5B214%5D=type%3Atx_solr_file&tx_solr%5Bpage%5D=0`

The related request urls are all similar to this: 

https://xyz.de/suche?tx_solr[page]=0

**Describe the solution you'd like**
In solr/Classes/Controller/SearchController -> resultsAction():
Make sure that the $currentPage is always >= 1. See following proposal:

```
public function resultsAction(): ResponseInterface
{   
    ...
    $currentPage = $this->request->hasArgument('page') ? (int)$this->request->getArgument('page') : 1; 

    ## proposal: ensure a valid $currentPage START
    if($currentPage < 1) $currentPage = 1;    
    ## proposal: ensure a valid $currentPage END

    $itemsPerPage = ($searchResultSet->getUsedResultsPerPage() ?: $this->typoScriptConfiguration->getSearchResultsPerPage(10));
    ...

}
```

**Target versions**
Release 11.5.0-rc-4 or Release 11.5.0-rc-5

Regards
Mike

**Comment by dkd-kaehm** [comment]
@bigahuna 
Thanks for this proposal.
Please create a pull-request for this issue.
