### ISSUE TITLE
[BUG] Can't index a translated record outside of rootpage

### ISSUE THREAD

**Issue by Raidri** [TYPO3-Solr/ext-solr#3325]
**Describe the bug**
I'm not pretty sure if it's a bug, but my storage folder is outside the rootpage. When I run the index process, the default language will be indexed but the translated entity not because of this error: "The rootPageRecord for the given rootPageRecord ID '10' is not marked as root rootPageRecord and can therefore not be used as site root rootPageRecord."

my storage folder has the PID 2 and the storage folder with the records have the ID 10.

Here is a snippet from my index config
```typoscript
articles = 1
            articles  {
                table = tx_ofproduct_domain_model_article
                additionalPageIds = 2,{$of_webapi.settings.storage.steutePid},{$of_webapi.settings.storage.nexyPid},{$of_webapi.settings.storage.meditecPid}
                additionalWhereClause = NOT deleted AND NOT hidden
                indexingPriority = 1
                fields {
                    title = title
                    url = TEXT
                    url {
                        typolink.parameter = {$of_product.settings.pages.articleDetailPid}
                        typolink.additionalParams = &tx_ofproduct_articledetail[article]={field:uid}
                        typolink.additionalParams.insertData = 1
                        typolink.returnLast = url
                        typolink.useCacheHash = 1
                    }

                }
            }
```

I think my problem ist that function: 

```php
/**
     * Gets the Site for a specific root page-id.
     *
     * @param int $rootPageId Root page Id to get a Site object for.
     * @return SiteInterface Site for the given page-id.
     * @throws DBALDriverException
     */
    public function getSiteByRootPageId(int $rootPageId)
    {
        $cacheId = 'SiteRepository' . '_' . 'getSiteByPageId' . '_' . $rootPageId;

        $methodResult = $this->runtimeCache->get($cacheId);
        if (!empty($methodResult)) {
            return $methodResult;
        }

        $methodResult = $this->buildSite($rootPageId);
        $this->runtimeCache->set($cacheId, $methodResult);

        return $methodResult;
    }
```

The translated record fails in the` $this->buildSite` method because there is not validation with this settings basic.useConfigurationTrackRecordsOutsideSiteroot. Could that be?

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.14
 - EXT:solr Version:11.5.0-rc-3
 - Used Apache Solr 8.11.1
 - PHP Version: 8.1

**Comment by dkd-kaehm** [comment]
I'll close this issue as there is nothing we can do from our side.

See: https://forge.typo3.org/issues/95688

### Workaround: 

Move the storage folder inside of site/root-page with all in system available languages. 
If no site with all languages exists, create a "virtual" one and put all the languages from other sites together. 
Make sure the language IDs are exact same and do not interference across the sites.
