### ISSUE TITLE
A TypeError occurs in the backend page view when TemplaVoilaPlus is installed

### ISSUE THREAD

**Issue by thomas-burger-de** [TYPO3-Solr/ext-solr#3327]
When TemplaVoilaPlus is used and the plugin "Search: Form, Result, Additional Components" is placed on a page, I get the following error message:

`Argument 2 passed to ApacheSolrForTypo3\Solr\Controller\Backend\PageModuleSummary::initialize() must be an instance of TYPO3\CMS\Backend\View\PageLayoutView, instance of Ppi\TemplaVoilaPlus\Controller\Preview\ListController given, called in /html/typo3/typo3conf/ext/solr/Classes/Controller/Backend/PageModuleSummary.php on line 73`

**Comment by dkd-kaehm** [comment]
@thomas-burger-de 
Please provide infos about the versions stack by using issue assistant from GH. 
https://github.com/TYPO3-Solr/ext-solr/issues/new?assignees=&labels=&template=bug_report.md&title=%5BBUG%5D+Please+add+a+speaking+title
