### ISSUE TITLE
[BUG] Reports module crashes with 503 error

### ISSUE THREAD

**Issue by peterkraume** [TYPO3-Solr/ext-solr#3349]
**Describe the bug**
The reports module crashes with a 503 error:
```
Argument 3 passed to ApacheSolrForTypo3\Solr\System\Solr\Node::__construct() must be of the type int, string given, called in /.../web/typo3conf/ext/solr/Classes/System/Solr/Node.php on line 92
```

**To Reproduce**
1. Go to Reports Module
2. See error

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.16
 - EXT:solr Version: 11.5.0
 - PHP Version: 7.4.30

**Comment by peterkraume** [comment]
It's not an error of EXT:solr but of EXT:tika. I'll provide a patch here:
https://github.com/TYPO3-Solr/ext-tika/issues/190

**Comment by dkd-kaehm** [comment]
@peterkraume 
Thanks for reporting that issue. I can not reproduce this issue on solr-ddev-site. 
Is dotenv in your setup?
If so, byside of casting  to int on Classes/System/Solr/Node.php:92
the troubles are possible in other sources. So we want to check the behavior for port as strings.

Relates: #2533

**Comment by peterkraume** [comment]
@dkd-kaehm I fixed the problem already. See https://github.com/TYPO3-Solr/ext-tika/issues/190
