### ISSUE TITLE
Unable to index images due to DeferredBackendImageProcessor

### ISSUE THREAD

**Issue by abvdveen** [TYPO3-Solr/ext-solr#3353]
Typo3 11.5.16 combined with solr 11.5 generates invalid image path strings.
See [https://forge.typo3.org/issues/98174](https://forge.typo3.org/issues/98174)

Using TS like this in an indexer config:

```
image_stringS = FILES
image_stringS {
    references {
        table = tx_extname_domain_model_project
        fieldName = image
    }
    renderObj = IMG_RESOURCE
    renderObj {
        file.import.data = file:current:uid
        file.treatIdAsReference = 1
        file.width = 100
        file.height = 100
    }
}
```

produces something like this in the index:

`typo3/image/process?token=5be607cb4004796fcb1a7c4aaf83138fcaf44b20&id=544190`

Adding 

`unset($GLOBALS['TYPO3_CONF_VARS']['SYS']['fal']['processors']['DeferredBackendImageProcessor']);`

to the ext_localconf.php of the ext fixes it.

**Comment by abvdveen** [comment]
I missed this one when searching for an existing issues, describes the same problem:  #2828

**Comment by abvdveen** [comment]
See also [https://forge.typo3.org/issues/93593](url)

**Comment by abvdveen** [comment]
And here [https://forge.typo3.org/issues/93245](url)

**Comment by dkd-kaehm** [comment]
@abvdveen 
Thanks for exploration.
As it is the same as #2828, I'll close this.
