### ISSUE TITLE
[BUG] Fallback of solr_core_read does not work

### ISSUE THREAD

**Issue by christophlehmann** [TYPO3-Solr/ext-solr#3362]
**Describe the bug**

This is about an empty `solr_core_read` in a site language.

As per default (last parameter in line 293 = true) a site language will be indexed, whether or not `solr_core_read` is empty.

![Bildschirmfoto 2022-10-18 um 11 50 53](https://user-images.githubusercontent.com/4953689/196398651-9a9a94ee-23bd-4eeb-aa60-e0e99fe9fcda.png)

In Line 306 `core_en` should be the default (fallback) core, if non given (=null value). But i couldn't be null, since its a string field and is might be just empty. 

An empty string leads to a wrong `path` and indexing fails.

**Expected behavior**

It could be more explizit: When a core is given and not empty, then index that language, else not. 

We can see it also as a feature, so that one can deactivate indexing a language with an empty `solr_core_read` property.

**Used versions (please complete the following information):**
 - TYPO3 Version:  ^11
 - EXT:solr Version: ^11

**Comment by christophlehmann** [comment]
@dkd-kaehm If the fix is fine for your, then i would go on with fixing the tests and extending the docs

**Comment by dkd-kaehm** [comment]
@christophlehmann 
LGTM, please open a pull request with this changes to start the tests.
