### ISSUE TITLE
[TASK] Rewrite Index Inspector using Extbase/Fluid

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/ext-solr#34]
Let's remove ExtJs from the Index Inspector backend module.

Possible replacement: http://www.jquery-bootgrid.com/

**Comment by timohund** [comment]
We should add a Controller in Classes/Controller/Backend with a FluidStandaloneView and use this. During the implemation we should also move the Logic to retrieve that data of the IndexInspector into a Service and test that, to keep the controller logic slim.
