### ISSUE TITLE
[BUG] Solr configuration not found because the root page is not configured

### ISSUE THREAD

**Issue by ochorocho** [TYPO3-Solr/ext-solr#3407]
**Describe the bug**

When editing e.g. a news record on a page where solr is not configured 

```
Call to a member function getSolrConfiguration() on null
```

**To Reproduce**
* Create a Mutli-Site setup. A site serves as "Content Storage" - so it is not actually used in the frontend (solr_enabled_read: false).
* Create news records on the "Content Storage"-Site 
* Create a news record and try to save it.

**Expected behavior**

Do not update or index items on a page that is not configured to use solr.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4623070/202127372-ca5e0103-4a61-46ee-b651-9fc79879576b.png)

**Used versions:**
 - TYPO3 Version: [e.g. 11.5.6]
 - Browser: Firefox
 - EXT:solr Version:  11.5.0 
 - Used Apache Solr Version: 8.11.1
 - PHP Version:  7.4.30
 - MySQL Version: 5.7.38

**Additional context**

**Comment by dkd-kaehm** [comment]
@ochorocho 
The pull request must go against this repository not on your fork.

**Comment by ochorocho** [comment]
@dkd-kaehm 🤦 sorry for the mess.
Created the PR against this repository, added "Fixes" to the commit message.
