### ISSUE TITLE
[TASK] Allow stdWrap on MM SOLR_RELATION cObject

### ISSUE THREAD

**Issue by b3nkai** [TYPO3-Solr/ext-solr#3408]
We currently can use a stdWrap on SOLR_RELATION like this:

```
plugin.tx_solr.index.queue {
	pages {
		myfield_stringM = SOLR_RELATION
		myfield_stringM {
			localField = myfield
			stdWrap.dataWrap = before | after
		}
	}
}
```

This is working fine for 0,n relation but with n,n (MM) relations, the stdWrap is not applied.

This is due to the fact that getRelatedItemsFromMMTable() method does not call stdWrap() method where getRelatedItemsFromForeignTable() does by calling resolveRelatedValue()

You can test on a MM relation with sys_category for example.

Target versions:
* 12.0.x/main
* 11.5.x

Relates: #3152

**Comment by dkd-kaehm** [comment]
@dkd-friedrich 
Please port this in 11.5.x

**Comment by dkd-friedrich** [comment]
Fixed with https://github.com/TYPO3-Solr/ext-solr/pull/3484 and https://github.com/TYPO3-Solr/ext-solr/pull/3475
