### ISSUE TITLE
[BUG] PHP Warning Trying to access array offset on value of type null in Util.php

### ISSUE THREAD

**Issue by froemken** [TYPO3-Solr/ext-solr#3413]
**Describe the bug**

PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3conf/ext/solr/Classes/Util.php line 119

**To Reproduce**
Delete a record which is not referenced to an existing col_pos. Happen when you switch backend layouts.

**Expected behavior**
Check value of BackendUtility::getRecord before accessing it as array

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.19
 - Browser: Chrome
 - EXT:solr Version: 11.5.0
 - Used Apache Solr Version: 8.11.1
 - PHP Version: 8.1.11
 - MySQL Version: 10.2.44-MariaDB-1:10.2.44+maria~bionic-log - mariadb.org binary distribution

**Comment by dkd-kaehm** [comment]
@froemken 
Thanks for reporting that issue.
I can not reproduce this issue currently within solr-ddev-site
ON:
* TYPO3 11.5.19 + 21
* PHP 8.1.8 
* EXT:solr 11.5.0, [release-11.5.x@01d568b](https://github.com/TYPO3-Solr/ext-solr/commit/01d568ba44557f430086639ae5bd3b9d1809af75)

Could you please check if #3427 resolves this issue?

**Comment by froemken** [comment]
Hi @dkd-kaehm 

yes, this will solve the issue, too.

The return value of BU::getRecord() is array|null that's why I thought you will add a test for array instead, before accessing the array value one line below.

Stefan
