### ISSUE TITLE
[BUG] Wrong base URL for news entries

### ISSUE THREAD

**Issue by marcel-lange-sns** [TYPO3-Solr/ext-solr#3417]
We have a multitree setup like that:

Domain A => core_de
-> Page 1
-> Page 2
-> Page 3
-> NEWS STORAGEFOLDER

Domain B => core_de
-> Page 1
-> Page 2
-> Page 3
-> NEWS STORAGEFOLDER

Domain C => core_en
-> Page 1
-> Page 2
-> Page 3
-> NEWS STORAGEFOLDER

When indexing via scheduler, the generated news urls in the indexed document  have the base domain of the first root tree (Domain A). Absolute URLS are generated although its not enforced for the typolink. 

Indexer config:
```
news {
        table = tx_news_domain_model_news

        fields {
            abstract = teaser

            author = author
            authorEmail_stringS = author_email

            title = title

            datetime_stringS = TEXT
            datetime_stringS {
                field = datetime
                date = d.m.Y H:i
            }

            datetime_dateS = TEXT
            datetime_dateS {
                field = datetime
                date = Y-m-d\TH:i:s\Z
            }

            content = SOLR_CONTENT
            content {
                cObject = COA
                cObject {
                    10 = TEXT
                    10 {
                        field = bodytext
                        noTrimWrap = || |
                    }

                    20 = SOLR_RELATION
                    20 {
                        localField = content_elements
                        foreignLabelField = bodytext
                        singleValueGlue = | |
                    }

                }
            }

            category_stringM = SOLR_RELATION
            category_stringM {
                localField = categories
                foreignLabelField = uid
                multiValue = 1
            }


            keywords = SOLR_MULTIVALUE
            keywords {
                field = keywords
            }

            tags_stringM = SOLR_RELATION
            tags_stringM {
                localField = tags
                multiValue = 1
            }

            url = CASE
            url {
                key.field = type

                # Internal
                1 = TEXT
                1 {
                    if.isTrue.field = internalurl
                    typolink.parameter.field = internalurl
                    typolink.useCacheHash = 1
                    typolink.returnLast = url
                }

                # External
                2 = TEXT
                2 {
                    if.isTrue.field = externalurl
                    field = externalurl
                }

                default = TEXT
                default {
                    typolink.parameter = {$plugin.tx_news.settings.detailPid}
                    typolink.additionalParams = &tx_news_pi1[controller]=News&tx_news_pi1[action]=detail&tx_news_pi1[news]={field:uid}&L={field:__solr_index_language}
                    typolink.additionalParams.insertData = 1
                    typolink.useCacheHash = 1
                    typolink.returnLast = url
                    forceAbsoluteUrl = 0           
                }
            }
        }
```
        
When indexing is done manuall over the SOLR Index Queue Tool, relatiev URLs are generated as expected.  
Indexing of normal pages works as expected as well.

**To Reproduce**
1. run force reendix scheduler for Site A (Domain A)
2. run force reendix scheduler for Site B (Domain B)
3. run Index  Queue Worker for Site A
4. run Index  Queue Worker for Site B
5. check the index of NEWS STORAGEFOLDER via Solr extensions info tool
6. there are absolute urls genered with the base-domain of site A

**Expected behavior**
In each tree the defined base domain defined via site configuration should be used to generate the urls or only relative URLs should begenerated if forceAbsoluteUrl isn't set for the typolink.

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.19
 - EXT:solr Version: 11.5.0
 - Used Apache Solr Version: 8.11.1
 - PHP Version: 7.4.0

**Comment by marcel-lange-sns** [comment]
Workarround is just to replace the domain in the url:
`url.stdWrap.replacement{
                10 {
                    search = #http(s)?:\/\/.*\/#U
                    replace = /
                    useRegExp = 1
                }
            }`

**Comment by dmitryd** [comment]
@marcel-lange-sns 

> only relative URLs should begenerated if forceAbsoluteUrl isn't set for the typolink.

This does not work like that anymore. Sometimes routing will generate absolute urls regardless of `forceAbsoluteUrl` setting.


Your TS:

> typolink.parameter = {$plugin.tx_news.settings.detailPid}

Is it only the host in the url, which is wrong? If all your domains have the same url for the detailPid, could you move those pages into different places (just for testing) and try indexing again? Will the url change or does it still point to the page in the first domain? If it points to the first domain, then the problem would be related to the constant.

**Comment by marcel-lange-sns** [comment]
@dmitryd 

> This does not work like that anymore. Sometimes routing will generate absolute urls regardless of forceAbsoluteUrl setting.
THX, I didn't now that

> typolink.parameter = {$plugin.tx_news.settings.detailPid}

> Is it only the host in the url, which is wrong? If all your domains have the same url for the detailPid, could you move those pages into different places (just for testing) and try indexing again? Will the url change or does it still point to the page in the first domain? If it points to the first domain, then the problem would be related to the constant.

Hence my workaround works, i din't checked that before. 
But indeed the uri path is the same for all pages (/blog/detail). Only the domain ist different. 
And all except the initial page,  where  added by copy and paste. The URL of the masterpage, i've copied from, is taken without the workaround. 
I'll check the suggested moving of the detailpage asap.

**Comment by marcel-lange-sns** [comment]
> Possibly related: #3415

And THX again. We change the detail page ID in Typoscript per Site configuration like that:
```
#### UK (RootID 42) ####
[site("identifier") == "site_uk"]
    plugin.tx_news.settings.detailPid = 162
[global]
```
So the liket issue could be the reason very well!
