### ISSUE TITLE
[TASK] Replace deprecated QueryGenerator

### ISSUE THREAD

**Issue by 3l73** [TYPO3-Solr/ext-solr#3453]
**What should be done in the scope of this task?**

The class `\TYPO3\CMS\Core\Database\QueryGenerator` is deprecated and will be removed with TYPO3 v12 LTS.

The method `getTreeList()` used could be replaced with ``\TYPO3\CMS\Core\Domain\Repository\PageRepository::getDescendantPageIdsRecursive()` or reimplemented.

**Comment by sabbelasichon** [comment]
This issue seems to be already tackled? Can it be closed?
