### ISSUE TITLE
[BUG] Solr Ext in Docker Environment with nginx and fpm cant call pages with curl

### ISSUE THREAD

**Issue by mceikens** [TYPO3-Solr/ext-solr#3474]
Hey,
i’m in trouble with tx_solr (version: 11.5.1), typo3 (version: 11.5.22) in my docker setup with nginx, fpm (php 8), database, solr.
My solr pages queue can’t index my pages because they do a curl request on the page.
So my docker environment can handle this, because i using a nginx proxy between them.
But i have allways an error.
„_Failed indexing page Index Queue item: 219935 url: […] in /usr/share/nginx/html/app/web/typo3conf/ext/solr/Classes/IndexQueue/PageIndexer.php:337_„

I tried a curl request from my fpm container to my domain, not localhost, and i get a html markup result.

CURL Requests i tried: 
`curl http://my.local-domain:8080/startseite.html -x nginx-proxy:80`

But a request with the same specs in solr, typo3 and guzzle gets me a error like above.
If i doesnt use a proxy i got a „_Connection refused_“ error.
So my question has anyone a idea?
Configured Settings
in AdditionalConfiguration.php
```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['sites'][1]['domains'] = ['my.local-domain:8080'];
$GLOBALS['TYPO3_CONF_VARS']['HTTP']['proxy'] = ['http' => "[http://nginx-proxy:80](http://nginx-proxy/)"];
```
TypoScript
```
plugin.tx_solr.solr.port = 8080
plugin.tx_solr.index.queue.pages.indexer.frontendDataHelper.port = 8080
plugin.tx_solr.index.queue.pages.indexer.frontendDataHelper.scheme = http
```
All other params in site config are correct my news table will be indexed correctly.
Only my pages will not indexed.

**Comment by dkd-kaehm** [comment]
Make sure your proxy delegates all headers, incl. 'X-Tx-Solr-Iq'
because page indexer uses headers for auth of EXT:solr internal requests.
See: 

https://github.com/TYPO3-Solr/ext-solr/blob/f9edd8bc4935baac066329d76bdf94b41f914d02/Classes/IndexQueue/PageIndexerRequest.php#L38

I'll close the issue.

**Comment by mceikens** [comment]
So i'll open this issue again.

I'll tried in multiple instances and versions of typo3 and solr, i check that all headers will delegated to my php fpm container, but in every case it doesnt work.

Only the page indexer will fail on the dev system (localhost domain)

In a production setup which we can reach over a classic domain the page indexer will work, but only on a dev system it doesnt work.

Even i tried to jump over a jumphost or a nginx proxy it doesnt work.

Why you will index the pages with a curl request and not over normal database requests?

**Comment by dkd-kaehm** [comment]
Please ask the question in community TYPO3 Slack ext-solr channel. 
Most probably in your setup is something wrong, which leads to this trouble.

The pages must be indexed via real FE of TYPO3 to be able to fetch real and exact same data, which the real user will see on the page call. 
That because countless configuration variants of TYPO3 for page rendering, the variants of ACL combinations on page and CEs.

Please refer to the EXT:solr docs:

Especially: 
https://docs.typo3.org/p/apache-solr-for-typo3/solr/11.5/en-us/GettingStarted/Index.html
and
https://docs.typo3.org/p/apache-solr-for-typo3/solr/11.5/en-us/FAQ/Index.html

**Comment by mceikens** [comment]
I have ask the question in slack. But i haven't get a helpful message to this problem.

At second i read the documentation and your code. It doesn't work!
