### ISSUE TITLE
[TASK:T12] TYPO3 Breaking: #96659 - Registration of cObjects via TYPO3_CONF_VARS

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#3476]
Move to new way of TYPO3 12+ to register custom content objects.
See: [Breaking: #96659 - Registration of cObjects via TYPO3_CONF_VARS](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96659-RegistrationOfCObjectsViaTYPO3_CONF_VARS.html)

**Comment by sabbelasichon** [comment]
@dkd-kaehm This seems to be tackled and merged already. Can the issue be marked as solved?
