### ISSUE TITLE
[FEATURE] Configurable delimiter for manual sort order on facet

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Solr/ext-solr#3483]
The delimiter of the manual sort order is currently hardcoded to `,`.  See https://github.com/TYPO3-Solr/ext-solr/blob/main/Classes/Domain/Search/ResultSet/Facets/AbstractFacetParser.php#L155

```php
$fields = GeneralUtility::trimExplode(',', $facetConfiguration['manualSortOrder']);
```

However when using solr for a products, a `,` is often used.

I suggest to add a new property `manualSortOrderDelimiter` which can be any char.

if accepted I can provide a PR

**Comment by dkd-kaehm** [comment]
@georgringer 
Thank for this suggestion.
This TypoScript setting is usable for community, so it can be applied.
Users can then provide the facet options containing a comma chars like(See the docs [for manualSortOrder](https://docs.typo3.org/p/apache-solr-for-typo3/solr/11.5/en-us/Configuration/Reference/TxSolrSearch.html#faceting-facets-facetname-manualsortorder) )

```
plugin.tx_solr.search.faceting.facets.[facetName] {
  manualSortOrder = A, B; C, D; E, F;
  manualSortOrderDelimiter = ;
}
``` 

Alternative way/feature could be the escaping of commas like:
```
plugin.tx_solr.search.faceting.facets.[facetName] {
  manualSortOrder = A\, B, C\, D, E\, F
}

**Comment by georgringer** [comment]
thanks @dkd-kaehm for your comment, however I don't know how to proceed. is the idea accepted. do you wanna handle that or should I?

**Comment by dkd-kaehm** [comment]
> thanks @dkd-kaehm for your comment, however I don't know how to proceed. is the idea accepted. do you wanna handle that or should I?

What do you think about?

> Alternative way/feature could be the escaping of commas like:
> 
> ```
> plugin.tx_solr.search.faceting.facets.[facetName] {
>    manualSortOrder = A\, B, C\, D, E\, F
> }
> ```

**Comment by georgringer** [comment]
TBH I don't like that too much. because what if the `\` is also part of the label. if there are lots of special chars, someone could just use `###` as split string and it would be fine. there is no need to limit the delimiter to a single character

**Comment by dkd-kaehm** [comment]
OK, fine, then we can go the `manualSortOrderDelimiter` setting way ;)

**Comment by georgringer** [comment]
@dkd-kaehm should I provide a patch or do you wanna go ahead?

**Comment by dkd-kaehm** [comment]
You can make it.
