### ISSUE TITLE
[TASK:T12] Style BE->Index Queue Module :: CSH

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#3488]
The CSH was removed from TYPO3 See: [#97312](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97312-DeprecateCSH-relatedMethods.html)

Currently already removed in EXT:solr T12 branch
`Classes/ViewHelpers/Backend/Button/HelpButtonViewHelper.php` 
and usage in `Resources/Private/Templates/Backend/Search/IndexQueueModule/Index.html` of it 
   
```
   "<solr:backend.button.helpButton title="Index Queue Initialization" description="{f:translate(key:'solr.backend.index_queue_module.help')}" />"
```
   
The markup/style must be restored.

**Comment by sfroemkenjw** [comment]
Solved with: https://github.com/TYPO3-Solr/ext-solr/pull/3658
