### ISSUE TITLE
[BUG] RecordMonitor doesn't respect Indexing priority

### ISSUE THREAD

**Issue by YKWeyer** [TYPO3-Solr/ext-solr#3492]
**Describe the bug**
Indexing priorities are considered only when using the Index Queue module. Newly-added items always get a default priority of `0`.

**To Reproduce**

1. Set an `indexingPriority` to an existing queue (e.g. `plugin.tx_solr.index.queue.news.indexingPriority = 50`)
2. Create a new item of the corresponding type (e.g. `news`) and save the record
3. Open the `tx_solr_indexqueue_item` table: the corresponding line gets the default priority (`0`)

**Expected behavior**
The queued item should probably get an indexingPriority of `50`

**Additional context**
We encountered this issue with plugin-version `11.0.7`, but as far as I can see in the latest codebase, there still are no mentions of the indexingPriority in [`QueueItemRepository::add`](https://github.com/TYPO3-Solr/ext-solr/blob/cbc7af1f0a7f8fe4e9b63bdff38b48384da16b97/Classes/Domain/Index/Queue/QueueItemRepository.php#L240).

Opening an issue to check if this is meant to be, or if it was just forgotten. I'm happy to provide a fix for this issue

---

Edit: sorry for the early submit and resulting edits, my finger slipped and I hit enter while editing the title 😅

**Comment by dkd-kaehm** [comment]
@YKWeyer 
Thanks for reporting that issue.
unfortunately the feature is not used on all required places.

Please kick the pull-request for this.

**Comment by YKWeyer** [comment]
@dkd-kaehm A bugfix was created under #3509. Let me know what you think :slightly_smiling_face:
