### ISSUE TITLE
Garbage collection tries to find rootpage for deleted page

### ISSUE THREAD

**Issue by akiessling** [TYPO3-Solr/ext-solr#3500]
**Describe the bug**
The error happens when i run the cleanup task from EXT:container https://github.com/b13/container/blob/master/Classes/Command/DeleteChildrenWithWrongPidCommand.php
A content element from soft-deleted page is about to be hard-deleted which triggers the EXT:solr GarbageCollector. 

Since the page that the container element belongs to is already soft-deleted, this triggers this exception in the end https://github.com/TYPO3-Solr/ext-solr/blob/main/Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php#L125

The exception probably needs to be caught in \ApacheSolrForTypo3\Solr\Domain\Index\Queue\RecordMonitor\Helper\RootPageResolver::buildResponsibleRootPageIds 

**To Reproduce**
Tricky... Should probably be reproduceable like this:

Soft-delete a page with a content element on it. 
Use the DataHandler to hard-delete the content element https://github.com/b13/container/blob/bf38dc3d4531132c895a563dbc4243cf4b54bbb8/Classes/Integrity/IntegrityFix.php#L43

**Expected behavior**
The missing rootpage should probably just be ignored

**Screenshots**
<img width="873" alt="image" src="https://user-images.githubusercontent.com/2895543/219786434-b039d719-d116-4933-bd03-d7c4fd86f350.png">

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.23
 - EXT:solr Version: 11.5.1
 - PHP Version: 8.1

**Comment by dkd-kaehm** [comment]
@dkd-friedrich 
Please check this out with awareness of "Exception handling improvements" task.
