### ISSUE TITLE
[BUG] Empty L-Queryparam in Opensearch URLs

### ISSUE THREAD

**Issue by infabo** [TYPO3-Solr/ext-solr#3521]
**Describe the bug**
Opensearch URLs are generated with empty L-queryparam

**To Reproduce**
1. Include opensearch typoscript
1. Go to `/?type=7567`
2. See URLs

**Expected behavior**
L-param has a value

**Screenshots**

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.24
 - Browser: any
 - EXT:solr Version: 11.5.1
 - Used Apache Solr Version: 8.11.1
 - PHP Version: 8.1.1
 - MySQL Version: -

**Additional context**

**Comment by dkd-kaehm** [comment]
Affected Versions:
* release-11.2.x
* release-11.5.x
* main
