### ISSUE TITLE
[BUG] PHP 8 warning in Util::isDraftRecord

### ISSUE THREAD

**Issue by dogawaf** [TYPO3-Solr/ext-solr#3531]
**Describe the bug**

Since an upgrade to php 8, I see this error in the logs:

```
PHP Warning: Trying to access array offset on value of type null in /var/www/html/web/typo3conf/ext/solr/Classes/Util.php line 119
```

**To Reproduce**

The error occurs in a php 8 setup, with TYPO3 11.5, when an editor save a content in the BE.
I was not able to reproduce the issue on my own, but the issue happens several times a day.

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.23
 - EXT:solr Version: [e.g. 11.5.0]
 - PHP Version:  8.0.27

**Comment by dogawaf** [comment]
The fix is maybe not the good one, because it can hide the real issue: why the record was not loaded?.

**Comment by koehnlein** [comment]
I can confirm this error and know how to reproduce it:

It occurs, when a record is deleted. For example a content element.

**Comment by baschny** [comment]
The fix https://github.com/TYPO3-Solr/ext-solr/commit/315ddf397e3f9cd8574288282d27bc49675ee6f4 does not really fix it completely. See https://github.com/TYPO3-Solr/ext-solr/pull/3642 for a more complete fix, this should / could also be backported to the 11 branch.
