### ISSUE TITLE
[BUG] Item 0 of field solr_enabled_read of TCA table site has no label

### ISSUE THREAD

**Issue by timdreier** [TYPO3-Solr/ext-solr#3563]
**Describe the bug**

```text
(1/1) #1440499338 UnexpectedValueException

Item 0 of field solr_enabled_read of TCA table site has no label
```

**To Reproduce**
1. open the site-module
2. edit any record

**Expected behavior**
No exception :)

**Used versions (please complete the following information):**
 - TYPO3 Version: 12.3.0
 - Browser: firefox
 - EXT:solr Version: v12 Branch
 - Used Apache Solr Version: [e.g. 8.11.1]
 - PHP Version: 8.1
 - MySQL Version: 8

**Comment by dkd-kaehm** [comment]
Fixed in #3564
