### ISSUE TITLE
[BUG:T12] "Reindex" button in "Solr Info"->"Index Documents" is gone

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#3580]
The button for reindexing document is gone.
This button we want again in TYPO3 12.
![Bildschirmfoto vom 2023-03-31 14-16-39](https://user-images.githubusercontent.com/25453927/229117757-7eb37606-e25b-429b-9541-de1bf0f00fc8.png)

**Comment by sfroemkenjw** [comment]
Solved with https://github.com/TYPO3-Solr/ext-solr/pull/3659
