### ISSUE TITLE
PHP Fatal error while trying to initialize pages queue from the Search > Index queue > Index Queue Initialization backend module

### ISSUE THREAD

**Issue by itekne** [TYPO3-Solr/ext-solr#361]
TYPO3 7.6.5
EXT:solrfal 2.1.2
EXT:solr 4.0.0

Since EXT:solr 4.0.0 update, get this error while trying to initialize pages queue from the Search > Index queue > Index Queue Initialization backend module :

#1: PHP Catchable Fatal Error: Argument 1 passed to ApacheSolrForTypo3\Solr\IndexQueue\Queue::getTableToIndexByIndexingConfigurationName() must be of the type array, object given, called in /var/www/xxx/web/typo3conf/ext/solrfal/Classes/Queue/Queue.php on line 60 and defined in /var/www/xxx/web/typo3conf/ext/solr/Classes/IndexQueue/Queue.php line 202 (More information)

Everything else, from indexing to results is OK.
Thanks !!!

**Comment by timoschmidt** [comment]
@itekne We know this. You'll need to update solrfal to Version 3.0.0, which will be released in the next days!

**Comment by itekne** [comment]
@timoschmidt Thank you

**Comment by timoschmidt** [comment]
@itekne Solrfal 3.0.0 is released now, you can update you extension from typo3-solr.com
