### ISSUE TITLE
[BUG] Cannot generate URLs for restricted detail PIDs

### ISSUE THREAD

**Issue by sascha-schieferdecker** [TYPO3-Solr/ext-solr#3615]
**Describe the bug**
 Cannot index restricted detail pages for e.g. news records anymore. Also happens with other custom indexers.

This worked with ext_solr 11.0.5 and TYPO3 10.4. 

Remark: If a parent page is restricted and set to extend this restriction to subpages, the generation of a detail link for results works. 

**To Reproduce**

Set access of a page to "show at any login" and put a news detail plugin on this page. The indexer can't get a link to the detail page anymore, the link generated always points to the login page. 

**Expected behavior**
The indexer should generate the link to the detailpage based on this TYPOSCRIPT:

```TYPOSCRIPT
default = TEXT
default {
	typolink.parameter = {$plugin.tx_news.settings.detailPid}
	typolink.additionalParams = &tx_news_pi1[controller]=News&tx_news_pi1[action]=detail&tx_news_pi1[news]={field:uid}&L={field:__solr_index_language}
	typolink.additionalParams.insertData = 1
	typolink.useCacheHash = 1
	typolink.returnLast = url
}
```

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.26
 - EXT:solr Version:  11.5.1/11.5.2
 - Used Apache Solr Version: Latest typo3solr/ext-solr:release-11.5.x
 - PHP Version: 7.4.33
 - MySQL Version: 5.7

**Comment by dkd-kaehm** [comment]
Please try https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/Typolink.html#linkaccessrestrictedpages

If it works, please create PR with description in FAQ in docs folder and add it to the TypoScript Examples file.

**Comment by sascha-schieferdecker** [comment]
It works 👍I'll create a PR.

**Comment by dmitryd** [comment]
Should this be set automatically by solr via [config.typolinkLinkAccessRestrictedPages](https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Setup/Config/Index.html#typolinklinkaccessrestrictedpages) when indexing?

**Comment by dkd-kaehm** [comment]
> Should this be set automatically by solr via [config.typolinkLinkAccessRestrictedPages](https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Setup/Config/Index.html#typolinklinkaccessrestrictedpages) when indexing?

I'll merge the provided pull-request.
IMHO the PR is fine for EXT:solrs responsibility.
The setting in config.typolinkLinkAccessRestrictedPages is global, can impact other plugins on that page.
