### ISSUE TITLE
[BUG] Problem with progressbar when running scheduler manualy

### ISSUE THREAD

**Issue by timoschmidt** [TYPO3-Solr/ext-solr#362]
Check what happens when the scheduler task is executed manually.

**Comment by dkd-friedrich** [comment]
It can occur that the progress bar is not displayed after executing the task manually, the reason for this is that depending on the locale setting the progress is returned with decimal comma and this invalid value cannot be evaluated.

EXT:solr initializes TSFE (`ApacheSolrForTypo3\Solr\Util::initializeTsfe`) for indexing and evaluates the TypoScript settings, including `config.locale_all`. If e.g. a german locale is configured PHP will use decimal comma and the progress bar will not be displayed.

**Comment by dkd-friedrich** [comment]
Issue exists in TYPO3 7.6.5 only. TYPO3 isn't setting LC_ALL currently, so this issue can be closed:

See:
- https://forge.typo3.org/issues/75825
- https://forge.typo3.org/issues/75141
- https://wiki.typo3.org/TYPO3_CMS_7.6.5
- https://wiki.typo3.org/TYPO3_CMS_7.6.6
