### ISSUE TITLE
[BUG] REOPEN Solr Ext in Docker Environment with nginx and fpm cant call pages with curl

### ISSUE THREAD

**Issue by mceikens** [TYPO3-Solr/ext-solr#3634]
See in this ticket, the state is currently the same: https://github.com/TYPO3-Solr/ext-solr/issues/3474

**Comment by dmitryd** [comment]
@mceikens Please, do not spam the bug tracker with support questions. This is not a bug in solr but a question for the TYPO3 slack at https://typo3.slack.com/archives/C02FF05Q4

**Comment by mceikens** [comment]
At first i didn't spam but okay.

At second i didn't get a answer of my question that is helpful
