### ISSUE TITLE
Latest supported solr version for EXT:solr 4.0.0 ?

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Solr/ext-solr#364]
Is the latest supported solr version still 4.10.4 
Or is 5.x supported too?
Actually solr 6.0 has already been releases recently too.

**Comment by dkd-janke** [comment]
Hello Andreas,

its still 4.10.
A short look at our roadmap: http://www.typo3-solr.com/en/solr-for-typo3/roadmap/
Support for Solr 5.0 is planned in Q4/2016
