### ISSUE TITLE
TYPO3 v12 compatibility

### ISSUE THREAD

**Issue by RZivaralam** [TYPO3-Solr/ext-solr#3684]
I would like to know when this plugin will be compatible with Typo 3 version 12?

**Comment by dkd-kaehm** [comment]
Work in progress, the main branch is altŕeady compatible with TYPO3 12.
Beta 12.0 will be released soonish. Stable release end of June - begin of July,
Please watch #3376 for open todos.

We want beta testers now. Please checkout current main and test it.
