### ISSUE TITLE
[BUG] FE-Plugin not working after Update to 3.1.2 (7.6 LTS)

### ISSUE THREAD

**Issue by Bufallo** [TYPO3-Solr/ext-solr#369]
After Updating the solr extension from version 3.1.1 to 3.1.2 (on TYPO3 LTS 7.6.5) my frontend is not working anymore.

I get the same error as mentioned here:
https://github.com/TYPO3-Solr/ext-solr/issues/117

Fatal error: Class 'Tx_Solr_ViewHelper_Lll' not found in /vagrant/typo3_src/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4536

I use a composer based setup.
When downgrading from 3.1.2 to 3.1.1 everything is working again after clearing the cache.

Greetings,
Benny

P.S.: Thanks for this awesome extension!

**Comment by timoschmidt** [comment]
I think this problem is related to composer. Installing the extension from packagist is working:

```bash
composer require "apache-solr-for-typo3/solr:3.1.2"
``` 

I'll investigate this issue.

**Comment by Bufallo** [comment]
Confirmed.
Replacing typo3-ter/solr with apache-solr-for-typo3/solr works.

**Comment by timoschmidt** [comment]
Since we do not need to use the class map in verion 5.x and greater because they are obsolete, i will close this issue.

**Comment by adymorz** [comment]
Closing this issue has the consequence that everyone trying to use solr 3.1.x from TER over composer in TYPO3 7.6 fails and looses some time, to find out, that including it in a different way (over packagist) solves the issue.

**Comment by timohund** [comment]
@adymorz This is an issue of the composer.typo3.org. See also the discussion on slack https://typo3.slack.com/messages/typo3-cms-composer from the 25 th april.

**Comment by adymorz** [comment]
@timohund Thank you for your answer. Could you please open an issue on https://github.com/TYPO3/CmsComposerPackageGenerator/issues?

**Comment by timohund** [comment]
@adymorz why not use this one: https://github.com/TYPO3/CmsComposerPackageGenerator/issues/12 ?

**Comment by timohund** [comment]
@adymorz no, if this is a problem for you, you can take care of that, we have currently more important issues.

**Comment by adymorz** [comment]
Not anymore :-)

Too bad that the results of your research get lost in the long timeline of the slack chat...

Thanks for your answers. I can live with the way it is.
