### ISSUE TITLE
Cannot instantiate interface

### ISSUE THREAD

**Issue by presedo** [TYPO3-Solr/ext-solr#3690]
When trying to simply add a solr plugin on a page (solr_pi_results, solr_pi_search BUT NOT solr_pi_frequentlysearch), I have an error on the backend

(1/1) Error
Cannot instantiate interface TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface

Coming from the following line

https://github.com/TYPO3-Solr/ext-solr/blob/a71fe94c1bdf1be7e75c5d906a2298fb0c4e2bc6/Classes/System/UserFunctions/FlexFormUserFunctions.php#L193

TYPO3 10.4
PHP 7.4
Solr extension 11.2.2

**Comment by dkd-kaehm** [comment]
Double of #3622, which is fixed.
Will be released soon.
