### ISSUE TITLE
[BUG] Results pagination is broken with `typo3fluid/fluid` 2.9+

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#3691]
The result pagination with disabled grouping is broken:

* The links to page number behaves as narrow >> button
* The last page-number (6 within solr-ddev-site) is not reacheble, the error is thrown:
   ```
   TypeError
   ApacheSolrForTypo3\Solr\Domain\Search\SearchRequest::setPage(): Argument #1 ($page) must be of type int, null given, called in /var/www/html/packages/ext-solr/Classes/Domain/Search/Uri/SearchUriBuilder.php on line 175
   ```
* The test `ApacheSolrForTypo3\Solr\Tests\Integration\Controller\SearchControllerTest::canDoAPaginatedSearch()` is broken and exits with same error from above

Relates: https://github.com/TYPO3/Fluid/issues/804

**Comment by dkd-kaehm** [comment]
Seems to be TYPO3 Core bug. 
@bmack please verify or falsify this assertion if you know more about that.

**Comment by bmack** [comment]
See https://github.com/TYPO3/Fluid/pull/806
