### ISSUE TITLE
[BUG] Performance issue when saving tt_content/pages

### ISSUE THREAD

**Issue by thomasrawiel** [TYPO3-Solr/ext-solr#3700]
When editing/ saving tt_content elements or editing page properties on enabled pages (hidden=0, deleted=0) the page load seems to be unusually high to finish when clicking the save button. 

With an editor account it takes about 20 seconds, compared to about 3 seconds for admin account

When removing the typoscript, the page is loaded instantly for both editor and admin accounts

The indexing itself and search results work just fine

Maybe an issue with a DataHandler or something along these lines

**To Reproduce**
- A more or less clean TYPO3 instance with just solr installed
composer.json:
```
 "require": {
    "typo3/cms-backend": "^11.5",
    "typo3/cms-belog": "^11.5",
    "typo3/cms-beuser": "^11.5",
    "typo3/cms-core": "^11.5",
    "typo3/cms-extbase": "^11.5",
    "typo3/cms-extensionmanager": "^11.5",
    "typo3/cms-filelist": "^11.5",
    "typo3/cms-filemetadata": "^11.5",
    "typo3/cms-fluid": "^11.5",
    "typo3/cms-fluid-styled-content": "^11.5",
    "typo3/cms-frontend": "^11.5",
    "typo3/cms-info": "^11.5",
    "typo3/cms-install": "^11.5",
    "typo3/cms-linkvalidator": "^11.5",
    "typo3/cms-lowlevel": "^11.5",
    "typo3/cms-recordlist": "^11.5",
    "typo3/cms-recycler": "^11.5",
    "typo3/cms-redirects": "^11.5",
    "typo3/cms-reports": "^11.5",
    "typo3/cms-rte-ckeditor": "^11.5",
    "typo3/cms-scheduler": "^11.5",
    "typo3/cms-setup": "^11.5",
    "typo3/cms-seo": "^11.5",
    "typo3/cms-t3editor": "^11.5",
    "typo3/cms-tstemplate": "^11.5",
    "helhum/typo3-console": "^7.1",
    "helhum/dotenv-connector": "^3.0",
    "apache-solr-for-typo3/solr": "^11.5"
  },
```

- typical typoscript is included (e.g. FSC, solr, myext). It doesn't acutally matter if any Typoscript is included at all.

- A root page with a template, where the Typoscript setup is
```
page = PAGE
page.10 = TEXT
page.10.value = Hello world
```
or any sitepackage typoscript

- an editor account with access to pages and tt_content, the web mount etc.

- Some subpages

- solr is set up in the siteconfig

**Behaviour**
Editing content on a subpage: The page load is high when clicking the Save button.

After removing the typoscript, actually just removing  `page = PAGE` is enough, the page loads "instantly" (<500ms)

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.28, also tested with all prior minor version up to 11.5.20
 - Browser: Chrome
 - EXT:solr Version: 11.5.0-11.5.3
 - Used Apache Solr Version: 8.11.1
 - PHP Version: 8.1.20, memory_limit 128M
 - MySQL Version: 8.0.23

**Additional context**
 - hosted on AWS : Linux 5.4.0-1041-aws
- on ddev (php 8.1.16) the difference is much less noticable -> no typoscript 50-80ms vs. with typoscript 400-500ms

**Comment by dkd-kaehm** [comment]
@thomasrawiel thanks for reporting this issue and descriptions.

1. Are there multiple site-trees on AWS/Production system?
2. How performant is your setups with new feature monitoringType=Delayed ? See: https://docs.typo3.org/p/apache-solr-for-typo3/solr/11.5/en-us/Configuration/Reference/ExtensionSettings.html#monitoringtype

**Comment by thomasrawiel** [comment]
@dkd-kaehm 
Yes, there are multiple site-trees. (about 20)

Setting monitoringType=Delayed seems to solve the issue

**Comment by dkd-kaehm** [comment]
That is fine then I'll close this issue.
But nevertheless please provide new measurements.
