### ISSUE TITLE
PHP fatal in index queue if item conf is empty

### ISSUE THREAD

**Issue by Mabahe** [TYPO3-Solr/ext-solr#371]
Already had this in different projects because of different reasons.

The Indexer want to update an item, but the indexing configuration is empty. This causes a (silent) fatal in AbstractIndexer::addDocumentFieldsFromTyposcript because $indexingConfiguration have to be an array.

Throw an exception in Indexer::getItemTypeConfiguration instead to trigger a failed indexing.

**Comment by timoschmidt** [comment]
Fixed with #377 please reopen when needed.
