### ISSUE TITLE
[BUG] TypeError in HierarchyFacetParser

### ISSUE THREAD

**Issue by thomasrawiel** [TYPO3-Solr/ext-solr#3724]
`ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\Facets\OptionBased\Hierarchy\HierarchyFacetParser` on line 71 

When the $nodesToCreate array contains integer indexes $value is of type integer.
Line 71: `$delimiterPosition = strpos($value, '-');`

This causes a type error for strpos
`strpos(): Argument #1 ($haystack) must be of type string, int given`

index config:
```
category = SOLR_RELATION
category {
    localField = categories
    foreignLabelField = uid
    multiValue = 1
}

category_stringM = SOLR_RELATION
category_stringM {
    localField = categories
    foreignLabelField = uid
    multiValue = 1
}
```

facet:
```
faceting.facets {
    category {
        label = category
        field = category_stringM
        #field = category
        type = hierarchy
        partialName = HierarchicalDropdowns
        keepAllFacetsOnSelection = 1
        keepAllOptionsOnSelection = 1
    }
}

```
![image](https://github.com/TYPO3-Solr/ext-solr/assets/5371428/f4197ce4-0162-4156-b1ef-fa32fb2a094d)

**Used versions**
 - TYPO3 Version: 11.5.29
 - EXT:solr Version: 11.5.3
 - Used Apache Solr Version: `image: typo3solr/ext-solr:11.5.3`
 - PHP Version: 8.1.16

Edit:
Maybe it's just a problem with the selection of the facet type, as this could be done with a normal option based facet

**Comment by thomasrawiel** [comment]
As always, reading the docs helps:
Added 

```
fieldProcessingInstructions {
    category = categoryUidToHierarchy
}
```

Now the filter works as expected

**Comment by dkd-kaehm** [comment]
Thanks for the infos.
IMHO the error is just fine for users, to see that it does not work...
I'll close this issue. Feel free to ask for reopen this issue, if it is wrong.
