### ISSUE TITLE
[BUG] 12.0.0-beta-1 : indexPage and incorrect fe_groups on access protected instance

### ISSUE THREAD

**Issue by Apen** [TYPO3-Solr/ext-solr#3735]
**Describe the bug**
The new version 12.0.0-beta-1 on last TYPO3 v12 doesnt get the correct fe_groups on frontend indexation. After a long debug session i notice a bug with 'solr.pageIndexingInstructions' & FrontendGroupsModifier .

This is a side effect of the Middleware order and the new attriibute 'solr.pageIndexingInstructions'.

`TYPO3\CMS\Frontend\Middleware\FrontendUserAuthenticator` is processed before `ApacheSolrForTypo3\Solr\Middleware\PageIndexerInitialization`.

So in `\ApacheSolrForTypo3\Solr\EventListener\PageIndexer\FrontendGroupsModifier` we will never have 'solr.pageIndexingInstructions' and we doesnt populate the correct fe_groups on a protected instance. So all the pages wil never be indexer and we only have the generic error message during indexing.

A smal test to validate that in `FrontendGroupsModifier ` ;

```php
public function __invoke(ModifyResolvedFrontendGroupsEvent $event): void
{
    $pageIndexerRequest = $event->getRequest()->getAttribute('solr.pageIndexingInstructions');

    // small test
    if ($event->getRequest()->hasHeader(PageIndexerRequest::SOLR_INDEX_HEADER)) {
        $jsonEncodedParameters = $event->getRequest()->getHeader(PageIndexerRequest::SOLR_INDEX_HEADER)[0];
        $pageIndexerRequest = GeneralUtility::makeInstance(PageIndexerRequest::class, $jsonEncodedParameters);
    }

    if (!$pageIndexerRequest instanceof PageIndexerRequest) {
        return;
    }
...
```

I force the ` $pageIndexerRequest ` to be regenerated, and all is working now :-)
This is not the correct solution, it is simply validate the bug.

Maybe fire the middleware before "typo3/cms-frontend/authentication" is the solution?
I let you choose that.

**Comment by dkd-kaehm** [comment]
Related change set: 

* https://github.com/TYPO3-Solr/ext-solr/commit/1a926ce1a3080991240f812aa4d398e3cbeaa73f
