### ISSUE TITLE
[FEATURE] make factor of width of search box on suggest configurable

### ISSUE THREAD

**Issue by Zanaxhir** [TYPO3-Solr/ext-solr#3752]
https://github.com/TYPO3-Solr/ext-solr/blob/4dd5d415e2c69bde292ac6ec8cd3f65cd5ad3cbd/Resources/Public/JavaScript/suggest_controller.js#L42

Can the magic-number '0.66' be transformed to a variable to be configured from outside?

**Comment by dkd-kaehm** [comment]
Double: #3356
