### ISSUE TITLE
Too strict return values during indexing

### ISSUE THREAD

**Issue by RazielleS** [TYPO3-Solr/ext-solr#3758]
**Describe the bug**
We have an integer field to be indexed by the page indexer.
Something like `plugin.tx_solr.index.queue.pages.fields.order_intS = tx_extension_some_field`.
The field is of course of type int in the database.

The method `\ApacheSolrForTypo3\Solr\IndexQueue\FrontendHelper\PageFieldMappingIndexer::resolveFieldValue` only allows arrays and strings as return values. But when it processes our field, it has type int. Thus throwing an exception.
Can the return value of this method be changed accordingly?

**To Reproduce**
1. Index an integer field with the PageFieldMappingIndexer

**Expected behavior**
No exception because of wrong return type.

**Used versions (please complete the following information):**
 - TYPO3 Version:12.4.3]
 - Browser: -
 - EXT:solr Version: [e.g. 12.0.0]
 - Used Apache Solr Version: dev-main (commit b15df83)
 - PHP Version: 8.2.7
 - MySQL Version: mariadb 10.5.18

**Comment by dkd-kaehm** [comment]
Current implementation does not care about right return type if value is serialized or is fetched directly from record:

https://github.com/TYPO3-Solr/ext-solr/blob/61076e3ed99ba2c4b9f17d44c2e50f278218780d/Classes/IndexQueue/FrontendHelper/PageFieldMappingIndexer.php#L120-L155

IMHO the return value can be set to `mixed` or a little bit stricter list of possible value types.

[solarium uses the values as follows](https://github.com/solariumphp/solarium/blob/7afd75fd18d208ab696e5b74be5072dcfdb46186/src/QueryType/Update/Query/Document.php#L236-L267):

> * If you supply NULL as the value the field will be removed
> * If you supply a numerically indexed array of values a multivalue field will be created.
> * In all cases any existing (multi)value or child document(s) will be overwritten.

**Comment by RazielleS** [comment]
I have found some more occurrences of too strict return types, so I changed the title of this issue to address them all.
I'll make a PR to change these.
