### ISSUE TITLE
solrfal for v12 is beta but not working

### ISSUE THREAD

**Issue by dmitryd** [TYPO3-Solr/ext-solr#3779]
**Describe the bug**

File queue for page context is always empty for EXT:solr and EXT:solrfal 12.0.x.

Looking to `solrfal/ext_localconf.php`:

```php
    $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['Indexer']['indexPagePostProcessPageDocument'][] = \ApacheSolrForTypo3\Solrfal\Detection\PageContextDetectorFrontendIndexingAspect::class;
```

This hook was removed in 192664daad1471e9ce98ea312a5c32feeba956c6 but solrfal beta for v12 still rely on it. Is there a way to get this quickly fixed for paying customers of solr EB? We need file indexing to work for the upgraded project...

**Comment by dkd-kaehm** [comment]
@dmitryd 
Thanks for reporting that issue. End of this week we'll release new beta with this fix.
This issue is already in EXT:solrfal tracker.
