### ISSUE TITLE
[BUG] Return value getPageItemChangedTime() must be of the type int, null returned 

### ISSUE THREAD

**Issue by hdietrich-timespin** [TYPO3-Solr/ext-solr#3806]
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of ApacheSolrForTypo3\Solr\IndexQueue\Queue::getPageItemChangedTime() must be of the type int, null returned 

here is the function: 

```
    protected function getPageItemChangedTime(array $page): int
    {
        if (!empty($page['content_from_pid'])) {
            // canonical page, get the original page's last changed time
            return $this->queueItemRepository->getPageItemChangedTimeByPageUid((int)$page['content_from_pid']);
        }
        return $this->queueItemRepository->getPageItemChangedTimeByPageUid((int)$page['uid']) ?? 0;
    }

```

**Problem**
The used function getPageItemChangedTimeByPageUid returns ?int => int|null, so you must cast return to "int" 
```
 return (int) $this->queueItemRepository->getPageItemChangedTimeByPageUid((int)$page['content_from_pid']) ;
```
or add  ?? 0
```
return $this->queueItemRepository->getPageItemChangedTimeByPageUid((int)$page['content_from_pid']) ?? 0;
```

or change return from function to:

```
    protected function getPageItemChangedTime(array $page): ?int
{ ....}

```

**Used versions**
 - EXT:solr Version: 11.5.1

---

#### Target branches: 

- [ ] release-11.5.x 
- [ ] main

**Comment by dkd-kaehm** [comment]
@hdietrich-timespin thanks for reporting that issue.
Could you please provide a PR with `..((int)$page['content_from_pid']) ?? 0` variant?

**Comment by hdietrich-timespin** [comment]
I can not provide a PR!
