### ISSUE TITLE
[BUG] Backend user logged out if edit a page or a page content in a member area (access only if logged in)

### ISSUE THREAD

**Issue by danieljanek78** [TYPO3-Solr/ext-solr#3845]
If a backend user (redactor or admin) edits a content element or a page inside page tree which is only available if logged in in frontend he will be logged out from backend (data is saved correct). Problem is fixed if deactivate solr ext.

1. create a page with access only if logged in in frontend
2. create a subpage or a content element
3. edit the page / element
4. > will be logged out from backend

 - TYPO3 Version: 12.4.7
 - Browser: chrome
 - EXT:solr Version: 12.0.0
 - Used Apache Solr Version: ?
 - PHP Version: 8.1
 - MySQL Version: ?

**Comment by dkd-kaehm** [comment]
@danieljanek78 
Thanks for reporting.
I can not reproduce this issue.
I can reproduce the logout only in one scenario, and that is the "Hide default language" on root page or on [sub]page.
Editing on those pages leads to the logouts.

Please use the "delayed" processing type together with new scheduler task "Event Queue Worker":
https://docs.typo3.org/p/apache-solr-for-typo3/solr/12.0/en-us/Configuration/Reference/ExtensionSettings.html#monitoring

**Comment by danieljanek78** [comment]
Thanks for your answer. I tried it with "delayed" processing and Event Queue Worker and ist seems to work.
