### ISSUE TITLE
[FEATURE] Make debugging of failed page indexing easier

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Solr/ext-solr#3846]
**Is your feature request related to a problem? Please describe.**
I updated to TYPO3 and solr v12 and now have a lot of `Error adding field 'created'='1681287239' msg=Invalid Date String:'1681287239'` issues.
This is easy to find for records, but pages don't reveal the issue.

**Describe the solution you'd like**
Better error logging in order to actually see the error without extra debugging efforts.

**Describe alternatives you've considered**
I used xdebug to retrieve the solr response containing the error.

**Additional context**

**Target versions**
next patch release for latest major version.

**Comment by dkd-kaehm** [comment]
@DanielSiepmann 
is #2590 the same and can be closed?

**Comment by DanielSiepmann** [comment]
I guess so. Didn't had issues for a long time.
