### ISSUE TITLE
[BUG] Exception with tx_solr_statistics after latest TYPO3 security update

### ISSUE THREAD

**Issue by mschwemer** [TYPO3-Solr/ext-solr#3877]
With the Security update at November, 14th 2023 the cookie generation changed in the TYPO3 core. 

This leads to an exception, when executing the search and statistics are enabled. 

Reason is, that the generated cookies are longer than the old ones and do not fit in the `tx_solr_statistics.cookie` any more. The available length is 32 chars, TYPO3 core allows up to 190. 

Solution is to raise the limit in `ext_tables.sql`

```
CREATE TABLE tx_solr_statistics
(
	cookie varchar(190) DEFAULT '' NOT NULL
);
```

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.41, 11.5.33, 12.4.8
 - Browser: independent
 - EXT:solr Version: all released versions

**Comment by dkd-kaehm** [comment]
Would we make it 255?

**Comment by dkd-kaehm** [comment]
We'll release following Versions:
* 12.0.1 with 
* 11.5.5
* 11.2.4(Apache Solr EB für TYPO3 10 ELTS (Extended-1-1) required)
* 11.0.9(Apache Solr EB für TYPO3 9 ELTS (Extended-2-2) required)
