### ISSUE TITLE
[BUG] Indexer does not work for extbase-records with sys_language_uid=-1

### ISSUE THREAD

**Issue by wrock** [TYPO3-Solr/ext-solr#3879]
**Describe the bug**
Indexer does not work for extbase-records with sys_language_uid=-1
Problem is in Indexer->isLanguageInAFreeContentMode($item, -1).
$typo3siteLanguage = $typo3site->getLanguageById($language) typo3site with -1 not configured.

**To Reproduce**
1. Try to index any extbase record contained in a folder with record-sys_language_uid=-1.

**Expected behavior**
Do not try to get SiteObject by language -1

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.33
 - Browser: chrome
 - EXT:solr Version: 11.5.4
 - Used Apache Solr Version: 11.5.x
 - PHP Version: 8.1
 - MySQL Version: 5.7

**Comment by wrock** [comment]
Solution: /Classes/IndexQueue/Indexer.php line 808:
if ($language === 0 || $language === -1) {

If you want I can create a pull request ...

**Comment by dkd-kaehm** [comment]
@wrock 
Thanks for reporting. 
Please create a pull requests against 
main and a cherry-pick port into release-11.5.x. 
Older EXT:solr versions do not support that feature.

**Comment by bitmotionAE** [comment]
This didn't yet fix the issue for "free content mode"-languages. Records with sys_language_uid = -1 are still skipped if the language to index is in free mode. The check in the pull request does not consider the sys_language_uid of the current item to index.
