### ISSUE TITLE
[BUG] Please increase size of cookie column of statistics

### ISSUE THREAD

**Issue by sfroemkenjw** [TYPO3-Solr/ext-solr#3882]
**Describe the bug**
We have activated Solr Suggest. While entering words a XHR request was send to the server. As a result I get following error in Browser DEV Toolbar:

```
An exception occurred while executing 'INSERT INTO `tx_solr_statistics` (`pid`, `root_pid`, `tstamp`, `language`, `num_found`, `suggestions_shown`, `time_total`, `time_preparation`, `time_processing`, `feuser_id`, `cookie`, `ip`, `page`, `keywords`, `filters`, `sorting`, `parameters`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [6302, 5864, 1700047231, 0, 1, 0, 0, 0, 0, 0, "2bd110bbed8a28a7ccb9c61a69bca844.b299e15690476cd7f969c1b97161e53dca26c27a1f4f986b6f40eef354609c2c", "37.24.176.0", 0, "ange", "a:0:{}", "", "O:8:\"stdClass\":18:{s:10:\"hl.tag.pre\";s:32:\"<span class=\"results-highlight\">\";s:7:\"json.nl\";s:4:\"flat\";s:2:\"hl\";s:4:\"true\";s:2:\"fl\";s:7:\"*,score\";s:5:\"start\";s:1:\"0\";s:11:\"hl.fragsize\";s:3:\"200\";s:2:\"fq\";a:2:{i:0;s:51:\"siteHash:\"6b2b8fff8b3a6affd99ae4892a27a894f5038279\"\";i:1;s:18:\"{!typo3access}-1,0\";}s:11:\"hl.tag.post\";s:7:\"<\/span>\";s:4:\"rows\";s:1:\"5\";s:13:\"hl.simple.pre\";s:32:\"<span class=\"results-highlight\">\";s:1:\"q\";s:4:\"ange\";s:7:\"defType\";s:7:\"edismax\";s:27:\"hl.useFastVectorHighlighter\";s:4:\"true\";s:14:\"hl.simple.post\";s:7:\"<\/span>\";s:10:\"omitHeader\";s:5:\"false\";s:2:\"qf\";s:135:\"content^40.0 title^5.0 keywords^2.0 tagsH1^5.0 tagsH2H3^3.0 tagsH4H5H6^2.0 tagsInline description^4.0 abstract subtitle navtitle author\";s:5:\"hl.fl\";s:7:\"content\";s:2:\"wt\";s:4:\"json\";}"]: Data too long for column 'cookie' at row 1
```

As you see the Session ID is much longer, than the 32 chars of your cookie column. I don't know why it is so long, as session ID was build by:

```
return GeneralUtility::makeInstance(Random::class)->generateRandomHexString(self::SESSION_ID_LENGTH);
```

where `SESSION_ID_LENGTH` is 32 chars long. But in `fe_session` and `be_session` tables the length is 190 chars.

To be compatible with TYPO3 session ID again I prefer increasing that value to at least 190, too.

**To Reproduce**

1. Activate Debug Preset in TYPO3 Settings
2. Activate suggest feature
3. Check, if there is something indexed in Solr Core
4. Open Browser Dev Toolbar. Switch to Network Tab and filter by XHR requests
5. Start typing some words
6. Analyze Error 500 Response with the error from above

**Expected behavior**
Return a clean JSON result for Solr Suggest feature

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.33
 - Browser: Chrome
 - EXT:solr Version: 11.5.3
 - Used Apache Solr Version: 8.11.2
 - PHP Version: 7.4
 - MySQL Version: 10.3.22-MariaDB-log - MariaDB Server

**Comment by dkd-kaehm** [comment]
double of #3877 
And fixed in #3880, #3881 and other ports.
