### ISSUE TITLE
[BUG] Data records with sys_language_uid = -1 do not index

### ISSUE THREAD

**Issue by ulrike-cosmoblonde** [TYPO3-Solr/ext-solr#3889]
**Describe the bug**
Records (tx_news) with sys_language = -1 (all languages) can no longer be indexed. The indexer fails with error message language -1 is not configured

**Used versions:**
 - TYPO3 Version: LTS 11.5
 - EXT:solr Version: Release 11.5.4

**Additional context**
This bug is caused by the changes from pull request #[3786](https://github.com/TYPO3-Solr/ext-solr/pull/3786)
If those changes in file  /solr/Classes/IndexQueue/Indexer.php  (ln 267-274) are removed it works as expected and indexes the records into all solr language cores.

Could you please add an additional check to handle sys_language_uid = -1 and to keep indexing into all solr language cores as before?

Thank you!
Ulrike

**Comment by dkd-kaehm** [comment]
@ulrike-cosmoblonde 
Thanks for reporting,
Double of #3879 it is already fixed in #3885, #3886
But please confirm, so we can release 11.5.5

**Comment by ulrike-cosmoblonde** [comment]
All working fine! thank you!
