### ISSUE TITLE
[BUG] Length of FeUser-Cookie has increased

### ISSUE THREAD

**Issue by chrosey** [TYPO3-Solr/ext-solr#3890]
**Describe the bug**
Since Update to TYPO3 11.5.33 Security Fix 
2023-11-14 [8fdec56561](https://github.com/typo3/typo3/commit/8fdec56561) [SECURITY] Limit user session to cookie domain (thanks to Benjamin Franzke)
The generated SessionID is not guaranteed to be 32 chars long anymore. In our case it will be 97 chars long (32 + '.' + 64). This results in an exception on inserting records into `tx_solr_statistics`

**To Reproduce**
1. Update to TYPO3 v11.5.33 (and most likely v12.4.8)
2. Start searching for anything (with statistics enabled)
3. See error

**Expected behavior**
I expect search results to appear.

**Screenshots**
![grafik](https://github.com/TYPO3-Solr/ext-solr/assets/7964040/0dd40d46-ec9e-4e9b-890c-c9e6f2286716)

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.33 (12.4.8)
 - Browser: doesn't matter
 - EXT:solr Version: 11.5
 - Used Apache Solr Version: 9.1.1
 - PHP Version: 8.1
 - MySQL Version: MariaDB 10.6

**Additional Information**
Our Workaround is to increase length of `cookie` column size to varchar(128)

**Comment by dkd-kaehm** [comment]
double of #3877
And fixed in #3880, #3881 and other ports.

**Comment by ohader** [comment]
What is this value used for? I just found references in `ext:solr` writing it, but it seems never to be read...

**Comment by dkd-kaehm** [comment]
> What is this value used for? I just found references in `ext:solr` writing it, but it seems never to be read...

That is for users last searches component, the users only last searches should be printed in FE from statistics table.

**Comment by ohader** [comment]
I found the reference to the TypoScript configuration in `plugin.tx_solr.search.frequentSearches`. However, it still seems, that the `cookie` value is not a required value there - maybe it's even superfluous?
