### ISSUE TITLE
[TASK] Add release tag for 12.0.x in docker hub

### ISSUE THREAD

**Issue by premar** [TYPO3-Solr/ext-solr#3894]
Is it possible to push an image with the current head of release 12.0.x (release-12.0.x) to Docker Hub, similar to what was done for versions 11.6.x, 11.5.x, and so forth? Previously, there were images with names like release-11.6.x, release-11.5.x, and so on.

We use this tag to automate certain processes for detecting the correct version.

We would appreciate it if this could be added :)

**Comment by dkd-kaehm** [comment]
This will be done automatically if the branch release-12.0.x is created.
We'll do this on switch to TYPO3 13 support. Current main is for TYPO3 12.
There are the tags 
* 12.0, 11.5, 11.2 
* + 
* 12.0.x-dev, 11.5.x-dev, 11.2.x-dev, 

which do the same. See: https://hub.docker.com/r/typo3solr/ext-solr/tags?page=1&name=-dev
