### ISSUE TITLE
isValidUrl make solr doesn't index pages in local environnement (docker)

### ISSUE THREAD

**Issue by MowWow** [TYPO3-Solr/ext-solr#391]
Hi,
 
I'm using solr with a TYPO3 7.6.4 installation, PHP v5.5
 
In the file PageIndexer.php, there is this code :
 

```
if (!GeneralUtility::isValidUrl($dataUrl)) {
           GeneralUtility::devLog(
               'Could not create a valid URL to get frontend data while trying to index a page.',
               'solr',
               3,
               array(
                   'item' => (array)$item,
                   'constructed URL' => $dataUrl,
                   'scheme' => $scheme,
                   'host' => $host,
                   'path' => $path,
                   'page ID' => $pageId,
                   'indexer options' => $this->options
               )
           );
           throw new \RuntimeException(
               'Could not create a valid URL to get frontend data while trying to index a page. Created URL: ' . $dataUrl,
               1311080805
           );
       }

```
 
So it checks if the url is valid or not. The problem is that in our company we use docker, so every developper has his own docker where he works, and the URL is always something like this : "myhost_web_1". My problem is that this kind of url cannot pass the validation of the isValidUrl function because of the underscores, and the pages indexation fail everytime. But for us, it's very complexe to change all the urls everywhere. 
 
Is it possible for you to add a typoscript config for example, that disable the url validation? for example : disableUrlValidation=1, when it's 1, the code skips the url validation part ?

Thanks a lot.

**Comment by timoschmidt** [comment]
@MowWow I would propose you to use valid urls because sooner or later you will run into other problems. But you could think about to provide a pull request, that allows you to disable this check.

**Comment by darkonevt777** [comment]
You just have to add your local domain name in /etc/hosts for 127.0.0.1 entry in your docker container.
