### ISSUE TITLE
[BUG] Performance issues with a lot of sites

### ISSUE THREAD

**Issue by deschilter** [TYPO3-Solr/ext-solr#3939]
**Describe the bug**
Installations with a lot of sites (50+) can run into performance and memory issues.
This happens when `\ApacheSolrForTypo3\Solr\Domain\Site\SiteRepository::getAvailableSites` is called, because when the site is built, new instance of the TSFE is created. Multiple if you got multiple Languages with fallbacks.
Every TSFE contains the entire TypoScript setup array, which can be quite large.

**Occurrences**
*Backend-Module initializeAction*
The [initializeAction](https://github.com/TYPO3-Solr/ext-solr/blob/119f557edea718178879e51b8f2bce45da04d9b7/Classes/Controller/Backend/Search/AbstractModuleController.php#L105) for the Backend Modules calls the method `autoSelectFirstSiteAndRootPageWhenOnlyOneSiteIsAvailable` which in turn calls `getAvailableSites`. This call is only relavant when only one site exist. 

*Backend-Modul initializeView*
It is also called in [initializeView](https://github.com/TYPO3-Solr/ext-solr/blob/119f557edea718178879e51b8f2bce45da04d9b7/Classes/Controller/Backend/Search/AbstractModuleController.php#L149) for the Backend-Modules. This call is to check if the are any sites configured.

*Scheduler Site-Selection*
The scheduler Module is also affected, because the Tasks require a site to index/re-index. The options for the dropdown are created using the result of `getAvailableSites`. This means the call is just to get the configured sites.

**Expected behavior**
It seems wasteful to create multiple instances of the entire TSFE, just to get the amount of available sites or the name and rootPageId.

**Used versions**
 I noticed this in TYPO3 12 LTS but the creation of the TSFE instances when building sites has been introduced in this commit: https://github.com/TYPO3-Solr/ext-solr/commit/ddcbc3bb6034ec3a02f410ee1a6b2ff961ff594d

**Comment by cricog** [comment]
Maybe one solution would be to replace `\ApacheSolrForTypo3\Solr\Domain\Site\Site::$configuration` by an on-demand `getConfiguration()` method that would do the TSFE processing (and that could have its own cache if needed) ?

**Comment by BugHunter2k** [comment]
This is still an issue. Is there any news with this?

**Comment by dkd-kaehm** [comment]
> This is still an issue. Is there any news with this?

#4145
