### ISSUE TITLE
[BUG] tx_solr 11.5.5 and solrfluidgrouping  11.0.0 PHP 8.1

### ISSUE THREAD

**Issue by fritzdacat** [TYPO3-Solr/ext-solr#3942]
When I additionally install the extension "solrfluidgrouping", I get this error:

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception PHP Warning: Attempt to read property "start" on null in /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/ViewHelpers/PageBrowserRangeViewHelper.php line 68

When I change line 68:

`$resultsFrom = $search->getResponseBody()->start + 1;`

to

`$resultsFrom = 0;
if ($search->getResponseBody() !== null) {
    $resultsFrom = $search->getResponseBody()->start + 1;
}`

it works.

**Comment by dkd-friedrich** [comment]
Resolved with #3943
