### ISSUE TITLE
[BUG] Backend Core Optimization PHP error

### ISSUE THREAD

**Issue by mehdichaouch** [TYPO3-Solr/ext-solr#3947]
Less than a big description, from backend, going to **_Core Optimization_**.
![image](https://github.com/TYPO3-Solr/ext-solr/assets/861701/df5fb03d-52a4-4a41-9a12-776d67986b8d)

```
(1/1) TypeError
ApacheSolrForTypo3\Solr\System\Solr\Schema\Schema::setManagedResourceId(): Argument #1 ($managedResourceId) must be of type string, null given, called in /var/www/vhosts/preprod.bcvs.ch/web/vendor/apache-solr-for-typo3/solr/Classes/System/Solr/Parser/SchemaParser.php on line 44

in /var/www/vhosts/..../web/vendor/apache-solr-for-typo3/solr/Classes/System/Solr/Schema/Schema.php line 34
    {
        return $this->managedResourceId;
    }

    public function setManagedResourceId(string $managedResourceId): void
    {
        $this->managedResourceId = $managedResourceId;
    }

```

https://github.com/TYPO3-Solr/ext-solr/blob/3276728eeec729578c9a3100b7e6acc517930238/Classes/System/Solr/Parser/SchemaParser.php#L44

**Used versions:**
 - TYPO3 Version: 12.4.10
 - Browser: chrome
 - EXT:solr Version: 12.0.1
 - Used Apache Solr Version: 9.3.0
 - PHP Version: 8.2.13
 - MariaDb Version: 10.5.21

Best,

**Comment by dkd-kaehm** [comment]
Double of #3064
