### ISSUE TITLE
[BUG] Hierarchy facet ignores partialName configuration

### ISSUE THREAD

**Issue by thomasrawiel** [TYPO3-Solr/ext-solr#3948]
As of version 12 the HierarchyFacet ignores the typoscript configuration for the partialName.

In `ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\Facets\OptionBased\Hierarchy\HierarchyFacet` the constructor parameter for the configuration has been renamed to  `array $facetConfiguration = [],` but the method getPartialName still uses the attribute `configuration`

```
public function getPartialName(): string
{
    return !empty($this->configuration['partialName']) ? $this->configuration['partialName'] : 'Hierarchy';
}
```

This will always be null and therefore it's currently not possible to change the used partial for the hierarchy facet.

For example when we have a facet like 
```
pageHierarchy {
    field = rootline
    label = rootline
    type = hierarchy
    partialName = MyPartialName
    keepAllOptionsOnSelection = 1
}
```
it will always use the default Hierarchy partial instead of `MyPartialName` 

edit: just checked the code in the repository, there it says `$this->facetConfiguration`, so I guess the problem will be solved with the next hotfix release

**Comment by dkd-kaehm** [comment]
@thomasrawiel 
Thanks for reporting.
Please use our issue template.
Which EXT:solr version is in use?

Seems to be fixed in https://github.com/TYPO3-Solr/ext-solr/commit/92500ae28aa400abe3045e279ce6742d72ea893a
So please try the dev-main state and close this issue if it is fixed.

**Comment by dkd-kaehm** [comment]
> edit: just checked the code in the repository, there it says `$this->facetConfiguration`, so I guess the problem will be solved with the next hotfix release

**Comment by thomasrawiel** [comment]
We currently use version 12.0.1 via composer/ packagist.

Yes, switching to the dev-main branch resolves the issue. Thanks.
