### ISSUE TITLE
[BUG] sub page of restricted page with "Extend to Subpages" is not indexed

### ISSUE THREAD

**Issue by deschilter** [TYPO3-Solr/ext-solr#3969]
**Describe the bug**
When a page is restricted to an `fe_group` by restricting the parent page and activating the "Extend to Subpages", it won't be indexed.
The indexing request will result in a 404 and the `frontendHelper` is never called.

This is because no or `pageUserGroup` is passed in the request. 
It is only passed if the current page is restricted: [PageIndexer.php#L297](https://github.com/TYPO3-Solr/ext-solr/blob/main/Classes/IndexQueue/PageIndexer.php#L297)
In that case the `FrontendGroupsModifier`  would grant access to the page, but without a `userGroup` or a `pageUserGroup`, it won't.

**To Reproduce**
1. Create a page called parent and restrict it to any fe_group
2. Check Extend to Subpages for the page parent
3. Create a subpage for the page parent called child
4. Index the pages

**Expected behavior**
Both pages, parent and child, should be correctly indexed.
Currently only the parent is indexed and the child results in an error.

**Used versions (please complete the following information):**
 - TYPO3 Version: 12.4.11
 - EXT:solr Version: 12.0.2
 - Used Apache Solr Version: typo3solr/ext-solr:latest
 - PHP Version: 8.1.26

**Comment by dkd-kaehm** [comment]
> It seems this was introduced by [this](https://github.com/TYPO3-Solr/ext-solr/commit/a6168bcc6df9fd941acd658af156d39975f3eff3) change and should therefore only affect v12

@deschilter There are 13 files changed, which part of change exactly?

Is #3926 related? Could you try if that fixes the issue?

**Comment by deschilter** [comment]
The part which checks if the FrontendGroupsModifier should be applied.
https://github.com/TYPO3-Solr/ext-solr/commit/a6168bcc6df9fd941acd658af156d39975f3eff3#diff-bf28763c35325e20091cdc41e71675d16a1f04fb2dbf94f7adb0b1d0f61abaf0R44

I tested #3926 and it does not solve this issue.
