### ISSUE TITLE
Queue adding for extensions like "news" or own extbase extensions ends up with 0 records

### ISSUE THREAD

**Issue by coarsy** [TYPO3-Solr/ext-solr#3978]
Every time I'll add new "news" items to the index queue with the button "Queue Selected Content For Indexing" 
it ends up with "Initialized indexing configurations: news(0 records)".

1. Go to the Apache SolR Index Queue Backend Module
2. Click on Queue Selected Content For Indexing
3. See message

All news should be added to the index queue.

 - TYPO3 Version: 11.5.36
 - EXT:solr Version: 11.5.0
 - Used Apache Solr Version: 8.11.1
 - PHP Version: 8.1.27
 - MySQL Version: 10.4.32
 
I'm using the standard typoscript configuration for the additional news queue which is shipped within the extension.
In the solr extension configuration I enabled "Enable/Disable record tracking outside siteroot".

I tested it also with the newest 11.5.6 version of the solr-extension and I always get the same message with 0 records applied to the queue.

**Comment by dkd-kaehm** [comment]
See: https://github.com/TYPO3-Solr/ext-solr/issues/3325#issuecomment-1900091020

**Comment by coarsy** [comment]
I read the comment you mentioned, but the page with the news records is inside the page tree and not outside. Everywhere I drop the datafolder with the news records inside it always ends up with 0 records.

**Comment by coarsy** [comment]
If I set up a new typo3 11.5.* page with DDEV and with only one language (DE) configured over the site module and install solr and news and adding some news of course I cannot geht them into the queue.

**Comment by dkd-kaehm** [comment]
> I read the comment you mentioned, but the page with the news records is inside the page tree and not outside. Everywhere I drop the datafolder with the news records inside it always ends up with 0 records.

Could you try to reproduce the issue on solr-ddev-site?
```shell
git clone -b release-11.5.x --single-branch git@github.com:TYPO3-Solr/solr-ddev-site.git && \
cd solr-ddev-site && \
rm composer.lock && \
ddev start && \
ddev solr:enable news
```

**Comment by dkd-kaehm** [comment]
> If I set up a new typo3 11.5.* page with DDEV and with only one language (DE) configured over the site module and install solr and news and adding some news of course I cannot geht them into the queue.

Didn't get you.
You know now the source of trouble?

**Comment by dkd-kaehm** [comment]
Please try https://github.com/TYPO3-Solr/ext-solr/issues/3978#issuecomment-1983153711

**Comment by coarsy** [comment]
Cloning into 'solr-ddev-site'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by dkd-kaehm** [comment]
> Cloning into 'solr-ddev-site'... [git@github.com](mailto:git@github.com): Permission denied (publickey). fatal: Could not read from remote repository.

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by coarsy** [comment]
Installed the 11.5.6 solr extension on my DDEV environment and still running into this problem. When I add news or other extbase extension data directly on the root page, everything is added to the queue. If I add news or other extension records on seperate datafolders they aren't added to the queue. 

Tested also this configuration in the setup:
plugin.tx_solr.index.queue.news.additionalPageIds = 1500

With the same result: Initialized indexing configurations: news (0 records).

I'm sure that on Typo3 10.x.x everything was running without any further setup.

**Comment by dkd-kaehm** [comment]
It may be the access rigths issue.
Make sure the root-line to news folder is not access restricted.

**Comment by coarsy** [comment]
I found the problem. In the configuration of the datafolder there must be [no_search_sub_entries] active! You can close this "bug". Thanks a lot for your answers and patience!
