### ISSUE TITLE
[BUG] TypeError : PageIndexer::indexPage(): $userGroup must be of type ?int, string given

### ISSUE THREAD

**Issue by Apen** [TYPO3-Solr/ext-solr#3986]
**Describe the bug**
A small type error when indexing restricted pages.

```
0: TypeError: ApacheSolrForTypo3\Solr\IndexQueue\PageIndexer::indexPage(): Argument #3 ($userGroup) must be of type ?int, string given, called in vendor/apache-solr-for-typo3/solr/Classes/IndexQueue/PageIndexer.php on line 66 and defined in vendor/apache-solr-for-typo3/solr/Classes/IndexQueue/PageIndexer.php:288
````

To fix this, we just need to cast to int :

```php
foreach ($systemLanguageUids as $systemLanguageUid) {
    $contentAccessGroups = $this->getAccessGroupsFromContent($item, $systemLanguageUid);
    foreach ($contentAccessGroups as $userGroup) {
        $this->indexPage($item, $systemLanguageUid, (int)$userGroup);
    }
}
```

**Used versions (please complete the following information):**
 - TYPO3 Version: 12.4.11
 - EXT:solr Version: 12.0.2
 - PHP Version: 8.2
 - MySQL Version: 8

**Comment by rr-it** [comment]
Some debugging later: I was pinging the wrong (old) TYPO3 system.

So when I send the request to the correct  URL, this issue does not come up at all.

1. Change TS-setup

```ts
plugin.tx_solr {
  index.queue {
    pages.indexer.frontendDataHelper {
      scheme = https
      host = example.ddev.site
    }
    news.indexer.frontendDataHelper < .pages.indexer.frontendDataHelper
  }
}
```

2. [!!!] Clear all caches via maintenance-tool

---

### Debugging:

1. Set breakpoint at lin 171:

https://github.com/TYPO3-Solr/ext-solr/blob/ccb703e5ca09955cb535b314c5a907e773e21703/Classes/IndexQueue/PageIndexerRequest.php#L163-L172

2. Then check:

-  `$url`  must be the correct TYPO3 instance
- `$responseString`
  - Should be:
     `{"requestId":"0123456789abc","actionResults":{"findUserGroups":"a:1:{i:0;i:0;}"}}`
  - When contacting the wrong (old) TYPO3 instance it was:
    `{"requestId":"0123456789abc","actionResults":{"findUserGroups":"a:1:{i:0;s:1:\"0\";}"}}`
