### ISSUE TITLE
[BUG] filter are ignored for suggestions on tx_solr_ajaxPage

### ISSUE THREAD

**Issue by sam-home** [TYPO3-Solr/ext-solr#3989]
**Describe the bug**
When I filter the page tx_solr_ajaxPage (?type=7384) by an facet (e.g. &tx_solr[filter][0]=color:red) suggestions are listed, which do not have color red. Documents are filtered correcly.

**To Reproduce**
1. Enable „Search - Ajaxify the search results with jQuery“
2. Create an Index with facets (e.g. color)
3. Add the solr search plugin to a page
4. Go to the page with ?type=7384 and filter by the facet (e.g. &tx_solr[filter][0]=color:red)
5. compare the result with the result without filter or another facet filter

**Expected behavior**
The suggestions on the page should only belong to results that match the filter.

**Used versions (please complete the following information):**
 - TYPO3 Version: [12.4.11]
 - EXT:solr Version: [12.0.2]
 - Used Apache Solr Version: [9.3.0]

**Comment by dkd-kaehm** [comment]
Thanks for reporting that issue, but EXT:solr is not intended to do it like your description.
Without Ajaxify-ing the things, EXT:solr behaves the same.
The search-input and suggestion-component are always in "initial" state, and after search, all the facet-options are resetted.
At most, the suggest-component should only take into account the real filters from TypoScript.

**Comment by dkd-kaehm** [comment]
You could try to modify the search-input action url, but I think this will not work as you like.
