### ISSUE TITLE
[BUG] Exception in Index Queue module on root page

### ISSUE THREAD

**Issue by garfieldius** [TYPO3-Solr/ext-solr#3990]
When switching to the "Index Queue" module and the virtual root page (UID 0) is selected, a PHP Error exception with thrown with the message "Call to a member function getSolrConfiguration() on null". This is because ApacheSolrForTypo3\Solr\Controller\Backend\Search\IndexQueueModuleController::getIndexQueues tries to access the `$selectedSite` property which is null on page 0.

Only the "Index Queue" module is affected. All other modules, including "Info" and "Core Administration" show the, expected, "No site could be found" message.

**To Reproduce**
1. Have a working TYPO, solr and EXT:solr setup
2. Select the virtual root page with UID 0
3. Switch to the "Index Queue" module

The exception is thrown.

**Expected behavior**
No exception is thrown and the "No site could be found" message is displayed instead.

**Used versions**
 - TYPO3 Version: 12.4.13
 - EXT:solr Version: 12.0.2
 - Used Apache Solr Version: 9.5.0
 - PHP Version: 8.3.2
 - MySQL Version: MariaDB 10.5

**Comment by spoonerWeb** [comment]
Fixed with 817b77d in v12.0.3.

**Comment by garfieldius** [comment]
Can confirm, works in 12.0.3
