### ISSUE TITLE
[BUG] solrfal: EventListener BeforePageDocumentIsProcessedForIndexing  is referenced in Services.yaml of solrfal though not available as PHP class there

### ISSUE THREAD

**Issue by chrisprog20** [TYPO3-Solr/ext-solr#3999]
**Describe the bug**
The event lister `BeforePageDocumentIsProcessedForIndexing ` is defined in EXT:solrfal/Configuration/Services.yaml but the respective PHP file is not available in solrfal >= 12.0.0. Ths leads to the problem that the page indexer does not start when manually triggering it.

**To Reproduce**
1. Go in the backend to 'Apache Solr' > 'Index Queue'
2. Click on 'Clear Index Queue'
3. After successful clearing click on the check box at 'pages' and on the button 'Queue Selected Content for Indexing'
4. After the index queue has been successfully initialized click on 'Index now' 
5. The error message shown below is visible

**Expected behavior**
After I performed steps 1 to 4 above I expect to see the following success message.
.
**Screenshots**
![error-message](https://github.com/TYPO3-Solr/ext-solr/assets/3862086/8e641162-21d8-4b24-9e5b-bb958a966fe4)
![success-message](https://github.com/TYPO3-Solr/ext-solr/assets/3862086/dc320c98-de15-43e5-9aa0-03c9f2e21bc5)

**Used versions:**
 - TYPO3 Version: 12.4.13
 - Browser: Chrome
 - EXT:solr Version: 12.0.2
 - Used Apache Solr Version: 9.5.0
 - PHP Version: 8.1.x
 - MySQL Version: 10.3.x

**Additional context**
The success message is shown if the configuration from the above mentioned EventListener is commented in:
![configuration-services-yaml-extract](https://github.com/TYPO3-Solr/ext-solr/assets/3862086/e5c6a16e-d416-4123-9336-3ba74ba078f7)

**Comment by chrisprog20** [comment]
The problem was that we had downloaded a version where the event listener BeforePageDocumentIsProcessedForIndexing was not included in the folder. After another download this file was available and the respective error gone. Hence this issue can be closed.

**Comment by dkd-friedrich** [comment]
Thanks for the update, I'm closing the issue
