### ISSUE TITLE
[TASK] Be able to disable tracking of visitors search inputs

### ISSUE THREAD

**Issue by christophlehmann** [TYPO3-Solr/ext-solr#4003]
**What should be done in the scope of this task?**

Tracking of user search input seems enabled by default. This

* floods the tables fe_sessions/tx_solr_last_searches
* starts sessions and thus sends session cookies.

There should ben an easy possibility to disable it.

Offtopic: Search inputs are only tracked, when they provide results.

Current TypoScript

```
plugin.tx_solr {
  search {
    lastSearches = 0
    lastSearches {
      limit = 10
      // tracking mode "user" or "global"
      mode = user
    }
  }
}
```

`lastSearches = 0` and `mode = ''` or `limit = 0` could be candidates to achieve disabling the tracking. What do you think?

**Comment by dkd-kaehm** [comment]
Yes, that is good idea.
Would propose `mode = disabled` to be more self explaining notation.

**Comment by christophlehmann** [comment]
And change it to be new default?

**Comment by dkd-kaehm** [comment]
For main in separate commit please.
It would be nice to backport that feature in non-Breaking manner.
