### ISSUE TITLE
[BUG] Page/MP with mount_pid = 0 and mount_pid_ol = 0 leads to initializing error

### ISSUE THREAD

**Issue by derMatze82** [TYPO3-Solr/ext-solr#4026]
**Describe the bug**
Having a simple Mount Point with option `Show this page` leads to the `Error occured while initializing` flash message when adding `pages` to the queue, although all pages were correctly written to the table tx_solr_indexqueue_item (and are also indexed correctly).
The method `isMountPointValid()` in `Classes/IndexQueue/Initializer/Page.php` checks for `empty($mountPoint['mountPageSource'])` and `!$this->mountedPageExists($mountPoint['mountPageSource'])`, which will lead to `$isValidMountPage = false` because of the `0` values for `mount_pid` and `mount_pid_ol`

**Expected behavior**
`mount_pid = 0` and `mount_pid_ol = 0` should lead to a valid Mount Point

**Used versions (please complete the following information):**
 - TYPO3 Version: 12.4.x
 - EXT:solr Version: 12.0.2
 - PHP Version: e.g. 8.3.x

**Comment by dkd-kaehm** [comment]
@derMatze82 
Thanks for reporting that issue.
Could create a pull-request with a fix?

**Comment by derMatze82** [comment]
@dkd-kaehm Sure! https://github.com/TYPO3-Solr/ext-solr/pull/4029
