### ISSUE TITLE
[BUG]  SiteRepository::getSiteByRootPageId() will raise PHP error instead of "No site could be found." when site config is missing 

### ISSUE THREAD

**Issue by abderrazakTgtLevio** [TYPO3-Solr/ext-solr#4033]
**Describe the bug**
In typo3 V12, with solr v12.0.2, an error message occurs when we try to open the "Index Queue" module, with a missing  Solr configuration  or by selecting the page with UID = 0.

**To Reproduce**
1. Go to "Index Queue" module
2. Select Page with UID = 0 or a page without Solr configuration
3. See error

![solrError](https://github.com/TYPO3-Solr/ext-solr/assets/152602653/b5eb74d7-ce8c-4617-926c-c25a0836b46c)

**Expected behavior**
An alert message displays the message : "No site could be found. Please choose other page in the page tree, which has solr configured."

**Used versions**
 - TYPO3 Version: 12.4.13
 - Browser: chrome
 - EXT:solr Version: 12.0.2
 - PHP Version: 8.2
 - MySQL Version: 8.0.23

**Comment by spoonerWeb** [comment]
Doubles #4013.

**Comment by spoonerWeb** [comment]
Fixed with 817b77d in v12.0.3.

**Comment by atigiti** [comment]
i'll try it, Thank you for your help.

**Comment by abderrazakTgtLevio** [comment]
i'll try it, Thank you for your help.

**Comment by dkd-kaehm** [comment]
> Fixed with [817b77d](https://github.com/TYPO3-Solr/ext-solr/commit/817b77d6d25c80fb0670ad1bae5a90280af02685) in v12.0.3.
