### ISSUE TITLE
[BUG] Updating already indexed page to "no index" does not remove the page from the index

### ISSUE THREAD

**Issue by davidsteeb** [TYPO3-Solr/ext-solr#4037]
**Describe the bug**
A previously indexed page is set to be excluded from search. This page no longer gets indexed, but is still visible (with potentially outdated content) in search results. 
The workaround our editors are using is to disable the page and re-enable the page again. 

**To Reproduce**
* Find a page that is indexed.
* Edit the page to exclude the page from being indexed.
* That same page is still part of the search results.

**Expected behavior**
Changing the status of a page to "exclude from search" should instantly remove the page from the search index (like deleting a page or hiding a page does).

**Used versions (please complete the following information):**
 - TYPO3 Version: [e.g. 12.4.14]
 - EXT:solr Version: [e.g. 12.0.3]

**Comment by spoonerWeb** [comment]
Can't confirm that issue.

1. Searched for the page directly => Found it.
2. Edited the page and set "Include in search" to no
3. Page was removed automatically from table `tx_solr_indexqueue_item`
4. Searched for the page directly => No result.

What did you do exactly to reproduce this issue? @davidsteeb

**Comment by dkd-kaehm** [comment]
Yep, isn't reproducible on dev-main and dev-12.0.x.
Closing.
