### ISSUE TITLE
Floatval is not locale aware

### ISSUE THREAD

**Issue by thombeck** [TYPO3-Solr/ext-solr#407]
Hi
I think a found a bug with the relevance bar. PHP's floatval is not locale aware so I modified the render function of viewhelepers relevance.php and relevanceBar.php.

    protected function render($documentScore, $maximumScore)
    {
        $content = '';
        if ($maximumScore > 0) {
            $score = floatval($documentScore);
            $LocaleInfo = localeconv();
            $score = str_replace($LocaleInfo["mon_thousands_sep"] , "", $documentScore);
            $score = str_replace($LocaleInfo["mon_decimal_point"] , ".", $score);
            
            $scorePercentage = round($score * 100 / $maximumScore);
            $content = $scorePercentage;
        }
        return $content;
    }

**Comment by timoschmidt** [comment]
@thombeck Thx for reporting and proposing a fix. I'll provide a patch as soon as possible. If you want to support feel free to provide a pull request

**Comment by dkd-friedrich** [comment]
Related to #362

**Comment by timoschmidt** [comment]
Also related: https://review.typo3.org/#/c/47455/

**Comment by timoschmidt** [comment]
And https://github.com/TYPO3/TYPO3.CMS/commit/38ecd2a672c5e8b4ae0f51e4b855ceb64d9111b0

**Comment by timoschmidt** [comment]
@thombeck Could it be that this was an issue with the TYPO3 Version 7.6.5? I've added you change in a brach (https://github.com/timoschmidt/ext-solr/tree/bugfix/master/407-floatVal-is-not-locale-aware)

Can you please describe how to reproduce or close the issue when it is no more relevant for the latest LTS release?

**Comment by timoschmidt** [comment]
No reply, If we need to do something please reopen.
