### ISSUE TITLE
Frontend plugin should produce a 500 error code when solr is unavailable

### ISSUE THREAD

**Issue by timoschmidt** [TYPO3-Solr/ext-solr#408]
The solr extension should produce a 500 error when the solr server is not available

**Comment by dkd-dobberkau** [comment]
Lets discuss this. I am unsure about this and would opt for a more user friendly "Seach is currently not available". I would also think that we have this for the search form.

**Comment by timoschmidt** [comment]
Sure, i mean the output and the message should be the same, but the http code should be different to be able to monitor an error.

**Comment by dkd-friedrich** [comment]
I think an improvement of the monitoring possibilities would be great and a different status code could help.

But currently I'm not sure about possible side effects, e.g. the search plugin (tx_solr_PiSearch_Search) shouldn't send an error, since it's often placed on all pages.

**Comment by timoschmidt** [comment]
As discussed, this should be done at another place.
