### ISSUE TITLE
[BUG] Facet filter values don't respect domain

### ISSUE THREAD

**Issue by danieljanek78** [TYPO3-Solr/ext-solr#4102]
**Describe the bug**
If we rename a category which is used as facet filter on the live server (domain.xyz) and we don't rename it on the staging server (stage.domain.xyz) - they use the same solr core - the old name is still shown on live website in filter option (with results 0).

**To Reproduce**
1. Index values with defined facet on a staging and on a live server
2. Set showEmptyFacets = 1
3. Rename either on stage or live (not on both)
4. reindex on that system
5. See frontend filters

**Expected behavior**
Facets should respect the page domain

**Used versions (please complete the following information):**
 - TYPO3 Version: 12.4.16
 - EXT:solr Version: 12.0.2
 - Used Apache Solr Version: 9.3.0

**Comment by dkd-kaehm** [comment]
@danieljanek78 

Thanks for reporting that issue.
That is known Apache Solr behavior, which can be solved by https://docs.typo3.org/p/apache-solr-for-typo3/solr/12.0/en-us/Backend/Scheduler.html#optimizing-cores-of-a-site
See: #2649

**Comment by danieljanek78** [comment]
@dkd-kaehm 

Thanks, but this scheduler is not working in my installation, see screenshot.
![Bildschirmfoto 2024-07-10 um 15 55 10](https://github.com/TYPO3-Solr/ext-solr/assets/129185738/287159f7-5806-4dff-81ce-e8b0f0cc929b)

**Comment by dkd-kaehm** [comment]
@danieljanek78 
Please test #4104
