### ISSUE TITLE
List of the most popular search queries in admin module

### ISSUE THREAD

**Issue by seirerman** [TYPO3-Solr/ext-solr#411]
Having a report listing the most used search terms would go a long way towards SEO. The solr GUI doesn't have this, but fortunately EXT:solr already logs all the search queries in tx_solr_statistics. 

Could be easily done by using a query like this:
`select keywords, count(keywords) as counter from tx_solr_statistics group by keywords order by counter desc limit 0,100;`

**Comment by timoschmidt** [comment]
@seirerman I think in general we could provide those log information when the logging of these terms is active. But in general i would propose and recommend to use an analytics tool like piwik and google analystics for this usecase and provide an api (server or clientside) for it to simplify the tracking integration.

**Comment by timohund** [comment]
Implemented in the codesprint and part of EXT:solr 5.1.0
