### ISSUE TITLE
[BUG] Adding Image not possible

### ISSUE THREAD

**Issue by lstitx** [TYPO3-Solr/ext-solr#4116]
**Describe the bug**
When trying to add a new image field to SOLR I get no output in the frontend. 

This is the typoscript: 
```
                tx_addressmanager_domain_model_address = 1
		tx_addressmanager_domain_model_address {
			table = tx_addressmanager_domain_model_address

			initialization = ApacheSolrForTypo3\Solr\IndexQueue\Initializer\Record

			fields {
				title = name
				....
			}
			attachments {
				fields = images
			}
		}
```

And this is the field I'm trying to add: 
![image](https://github.com/user-attachments/assets/6dfe26ac-7ebc-43e8-aee1-2a4e4fba51af)

**Expected behavior**
I want a FAL Object or a URL to access the image.

**Screenshots**

**Used versions (please complete the following information):**
 - TYPO3 Version: 12.4.16
 - Browser: chrome
 - EXT:solr Version: dev-release-12.0.x
 - Used Apache Solr Version: 9.6.0
 - PHP Version: 8.0
 - MySQL Version:  8.0.30 

**Additional context**

**Comment by dkd-dobberkau** [comment]
Are you using ext:solrfal?

**Comment by lstitx** [comment]
No. But I used [this](https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Backend/IndexQueue.html) as a guide on how to add files.

**Comment by dkd-kaehm** [comment]
@lstitx 
That setting is for EXT:solrfal record/page context file detection.

See: https://www.typo3-solr.com/fileadmin/Dokumente/Solr_for_TYPO3/Documentation/solrfal/solrfal_12.0.pdf

```
attachments
-----------

:Type: boolean
:TS Path: plugin.tx_solr.index.queue.[indexingConfiguration].attachments
:Default: 0
:Function: enables file attachment detection when indexing the record


fields
~~~~~~

:Type: string, comma separated values (column names of tables)
:TS Path: plugin.tx_solr.index.queue.[indexingConfiguration].attachments.fields
:Default: \*
:Function: define in which columns of an record files should be detected
```

--- 

### Possible solution for you:

See: https://github.com/TYPO3-Solr/ext-solr/issues/1701#issuecomment-2250873012
