### ISSUE TITLE
[BUG] getPageOverlay hook was not converted to service in ext-solr 12.x

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#4151]
**Describe the bug**
When debugging some 403 errors in the indexing of pages we discovered that the 
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_page.php']['getPageOverlay'][__CLASS__]
hook that was deprecated and removed with [TYPO3 12 deprecation](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-98303-InterfacesForPageRepositoryLanguageOverlayHooks.html)
has not been converted into the corresponding PSR-14 Event and thus resulting in that the method 
getPageOverlay_preProcess is never called and processed

**To Reproduce**
1. Using the feature extendToSubpages results in that pages are not indexed properly

**Expected behavior**
Pages should be indexed properly

**Used versions (please complete the following information):**
 - TYPO3 Version: 12.4.x
 - EXT:solr Version: 12.0.5
 - PHP Version: 8.3
 - MySQL Version: 8.4

**Additional context**
By inspecting the code I believe this has been properly solved in TYPO3 13 by adding the attribute
#[AsEventListener

**Comment by dkd-kaehm** [comment]
Fixed in #4152 for release-12.0.x.
In main branch aka TYPO3 13 it was fixed by f859f0c5b8fcf8c52f978267015b875568667afc
