### ISSUE TITLE
[BUG] solarfal Core: Exception handler (CLI): Uncaught TYPO3 Exception: Call to a member function checkRecord() on null | Error thrown in file typo3/sysext/core/Classes/Resource/ResourceFactory.php in line 494

### ISSUE THREAD

**Issue by RZivaralam** [TYPO3-Solr/ext-solr#4181]
Hello everyone,
I have the following error:
Core: Exception handler (CLI): Uncaught TYPO3 Exception: Call to a member function checkRecord() on null | Error thrown in file /typo3/sysext/core/Classes/Resource/ResourceFactory.php in line 494

Our server runs reindexTask in Solr automatically and we use Solrfal too. The problem occurred in solrfal/Classes/Service/FileAttachmentResolver.php in the function detectFilesInInlineField  for these two codes
	     
             $fileCollector->addFilesFromRelation($tableName, $fieldName, $record);
	     $fileReferences = $fileCollector->getFiles();

I added this "if code" and after that, i dont have any of the above errors:

	   if (! (is_object($GLOBALS['TSFE'] ?? false)) ) {
	      $fileCollector->addFilesFromRelation($tableName, $fieldName, $record);
	       $fileReferences = $fileCollector->getFiles();
	   }

i use this code to run the original code when I run reindexTask manually and whenever the server runs the code automatically it will not run and i don't have the problem too.

I'm sure you can better understand how to solve this problem.

**Comment by dkd-kaehm** [comment]
@RZivaralam 
Please use the issue template, because we want the infos.
Which versions are used?

**Comment by RZivaralam** [comment]
I have the following error:
Core: Exception handler (CLI): Uncaught TYPO3 Exception: Call to a member function checkRecord() on null | Error thrown in file /typo3/sysext/core/Classes/Resource/ResourceFactory.php in line 494

**To Reproduce**
Steps to reproduce the behavior:
Our server runs reindexTask in Solr automatically and we use Solrfal too. The problem occurred in solrfal/Classes/Service/FileAttachmentResolver.php in the function detectFilesInInlineField for these two codes

         $fileCollector->addFilesFromRelation($tableName, $fieldName, $record);
     $fileReferences = $fileCollector->getFiles();


**Expected behavior**
I added this "if code" and after that, I do not have any of the above errors:

   if (! (is_object($GLOBALS['TSFE'] ?? false)) ) {
      $fileCollector->addFilesFromRelation($tableName, $fieldName, $record);
       $fileReferences = $fileCollector->getFiles();
   }

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.32
 - Browser: -
 - EXT:solr Version: 11.5.6
  - EXT:solrfal Version: 11.0.0
 - PHP Version: 8.2.23
 - MySQL Version: 10.3.39-MariaDB-log

**Additional context**
I use this code to run the original code when I run reindexTask manually and whenever the server runs the code automatically it will not run and i don't have the problem too.

I'm sure you can better understand how to solve this problem.

**Comment by dkd-kaehm** [comment]
@RZivaralam thanks.
Could you try the EXT:solrfal 11.0.1?

**Comment by RZivaralam** [comment]
hey @dkd-kaehm thanks for your suggestion. After updating i don't have any problem.
