### ISSUE TITLE
[BUG] TYPO3 13 / dev main: Doctrine\DBAL\Exception\SyntaxErrorException

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Solr/ext-solr#4207]
**Describe the bug**
When I try to open Module Apache Solr > Info I get the following error:

```
(1/3) #1064 Doctrine\DBAL\Exception\SyntaxErrorException
An exception occurred while executing a query: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') `pidlist` ON (`sys_template`.`pid` = `pidlist`.`uid`) WHERE ((`sys_template...' at line 1
```

in /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/System/Configuration/ConfigurationManager.php line 187

**Used versions (please complete the following information):**
 - TYPO3 Version: 13.4.0
 - Browser: chrome
 - EXT:solr Version: [e.g. 13.0.0-dev]
 - Used Apache Solr Version: [e.g. 9.4]
 - PHP Version: [e.g. 8.2.0]
 - MySQL Version: mariadb 10.4
 
 
 ---

### Maintaners Notes:

Relates: #4203

**Comment by linawolf** [comment]
Same happens when I raise solr Version to 9.7

**Comment by linawolf** [comment]
I think this might be due to the fact that I am not using sys_template records anymore but site sets?

**Comment by dkd-kaehm** [comment]
> I think this might be due to the fact that I am not using sys_template records anymore but site sets?

@linawolf Thanks, that is a fine hint!
I'll close this issue in favor of #4209. Please comment the feature issue if necessary.
