### ISSUE TITLE
[FEATURE] Add support for TYPO3 13+ Site sets

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#4209]
We want to implement [Site sets](https://docs.typo3.org/m/typo3/reference-coreapi/13.4/en-us/ApiOverview/SiteHandling/SiteSets.html) feature within EXT:solr.

See: [comment from @linawolf in #4207](https://github.com/TYPO3-Solr/ext-solr/issues/4207#issuecomment-2449283303)

**Comment by codemonkey1988** [comment]
This feature would be really nice to have.
I'm currently building a new website based on TYPO3 13.4 LTS using Site Sets only. Site Sets are fully deployable and therefore my choice for that project. I try to avoid a template record in order to have a single TypoScript entry point for my instance.

**Comment by dkd-kaehm** [comment]
Work already without any changes, please let us know if something does not work.

#### Tested within solr-ddev-site

1. Run: 
```
ddev ssh
echo 'UPDATE db.sys_template SET deleted=1 WHERE 1=1;' | typo3 database:import
echo -e 'dependencies:\n  - bootstrap-package/full' >> config/sites/solr-testsystem/config.yaml
typo3 cache:flush
```
2. Flushing all possible caches in BE/Maintenance-Module.
3. Clearing all stuff in EXT:solr BE Modules and add to index queue all the configs

4. Clickie-Tests in BE(CRUD on content, page, records)
5. Clickie-Tests on FE-Search

---

@linawolf and @georgringer 
Thanks for https://forge.typo3.org/issues/105541 !!!
That small few lines TYPO3 core fix, fixed a lot of issues within EXT:solr!
:heart:
