### ISSUE TITLE
`solr:form` VH does not find TypoScript settings when plugin was instantiated via `EXTBASEPLUGIN`

### ISSUE THREAD

**Issue by ghost** [TYPO3-Solr/ext-solr#4212]
I render the following via `<f:cObject typoscriptObjectPath="lib.searchBar"/>`
```
lib {
  searchBar = EXTBASEPLUGIN
  searchBar {
    extensionName = Solr
    pluginName = pi_search
    settings {
      search {
        targetPage = {$pages.search}
      }
    }
  }
}
```
to have the search bar available centrally in the navigation.
But calling `<solr:form>` in the Form Fluid template does not respect the `targetPage` in any way,even though it is in the settings array, so
`f:uri(pageUid: settings.search.targetPage)`
works! Only the `<solr:form>` does not find it.
If I also set 
`plugin.tx_solr.search.targetPage = {$pages.search}`
it works, however.

Expected:
The configuration in the `EXTBASEPLUGIN` should be found and also win over the global TypoScript, because everything under `EXTBASEPLUGIN` should effectively act like it was a FlexForm.

The ViewHelper render method does this, which seems to not be able to fetch settings from `EXTBASEPLUGIN`:
```
        $pageUid = $this->arguments['pageUid'] ?? null;
        if ($pageUid === null && !empty($this->getTypoScriptConfiguration()->getSearchTargetPage())) {
            $pageUid = $this->getTypoScriptConfiguration()->getSearchTargetPage();
        }
        $pageUid = (int)$pageUid;
```

**Comment by dkd-kaehm** [comment]
@snk-spo 
Thanks for reporting that issue. 
Please provide infos about versions-stack.

**Comment by dkd-kaehm** [comment]
@snk-spo 
Thanks for clarification. On which places of our docs did you expected a hints about that?
