### ISSUE TITLE
Records starttime and endtime is not recognized

### ISSUE THREAD

**Issue by thomas-schubert-av** [TYPO3-Solr/ext-solr#4214]
**Szenario**
Page Record has a start time in future and should be visible automatically in a solr powerd plugin or another search request at the website.

**Expected behavior**
Page is available in the index queue and is indexed automatically via the indexing cronjob if the time has come. 

**To Reproduce**
- Create Page
- set start time to future time
- save
- check if item is added to the item queue

**Error**
The item is not added to the indexing queue with indextime = starttime. Item is never added to index queue, if the record is not saved anymore in the backend

**Possible solution**
remove the corresponding restriction from the query builder in ConfigurationAwareRecordService::getQueryBuilderForTable so that only hidden and deleted records are unfetchable.

**Used versions (please complete the following information):**
 - TYPO3 Version: 12.4.22
 - Browser: /
 - EXT:solr Version: 12.0.5
 - Used Apache Solr Version: /
 - PHP Version: 8.1.30
 - MySQL Version: 8

**Additional context**
Indexing these records w/o starttime works fine, no config error

**Comment by dkd-kaehm** [comment]
Please check and review #4169

Relates: #4113, #3547
