### ISSUE TITLE
Unused and uninitialized `Node` property `$depth`

### ISSUE THREAD

**Issue by snk-spo** [TYPO3-Solr/ext-solr#4216]
The Hierarchy `Node` class has an unused (_and always uninitialized!_) property `protected int $depth;` It has no getters/setters and no c'tor initialisation. Should it be actually filled with the depth of the node (forgotten to be implemented) or is this a leftover (forgotten to be removed)?

I could need this property in my current use case (I need filters on a single specific rootline level, so I could just take all nodes with a given depth).

edit: `ext:solr` v12

**Comment by dkd-kaehm** [comment]
> It should be pretty easy to make this usable:
> 
> Default it to 1 (or 0, whetever is the intended logic here). And if `$parentNode !== null` in the c'tor you initialize it to `$parent->getDepth() + 1`

Seems to be forgotten since initial implementation. Static analyzers do not complain about that :/

Please provide a pull-request.
