### ISSUE TITLE
[BUG] Missing int cast in FlexFormUserFunctions

### ISSUE THREAD

**Issue by ayacoo** [TYPO3-Solr/ext-solr#4220]
**Describe the bug**

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: ApacheSolrForTypo3\Solr\ConnectionManager::getConnectionByPageId(): Argument #2 ($language) must be of type int, string given, called in /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/System/UserFunctions/FlexFormUserFunctions.php on line 124`

**To Reproduce**

Reproducing this is not quite so easy. But we definitely have a ‘0’ in $pageRecord[‘sys_language_uid’]

**Expected behavior**

A simple int cast would help us here. If its OK, we can prepare a PR with this little change.

**Used versions (please complete the following information):**
 - TYPO3 Version 12.4
 - EXT:solr Version: 12.0.5
 - PHP Version: 8.3

**Comment by dkd-kaehm** [comment]
@ayacoo Thanks for reporting, please provide the PR.

**Comment by dkd-kaehm** [comment]
Fixed in #4220
