### ISSUE TITLE
Missing TYPO3 version check for default search plugin replacement

### ISSUE THREAD

**Issue by alebell** [TYPO3-Solr/ext-solr#423]
In the file ext_localconf.php the default search plugin is replaced by the solr plugin "plugin.tx_solr_PiResults_Results". Unfortunately a change in commit 71785acf242e4d82d2f8cc5172d32c1bf17ca38f breaks this behaviour in TYPO3 versions 6.2.x. To keep compatibility to TYPO3 6.2.x the implemented check for installed "compatibility6" sysext is not enough. We should additionally check for TYPO3 branch version <= 6.2.

**Comment by dkd-dobberkau** [comment]
please check this blogpost for our info about supported versions:
http://www.typo3-solr.com/en/blog/details/news/apache_solr_for_typo3_version_40_released/
it might be that 6.2 is no longer supported in the present codebase.

**Comment by alebell83** [comment]
Hi Olivier

Thank you for your advice. I'm aware that version 4.x of ext-solr doesn't support TYPO3 6.2 LTS anymore. But - and please correct me if I'm wrong - I thought that the 3.x branch is still maintained to provide compatibility to TYPO3 6.2.x LTS. I'm currently working on a system with TYPO3 6.2.x with ext-solr version 3.1.2 running and I'm affected by this issue.

Commit 71785acf242e4d82d2f8cc5172d32c1bf17ca38f was merged in the 3.x branch between releases 3.1.1 and 3.1.2. So if you still manage to maintain branch 3.x, I guess this should be fixed.

**Comment by timohund** [comment]
Not relevant anymore since 8.7 is the latest supported release and 6.1 the latest releast for 7.x. Please open a new issue if you think this is still relevant.
