### ISSUE TITLE
[BUG] No indexation for record with starttime in the future

### ISSUE THREAD

**Issue by marc-munos** [TYPO3-Solr/ext-solr#4263]
**Describe the bug**
Records with starttime in the future are not queued for indexation

**To Reproduce**
- Create a record, a page for instance
- Set a starttime in the future
- assert the record is not queued for indexation (ie. not inserted into tx_solr_indexqueue_item)

**Expected behavior**
The record should be inserted in queue with a changed date equal to the starttime

**Screenshots**
na

**Used versions (please complete the following information):**
 - TYPO3 Version: 12
 - EXT:solr Version: 12

**Additional context**

**Comment by marc-munos** [comment]
proposed fix :  https://github.com/TYPO3-Solr/ext-solr/pull/4264

**Comment by dkd-kaehm** [comment]
Closing: is fixed in #4169, #4258
