### ISSUE TITLE
Version that works without the compatibility6 Extension

### ISSUE THREAD

**Issue by rnakielski** [TYPO3-Solr/ext-solr#428]
Trying to get our site running with TYO3 7.6 LTS I installed the actual TER Version of solr (4.0.2). When I uninstall the compatibility6 extension frontend and backend brakes for various reasons (e.g. the usage of t3lib_extMgm without namespaces). Checking some branches here in github at least some of these things are fixed. 
Will there be a TER-version that works without compatibility6 or is there a recommended branch in github we can use for a production environment?

**Comment by dkd-dobberkau** [comment]
please check our blog here: http://www.typo3-solr.com/en/blog/details/news/apache_solr_for_typo3_version_40_released/

**Comment by rnakielski** [comment]
Thanks Olivier,
I did read the blog. In fact I do already use solr extension Version 4.0.2. It works with TYPO3 7.6 - but only when I use the  compatibility6 Extension. Do I have to wait for solr extension Version 5.0 to use it without compatibility6?

**Comment by dkd-dobberkau** [comment]
maybe @timoschmidt can answer this one

**Comment by timoschmidt** [comment]
@rnakielski EXT:solr 4.0.2 is working without compatibility6 in TYPO3 7.6, i am using it in several projects. Can you tell me where t3lib_extMgm is used?

**Comment by rnakielski** [comment]
Sorry, I had some mishmash of Versions - after reloading 4.0.2 from TER it works very well.
