### ISSUE TITLE
[TASK] Use short array syntax ['a'] instead of array('a') when possible

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#477]
Since php 5.4 we can use the short array syntax 

``` php

  $foo = ['a'];
```

instead of

``` php
  $foo = array('a');
```

We can use this where possible to make the code more readable.

**Comment by timohund** [comment]
We've replaced a lot of occurences in 6.0 and can continue on this in 6.1

**Comment by thomashohn** [comment]
@timohund - I Could go through here - if you would like some help here?
