### ISSUE TITLE
[BUG]  Displayed date differ from saved date

### ISSUE THREAD

**Issue by dkd-friedrich** [TYPO3-Solr/ext-solr#481]
**Describe the bug**
When displaying the changed date field, it is one hour less than the real value.
Current TZ: Europe/Paris

The dates are converting using the `timestampToIsodate()` and timestamp processing instructions, respectively used when saving and loading.

- https://github.com/TYPO3-Solr/ext-solr/blob/a18ab72a461a468a3a115defd83d78b982c105a6/Classes/System/DateTime/FormatService.php#L67

**To Reproduce**

This test case use project https://github.com/TYPO3-Solr/solr-ddev-site

1. Change the timezone wihtin `.ddev/config.yaml` (~ line 26) from UTC to i.e. `Europe/Berlin`
2. Enable extension news: `ddev enable-news`
3. Index all items
4. ...

**Expected behavior**

To be done

**Screenshots**

**Used versions (please complete the following information):**
 - TYPO3 Version: [e.g. 9.5.1]
 - Browser: [e.g. chrome, safari]
 - EXT:solr Version: [e.g. 8.0.0]
 - Used Apache Solr Version: [e.g. 6.6.0]
 - PHP Version: [e.g. 7.2.0]
 - MySQL Version: [e.g. 5.6.0]

**Additional context**

---

Origin: https://forge.typo3.org/issues/14092

Value: 5
Effort: 20

**Comment by jackd248** [comment]
Having the same problem with saving date information, while using the ext-solr in combination with the news extension.
The timezone information will not be saved in the core, so the date in TYPO3 is TZ: Europe/Berlin and the date in Solr Core is TZ: UTC. 

The processing instructions does'nt consider the timezone.

**Comment by 3l73** [comment]
This problem may be relates to a behaviour of PHP:

- https://www.php.net/manual/en/datetime.createfromformat.php
> The timezone parameter and the current timezone are ignored when the datetime parameter either contains a UNIX timestamp (e.g. 946684800) or specifies a timezone (e.g. 2010-01-28T15:00:00+02:00).

**Comment by 3l73** [comment]
@jackd248 Can you provide more information about your issue?

- Did you still have this issue?
- Which version of ext-solr are you using?
- Which field did you read exactly?

Currently I only found a difference between field `indexed` and `changed` within a document stored inside of the Solr core.

May be you can offer a test case?

**Comment by dkd-kaehm** [comment]
@jackd248
Please reply to https://github.com/TYPO3-Solr/ext-solr/issues/481#issuecomment-791324572
