### ISSUE TITLE
[TASK]  Provide settings for authentication to solr-server

### ISSUE THREAD

**Issue by dkd-friedrich** [TYPO3-Solr/ext-solr#482]
This is currently already possible, but only as part of a URL. Since we already have separate settings for "host" etc. it might be a good idea to also add username/password-settings as well for HTTP-authentication.

https://forge.typo3.org/issues/54631

Value: 1
Effort: 5

**Comment by sirdiego** [comment]
The biggest drawback with the current "URL-Based-Authentication" is that the username/password are displayed wherever the host is displayed (e.g. Reports-Module).

**Comment by dkd-dobberkau** [comment]
any suggestions? Is this admin only atm?

**Comment by irnnr** [comment]
admin only

**Comment by sirdiego** [comment]
I think I just stumbled upon another issue with the "URL-Based-Authentication". I guess passwords with ":" and "?" are not possible at the moment.

**Comment by timohund** [comment]
Possible since 6.0.1:

Please use:

plugin.tx_solr.solr.username =
plugin.tx_solr.solr.password = 

This information is also not shown in the report.
