### ISSUE TITLE
Shell script not working anymore

### ISSUE THREAD

**Issue by obi12341** [TYPO3-Solr/ext-solr#49]
Hello,

your shell script ```install-solr-existing-tomcat.sh``` is not working anymore, because you removed solr-4.8.1 from your mirror.

**Comment by dkd-dobberkau** [comment]
Please use the current script that comes with TER Version EXT:solr 3.0.1 as this uses the apache archives for that.
See: https://github.com/TYPO3-Solr/ext-solr/tree/release-3.0.x/Resources/Shell for the source

**Comment by obi12341** [comment]
Thanks for your answer. :)
