### ISSUE TITLE
[TASK] Migrate from devLog() to Logging-API

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#490]
devLog() is currently not usable in TYPO3 CMS v6. And in general imho we should use the Logging-API meanwhile.

I guess this task is important since without logging-functionality in some cases it's quite hard to drill down problems with a solr-installation.

**Comment by timohund** [comment]
First step could be to register a devLog listener that writes into a log using the logging framework:

https://daniel-siepmann.de/Posts/2016-05-27-typo3-custom-devlog.html

**Comment by thomashohn** [comment]
Since the ext:solrfal uses the standard TYPO3 logger framework - I would suggest replacing devLog with debug from TYPO3 logger framework. Any objections @irnnr or @timohund ?

**Comment by irnnr** [comment]
sounds good
