### ISSUE TITLE
Use SYS_LASTCHANGED for latest changes on pages

### ISSUE THREAD

**Issue by seirerman** [TYPO3-Solr/ext-solr#52]
Right now, pages get indexed with the tstamp value as "changed" in the Solr index.
This means that only changes to the page record itself are considered, and facets for the age of pages are basically worthless if the actual content is not taken into account.

Wouldn't it be better if SYS_LASTCHANGED is used, since it considers both changes to pages and tt_content?

Editing
```php
$document->setField('changed',     $pageRecord['SYS_LASTCHANGED']);
```
in /typo3conf/ext/solr/Classes/Typo3PageIndexer.php, line 242 solved the problem for me. 
I'm not sure if that was all there was to do.

**Comment by irnnr** [comment]
Good point, the record monitor is taking that into account actually. Will have to look into that.
