### ISSUE TITLE
TS - query.sortBy

### ISSUE THREAD

**Issue by dkd-friedrich** [TYPO3-Solr/ext-solr#525]
Guy Couronné wrote:

> It would be useful to add stdWrap support for query.sortBy.
> 
> It would change on Tx_Solr_Search_SortingComponent->initializeSearchComponent() {...}

---

https://forge.typo3.org/issues/64857

Effort: 5
Value: 1

**Comment by dkd-kaehm** [comment]
Closing in favor of #2712
