### ISSUE TITLE
Search using spellchecker suggestions uses wrong term for highlighting

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#526]
intro package with option searchUsingSpellCheckerSuggestion
-     search for kisper
-     suggests search for kasper
-     renders results for kasper
-     sets highlighting in sword_list to kisper

https://forge.typo3.org/issues/41534

**Comment by timohund** [comment]
Estimation:

Effort: 5
Value: 5

**Comment by timohund** [comment]
We should add an integration test for that

**Comment by timohund** [comment]
I think it could be an option to add a property $performedQueryString to the SearchRequest, that has a fallback to the users querystring when nothing was set. During the correction this property can be set to the actual performed querystring.

**Comment by dkd-kaehm** [comment]
@timohund 
This issue is fixed somewhere, see my screenshot:
![bildschirmfoto 2017-09-11 um 18 57 01](https://user-images.githubusercontent.com/25453927/30286774-0c9e99cc-9723-11e7-86ad-f89130717bc9.JPG)

reopen if something wrong!
