### ISSUE TITLE
Pages with "config.index_enable=0" shouldn't get counted as failure

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#537]
When some pages (a branch) has set "config.index_enable=0" those pages will get counted as "Failure" when being indexed.

Instead those pages (index queue items) should get marked as "disabled".

The value "config.index_enable" can only change for a page when its TypoScript cache will get cleared. This is the case after pushing the "clear all caches" button.

The disabled pages will get their indexing_priority set to -1 so other index queue items take precedence.

Only possibility that "config.index_enable" can change without relation to clear all caches is the flag "forceTemplateParsing" of TSFE. If this is set the page will not get disabled but only have its indexing priority set to -1 so they don't lock up the indexing of other items. Usually this should never happen as "forceTemplateParsing" can only get set via the adminPanel (or from custom code). As the indexed pages are rendered via the frontend internally without a BE user being logged in (or simulated BE login) forceTemplateParsing should never be set when indexing a page.

The scheduler indexequeu worker task gets modified to show such disabled pages separate from failures.

When the cache gets cleared the "disabled" flag is removed from those pages and the indexequeue will try to index them again.

https://review.typo3.org/#/c/35780/
https://forge.typo3.org/issues/55452

**Comment by timohund** [comment]
Effort: 13
Value: 5

**Comment by timohund** [comment]
Discussion:

**1**
There are different scenarios where this issue is not only cosmetic (Scheduler shows "Failure" altough pages were simply skipped because of "config.index_enable=0").

If for example a site features multiple languages and indexing is disabled for one of those languages via

[globalVar = GP:L=1]
config.index_enable = 0
[end]

Or something similar for specific usergroups (or language/usergroup combinations) then the page will maybe not get indexed for other languages/usergroups. "Maybe" only because it depends on the order of how the different variants get indexed. If the first variant (language/usergroup combination) fails because of "config.index_enable=0" then all other variants will also not get indexed.

**2**
 Updated by Bernhard Kraft over 2 years ago
Comment Edit
Additionally I think it is somehow a design flaw in EXT:solr to only take language/usergroup into account for different indexing variants. If someone sets a condition which changes the rendering of content elements for example depending on the IP of a visitor solr will fail to index contents properly for this visitor (as he sees it).

I guess for an optimal result the admin would need the possibility to define additional constraints on indexing except language/usergroup. Of course an admin would need some knowledge about how different variants of content can get generated on his site and configure solr accordingly.

In fact here the problem is the mapping of:
data <==> view

Usually in TYPO3 the behaviour is like:
View(data=
.. a View gets passed some data and gets rendered

Altough this is CMS algorithm nitpicking now and has nothing to do with this issue I assume the following concept ...
Data(Views)
(A Dataset (record, etc.) getting passed all possible views and knows where it has to insert its data) ... is more appropriate in means of caching, refreshing, etc.

**Comment by dkd-kaehm** [comment]
We should avoid adding new sources of options for "visibility" purposes.
There are already "no_search", "no_search_sub_entries", "hidden", etc.
The "config.index_enable" within TypoScript field of page and bubbling it down to the sub pages on RecordMonitor or Initializing contexts is a pandora's box.
