### ISSUE TITLE
 Page property "is_siteroot" gets accessed directly at multiple occasions

### ISSUE THREAD

**Issue by dkd-friedrich** [TYPO3-Solr/ext-solr#539]
Bernhard Kraft wrote:

> This is a cleanup request. The page property "is_siteroot" gets queried/used in "if" statements directly at multiple locations.
> 
> Proposal: See patch posted to gerrit. Introduce a static utility method "isSolrIndexingStarginpoint" which currently gets passed the whole page record. If at some time a page domain model gets used the check for "is_siteroot" will have to get changed at only one place. This also allows extensions which alter the behaviour of solr to easier interfere with this aspect (Indexing Startpoint).
> 
> At least it also is cleaner.

---

https://forge.typo3.org/issues/61165

Value: 8
Effort: 5

**Comment by thomashohn** [comment]
@timohund I could have a look at this - I Guess a method called isSiteRoot in the util class would be appropriate?

**Comment by thomashohn** [comment]
@timohund I think this issue can be closed now
