### ISSUE TITLE
Indexing crashes

### ISSUE THREAD

**Issue by kimamil** [TYPO3-Solr/ext-solr#551]
I still don't know the exact issue in my setup, but changing

       /**
         * Converts an item array (record) to a Solr document by mapping the
         * record's fields onto Solr document fields as configured in TypoScript.
         *
         * @param Tx_Solr_IndexQueue_Item $item An index queue item
         * @param integer $language Language Id
         * @return Apache_Solr_Document The Solr document converted from the record
         */
        protected function itemToDocument(Tx_Solr_IndexQueue_Item $item, $language = 0) {
                $document = NULL;

                $itemRecord = $this->getFullItemRecord($item, $language);
                if (!is_null($itemRecord)) {
                        $itemIndexingConfiguration = $this->getItemTypeConfiguration($item, $language);

                        $document = $this->getBaseDocument($item, $itemRecord);
                        $document = $this->addDocumentFieldsFromTyposcript($document, $itemIndexingConfiguration, $itemRecord);
                }

                return $document;
        }

to

      /**
         * Converts an item array (record) to a Solr document by mapping the
         * record's fields onto Solr document fields as configured in TypoScript.
         *
         * @param Tx_Solr_IndexQueue_Item $item An index queue item
         * @param integer $language Language Id
         * @return Apache_Solr_Document The Solr document converted from the record
         */
        protected function itemToDocument(Tx_Solr_IndexQueue_Item $item, $language = 0) {
                $document = NULL;

                $itemRecord = $this->getFullItemRecord($item, $language);
                if (!is_null($itemRecord)) {
                        $itemIndexingConfiguration = $this->getItemTypeConfiguration($item, $language);

                        if($itemIndexingConfiguration){
                                $document = $this->getBaseDocument($item, $itemRecord);
                                $document = $this->addDocumentFieldsFromTyposcript($document, $itemIndexingConfiguration, $itemRecord);
                         }
                }

                return $document;
        }

in /var/www/swisstph-intranet/typo3conf/ext/solr/Classes/IndexQueue/Indexer.php seems to resolve the issue (at least for the failing documents I guess)

**Comment by timohund** [comment]
@kimamil Can you please provide some more information. 

- For what record type is it failing?
- What the error message?
- How can it be reproduced?

Also a EXT:solr version and TYPO3 version would be usefull.

**Comment by kimamil** [comment]
Ok, I try ...

So solr-version is 4.8.1, and the extension 'solr' is on 3.0.1 on a TYPO3 6.2 instance

In the "search" be-module, at the "index queue" i can see that only the record type "page" is showing errors. A Click on "show Error" gives me:

```
1319116885: exception 'RuntimeException' with message 'Failed to execute Page Indexer Request. See log for details. Request ID: 57a1d6f9ab401' in <yourAbsTYPO3PathHere>/typo3conf/ext/solr/Classes/IndexQueue/PageIndexerRequest.php:163
```

I think, that my code change does not solve the actual problem (which I still couldn't figure out) but it's unclean code which should be changed, so indexing can continue with records that can be indexed instead of failing with a fatal ...

**Comment by kimamil** [comment]
So, finally, I recognized the issue I had, and it had to do with Authentication via ig_ldap_sso_auth and using SSO and Kerberos. When solr tried to access pages via file_get_content() the server of course replied with "Unauthorized".

Still, pls clean the code ;)

**Comment by kimamil** [comment]
Finally I solved my Issue with Kerberos and SSO, the initial issue remains ...

> PHP Catchable fatal error:  Argument 2 passed to Tx_Solr_IndexQueue_AbstractIndexer::addDocumentFieldsFromTyposcript() must be of the type array, null given, called in <ourserver>/typo3conf/ext/solr/Classes/IndexQueue/Indexer.php on line 274 and defined in <ourserver>/typo3conf/ext/solr/Classes/IndexQueue/AbstractIndexer.php on line 52


solution might (probably least invasive) be:
```
      /**
         * Converts an item array (record) to a Solr document by mapping the
         * record's fields onto Solr document fields as configured in TypoScript.
         *
         * @param Tx_Solr_IndexQueue_Item $item An index queue item
         * @param integer $language Language Id
         * @return Apache_Solr_Document The Solr document converted from the record
         */
        protected function itemToDocument(Tx_Solr_IndexQueue_Item $item, $language = 0) {
                $document = NULL;

                $itemRecord = $this->getFullItemRecord($item, $language);
                if (!is_null($itemRecord)) {
                        $itemIndexingConfiguration = $this->getItemTypeConfiguration($item, $language);
                        if(!$itemIndexingConfiguration) $itemIndexingConfiguration = array();

                        $document = $this->getBaseDocument($item, $itemRecord);
                        $document = $this->addDocumentFieldsFromTyposcript($document, $itemIndexingConfiguration, $itemRecord);
                }

                return $document;
        }

```
