### ISSUE TITLE
[BUG] Adding new scheduler task throw: `Call to a member function getRootPageId() on null`

### ISSUE THREAD

**Issue by jousch** [TYPO3-Solr/ext-solr#560]
# Commit #557 breaks sysext:scheduler.
---
## Environment

* TYPO3 7.6.10 (stable Release)
* ext:solr with commit #557 or newer
* no existing ext:solr relevant scheduler task
* one page marked as root page in just one pagetree
* solr typoscript included or not included
* (no solr connections initialized)

### How to reproduce

* Open scheduler backend module
* Press "Add task"

```
Call to a member function getRootPageId() on null 

Error thrown in file
/app/web/typo3conf/ext/solr/Classes/Site.php in line 127.
```

![image](https://cloud.githubusercontent.com/assets/2861556/17507066/cada7e9c-5e0d-11e6-95c6-f54642dba0bf.png)

**Comment by DanielSiepmann** [comment]
Sorry for introducing this bug.
The provided Pull Requests for 5.x and master should fix it.

I didn't create the documented environment to reproduce the issue. But as the signature allows `null` I've added a check before calling a method on null.

**Comment by jousch** [comment]
@DanielSiepmann thx, no error anymore ;-)
