### ISSUE TITLE
PageIndexer overwrites documents in invalid language

### ISSUE THREAD

**Issue by astehlik** [TYPO3-Solr/ext-solr#592]
I think there is a bug in https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/IndexQueue/PageIndexer.php#L138.

If a page exists in a language that should not be indexed there will be no matching entry in the `$solrConnections` array.

The connection is still added to the available solr connections with value `null`.

The frontend helper ist still called with both languages, even if there is no valid connection. It will use the default solr connection for indexing the translated page and overwrite the original values.

IMO there should be a check if there is a valid connection for the given language before adding it to the available connections array:

```
if (isset($solrConnections[$languageId])) {
    $accessibleSolrConnections[$languageId] = $solrConnections[$languageId];    
}
```

**Comment by timohund** [comment]
Fixes with: #659
