### ISSUE TITLE
[TASK] Query - remove by "fieldname:fieldvalue"

### ISSUE THREAD

**Issue by cihanin2code** [TYPO3-Solr/ext-solr#607]
Hi,

It is possible to add filter-strings of form "fieldname:value" with Query->addFilter(). But there is no equivalent method for removing filters by giving the filter "fieldname:value". So a Query->removeFilterByString() would be very helpful:

```
    /**
     * @param string $filterString The filter to remove, in the form of field:value
     * @return void
     */
    public function removeFilter($filterString) {
        foreach ($this->filters as $key => $curFilterString) {
            if ($curFilterString === $filterString) {
                unset($this->filters[$key]);
            }
        }
    }
```

**Comment by timohund** [comment]
Remove by filter allready exist with another scope. The methode Query::removeFilterByValue was added to implement the needed behaviour.
