### ISSUE TITLE
PHP Error on Admin Tools > Search page

### ISSUE THREAD

**Issue by benjaminpick** [TYPO3-Solr/ext-solr#63]
After going through the installation manual, I see the following PHP error:

<pre>PHP Catchable Fatal Error: Argument 1 passed to ApacheSolrForTypo3\Solr\Domain\Model\ModuleData::setSite() must be an instance of Tx_Solr_Site, null given, called in /webroot/typo3conf/ext/solr/Classes/Backend/SolrModule/AbstractModuleController.php on line 141 and defined in /webroot/typo3conf/ext/solr/Classes/Domain/Model/ModuleData.php line 50</pre>

Using Typo3 6.2.14, and ext-solr 3.0.1.

(Attached the reports page section ... It is strange that there is no connection error because I put in a bad url on purpose.)

![auswahl_302](https://cloud.githubusercontent.com/assets/244542/9785031/88b203ba-57af-11e5-9e82-c9719c148878.png)

**Comment by benjaminpick** [comment]
Just tried master, the error still persists.

**Comment by julianBob** [comment]
Hello, i have the same problem  with TYPO3 7.4 and master

**Comment by benjaminpick** [comment]
Yes I've seen this PHP error message in other forums as well, for example: https://forum.typo3.org/index.php/t/201441/

**Comment by irnnr** [comment]
Can you please try with the latest master. We added a legacy class map.

**Comment by mnml89** [comment]
I have the same error with Typo3 6.2.15 and the solr version 3.0.1. 
The error also appears with the latest master version.

#1: PHP Catchable Fatal Error: Argument 1 passed to ApacheSolrForTypo3\Solr\Domain\Model\ModuleData::setSite() must be an instance of ApacheSolrForTypo3\Solr\Site, null given, called in /typo3conf/ext/solr/Classes/Backend/SolrModule/AbstractModuleController.php on line 145 and defined in /typo3conf/ext/solr/Classes/Domain/Model/ModuleData.php line 53 (More information)

**Comment by dkd-dobberkau** [comment]
can you check with master @mnml89?

**Comment by mnml89** [comment]
@dkd-dobberkau 
As I said, I tried with both - version 3.0.1 and the master. If you mean with master the one I can find here: https://github.com/TYPO3-Solr/ext-solr (I'm new at github, sorry).
Only the lines changed from 50 to 53 and 141 to 145, but the error message is the same.

**Comment by mnml89** [comment]
Hello guys,

after I installed the newest master and checked my connection configuration for solr, the extension works fine with the current master version and Typo3 6.2.15.

Thanks

**Comment by irnnr** [comment]
@benjaminpick @julianBob please provide feedback whether this issue has been solved for you.

**Comment by benjaminpick** [comment]
After uploading the master version & clearing the Cache, the error is still there. I had to click "Initizialize Solr connections" and then the search page appears correctly. 

So yes the issue is resolved but if possible, test if null and show a notice that hints for possible causes (did you click on Initizalize Solr Connection? etc.)

**Comment by timoschmidt** [comment]
@benjaminpick 

Hi benjamin, this should be resolved now in the latest dev-master i've checked this and added an introduction how to configure the module properly when no site is available. Can you maybe re-check and confirm? Then we can close this issue.

**Comment by benjaminpick** [comment]
Hi,

I'm sorry but I cannot test this anymore ...
Yes you can close the issue. My last comment was mainly cosmetic.

Benjamin

**Comment by timoschmidt** [comment]
I've tested this again after upgrading ext_solr from 3.0.2 to 3.1.0 and now everything is fine.
