### ISSUE TITLE
[Feature] Scheduler run per language

### ISSUE THREAD

**Issue by Niclz** [TYPO3-Solr/ext-solr#643]
The indexing scheduler job should be parameterized with, which language to be indexed. In this way, we can prioritized which records should be indexed first.
E.g.: english record should be first indexed, than german one, since it's "prime time" in english speaking countries (north america), but not in german speaking countries (europe).

**Comment by irnnr** [comment]
Theoretically possible, but due to how translations work in TYPO3 I don't think it makes much sense. Translations are "shadow" versions of a page, and you'll always have to index/access the default language before indexing the translation.
