### ISSUE TITLE
Garbage Collector and Record Monitor when frontend editing

### ISSUE THREAD

**Issue by megamisan** [TYPO3-Solr/ext-solr#647]
When changing record information using frontend editing actions (delete, hide, up, down), the SOLR Garbage Collector and Record Monitor are not triggered since the current ```TYPO3_MODE``` is ```FE```.

The Garbage Collector and Record Monitor hooks should be activated when ```TYPO3_MODE``` is ```BE``` AND when ```TYPO3_MODE``` is ```FE``` and ```$_POST['TSFE_EDIT']``` is set.

**Comment by dkd-dobberkau** [comment]
Can you care for a PR?

**Comment by irnnr** [comment]
Is this happening when modifying records in FE mode through Extbase?

**Comment by megamisan** [comment]
It is happening when using the edit icons in Frontend. Specifically hide and delete buttons. I guess it should also happen when using the move up and move down buttons.
<img width="230" alt="editicons" src="https://cloud.githubusercontent.com/assets/12088094/18361254/713781e4-7601-11e6-9b2f-ff484caec058.png">

Extension feedit must be installed, admin panel activated and frontend editing options activated through admin panel or TSconfig.

The issue is observed on TYPO3 CMS 7 with PHP 5.6.

**Comment by irnnr** [comment]
ok, thanks
