### ISSUE TITLE
[BUG / IMPROVMENT] Indexing root page records (additionalPageIds) does not work

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Solr/ext-solr#649]
Due to the check if additionalPageIds are empty indexing of root page records does not work.
As I started explaining in https://github.com/TYPO3-Solr/ext-solr/issues/485
it is probably an edge case where that is necessary but I should be simple to fix by modifying the condition 
```
if (!empty($this->indexingConfiguration['additionalPageIds']))
```
in \ApacheSolrForTypo3\Solr\IndexQueue\Initializer\AbstractInitializer::getPages

to something like:
```
if (!isset($this->indexingConfiguration['additionalPageIds']) && (string)$this->indexingConfiguration['additionalPageIds'] !== '')
```

So I see no reason why not to support. The change listing issue should then be fixed in combination with:
https://github.com/TYPO3-Solr/ext-solr/issues/485

**Comment by irnnr** [comment]
We're not going to add that for the reasons provided in the other discussion. Just because it can be done does not mean it should be done.
