### ISSUE TITLE
Request for new method in Site.php

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#650]
We are currently writing a command line interface to install TYPO3 Solr on 400+ sites. Some sites are single sites whereas we have sites with more installations in then. We have an issue when configuring which tables to index on the multisites. Since pages are cached in protected static $sitePagesCache there is a problem when we iterate over all sites since there is not method to empty this array causing the content that is written into tx_solr_indexqueue_item to be a mix between the different sites. We would like to request a new public static method called clearSitePagesCache that initializes the array. We can provide a patch/pull request for it. 

Our current work around is to extend the Site class with our own class- which then again XClasses the original class.

**Comment by timohund** [comment]
@thomashohn Sounds good. Can you create a pull request?

**Comment by thomashohn** [comment]
Yes I can do that :-)
