### ISSUE TITLE
100% indexed but less docs than news

### ISSUE THREAD

**Issue by rnakielski** [TYPO3-Solr/ext-solr#651]
We have a new website (relaunch) with some more than 13,000 tx_news news migrated. I indexed all news and in the scheduler it shows 100%. In table tx_solr_indexqueue_item I see 13118 records. But checking index fields in the search module it says 9657 documents. The same amount I see in the solr admin panel: Num Docs: 9657. Shouldn't the number of docs be the same as there are indexqueue items? What can be wrong? Does the core need to be bigger (currently 32MB)

**Comment by irnnr** [comment]
hi @rnakielski,

please ask support questions on slack. We use GitHub issues for code related bugs and features only.
