### ISSUE TITLE
[TASK] Hierarchical fields should have trailsing slash (v5.1.0)

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Solr/ext-solr#683]
According to http://wiki.apache.org/solr/HierarchicalFaceting#Terms_Containing_Another_Term_in_the_Beginning

one should use trailing slashes for hierarchical field.
The reason is when using facet.prefix option in solr for instance, the hierarchy contains those fields:
"1-Books/OldBook"
"1-Books/OldBookParts"

if one uses facet.prefix=1-Books/OldBook
it would match both of those facets. 

If there is a trailing slash I can use
facet.prefix=1-Books/OldBook/

and it will not match "1-Books/OldBookParts"

**Comment by timohund** [comment]
I thinks this is a valid point. Do you have the time to create a pull request?

**Comment by AndreasA** [comment]
Not this week. Probably next week. Maybe the weekend (though I can't test it then)

**Comment by AndreasA** [comment]
Sorry, for the delay.
Had to do a lot of things in my private time and work time.
Hopefully, I can implement it soon. It shouldn't be that hard to implement, just need the time and a testsystem where I can test solr :)

**Comment by timohund** [comment]
@AndreasA Thx for your reply maybe our devbox is an option: https://github.com/TYPO3-Solr/solr-typo3-devbox by now you would need to start a docker container for Apache Solr 6.3 in parallel, but we'll add this in the next days.

**Comment by AndreasA** [comment]
PR added
