### ISSUE TITLE
Make check manipulateCacheActions check more Typo3 conform

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#687]
We have some usergroup with users that can perform solr installations. In order for them to call the "Ininitalize Solr connections" it would be nice to extend the check in manipulateCacheActions from

 if ($GLOBALS['BE_USER']->isAdmin()) {}

to

if (($GLOBALS['BE_USER']->isAdmin()) || ($GLOBALS['BE_USER']->getTSConfigVal('options.clearSolrConnectionCache'))) { }

In this way it would be possible to give special usergroups access to the "Initialize Solr Connection". This is also done so in the TYPO3 core for clearing various caches. 

Pull request can be provided :-)

**Comment by irnnr** [comment]
I'm not a fan of that idea since also only admins can access the Solr backend module and these two are closely related.

**Comment by thomashohn** [comment]
With more that +400 sites and not wanting everybody to be admin I find it ok :-)
BTW there is, as I see it. nothing that prohibits you for enabling the Backend module for others than admins in your own extension - which I have actually done...

**Comment by irnnr** [comment]
Sure, there are a lot of things you CAN do, it doesn't mean you SHOULD. With the core extension we try to satisfy the most common 90-95% use cases. What you describe is an edge case. I suggest you make you modifications in a custom extension, classing what is needed.

**Comment by thomashohn** [comment]
Hi Inno - fine with me - lets close the issue then :-)
