### ISSUE TITLE
[DISCUSSION] Use compoundIndex Format by default

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#695]
Since from time to time there is a problem with "too many open files" i want to discuss if we maybe should use the "compound" index format.

See: https://cwiki.apache.org/confluence/display/solr/IndexConfig+in+SolrConfig

Advantage: Less open files, less errors.
Disadvantage: Slower, we should measure the performance difference.

**Comment by timohund** [comment]
Feedback from the solr irc channel is, that the impact is pretty small and high end users could switch it off. So i would try it.

**Comment by irnnr** [comment]
sounds good to me to at least give it a try
