### ISSUE TITLE
Column cookie too small in tx_solr_statistics

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#702]
The column cookie in tx_solr_statistics is only defined as varchar(10). This is too small since the session id is stored in that column. The session id is defined as a varchar(32) in table fe_sessions - it would be nice to have fixed this.

**Comment by timohund** [comment]
@thomashohn Thx for reporting. Can you create a pull request?

**Comment by thomashohn** [comment]
@timohund - Yes i'll do that :-)

**Comment by timohund** [comment]
Fixed with #703
