### ISSUE TITLE
Statistics module fails if running mysql in strict mode

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#703]
Running mysql in strict mode makes the statistics module fail with at least this error:

_caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery' (60 chars)
   ERROR => 'Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggre
      gated column 'tho.virksomheda.systime.dk.tx_solr_statistics.tstamp' which is
       not functionally dependent on columns in GROUP BY clause; this is incompati
      ble with sql_mode=only_full_group_by' (264 chars)
   lastBuiltQuery => 'SELECT FLOOR(tstamp/86400) AS bucket, tstamp, COUNT(*) AS numQueries FROM tx
      _solr_statistics WHERE tstamp > 1474869698 AND root_pid = 3586 GROUP BY b
      ucket ORDER BY bucket ASC' (174 chars)_

**Comment by thomashohn** [comment]
Should I fix this one too? Or?

**Comment by timohund** [comment]
This would be nice, it would be nice if you can add an integration test as well. I think the problem is the groupby criterion in strict mode.

**Comment by thomashohn** [comment]
Fixed - there was also a bug in the statement. I could not add a test since it had to delete det dev-box due to insufficient space on my machine a couple of weeks ago...
