### ISSUE TITLE
[TASK] Migrate CommandController to Symfony command

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#707]
We should migrate the cli controllers to the symfony command.

**Comment by georgringer** [comment]
Sorry this is for 8x only, symfony commands are available since 8.0. I propose to create an issue tag 8x or just dismiss this issue

**Comment by timohund** [comment]
We will provide this as symfony command in solrconsole and integrate this into EXT:solr afterwards

**Comment by dkd-kaehm** [comment]
Sorry, no needs for currently supported EXT:Solr versions.
Closing it.
