### ISSUE TITLE
[Improvement] Improve speed in method getMonitoredTables

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#714]
The method getMonitoredTables current starts by calling
` $solrConfiguration = Util::getSolrConfigurationFromPageId($pageId);`
Before calling the method getMonitoredTables a call to been done to Util::getSolrConfigurationFromPageId  and stored $this->solrConfiguration.
So instead one could call  $this->solrConfiguration directly and remove the parameter

**Comment by timohund** [comment]
@thomashohn could catch. I would say we can move the logic to the configuration object into a method getMonitoredTables and then just call this method from the record monitor.

**Comment by thomashohn** [comment]
@timohund I think you need to elaborate on that
