### ISSUE TITLE
Missing update of db fields indexed and errors in tx_solr_indexqueue_item via method updateItem

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#718]
Should the method updateItem in Queue.php reset db_fields indexed and errors in the table tx_solr_indexqueue_item to ensure that updated items are re-indexed? Since pages are handled in a special way it happens for then.
We can provide a patch for this.

**Comment by irnnr** [comment]
* `indexed`: no
* `errors`: maybe, but probably no as well

**Comment by thomashohn** [comment]
@irnnr - my bad you are right - i'll close the issue
