### ISSUE TITLE
[BUG] BackendSummary not working

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Solr/ext-solr#731]
Because of a typo in `ext_localconf.php`, the backend summary does not work. Instead of `$_EXTKEY . '_PiResults_Results'` it must be `$_EXTKEY . '_pi_results'`

**Comment by thomashohn** [comment]
@timohund I could do this one - but how to test the fix?

**Comment by timohund** [comment]
I've tested the fix and will add a testcase for it.
