### ISSUE TITLE
[TASK] Raise code quality

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Solr/ext-solr#743]
- Remove unsued code
- Improve php doc if wrong/missing
- Remove not used arguments
- Fix wrong calls
- If code is touched, use ::class

**Comment by timohund** [comment]
I think it's good to resolve as much as possible from: https://scrutinizer-ci.com/g/TYPO3-Solr/ext-solr/issues/master

**Comment by georgringer** [comment]
I looked first just to phpstorm code checks as it is easer to do, others will follow

**Comment by georgringer** [comment]
I looked first just to phpstorm code checks as it is easer to do, others will follow
