### ISSUE TITLE
Moving "Lib" to "Resources/Private/Php/Lib" (or similar) ?

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Solr/ext-solr#75]
I think it would make sense to move Lib to Resources/Private/Php/Lib (or similar) as only the classes are needed and by moving it there it would be impossible to access anything inside the folder (e.g. PDFs or similiar) from the webserver directly (default htaccess rules).

**Comment by irnnr** [comment]
Yes, thought about that as well already. Just needs to work with autoloading

**Comment by AndreasA** [comment]
Wouldn't it have been better to use Resource/Private/Php?
As only Resource/Private is in htaccess denied according to _.htaccess

**Comment by irnnr** [comment]
There's an .htaccess in Php as well

**Comment by AndreasA** [comment]
Yes but nginx for instance doesn't support .htaccess and it might get lost upon deployment (when deploying manually) as it is a hidden file.
Putting it intoy Resources/Private would have the deny setting from typo3 default and therefore would also be part of a nginx configuration.
