### ISSUE TITLE
[BUG] solrconfig.xml More Like This Handler configuration is broken

### ISSUE THREAD

**Issue by maritwho** [TYPO3-Solr/ext-solr#765]
The configuration for the More Like This Handler in the sorlconfig.xml is wrong. In version 4.0.* it is line 268 on master 255. The configuration should look like:

`<requestHandler name="/mlt" class="solr.MoreLikeThisHandler">`

But it looks like

`<requestHandler name="mlt" class="solr.MoreLikeThisHandler">`

The missing leading slash breaks the functionality.

**Comment by irnnr** [comment]
I think previously we explicitly called the handler via a request type, that's why it was (intentionally) never configured as an explicitly exposed endpoint

**Comment by timohund** [comment]
@irnnr Do you see a problem in making it available as request handler?

**Comment by irnnr** [comment]
No, just mentioning the historical background. It was just deemed so "special" that it was not exposed explicitly.
