### ISSUE TITLE
Facet ViewHelper does not Fallback to current Page if no targetPage for Search is set

### ISSUE THREAD

**Issue by jonnsn** [TYPO3-Solr/ext-solr#77]
If plugin.tx_solr.search.targetPage is **not** set the facetRenderers targetLinkPageId will be set to 0 which will result in Facets rendered without any link.

Changing solr/Classes/ViewHelper/Facet.php line 87 from
```php
$facetRenderer->setLinkTargetPageId($this->configuration['search.']['targetPage']);
```
to
```php
$facetRenderer->setLinkTargetPageId($this->configuration['search.']['targetPage'] ? $this->configuration['search.']['targetPage'] : $GLOBALS['TSFE']->id);
```
fixes the Problem.

Apart from that, if plugin.tx_solr.search.targetPage **is set** and the targetPage in the FlexForm of the Plugin is also set, the Value of the FlexForm is ignored and the default TS value is used to render the link. I could not find a solution for that one yet.

**Comment by Mabahe** [comment]
Referenced commit should also fix this. Can you test this, please?
