### ISSUE TITLE
Index title and alttext attributes on HTML pages

### ISSUE THREAD

**Issue by JostBaron** [TYPO3-Solr/ext-solr#78]
Currently, some attributes are not indexed, although they may contain content. Examples are the `title` and the `alt` attributes.

This could probably be done by parsing the HTML document using libxml/DOMDocument instead of doing magic with regular expressions.

**Comment by irnnr** [comment]
Page title is being indexed. What do you mean with alttext? You can add other fields using the TypoScript configuration.

**Comment by JostBaron** [comment]
What I mean these attibutes:

    <a href="somepage.html" title="Some text that occurs when hovering over the image">
        <img alt="Nice image showing an even nicer scenery." src="landscape.jpg">
    </a>

But of course not all attributes should be indexed, so there has to be a filter or setting to choose them.

**Comment by seirerman** [comment]
Shouldn't this come from FAL fields instead of parsing the HTML content?

**Comment by irnnr** [comment]
I get the point, but I'm hesitant to add it since it would be quite some effort to change the indexer to take into account html tag attributes and the only for some. 

If you can come up with a PR I'm willing to take a look, otherwise it is very low priority as the current way works well enough.

**Comment by dkd-kaehm** [comment]
In EXT:solfal is it possible to figure out the indexing fields.

No alternative way needed currently.
