### ISSUE TITLE
Multilanguage/multicore setup, page records in non default languages contain th "url" parameter of the default language

### ISSUE THREAD

**Issue by artur2000** [TYPO3-Solr/ext-solr#786]
We work on a project with EXT:solr version 5.1.0 with a multilanguage/multicore setup as suggested in the documentation.
All works fine except this thing: For the indexing configuration "pages" all solr documents for all language cores contain the same parameter "url" of the default language page. 
This way the TYPO3 search works as expected and delivers correct translated contents in the results list, but clicking on a link brngs us to the default language page instead of the translated version.

I followed the hint given here below to generate correct URls using ` L={field:__solr_index_language}` https://docs.typo3.org/typo3cms/extensions/solr/Configuration/Reference/TxSolrIndex.html#queue-indexconfig.

It just did not work. After long and painfull debugging I found out, that to create a correct url for a solr document of a page the field "__solr_index_language" (as suggested in documentation) can not be used since it is used only in the general purpose indexer (\ApacheSolrForTypo3\Solr\IndexQueue\Indexer) which is used for records like tt_news etc. 
For pages a dedictaed indexer (\ApacheSolrForTypo3\Solr\IndexQueue\PageIndexer) is beeing used, where this field is not set anymore. Instead a full page record is fetched by the TYPO3 APIand version 7 LTS sets a field "_PAGES_OVERLAY_LANGUAGE" there holding the language id, so one can can use that instead.

```
url = TEXT
url {
       typolink.parameter = {field:uid}
       typolink.parameter.insertData = 1
       typolink.additionalParams = &L={field:_PAGES_OVERLAY_LANGUAGE}
       typolink.additionalParams.insertData = 1
       typolink.returnLast = url
       typolink.useCacheHash = 1
}
```

It would be good to update the documentation or implement the field "__solr_index_language" there as well for consistency.

**Comment by timohund** [comment]
@artur2000 can you share your pages queue configuration somewhere? The documentation you have mentioned is related to records? For pages nomally the TYPO3_REQUEST_URL as url. This should allready contain the language.

**Comment by timohund** [comment]
I this is required i would propose to make "__solr_index_language" also available here to have a consitent behaviour for records and pages.

**Comment by timohund** [comment]
Fixed with: https://github.com/TYPO3-Solr/ext-solr/pull/1417
