### ISSUE TITLE
TYPO3 7.5 "PHP Warning: array_flip() expects parameter 1 to be array, string given in ...." in Backend Module ->  Index Queue

### ISSUE THREAD

**Issue by elmarputz** [TYPO3-Solr/ext-solr#79]
When clicking on Index Queue with Solr Collections already initialized, i get the following error in the backend: 

    PHP Warning: array_flip() expects parameter 1 to be array, string given in /usr/www/users/fhpooz/typo3_src/typo3_src-7.5.0/typo3/sysext/backend/Classes/Form/Element/SelectCheckBoxElement.php line 45

The stack trace shows the following method call as being responsible for the warning: 

    ApacheSolrForTypo3\Solr\Backend\IndexingConfigurationSelectorField::renderSelectCheckbox(array, "")

I did a typo3 upgrade from 7.4 to 7.5 with already initalized queue (pages only) - indexing and rendering seems to work as expected for now

**Comment by sorenmalling** [comment]
It's fixed with this PR

https://github.com/TYPO3-Solr/ext-solr/pull/80

**Comment by irnnr** [comment]
#82
