### ISSUE TITLE
Prevent further SQL hammering in getConfigurationFromPageId

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#814]
I believe there are more results that can be cached in the getConfigurationFromPageId as proposed by Claus Due in [Pull-request](https://github.com/TYPO3-Solr/ext-solr/pull/732).

**Comment by timohund** [comment]
@thomashohn Can we close this issue?

**Comment by thomashohn** [comment]
Hi yes - I think #816 fixed it :-)
