### ISSUE TITLE
ViewHelpers are loaded by using the old class names

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Solr/ext-solr#84]
ApacheSolrForTypo3\Solr\Template::addViewHelper

uses the old ViewHelper classnames like Tx_Solr_ViewHelper_Lll

The issue is with loadViewHelper

Furthermore, the new ViewHelper classNames actually shouldn't need to manually include the .php fiel anymore as it should already be loaded via Typo3 classloader.

**Comment by irnnr** [comment]
I'm aware of that, but I don't intend to spend a lot of time on it. It's more of a backwards compatibility issue. It'll be resolved once we switch to Fluid.

**Comment by AndreasA** [comment]
True. So I guess the easiest solution is just to keep the migrations map until fluid switch is done.

**Comment by irnnr** [comment]
yeah, that's the plan

**Comment by AndreasA** [comment]
Then I am closing this :)

**Comment by irnnr** [comment]
:+1:
