### ISSUE TITLE
Util::getFileDocumentId still in use? If so there are classes missing

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Solr/ext-solr#85]
I just noticed that in util there is a method getFileDocumentId which requires a Class Tx_Solr_FileIndexer_File
as parameter.
That one is first not namespaced and second I can't find a corresponding object, so I guess it should be removed?

**Comment by irnnr** [comment]
That class is here: https://github.com/TYPO3-Solr/ext-solrfile/blob/master/classes/fileindexer/class.tx_solr_fileindexer_file.php

It's used for file indexing. However, of course EXT:solrfile does not work with TYPO3 6.2/FAL anymore. I'll have to check with EXT:solrfal whether it is used there. Either way I think we still need the method to generate file document IDs.

**Comment by AndreasA** [comment]
I don't think it is used there as the file object itself has an id.
Anyway even so I think that method should be put in FileIndexer instead after all it uses an object from that ext.

**Comment by dkd-dobberkau** [comment]
@timoschmidt can you have a look at this on occassion?

**Comment by timoschmidt** [comment]
@dkd-dobberkau sure

**Comment by timoschmidt** [comment]
@dkd-dobberkau 
@irnnr 

This function is not used in solrfal and also the argument class itsself "tx_solr_fileindexer_File" is shipped with solrfile. Solrfile does not work with solrfal, so i would propose we can remove it in dev-master.
