### ISSUE TITLE
[TASK] Allow to disable siteHash check

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#862]
The setting plugin.tx_solr.search.query.allowedSites = can be used by now, to enable a search on different sites. But this has currently the limitation that only sites from the same TYPO3 system can be used for search:

* \* and __all means: All sites of the same TYPO3 System
* __current_site means only the current site
* and it is possible to configure domains within the same system

I would suggest to make a (breaking) change here to allow the search on any site (also when it is located in another instance. Afterwards we would have the following meanings:

* \*   Any site (no sitehash check)
* __all (all sites from the instance)
* and it is possible to configure domains within the same system

Another approach would be to introduce a new setting like __any or __global but then the meaning of * would be confusing for me. Anyhow we need a possibility to disabled this check.

**Comment by irnnr** [comment]
I don't think this is a good idea / I don't think this should be implemented. The purpose of the site hash is basically so that you could index multiple sites into one core/index.

Besides that there is EXT:solr_disablesitehash for exactly those use cases where someone would want to disable the site hash. https://github.com/TYPO3-Solr/ext-solr_disablesitehash

**Comment by timohund** [comment]
@irnnr I know this extension. What about to move this functionallity into EXT:solr? i think this simpflies the maintenance and testing of this a lot.

**Comment by irnnr** [comment]
What maintenance? There's not much to do, is it?

The site hash really is essential to quite a few things in the extension / it's used in quite some areas. So the "feature" - rather ability - to turn it off should be left to people / use cases where the user absolutely knows what they're doing. The extension is easy enough to install and use.

Why?:

I think the best explanation is the department scenario:  
A large installation with multiple sites for each department (university/company). They all index into the same core. By having the site hash you can ensure that while you're on a department's site you will only results for that particular department. When you search from the organization's umbrella/head/general site you could by default also search only that. However, you could implement a checkbox "search entire organization", that when checked would disable the site hash and thus returning results from all departments.

The site hash also ensures that in this scenario, when emptying/re-initializing an index, only documents for a particular site are affected.

Hope that makes sense.
