### ISSUE TITLE
[TASK] Documentation: Add site search box example

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/ext-solr#869]
A FAQ item that should be added to the documentation is how to add a search form field on every page.

There is an example TS snippet for the old(?) intro package, but nothing in the docs.

https://typo3.slack.com/archives/random/p1483979164001584

**Comment by irnnr** [comment]
Also need to check whether the current example configuration for the intro package still works.

**Comment by dkd-kaehm** [comment]
To do not search the source of question, here is the question from Slack Link above:
"how can i shift a plugin into template header? i need to have a solr-search input in every page header"

![bildschirmfoto 2017-04-07 um 10 05 49](https://cloud.githubusercontent.com/assets/25453927/24791310/f06058d8-1b79-11e7-9eb2-acaa01b1d541.png)
