### ISSUE TITLE
An "avoid commit" setting

### ISSUE THREAD

**Issue by RasmusWernerLarsen** [TYPO3-Solr/ext-solr#870]
I'm looking into implementing an "AvoidCommit" setting for ext-solr.

The idea would be that when this option is set, ext-solr will never issue any solr commit operations against the SOLR server, but instead rely on the solr servers autocommit feature (or say, an external job of some kind, maybe even manual action, though neither of those is our usecase).

The point is to improve scalability and performance, because in our usecase where we have approximately 500 individual sites sharing a single core, it's very difficult to control how many commits are issued and how they're distributed. The result is that, especially in maintenance situations, we can experience quite high commit rates and in particular commits with very few seconds between, this in turn causes concurrent warming searchers which is very harmful to solr performance. Also a commit will invalidate most of the high level caches, which is never a nice thing for performance if it happens all the time.

An alternative name for this setting could be "AutoCommitMode" because really that's what it comes down to. We want ext-solr to not even consider the issue of data reliability and data visibility, we want the AutoCommit interval to fully handle that.

Ofcourse, I'm not really suggesting that we conditionally override the "commit" call in the solrClient library or anything like that, if you really want to call the commit code, you should be able to, in case you have some manual administrative function that wants to hit it, but no ext-solr component should do it implicitly.

Looking for thoughts, ideas and criticism...

**Comment by timohund** [comment]
@RasmusWernerLarsen Hi, i think this is a good idea and makes sence, i would propose to introduce the following setting (that defaults to true):

```
plugin.tx_solr.index.enableCommits
```

When you set it to false we would avoid the call's of commit(). What do your think?

**Comment by RasmusWernerLarsen** [comment]
I like it... Will implement that.
