### ISSUE TITLE
Stopwords are not saved correctly in 8 LTS

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#896]
The stopwords are not saved correctly in the backend. Linebreaks are converted to entities

**Comment by kasperligaard** [comment]
This could be because the RTE transformation ts_css was removed, cf. https://review.typo3.org/#/q/ts_css.

**Comment by thomashohn** [comment]
The problem seems to be that $escapeOutput should be false in ImplodeViewHelper - there might be other places where this could be a problem. PR #900 should fix it in Backend module StopWords

**Comment by timohund** [comment]
Fixed by pr #900
