### ISSUE TITLE
TYPO3 8 ExtensionManagementUtility::extRelPath() is deprecated

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#901]
The use of `TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extRelPath()` is deprecated and should be fixed to use either 

`use PathUtility::getAbsoluteWebPath()`
or 
`->siteRelPath() `

**Comment by timohund** [comment]
@thomashohn Yes, but we should change this, when we drop 7 LTS support (in 7.0).

**Comment by thomashohn** [comment]
Fine with me - but since it's supported on both 7 and 8 we would normally get rid of deprecations as soon as possible ;-)

**Comment by thomashohn** [comment]
Since the replacement is supported in both TYPO3 7 and TYPO3 8 it think it's would be safe to replace it already. In addition one should remove the two globals $GLOBALS['PATH_solr'] and $GLOBALS['PATHrel_solr'] since they do not really make any sense currently

**Comment by timohund** [comment]
@thomashohn I've it works in  7 and 8 and you can create a PR this would be cool. Maybe you can also add a test that covers the usage.

**Comment by thomashohn** [comment]
So since the usage in in ext_* files I'm not sure a Test makes sense - but will look into it.

**Comment by timohund** [comment]
@thomashohn i agree

**Comment by timohund** [comment]
Fixed with #948
