### ISSUE TITLE
[TASK] Identify parts to streamline database usage

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#904]
With 8 LTS doctrine is introduced and the old database interface is deprecated. To prepare a migration to doctrine, we should idefintify the parts in the code that access the database and check what can be streamlined (Moved into one class for the same table e.g. IndexQueue or XYRepository).

This simplifies the migration to doctrine, when we drop the 7 LTS support. As first step i would only see now, to move the functionallity into one class per tables, like *Repository. The next step could be to migrate the code to doctrine.

**Comment by thomashohn** [comment]
So to understand you correct - you would make a class called "SolrIndexqueueItemDB"  for tx_solr_indexqueue_item and then wrap all SQL statements accessing that table into methods in that class? The name of the class is still open ;-)

**Comment by timohund** [comment]
@thomashohn  I think to have this for all classes is currently no realistic. I think we need to decide this from case to case. If you want to work on that we can also discus this on slack/skype. A good starting point to check all queries to the index_queue and check what can be streamlined there, it think this could simpliefy the migration to doctrine later.

**Comment by timohund** [comment]
Since we analysed and identified a lot of places for the current release and migrated them, i'll close that issue. Please open a new issue for specific parts that should be changed or moved
