### ISSUE TITLE
[TASK] Unify PR/Commit messages

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#916]
Suggestion could be to provide a git-commit hook like the one used in typo3 to ensure a certain style of commits. We could then also ensure that the same notation will be used consistently.

Since I work on a lot of projects with different styles/commit messages a "gatekeeper" would be nice :-)

**Comment by timohund** [comment]
@thomashohn Good idea. If you have time to work on this feel free to do so.

**Comment by timohund** [comment]
Templates have been added to master. Please create a pr for change requests.
