### ISSUE TITLE
[TASK] Add indexes to the pages table

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#939]
I have been profiling the Solr extension with TYPO3 8.x via blackfire.io. 

In the "normal" case with creating pages/elements etc. performance is ok. The case where an existing page-tree is copied shows major performance issues in relation to the database.
The test consists of a page tree with 6 nodes, 366 tt_content elements and 4 file references.
As seen on the screen-shot there seems to be 2 missing indexes and a rewrite of the SQL statement in getDestinationMountPropertiesByRootLine.
<img width="889" alt="solr-missing-indexes" src="https://cloud.githubusercontent.com/assets/3414869/22627016/3a18fe3e-ebba-11e6-95b3-af39f9643c74.png">
Adding the following two indexes:
```
alter table pages add index content_from_pid_deleted (content_from_pid, deleted);
alter table pages add index doktype_no_search_deleted (doktype, no_search, deleted);
```
gives the following performance boost:
<img width="866" alt="solr-adding-indexes" src="https://cloud.githubusercontent.com/assets/3414869/22627026/52b0588e-ebba-11e6-9875-cc75ffd4db35.png">

A PR can be provided

**Comment by irnnr** [comment]
This seems to affect only mount pages?

**Comment by thomashohn** [comment]
No - since the RecordMonitor executes the `update` from the class `MountPagesUpdater` the SQL statement will be executed in all cases - causing the overhead - or do I miss something?

**Comment by irnnr** [comment]
ok

**Comment by thomashohn** [comment]
Merged
