### ISSUE TITLE
[BUG] Mounted pages from outside of the page tree lead to index queue errors

### ISSUE THREAD

**Issue by alappe** [TYPO3-Solr/ext-solr#953]
## Setup:

I have a record storage with pages that are shared across various page trees, where pages do mount them and display their content:

![screen shot 2017-02-09 at 15 42 18](https://cloud.githubusercontent.com/assets/1357848/22787950/5d2470da-eede-11e6-9f97-4f85d5bd9635.png)

## Expected

Index pages normally…

## What is happening

When I click »Queue Selected Content for Indexing« I get the following exception:

![screen shot 2017-02-09 at 15 44 04](https://cloud.githubusercontent.com/assets/1357848/22788034/a233fdee-eede-11e6-973b-83808f8e0408.png)

**Comment by timohund** [comment]
We should add an integration test for this scenario and check what's wrong
