### ISSUE TITLE
[TASK] Move all dateFormatting functions from Util to System/DateTime/FormatService

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#957]
To reduce the complexity of the Util class, we should move the DateFormatting functions to the responsible service (System/DateTime/FormatService). The old method should be marked as deprecated and to be removed in version 7. The util method should use the service to provide backwards compatibility.

The following functions a relevant.

* timestampToIso
* isoToTimestamp
* timestampToUtcIso
* utcIsoToTimestamp

**Comment by thomashohn** [comment]
Hi Timo - I could have a look at this one?

**Comment by timohund** [comment]
@thomashohn sure, would be nice, at the same time we could add a unit test for them.
