### ISSUE TITLE
[BUG] Initialise SolrConnection missing in Page menu

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-solr#962]
The initialise solr connection is missing in the "Menu" on the page-tree - since they have changed that with TYPO3 8.x i guess you need to hook into the menu somehow else

TYPO3 7.6.15
<img width="210" alt="screen shot 2017-02-10 at 11 23 01" src="https://cloud.githubusercontent.com/assets/3414869/22823376/9877ba66-ef83-11e6-8938-008b0558df1d.png">

TYPO3 dev-master
<img width="186" alt="screen shot 2017-02-10 at 11 23 18" src="https://cloud.githubusercontent.com/assets/3414869/22823391/ab424dd2-ef83-11e6-8744-e69f48416a87.png">

**Comment by tomasnorre** [comment]
FYI: It's related to this change: 
https://forge.typo3.org/issues/78192

**Comment by irnnr** [comment]
when fixing this I'd suggest to also move the item to the bottom like the clear cache menu and also use the same (black) icon
