### ISSUE TITLE
[BUG] Wrong TS path in frontendDataHelper documentation

### ISSUE THREAD

**Issue by dkd-friedrich** [TYPO3-Solr/ext-solr#964]
Documented TS paths for the  frontendDataHelper have to be fixed, `indexer` is missing for `scheme`, `host` and `path`.

**Comment by timohund** [comment]
@dkd-friedrich had a look on this today: https://github.com/TYPO3-Solr/ext-solr/blob/master/Documentation/Configuration/Reference/TxSolrIndex.rst#queue-pages-indexer-authorization-password the "indexer" level is present there, what is correct in your opinion here?

**Comment by dkd-friedrich** [comment]
@timohund Right, it's correct in the heading, but not in the provided "TS Path".
