### ISSUE TITLE
@facetText from category shows uid

### ISSUE THREAD

**Issue by eBornstein** [TYPO3-Solr/ext-solr#966]
Hi,
I have configured a facet, which shows the category tree when searching.
Upon selecting one category, it gets activated and is displayed under "active filters", it is only shown as "Categories: 1", so instead of showing the category title, the id is shown.
How can I get the category name instead of uid.

solr 5.1.1
TYPO3 7.6.12

My setup:
plugin.tx_solr.index {
  fieldProcessingInstructions {
    category_stringM = categoryUidToHierarchy
  }
}
plugin.tx_solr {
  search {
    faceting {
      facets {
        category_stringM {
          label = Categories
          field = category_stringM
          type = hierarchy
          hierarchy = HMENU
          hierarchy {
            1 = TMENU
            1 {
              NO = 1
              NO {
                wrapItemAndSub = |
                stdWrap.cObject = RECORDS
                stdWrap.cObject {
                  source.field = facetKey
                  tables = sys_category
                  dontCheckPid = 1
                  conf.sys_category = TEXT
                  conf.sys_category.field = title
                  conf.sys_category.htmlSpecialChars = 1
                }
                stdWrap.dataWrap = |&nbsp;<span class="facetoption-result-count">({field:numberOfResults})</span>
              }
...

**Comment by dkd-dobberkau** [comment]
No offense: This is not a support forum.
Can you please use our slack #ext-solr https://forger.typo3.org/slack ?

**Comment by eBornstein** [comment]
Yeah sure, sry.
I thought maybe it's a bug or it could be a feature request.
