### ISSUE TITLE
Solr Host validation

### ISSUE THREAD

**Issue by tomasnorre** [TYPO3-Solr/ext-solr#967]
Would be helpful to have validation that help "stupid" people like me, that haven't worked a lot with solr. 

I have tried to debug why my solr didn't index as expected. And turned out to be due to a # in my path.

`path = /sorl/#/english`, which should have been `path = /solr/english/`,

Perhaps the configuration check should validate the url, to make sure this is not happening. 

I got the 
```
throw new \RuntimeException(
                'Failed indexing page Index Queue item ' . $item->getIndexQueueUid(),
                1331837081
            );
```

Which is actually correct, but  an error earlier and more concrete is this case could be helpful. 

When I have more time i would be happy to submit a pull request. But please let me know first, if you want this check in.

Thanks for a cool extension.

**Comment by timohund** [comment]
@tomasnorre That's a good idea! It would help a lot, if you could provide a pull request.

**Comment by tomasnorre** [comment]
I will do that as soon as i find the time :)

**Comment by thomashohn** [comment]
Please not that "/sorl/#/english" is indeed a valid URL - just not for solr - so maybe it should just be checked that the path contains /xxx/yy etc. and not signs like "#" etc.

**Comment by tomasnorre** [comment]
@thomashohn I didn't mean that it wasn't a valid URL, I meant in context of solr-configuration it isn't valid url. :)

**Comment by thomashohn** [comment]
@tomasnorre Should it be shown in the "Reports" or where?

**Comment by tomasnorre** [comment]
I want it to be shown in the "Overview page" when hitting search, similar to when it cannot establish connection to Solr Server.

Like today where it suggests there is no domain name configured, no root page etc.

**Comment by thomashohn** [comment]
<img width="829" alt="screen shot 2017-02-18 at 18 41 50" src="https://cloud.githubusercontent.com/assets/3414869/23095431/1e96d2bc-f60a-11e6-9a60-da4e4e126ea7.png">

**Comment by irnnr** [comment]
The above message should not be possible together with the bottom one, or is that just a mockup?

**Comment by thomashohn** [comment]
@irnnr Actually in the special case where the path is /solr/#/core_xx it is possible since that is a path that can be pinged. I didn't want the path check to have higher priority than the ping check so normally there would be a "red" one saying that the server could not be contacted and then the orange one.

**Comment by irnnr** [comment]
ok
