### ISSUE TITLE
[TASK] Move Util::isRootPage to RootPageResolver as non static method

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#970]
We should move Util::isRootPage to the RootPageResolver as non static method and make Util::isRootPage deprecated. Along with that, this method should use the cache of the RootPageResolver.

**Comment by thomashohn** [comment]
@timohund I could have a look at this one - in addition I would suggest using the runtime cache instead of an own cache..

**Comment by timohund** [comment]
That's a good idea, move it to RootPageResolver and use the runtime cache, then we don't the a seperate cache "tx_solr_siteroots"
