### ISSUE TITLE
Adjust background color for scheduler task progress bar

### ISSUE THREAD

**Issue by tomasnorre** [TYPO3-Solr/ext-solr#972]
It would be cool if the background color or the font color was more suitable the blue and light-grey background. It difficult to read the text that is not in the blue area.

![screen shot 2017-02-15 at 16 52 16](https://cloud.githubusercontent.com/assets/1212481/22982447/6f0b84e4-f39f-11e6-96aa-3c91047fff44.png)

**Comment by thomashohn** [comment]
@tomasnorre Personally I would choose black :-)

**Comment by tomasnorre** [comment]
@thomashohn as font or background-color ?

**Comment by thomashohn** [comment]
Font-color :-)
<img width="463" alt="screen shot 2017-02-15 at 18 15 44" src="https://cloud.githubusercontent.com/assets/3414869/22986120/cf196fc6-f3aa-11e6-8225-471019f0bd3a.png">

**Comment by thomashohn** [comment]
It's not that often you will look into these numbers anyway ;-)

**Comment by thomashohn** [comment]
@tomasnorre Alternatively a dark grey ;-)
<img width="696" alt="screen shot 2017-02-15 at 19 04 53" src="https://cloud.githubusercontent.com/assets/3414869/22988259/bc022fac-f3b1-11e6-9b39-3f4fa845f185.png">

**Comment by thomashohn** [comment]
Hi @tomasnorre / @timohund - I have proposed a change to the TYPO3 core since I believe the change should occur/be performed there - see https://forge.typo3.org/issues/79844 :-)

**Comment by timohund** [comment]
Thank you @thomashohn. I'll close the issue

**Comment by thomashohn** [comment]
It was accepted and merged into the dev branch - meaning it will be part of TYPO3 8.7
